import type { Card } from './cards';

const EB01_CARDS: Card[] = [
  { id: "EB01-001", name: "Kouzuki Oden", set: "Memorial Collection", setCode: "EB01", number: "001", type: "Leader", color: "Red/Green", rarity: "L", cost: 4, power: 5000, attribute: "Slash" },
  { id: "EB01-002", name: "Izo", set: "Memorial Collection", setCode: "EB01", number: "002", type: "Character", color: "Red", rarity: "R", cost: 5, power: 7000, attribute: "Ranged" },
  { id: "EB01-003", name: "Kid &amp; Killer", set: "Memorial Collection", setCode: "EB01", number: "003", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000, attribute: "Slash" },
  { id: "EB01-004", name: "Koza", set: "Memorial Collection", setCode: "EB01", number: "004", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Ranged" },
  { id: "EB01-005", name: "Doma", set: "Memorial Collection", setCode: "EB01", number: "005", type: "Character", color: "Red", rarity: "C", cost: 1, power: 3000, attribute: "Slash" },
  { id: "EB01-006", name: "Tony Tony.Chopper", set: "Memorial Collection", setCode: "EB01", number: "006", type: "Character", color: "Red", rarity: "SuperRare", cost: 3, power: 4000, attribute: "Strike" },
  { id: "EB01-007", name: "Yamato", set: "Memorial Collection", setCode: "EB01", number: "007", type: "Character", color: "Red", rarity: "C", cost: 5, power: 5000, attribute: "Strike" },
  { id: "EB01-008", name: "LittleOars Jr.", set: "Memorial Collection", setCode: "EB01", number: "008", type: "Character", color: "Red", rarity: "R", cost: 6, power: 7000, attribute: "Strike" },
  { id: "EB01-009", name: "Just Shut Up and Come with Us!!!!", set: "Memorial Collection", setCode: "EB01", number: "009", type: "Event", color: "Red", rarity: "C", cost: 1 },
  { id: "EB01-010", name: "There's No Way You Could Defeat Me!!", set: "Memorial Collection", setCode: "EB01", number: "010", type: "Event", color: "Red", rarity: "R", cost: 3 },
  { id: "EB01-011", name: "Mini-Merry", set: "Memorial Collection", setCode: "EB01", number: "011", type: "Stage", color: "Red", rarity: "C", cost: 1 },
  { id: "EB01-012", name: "Cavendish", set: "Memorial Collection", setCode: "EB01", number: "012", type: "Character", color: "Green", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Slash" },
  { id: "EB01-013", name: "Kouzuki Hiyori", set: "Memorial Collection", setCode: "EB01", number: "013", type: "Character", color: "Green", rarity: "R", cost: 4, attribute: "Wisdom" },
  { id: "EB01-014", name: "Sanji", set: "Memorial Collection", setCode: "EB01", number: "014", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "EB01-015", name: "Scratchmen Apoo", set: "Memorial Collection", setCode: "EB01", number: "015", type: "Character", color: "Green", rarity: "R", cost: 1, power: 1000, attribute: "Special" },
  { id: "EB01-016", name: "Bingoh", set: "Memorial Collection", setCode: "EB01", number: "016", type: "Character", color: "Green", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "EB01-017", name: "Blueno", set: "Memorial Collection", setCode: "EB01", number: "017", type: "Character", color: "Green", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "EB01-018", name: "Mountain God", set: "Memorial Collection", setCode: "EB01", number: "018", type: "Character", color: "Green", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "EB01-019", name: "Off-White", set: "Memorial Collection", setCode: "EB01", number: "019", type: "Event", color: "Green", rarity: "R", cost: 2 },
  { id: "EB01-020", name: "Chambres", set: "Memorial Collection", setCode: "EB01", number: "020", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "EB01-021", name: "Hannyabal", set: "Memorial Collection", setCode: "EB01", number: "021", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 4, power: 5000, attribute: "Slash" },
  { id: "EB01-022", name: "Inazuma", set: "Memorial Collection", setCode: "EB01", number: "022", type: "Character", color: "Blue", rarity: "SuperRare", cost: 6, power: 7000, attribute: "Slash" },
  { id: "EB01-023", name: "Edward Weevil", set: "Memorial Collection", setCode: "EB01", number: "023", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 6000, attribute: "Slash" },
  { id: "EB01-024", name: "Hamlet", set: "Memorial Collection", setCode: "EB01", number: "024", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "EB01-025", name: "Fourtricks", set: "Memorial Collection", setCode: "EB01", number: "025", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 5000, attribute: "Slash" },
  { id: "EB01-026", name: "Prince Bellett", set: "Memorial Collection", setCode: "EB01", number: "026", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 2000, attribute: "Ranged" },
  { id: "EB01-027", name: "Mr.1(Daz.Bonez)", set: "Memorial Collection", setCode: "EB01", number: "027", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "EB01-028", name: "Gum-Gum Champion Rifle", set: "Memorial Collection", setCode: "EB01", number: "028", type: "Event", color: "Blue", rarity: "R", cost: 1 },
  { id: "EB01-029", name: "Sorry. I'm a Goner.", set: "Memorial Collection", setCode: "EB01", number: "029", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "EB01-030", name: "Loguetown", set: "Memorial Collection", setCode: "EB01", number: "030", type: "Stage", color: "Blue", rarity: "C", cost: 2 },
  { id: "EB01-031", name: "Kalifa", set: "Memorial Collection", setCode: "EB01", number: "031", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 5000, attribute: "Wisdom" },
  { id: "EB01-032", name: "Army Wolves", set: "Memorial Collection", setCode: "EB01", number: "032", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "EB01-033", name: "Blueno", set: "Memorial Collection", setCode: "EB01", number: "033", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "EB01-034", name: "Ms. Wednesday", set: "Memorial Collection", setCode: "EB01", number: "034", type: "Character", color: "Purple", rarity: "SuperRare", cost: 3, power: 4000, attribute: "Slash" },
  { id: "EB01-035", name: "Ms. Monday", set: "Memorial Collection", setCode: "EB01", number: "035", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 5000, attribute: "Strike" },
  { id: "EB01-036", name: "Minochihuahua", set: "Memorial Collection", setCode: "EB01", number: "036", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000, attribute: "Strike" },
  { id: "EB01-037", name: "Mr. 9", set: "Memorial Collection", setCode: "EB01", number: "037", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "EB01-038", name: "Oh Come My Way", set: "Memorial Collection", setCode: "EB01", number: "038", type: "Event", color: "Purple", rarity: "C", cost: 1 },
  { id: "EB01-039", name: "Conquerer of Three Worlds Ragnaraku", set: "Memorial Collection", setCode: "EB01", number: "039", type: "Event", color: "Purple", rarity: "R", cost: 5 },
  { id: "EB01-040", name: "Kyros", set: "Memorial Collection", setCode: "EB01", number: "040", type: "Leader", color: "Black/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Slash" },
  { id: "EB01-041", name: "Crocus", set: "Memorial Collection", setCode: "EB01", number: "041", type: "Character", color: "Black", rarity: "C", cost: 6, power: 8000, attribute: "Wisdom" },
  { id: "EB01-042", name: "Scarlet", set: "Memorial Collection", setCode: "EB01", number: "042", type: "Character", color: "Black", rarity: "R", cost: 2, attribute: "Wisdom" },
  { id: "EB01-043", name: "Spandine", set: "Memorial Collection", setCode: "EB01", number: "043", type: "Character", color: "Black", rarity: "R", cost: 3, power: 2000, attribute: "Wisdom" },
  { id: "EB01-044", name: "Funkfreed", set: "Memorial Collection", setCode: "EB01", number: "044", type: "Character", color: "Black", rarity: "C", cost: 1, power: 1000, attribute: "Slash" },
  { id: "EB01-045", name: "Brook", set: "Memorial Collection", setCode: "EB01", number: "045", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "EB01-046", name: "Brook", set: "Memorial Collection", setCode: "EB01", number: "046", type: "Character", color: "Black", rarity: "SuperRare", cost: 3, power: 4000, attribute: "Slash" },
  { id: "EB01-047", name: "Laboon", set: "Memorial Collection", setCode: "EB01", number: "047", type: "Character", color: "Black", rarity: "C", cost: 2, power: 4000, attribute: "Strike" },
  { id: "EB01-048", name: "Laboon", set: "Memorial Collection", setCode: "EB01", number: "048", type: "Character", color: "Black", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Strike" },
  { id: "EB01-049", name: "T-Bone", set: "Memorial Collection", setCode: "EB01", number: "049", type: "Character", color: "Black", rarity: "R", cost: 5, power: 5000, attribute: "Slash" },
  { id: "EB01-050", name: "...I Want to Live!!", set: "Memorial Collection", setCode: "EB01", number: "050", type: "Event", color: "Black", rarity: "C", cost: 3 },
  { id: "EB01-051", name: "Finger Pistol", set: "Memorial Collection", setCode: "EB01", number: "051", type: "Event", color: "Black", rarity: "R", cost: 4 },
  { id: "EB01-052", name: "Viola", set: "Memorial Collection", setCode: "EB01", number: "052", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 2, attribute: "Special" },
  { id: "EB01-053", name: "Gastino", set: "Memorial Collection", setCode: "EB01", number: "053", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000, attribute: "Special" },
  { id: "EB01-054", name: "Gan.Fall", set: "Memorial Collection", setCode: "EB01", number: "054", type: "Character", color: "Yellow", rarity: "R", cost: 3, power: 4000, attribute: "Slash" },
  { id: "EB01-055", name: "Charlotte Compote", set: "Memorial Collection", setCode: "EB01", number: "055", type: "Character", color: "Yellow", rarity: "C", cost: 7, power: 9000, attribute: "Wisdom" },
  { id: "EB01-056", name: "Charlotte Flampe", set: "Memorial Collection", setCode: "EB01", number: "056", type: "Character", color: "Yellow", rarity: "R", cost: 1, power: 1000, attribute: "Special" },
  { id: "EB01-057", name: "Shirahoshi", set: "Memorial Collection", setCode: "EB01", number: "057", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 2, attribute: "Wisdom" },
  { id: "EB01-058", name: "Mont Blanc Cricket", set: "Memorial Collection", setCode: "EB01", number: "058", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "EB01-059", name: "Kingdom Come", set: "Memorial Collection", setCode: "EB01", number: "059", type: "Event", color: "Yellow", rarity: "R", cost: 6 },
  { id: "EB01-060", name: "Did Someone Say...Kami?", set: "Memorial Collection", setCode: "EB01", number: "060", type: "Event", color: "Yellow", rarity: "C", cost: 4 },
  { id: "EB01-061", name: "Mr.2.Bon.Kurei(Bentham)", set: "Memorial Collection", setCode: "EB01", number: "061", type: "Character", color: "Purple", rarity: "SecretRare", cost: 4, power: 1000, attribute: "Special" },
];

export default EB01_CARDS;
