import type { Card } from './cards';

const EB02_CARDS: Card[] = [
  { id: "EB02-001", name: "Karoo", set: "Anime 25th Collection", setCode: "EB02", number: "001", type: "Character", color: "Red", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "EB02-002", name: "Sabo", set: "Anime 25th Collection", setCode: "EB02", number: "002", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000, attribute: "Special" },
  { id: "EB02-003", name: "Tony Tony.Chopper", set: "Anime 25th Collection", setCode: "EB02", number: "003", type: "Character", color: "Red", rarity: "R", cost: 3, power: 3000, attribute: "Strike" },
  { id: "EB02-004", name: "Don Accino", set: "Anime 25th Collection", setCode: "EB02", number: "004", type: "Character", color: "Red", rarity: "C", cost: 8, power: 10000, attribute: "Special" },
  { id: "EB02-005", name: "Fake Straw Hat Crew", set: "Anime 25th Collection", setCode: "EB02", number: "005", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Ranged" },
  { id: "EB02-006", name: "Yamato", set: "Anime 25th Collection", setCode: "EB02", number: "006", type: "Character", color: "Red", rarity: "SuperRare", cost: 6, power: 7000, attribute: "Strike" },
  { id: "EB02-007", name: "Cloven Rose Blizzard", set: "Anime 25th Collection", setCode: "EB02", number: "007", type: "Event", color: "Red", rarity: "C", cost: 3 },
  { id: "EB02-008", name: "The Peak", set: "Anime 25th Collection", setCode: "EB02", number: "008", type: "Event", color: "Red", rarity: "R", cost: 2 },
  { id: "EB02-009", name: "Thousand Sunny", set: "Anime 25th Collection", setCode: "EB02", number: "009", type: "Stage", color: "Red", rarity: "C", cost: 2 },
  { id: "EB02-010", name: "Monkey.D.Luffy", set: "Anime 25th Collection", setCode: "EB02", number: "010", type: "Leader", color: "Green/Purple", rarity: "L", cost: 4, power: 5000, attribute: "Strike" },
  { id: "EB02-011", name: "Arlong", set: "Anime 25th Collection", setCode: "EB02", number: "011", type: "Character", color: "Green", rarity: "SuperRare", cost: 3, power: 4000, attribute: "Slash" },
  { id: "EB02-012", name: "Gaimon", set: "Anime 25th Collection", setCode: "EB02", number: "012", type: "Character", color: "Green", rarity: "C", cost: 1, power: 1000, attribute: "Wisdom" },
  { id: "EB02-013", name: "Carrot", set: "Anime 25th Collection", setCode: "EB02", number: "013", type: "Character", color: "Green", rarity: "C", cost: 1, attribute: "Special" },
  { id: "EB02-014", name: "Sarfunkel", set: "Anime 25th Collection", setCode: "EB02", number: "014", type: "Character", color: "Green", rarity: "C", cost: 2, attribute: "Wisdom" },
  { id: "EB02-015", name: "Jewelry Bonney", set: "Anime 25th Collection", setCode: "EB02", number: "015", type: "Character", color: "Green", rarity: "SuperRare", cost: 7, power: 7000, attribute: "Special" },
  { id: "EB02-016", name: "Chopperman", set: "Anime 25th Collection", setCode: "EB02", number: "016", type: "Character", color: "Green", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "EB02-017", name: "Nami", set: "Anime 25th Collection", setCode: "EB02", number: "017", type: "Character", color: "Green", rarity: "R", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "EB02-018", name: "Buggy", set: "Anime 25th Collection", setCode: "EB02", number: "018", type: "Character", color: "Green", rarity: "R", cost: 4, power: 6000, attribute: "Slash" },
  { id: "EB02-019", name: "Roronoa Zoro", set: "Anime 25th Collection", setCode: "EB02", number: "019", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000, attribute: "Slash" },
  { id: "EB02-020", name: "We Are!", set: "Anime 25th Collection", setCode: "EB02", number: "020", type: "Event", color: "Green", rarity: "R", cost: 2 },
  { id: "EB02-021", name: "Gum-Gum Giant Pistol", set: "Anime 25th Collection", setCode: "EB02", number: "021", type: "Event", color: "Green", rarity: "C", cost: 3 },
  { id: "EB02-022", name: "Usopp", set: "Anime 25th Collection", setCode: "EB02", number: "022", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "EB02-023", name: "Crocodile", set: "Anime 25th Collection", setCode: "EB02", number: "023", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000, attribute: "Special" },
  { id: "EB02-024", name: "Sogeking", set: "Anime 25th Collection", setCode: "EB02", number: "024", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "EB02-025", name: "Donquixote Rosinante", set: "Anime 25th Collection", setCode: "EB02", number: "025", type: "Character", color: "Blue", rarity: "R", cost: 2, power: 3000, attribute: "Special" },
  { id: "EB02-026", name: "Nefeltari Vivi", set: "Anime 25th Collection", setCode: "EB02", number: "026", type: "Character", color: "Blue", rarity: "SuperRare", cost: 3, power: 2000, attribute: "Slash" },
  { id: "EB02-027", name: "Vista", set: "Anime 25th Collection", setCode: "EB02", number: "027", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000, attribute: "Slash" },
  { id: "EB02-028", name: "Portgas.D.Ace", set: "Anime 25th Collection", setCode: "EB02", number: "028", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 5000, attribute: "Special" },
  { id: "EB02-029", name: "Grandpa Ryu", set: "Anime 25th Collection", setCode: "EB02", number: "029", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 5000, attribute: "Wisdom" },
  { id: "EB02-030", name: "And That's When Somebody Makes Fun of Their Friend's Dream!!!!", set: "Anime 25th Collection", setCode: "EB02", number: "030", type: "Event", color: "Blue", rarity: "C", cost: 2 },
  { id: "EB02-031", name: "Hope", set: "Anime 25th Collection", setCode: "EB02", number: "031", type: "Event", color: "Blue", rarity: "R", cost: 2 },
  { id: "EB02-032", name: "Iceburg", set: "Anime 25th Collection", setCode: "EB02", number: "032", type: "Character", color: "Purple", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "EB02-033", name: "Klabautermann", set: "Anime 25th Collection", setCode: "EB02", number: "033", type: "Character", color: "Purple", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "EB02-034", name: "Komei", set: "Anime 25th Collection", setCode: "EB02", number: "034", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 6000, attribute: "Wisdom" },
  { id: "EB02-035", name: "Sanji &amp; Pudding", set: "Anime 25th Collection", setCode: "EB02", number: "035", type: "Character", color: "Purple", rarity: "SuperRare", cost: 5, power: 7000, attribute: "Strike" },
  { id: "EB02-036", name: "Nico Robin", set: "Anime 25th Collection", setCode: "EB02", number: "036", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 2000, attribute: "Strike" },
  { id: "EB02-037", name: "Franky", set: "Anime 25th Collection", setCode: "EB02", number: "037", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 4000, attribute: "Strike" },
  { id: "EB02-038", name: "Magellan", set: "Anime 25th Collection", setCode: "EB02", number: "038", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000, attribute: "Special" },
  { id: "EB02-039", name: "GERMA 66", set: "Anime 25th Collection", setCode: "EB02", number: "039", type: "Event", color: "Purple", rarity: "C", cost: 4 },
  { id: "EB02-040", name: "BRAND NEW WORLD", set: "Anime 25th Collection", setCode: "EB02", number: "040", type: "Event", color: "Purple", rarity: "R", cost: 2 },
  { id: "EB02-041", name: "Merry Go", set: "Anime 25th Collection", setCode: "EB02", number: "041", type: "Stage", color: "Purple", rarity: "R", cost: 1 },
  { id: "EB02-042", name: "All-Hunt Grount", set: "Anime 25th Collection", setCode: "EB02", number: "042", type: "Character", color: "Black", rarity: "C", cost: 6, power: 8000, attribute: "Strike" },
  { id: "EB02-043", name: "Jonathan", set: "Anime 25th Collection", setCode: "EB02", number: "043", type: "Character", color: "Black", rarity: "C", cost: 7, power: 9000, attribute: "Wisdom" },
  { id: "EB02-044", name: "Sengoku", set: "Anime 25th Collection", setCode: "EB02", number: "044", type: "Character", color: "Black", rarity: "SuperRare", cost: 7, power: 7000, attribute: "Wisdom" },
  { id: "EB02-045", name: "Trafalgar Law", set: "Anime 25th Collection", setCode: "EB02", number: "045", type: "Character", color: "Black", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Slash" },
  { id: "EB02-046", name: "Hildon", set: "Anime 25th Collection", setCode: "EB02", number: "046", type: "Character", color: "Black", rarity: "C", cost: 3, power: 3000, attribute: "Wisdom" },
  { id: "EB02-047", name: "Blueno", set: "Anime 25th Collection", setCode: "EB02", number: "047", type: "Character", color: "Black", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "EB02-048", name: "Brook", set: "Anime 25th Collection", setCode: "EB02", number: "048", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "EB02-049", name: "Monkey.D.Garp", set: "Anime 25th Collection", setCode: "EB02", number: "049", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000, attribute: "Strike" },
  { id: "EB02-050", name: "Kokoro no Chizu", set: "Anime 25th Collection", setCode: "EB02", number: "050", type: "Event", color: "Black", rarity: "R", cost: 2 },
  { id: "EB02-051", name: "Three-Pace Hum Soul Notch Slash", set: "Anime 25th Collection", setCode: "EB02", number: "051", type: "Event", color: "Black", rarity: "C", cost: 3 },
  { id: "EB02-052", name: "Enel", set: "Anime 25th Collection", setCode: "EB02", number: "052", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 10, power: 11000, attribute: "Special" },
  { id: "EB02-053", name: "Myskina Olga", set: "Anime 25th Collection", setCode: "EB02", number: "053", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Wisdom" },
  { id: "EB02-054", name: "Sanji", set: "Anime 25th Collection", setCode: "EB02", number: "054", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000, attribute: "Strike" },
  { id: "EB02-055", name: "Jinbe", set: "Anime 25th Collection", setCode: "EB02", number: "055", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "EB02-056", name: "Vegapunk", set: "Anime 25th Collection", setCode: "EB02", number: "056", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 5, attribute: "Wisdom" },
  { id: "EB02-057", name: "Mad Treasure", set: "Anime 25th Collection", setCode: "EB02", number: "057", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 5000, attribute: "Special" },
  { id: "EB02-058", name: "UUUUUS!", set: "Anime 25th Collection", setCode: "EB02", number: "058", type: "Event", color: "Yellow", rarity: "R", cost: 2 },
  { id: "EB02-059", name: "Without Your Help I Can't Become the King of the Pirates!!!!", set: "Anime 25th Collection", setCode: "EB02", number: "059", type: "Event", color: "Yellow", rarity: "C", cost: 4 },
  { id: "EB02-060", name: "Merry Go", set: "Anime 25th Collection", setCode: "EB02", number: "060", type: "Stage", color: "Yellow", rarity: "C", cost: 2 },
  { id: "EB02-061", name: "Monkey.D.Luffy", set: "Anime 25th Collection", setCode: "EB02", number: "061", type: "Character", color: "Purple", rarity: "SecretRare", cost: 6, power: 7000, attribute: "Strike" },
];

export default EB02_CARDS;
