// EB03: ONE PIECE HEROINES EDITION - Synced from official cardlist
// 90 entries including variants
const EB03_CARDS = [
  { id: "EB03-001", name: "Nefeltari Vivi", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "001", type: "Leader", color: "Red/Blue", rarity: "L", cost: 4, power: 5000 },
  { id: "EB03-001_p1", name: "Nefeltari Vivi (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "001", type: "Leader", color: "Red/Blue", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=EB03-001&variant=p1" },
  { id: "EB03-002", name: "Ain", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "002", type: "Character", color: "Red", rarity: "C", cost: 5, power: 6000 },
  { id: "EB03-003", name: "Uta", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "003", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 7000 },
  { id: "EB03-003_p1", name: "Uta (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "003", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 7000, imageUrl: "/api/card-image?id=EB03-003&variant=p1" },
  { id: "EB03-004", name: "Carina", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "004", type: "Character", color: "Red", rarity: "C", cost: 3, power: 2000 },
  { id: "EB03-005", name: "Sugar", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "005", type: "Character", color: "Red", rarity: "R", cost: 3 },
  { id: "EB03-006", name: "Nami", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "006", type: "Character", color: "Red", rarity: "R", cost: 5, power: 7000 },
  { id: "EB03-007", name: "Baccarat", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "007", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000 },
  { id: "EB03-008", name: "Hibari", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "008", type: "Character", color: "Red", rarity: "R", cost: 3, power: 5000 },
  { id: "EB03-008_p1", name: "Hibari (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "008", type: "Character", color: "Red", rarity: "R", cost: 3, power: 5000, imageUrl: "/api/card-image?id=EB03-008&variant=p1" },
  { id: "EB03-009", name: "Makino", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "009", type: "Character", color: "Red", rarity: "C", cost: 1 },
  { id: "EB03-010", name: "Monet", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "010", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000 },
  { id: "EB03-011", name: "But If We Ever See Each Other Again... Will You Call Me Your Shipmate?!!", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "011", type: "Event", color: "Red", rarity: "C", cost: 1 },
  { id: "EB03-012", name: "Otama", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "012", type: "Character", color: "Green", rarity: "R", cost: 2 },
  { id: "EB03-013", name: "Carrot", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "013", type: "Character", color: "Green", rarity: "R", cost: 6, power: 7000 },
  { id: "EB03-013_p1", name: "Carrot (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "013", type: "Character", color: "Green", rarity: "R", cost: 6, power: 7000, imageUrl: "/api/card-image?id=EB03-013&variant=p1" },
  { id: "EB03-014", name: "Kuina", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "014", type: "Character", color: "Green", rarity: "C", cost: 2 },
  { id: "EB03-015", name: "Camie", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "015", type: "Character", color: "Green", rarity: "C", cost: 2 },
  { id: "EB03-016", name: "Kouzuki Hiyori", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "016", type: "Character", color: "Green", rarity: "C", cost: 1 },
  { id: "EB03-017", name: "Jewelry Bonney", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "017", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000 },
  { id: "EB03-018", name: "Tashigi", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "018", type: "Character", color: "Green", rarity: "SR", cost: 4, power: 6000 },
  { id: "EB03-018_p1", name: "Tashigi (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "018", type: "Character", color: "Green", rarity: "SR", cost: 4, power: 6000, imageUrl: "/api/card-image?id=EB03-018&variant=p1" },
  { id: "EB03-019", name: "Wanda", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "019", type: "Character", color: "Green", rarity: "C", cost: 6, power: 7000 },
  { id: "EB03-020", name: "There You Are, Sore Loser!", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "020", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "EB03-021", name: "Alvida", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "021", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 2000 },
  { id: "EB03-022", name: "Isuka", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "022", type: "Character", color: "Blue", rarity: "R", cost: 6, power: 6000 },
  { id: "EB03-023", name: "Kaya", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "023", type: "Character", color: "Blue", rarity: "C", cost: 2 },
  { id: "EB03-024", name: "Nefeltari Vivi", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "024", type: "Character", color: "Blue", rarity: "SR", cost: 5, power: 4000 },
  { id: "EB03-024_p1", name: "Nefeltari Vivi (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "024", type: "Character", color: "Blue", rarity: "SR", cost: 5, power: 4000, imageUrl: "/api/card-image?id=EB03-024&variant=p1" },
  { id: "EB03-025", name: "Hina", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "025", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000 },
  { id: "EB03-025_p1", name: "Hina (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "025", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000, imageUrl: "/api/card-image?id=EB03-025&variant=p1" },
  { id: "EB03-026", name: "Boa Hancock", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "026", type: "Character", color: "Blue", rarity: "SR", cost: 6, power: 8000 },
  { id: "EB03-026_p1", name: "Boa Hancock (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "026", type: "Character", color: "Blue", rarity: "SR", cost: 6, power: 8000, imageUrl: "/api/card-image?id=EB03-026&variant=p1" },
  { id: "EB03-027", name: "Marguerite", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "027", type: "Character", color: "Blue", rarity: "R", cost: 6, power: 7000 },
  { id: "EB03-028", name: "Yu", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "028", type: "Character", color: "Blue", rarity: "C", cost: 2 },
  { id: "EB03-029", name: "Insolent Fool!! Stand Down!!", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "029", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "EB03-030", name: "Viola", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "030", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 6000 },
  { id: "EB03-031", name: "Vinsmoke Reiju", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "031", type: "Character", color: "Purple", rarity: "SR", cost: 5, power: 5000 },
  { id: "EB03-031_p1", name: "Vinsmoke Reiju (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "031", type: "Character", color: "Purple", rarity: "SR", cost: 5, power: 5000, imageUrl: "/api/card-image?id=EB03-031&variant=p1" },
  { id: "EB03-032", name: "Charlotte Flampe", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "032", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 2000 },
  { id: "EB03-033", name: "Charlotte Brulee", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "033", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 6000 },
  { id: "EB03-034", name: "Charlotte Linlin", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "034", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 7000 },
  { id: "EB03-034_p1", name: "Charlotte Linlin (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "034", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 7000, imageUrl: "/api/card-image?id=EB03-034&variant=p1" },
  { id: "EB03-035", name: "Charlotte Pudding", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "035", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 4000 },
  { id: "EB03-036", name: "Baby 5", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "036", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 2000 },
  { id: "EB03-037", name: "Lim", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "037", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000 },
  { id: "EB03-038", name: "Thanks for the Treat. \u2661", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "038", type: "Event", color: "Purple", rarity: "C", cost: 1 },
  { id: "EB03-039", name: "Ulti", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "039", type: "Character", color: "Black", rarity: "R", cost: 6, power: 7000 },
  { id: "EB03-040", name: "Kalifa", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "040", type: "Character", color: "Black", rarity: "C", cost: 5, power: 6000 },
  { id: "EB03-041", name: "Kujyaku", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "041", type: "Character", color: "Black", rarity: "R", cost: 4, power: 6000 },
  { id: "EB03-041_p1", name: "Kujyaku (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "041", type: "Character", color: "Black", rarity: "R", cost: 4, power: 6000, imageUrl: "/api/card-image?id=EB03-041&variant=p1" },
  { id: "EB03-042", name: "Koala", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "042", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000 },
  { id: "EB03-042_p1", name: "Koala (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "042", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000, imageUrl: "/api/card-image?id=EB03-042&variant=p1" },
  { id: "EB03-043", name: "Stussy", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "043", type: "Character", color: "Black", rarity: "R", cost: 7, power: 7000 },
  { id: "EB03-044", name: "Black Maria", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "044", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000 },
  { id: "EB03-045", name: "Perona", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "045", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 6000 },
  { id: "EB03-045_p1", name: "Perona (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "045", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 6000, imageUrl: "/api/card-image?id=EB03-045&variant=p1" },
  { id: "EB03-046", name: "Miss Doublefinger(Zala)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "046", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000 },
  { id: "EB03-047", name: "Miss.Valentine(Mikita)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "047", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000 },
  { id: "EB03-048", name: "Rebecca", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "048", type: "Character", color: "Black", rarity: "R", cost: 2 },
  { id: "EB03-049", name: "I Knew You People Were Behind This.", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "049", type: "Event", color: "Black", rarity: "C", cost: 1 },
  { id: "EB03-050", name: "Conis", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "050", type: "Character", color: "Yellow", rarity: "C", cost: 2 },
  { id: "EB03-051", name: "Charlotte Smoothie", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "051", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 3000 },
  { id: "EB03-052", name: "Shirahoshi", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "052", type: "Character", color: "Yellow", rarity: "R", cost: 3 },
  { id: "EB03-053", name: "Nami", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "053", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000 },
  { id: "EB03-053_p1", name: "Nami (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "053", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000, imageUrl: "/api/card-image?id=EB03-053&variant=p1" },
  { id: "EB03-054", name: "Nico Robin", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "054", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000 },
  { id: "EB03-055", name: "Nico Robin", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "055", type: "Character", color: "Yellow", rarity: "SR", cost: 7, power: 8000 },
  { id: "EB03-055_p1", name: "Nico Robin (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "055", type: "Character", color: "Yellow", rarity: "SR", cost: 7, power: 8000, imageUrl: "/api/card-image?id=EB03-055&variant=p1" },
  { id: "EB03-056", name: "Belo Betty", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "056", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 3000 },
  { id: "EB03-057", name: "Yamato", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "057", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000 },
  { id: "EB03-057_p1", name: "Yamato (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "057", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000, imageUrl: "/api/card-image?id=EB03-057&variant=p1" },
  { id: "EB03-058", name: "Lilith", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "058", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000 },
  { id: "EB03-059", name: "S-Snake", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "059", type: "Character", color: "Yellow", rarity: "R", cost: 6, power: 7000 },
  { id: "EB03-060", name: "Will You Be My Servant?", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "060", type: "Event", color: "Yellow", rarity: "C", cost: 1 },
  { id: "EB03-061", name: "Uta", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "061", type: "Character", color: "Green", rarity: "SEC", cost: 7, power: 8000 },
  { id: "EB03-061_p1", name: "Uta (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "061", type: "Character", color: "Green", rarity: "SEC", cost: 7, power: 8000, imageUrl: "/api/card-image?id=EB03-061&variant=p1" },
  { id: "EB03-061_p2", name: "Uta (Manga)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "061", type: "Character", color: "Green", rarity: "SEC", cost: 7, power: 8000, imageUrl: "/api/card-image?id=EB03-061&variant=p2" },
  { id: "EB03-062", name: "Trafalgar Law", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "062", type: "Character", color: "Yellow", rarity: "SEC", cost: 8, power: 6000 },
  { id: "EB03-062_p1", name: "Trafalgar Law (Alt Art)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "062", type: "Character", color: "Yellow", rarity: "SEC", cost: 8, power: 6000, imageUrl: "/api/card-image?id=EB03-062&variant=p1" },
  { id: "EB03-003_p2", name: "Uta (Manga)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "003", type: "Character", color: "Red", rarity: "SP", cost: 5, power: 7000, imageUrl: "/api/card-image?id=EB03-003&variant=p2" },
  { id: "EB03-018_p2", name: "Tashigi (SP)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "018", type: "Character", color: "Green", rarity: "SP", cost: 4, power: 6000, imageUrl: "/api/card-image?id=EB03-018&variant=p2" },
  { id: "EB03-024_p2", name: "Nefeltari Vivi (SP)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "024", type: "Character", color: "Blue", rarity: "SP", cost: 5, power: 4000, imageUrl: "/api/card-image?id=EB03-024&variant=p2" },
  { id: "EB03-026_p2", name: "Boa Hancock (SP)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "026", type: "Character", color: "Blue", rarity: "SP", cost: 6, power: 8000, imageUrl: "/api/card-image?id=EB03-026&variant=p2" },
  { id: "EB03-031_p2", name: "Vinsmoke Reiju (SP)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "031", type: "Character", color: "Purple", rarity: "SP", cost: 5, power: 5000, imageUrl: "/api/card-image?id=EB03-031&variant=p2" },
  { id: "EB03-042_p2", name: "Koala (SP)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "042", type: "Character", color: "Black", rarity: "SP", cost: 4, power: 5000, imageUrl: "/api/card-image?id=EB03-042&variant=p2" },
  { id: "EB03-045_p2", name: "Perona (SP)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "045", type: "Character", color: "Black", rarity: "SP", cost: 4, power: 6000, imageUrl: "/api/card-image?id=EB03-045&variant=p2" },
  { id: "EB03-053_p2", name: "Nami (SP)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "053", type: "Character", color: "Yellow", rarity: "SP", cost: 5, power: 6000, imageUrl: "/api/card-image?id=EB03-053&variant=p2" },
  { id: "EB03-055_p2", name: "Nico Robin (SP)", set: "ONE PIECE HEROINES EDITION", setCode: "EB03", number: "055", type: "Character", color: "Yellow", rarity: "SP", cost: 7, power: 8000, imageUrl: "/api/card-image?id=EB03-055&variant=p2" },
];

export default EB03_CARDS;
