// EB04: THE AZURE SEA’S SEVEN - Synced from official cardlist
// 40 entries including variants
const EB04_CARDS = [
  { id: "EB04-011", name: "Scaled Neptunian", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "011", type: "Character", color: "Green", rarity: "C", cost: 7, power: 8000 },
  { id: "EB04-012", name: "Kikunojo", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "012", type: "Character", color: "Green", rarity: "SR", cost: 7, power: 8000 },
  { id: "EB04-012_p1", name: "Kikunojo (Alt Art)", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "012", type: "Character", color: "Green", rarity: "SR", cost: 7, power: 8000, imageUrl: "/api/card-image?id=EB04-012&variant=p1" },
  { id: "EB04-013", name: "Carrot", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "013", type: "Character", color: "Green", rarity: "SR", cost: 8, power: 9000 },
  { id: "EB04-013_p1", name: "Carrot (Alt Art)", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "013", type: "Character", color: "Green", rarity: "SR", cost: 8, power: 9000, imageUrl: "/api/card-image?id=EB04-013&variant=p1" },
  { id: "EB04-014", name: "Kozuki Sukiyaki", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "014", type: "Character", color: "Green", rarity: "C", cost: 3 },
  { id: "EB04-015", name: "Jinbe", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "015", type: "Character", color: "Green", rarity: "R", cost: 7, power: 8000 },
  { id: "EB04-016", name: "Bird Neptunian", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "016", type: "Character", color: "Green", rarity: "C", cost: 5, power: 7000 },
  { id: "EB04-017", name: "Mystoms", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "017", type: "Character", color: "Green", rarity: "C", cost: 6, power: 5000 },
  { id: "EB04-018", name: "Megalo", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "018", type: "Character", color: "Green", rarity: "R", cost: 4, power: 4000 },
  { id: "EB04-018_p1", name: "Megalo (Alt Art)", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "018", type: "Character", color: "Green", rarity: "R", cost: 4, power: 4000, imageUrl: "/api/card-image?id=EB04-018&variant=p1" },
  { id: "EB04-019", name: "Eleclaw", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "019", type: "Event", color: "Green", rarity: "R", cost: 1 },
  { id: "EB04-020", name: "Shark Brick Fist", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "020", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "EB04-021", name: "Igaram", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "021", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "EB04-022", name: "Issho", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "022", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 7000 },
  { id: "EB04-022_p1", name: "Issho (Alt Art)", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "022", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 7000, imageUrl: "/api/card-image?id=EB04-022&variant=p1" },
  { id: "EB04-023", name: "Chaka & Pell", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "023", type: "Character", color: "Blue", rarity: "R", cost: 8, power: 9000 },
  { id: "EB04-024", name: "Terracotta", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "024", type: "Character", color: "Blue", rarity: "C", cost: 2 },
  { id: "EB04-025", name: "Nefeltari Vivi", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "025", type: "Character", color: "Blue", rarity: "SR", cost: 7, power: 4000 },
  { id: "EB04-025_p1", name: "Nefeltari Vivi (Alt Art)", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "025", type: "Character", color: "Blue", rarity: "SR", cost: 7, power: 4000, imageUrl: "/api/card-image?id=EB04-025&variant=p1" },
  { id: "EB04-026", name: "Bluegrass", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "026", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 6000 },
  { id: "EB04-027", name: "Boa Hancock", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "027", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 7000 },
  { id: "EB04-028", name: "Ice Time", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "028", type: "Event", color: "Blue", rarity: "R", cost: 5 },
  { id: "EB04-029", name: "I Heard the Sound...of a Lady's Teardrops Falling", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "029", type: "Event", color: "Blue", rarity: "UC", cost: 1 },
  { id: "EB04-030", name: "Kaido", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "030", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 9000 },
  { id: "EB04-031", name: "King", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "031", type: "Character", color: "Purple", rarity: "R", cost: 6, power: 7000 },
  { id: "EB04-031_p1", name: "King (Alt Art)", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "031", type: "Character", color: "Purple", rarity: "R", cost: 6, power: 7000, imageUrl: "/api/card-image?id=EB04-031&variant=p1" },
  { id: "EB04-032", name: "Queen", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "032", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 1000 },
  { id: "EB04-033", name: "Groggy Monsters", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "033", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 6000 },
  { id: "EB04-034", name: "Charlotte Pudding", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "034", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 1000 },
  { id: "EB04-035", name: "Hitokiri Kamazo", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "035", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "EB04-036", name: "Foxy", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "036", type: "Character", color: "Purple", rarity: "SR", cost: 8, power: 9000 },
  { id: "EB04-036_p1", name: "Foxy (Alt Art)", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "036", type: "Character", color: "Purple", rarity: "SR", cost: 8, power: 9000, imageUrl: "/api/card-image?id=EB04-036&variant=p1" },
  { id: "EB04-037", name: "Porche", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "037", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 2000 },
  { id: "EB04-038", name: "Rosinante & Law", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "038", type: "Character", color: "Purple", rarity: "SR", cost: 6, power: 8000 },
  { id: "EB04-038_p1", name: "Rosinante & Law (Alt Art)", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "038", type: "Character", color: "Purple", rarity: "SR", cost: 6, power: 8000, imageUrl: "/api/card-image?id=EB04-038&variant=p1" },
  { id: "EB04-039", name: "Eustass\"Captain\"Kid", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "039", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 8000 },
  { id: "EB04-040", name: "Flame Dragon Torch", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "040", type: "Event", color: "Purple", rarity: "R", cost: 1 },
  { id: "EB04-041", name: "Stealth Black", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "041", type: "Event", color: "Purple", rarity: "C", cost: 3 },
  { id: "EB04-039_p1", name: "Eustass\"Captain\"Kid (SP)", set: "THE AZURE SEA’S SEVEN", setCode: "EB04", number: "039", type: "Character", color: "Purple", rarity: "SP", cost: 7, power: 8000, imageUrl: "/api/card-image?id=EB04-039&variant=p1" },
];

export default EB04_CARDS;
