import type { Card } from './cards';

const OP01_CARDS: Card[] = [
  { id: "OP01-001", name: "Roronoa Zoro", set: "Romance Dawn", setCode: "OP01", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP01-002", name: "Trafalgar Law", set: "Romance Dawn", setCode: "OP01", number: "002", type: "Leader", color: "Red/Green", rarity: "L", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP01-003", name: "Monkey.D.Luffy", set: "Romance Dawn", setCode: "OP01", number: "003", type: "Leader", color: "Red/Green", rarity: "L", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP01-004", name: "Usopp", set: "Romance Dawn", setCode: "OP01", number: "004", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000, attribute: "Ranged" },
  { id: "OP01-005", name: "Uta", set: "Romance Dawn", setCode: "OP01", number: "005", type: "Character", color: "Red", rarity: "R", cost: 4, power: 4000, attribute: "Special" },
  { id: "OP01-006", name: "Otama", set: "Romance Dawn", setCode: "OP01", number: "006", type: "Character", color: "Red", rarity: "UC", cost: 1, attribute: "Special" },
  { id: "OP01-007", name: "Caribou", set: "Romance Dawn", setCode: "OP01", number: "007", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP01-008", name: "Cavendish", set: "Romance Dawn", setCode: "OP01", number: "008", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP01-009", name: "Carrot", set: "Romance Dawn", setCode: "OP01", number: "009", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP01-010", name: "Komachiyo", set: "Romance Dawn", setCode: "OP01", number: "010", type: "Character", color: "Red", rarity: "C", cost: 1, power: 3000, attribute: "Strike" },
  { id: "OP01-011", name: "Gordon", set: "Romance Dawn", setCode: "OP01", number: "011", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000, attribute: "Wisdom" },
  { id: "OP01-012", name: "Sai", set: "Romance Dawn", setCode: "OP01", number: "012", type: "Character", color: "Red", rarity: "C", cost: 2, power: 4000, attribute: "Slash" },
  { id: "OP01-013", name: "Sanji", set: "Romance Dawn", setCode: "OP01", number: "013", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP01-014", name: "Jinbe", set: "Romance Dawn", setCode: "OP01", number: "014", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP01-015", name: "Tony Tony.Chopper", set: "Romance Dawn", setCode: "OP01", number: "015", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000, attribute: "Wisdom" },
  { id: "OP01-016", name: "Nami", set: "Romance Dawn", setCode: "OP01", number: "016", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000, attribute: "Special" },
  { id: "OP01-017", name: "Nico Robin", set: "Romance Dawn", setCode: "OP01", number: "017", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP01-018", name: "Hajrudin", set: "Romance Dawn", setCode: "OP01", number: "018", type: "Character", color: "Red", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP01-019", name: "Bartolomeo", set: "Romance Dawn", setCode: "OP01", number: "019", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000, attribute: "Special" },
  { id: "OP01-020", name: "Hyogoro", set: "Romance Dawn", setCode: "OP01", number: "020", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP01-021", name: "Franky", set: "Romance Dawn", setCode: "OP01", number: "021", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000, attribute: "Ranged" },
  { id: "OP01-022", name: "Brook", set: "Romance Dawn", setCode: "OP01", number: "022", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP01-023", name: "Marco", set: "Romance Dawn", setCode: "OP01", number: "023", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP01-024", name: "Monkey.D.Luffy", set: "Romance Dawn", setCode: "OP01", number: "024", type: "Character", color: "Red", rarity: "SuperRare", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP01-025", name: "Roronoa Zoro", set: "Romance Dawn", setCode: "OP01", number: "025", type: "Character", color: "Red", rarity: "SuperRare", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP01-026", name: "Gum-Gum Fire-Fist Pistol Red Hawk", set: "Romance Dawn", setCode: "OP01", number: "026", type: "Event", color: "Red", rarity: "R", cost: 2 },
  { id: "OP01-027", name: "Round Table", set: "Romance Dawn", setCode: "OP01", number: "027", type: "Event", color: "Red", rarity: "C", cost: 4 },
  { id: "OP01-028", name: "Green Star Rafflesia", set: "Romance Dawn", setCode: "OP01", number: "028", type: "Event", color: "Red", rarity: "C", cost: 1 },
  { id: "OP01-029", name: "Radical Beam!!", set: "Romance Dawn", setCode: "OP01", number: "029", type: "Event", color: "Red", rarity: "UC", cost: 1 },
  { id: "OP01-030", name: "In Two Years!! At the Sabaody Archipelago!!", set: "Romance Dawn", setCode: "OP01", number: "030", type: "Event", color: "Red", rarity: "UC", cost: 1 },
  { id: "OP01-031", name: "Kouzuki Oden", set: "Romance Dawn", setCode: "OP01", number: "031", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP01-032", name: "Ashura Doji", set: "Romance Dawn", setCode: "OP01", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP01-033", name: "Izo", set: "Romance Dawn", setCode: "OP01", number: "033", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 3000, attribute: "Ranged" },
  { id: "OP01-034", name: "Inuarashi", set: "Romance Dawn", setCode: "OP01", number: "034", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP01-035", name: "Okiku", set: "Romance Dawn", setCode: "OP01", number: "035", type: "Character", color: "Green", rarity: "R", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP01-036", name: "Otsuru", set: "Romance Dawn", setCode: "OP01", number: "036", type: "Character", color: "Green", rarity: "C", cost: 1, power: 3000, attribute: "Wisdom" },
  { id: "OP01-037", name: "Kawamatsu", set: "Romance Dawn", setCode: "OP01", number: "037", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP01-038", name: "Kanjuro", set: "Romance Dawn", setCode: "OP01", number: "038", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP01-039", name: "Killer", set: "Romance Dawn", setCode: "OP01", number: "039", type: "Character", color: "Green", rarity: "UC", cost: 2, power: 2000, attribute: "Slash" },
  { id: "OP01-040", name: "Kin'emon", set: "Romance Dawn", setCode: "OP01", number: "040", type: "Character", color: "Green", rarity: "SuperRare", cost: 6, power: 6000, attribute: "Slash" },
  { id: "OP01-041", name: "Kouzuki Momonosuke", set: "Romance Dawn", setCode: "OP01", number: "041", type: "Character", color: "Green", rarity: "R", cost: 1, attribute: "Slash" },
  { id: "OP01-042", name: "Komurasaki", set: "Romance Dawn", setCode: "OP01", number: "042", type: "Character", color: "Green", rarity: "UC", cost: 1, attribute: "Wisdom" },
  { id: "OP01-043", name: "Shinobu", set: "Romance Dawn", setCode: "OP01", number: "043", type: "Character", color: "Green", rarity: "C", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP01-044", name: "Shachi", set: "Romance Dawn", setCode: "OP01", number: "044", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP01-045", name: "Jean Bart", set: "Romance Dawn", setCode: "OP01", number: "045", type: "Character", color: "Green", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP01-046", name: "Denjiro", set: "Romance Dawn", setCode: "OP01", number: "046", type: "Character", color: "Green", rarity: "R", cost: 5, power: 7000, attribute: "Slash" },
  { id: "OP01-047", name: "Trafalgar Law", set: "Romance Dawn", setCode: "OP01", number: "047", type: "Character", color: "Green", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP01-048", name: "Nekomamushi", set: "Romance Dawn", setCode: "OP01", number: "048", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP01-049", name: "Bepo", set: "Romance Dawn", setCode: "OP01", number: "049", type: "Character", color: "Green", rarity: "R", cost: 4, power: 4000, attribute: "Strike" },
  { id: "OP01-050", name: "Penguin", set: "Romance Dawn", setCode: "OP01", number: "050", type: "Character", color: "Green", rarity: "C", cost: 3, power: 2000, attribute: "Strike" },
  { id: "OP01-051", name: "Eustass\"Captain\"Kid", set: "Romance Dawn", setCode: "OP01", number: "051", type: "Character", color: "Green", rarity: "SuperRare", cost: 8, power: 8000, attribute: "Special" },
  { id: "OP01-052", name: "Raizo", set: "Romance Dawn", setCode: "OP01", number: "052", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP01-053", name: "Wire", set: "Romance Dawn", setCode: "OP01", number: "053", type: "Character", color: "Green", rarity: "C", cost: 2, power: 4000, attribute: "Slash" },
  { id: "OP01-054", name: "X.Drake", set: "Romance Dawn", setCode: "OP01", number: "054", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP01-055", name: "You Can Be My Samurai!!", set: "Romance Dawn", setCode: "OP01", number: "055", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "OP01-056", name: "Demon Face", set: "Romance Dawn", setCode: "OP01", number: "056", type: "Event", color: "Green", rarity: "UC", cost: 6 },
  { id: "OP01-057", name: "Paradise Waterfall", set: "Romance Dawn", setCode: "OP01", number: "057", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP01-058", name: "Punk Gibson", set: "Romance Dawn", setCode: "OP01", number: "058", type: "Event", color: "Green", rarity: "R", cost: 2 },
  { id: "OP01-059", name: "BE-BENG!!", set: "Romance Dawn", setCode: "OP01", number: "059", type: "Event", color: "Green", rarity: "C", cost: 3 },
  { id: "OP01-060", name: "Donquixote Doflamingo", set: "Romance Dawn", setCode: "OP01", number: "060", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP01-061", name: "Kaido", set: "Romance Dawn", setCode: "OP01", number: "061", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP01-062", name: "Crocodile", set: "Romance Dawn", setCode: "OP01", number: "062", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP01-063", name: "Arlong", set: "Romance Dawn", setCode: "OP01", number: "063", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP01-064", name: "Alvida", set: "Romance Dawn", setCode: "OP01", number: "064", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP01-065", name: "Vergo", set: "Romance Dawn", setCode: "OP01", number: "065", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "OP01-066", name: "Krieg", set: "Romance Dawn", setCode: "OP01", number: "066", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP01-067", name: "Crocodile", set: "Romance Dawn", setCode: "OP01", number: "067", type: "Character", color: "Blue", rarity: "SuperRare", cost: 7, power: 7000, attribute: "Special" },
  { id: "OP01-068", name: "Gecko Moria", set: "Romance Dawn", setCode: "OP01", number: "068", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP01-069", name: "Caesar Clown", set: "Romance Dawn", setCode: "OP01", number: "069", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP01-070", name: "Dracule Mihawk", set: "Romance Dawn", setCode: "OP01", number: "070", type: "Character", color: "Blue", rarity: "SuperRare", cost: 9, power: 9000, attribute: "Slash" },
  { id: "OP01-071", name: "Jinbe", set: "Romance Dawn", setCode: "OP01", number: "071", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 2000, attribute: "Strike" },
  { id: "OP01-072", name: "Smiley", set: "Romance Dawn", setCode: "OP01", number: "072", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 1000, attribute: "Special" },
  { id: "OP01-073", name: "Donquixote Doflamingo", set: "Romance Dawn", setCode: "OP01", number: "073", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP01-074", name: "Bartholomew Kuma", set: "Romance Dawn", setCode: "OP01", number: "074", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP01-075", name: "Pacifista", set: "Romance Dawn", setCode: "OP01", number: "075", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP01-076", name: "Bellamy", set: "Romance Dawn", setCode: "OP01", number: "076", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 4000, attribute: "Strike" },
  { id: "OP01-077", name: "Perona", set: "Romance Dawn", setCode: "OP01", number: "077", type: "Character", color: "Blue", rarity: "UC", cost: 1, power: 2000, attribute: "Special" },
  { id: "OP01-078", name: "Boa Hancock", set: "Romance Dawn", setCode: "OP01", number: "078", type: "Character", color: "Blue", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP01-079", name: "Ms. All Sunday", set: "Romance Dawn", setCode: "OP01", number: "079", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 1000, attribute: "Strike" },
  { id: "OP01-080", name: "Miss Doublefinger(Zala)", set: "Romance Dawn", setCode: "OP01", number: "080", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP01-081", name: "Mocha", set: "Romance Dawn", setCode: "OP01", number: "081", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP01-082", name: "Monet", set: "Romance Dawn", setCode: "OP01", number: "082", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP01-083", name: "Mr.1(Daz.Bonez)", set: "Romance Dawn", setCode: "OP01", number: "083", type: "Character", color: "Blue", rarity: "UC", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP01-084", name: "Mr.2.Bon.Kurei(Bentham)", set: "Romance Dawn", setCode: "OP01", number: "084", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP01-085", name: "Mr.3(Galdino)", set: "Romance Dawn", setCode: "OP01", number: "085", type: "Character", color: "Blue", rarity: "UC", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP01-086", name: "Overheat", set: "Romance Dawn", setCode: "OP01", number: "086", type: "Event", color: "Blue", rarity: "R", cost: 2 },
  { id: "OP01-087", name: "Officer Agents", set: "Romance Dawn", setCode: "OP01", number: "087", type: "Event", color: "Blue", rarity: "C", cost: 2 },
  { id: "OP01-088", name: "Desert Spada", set: "Romance Dawn", setCode: "OP01", number: "088", type: "Event", color: "Blue", rarity: "UC", cost: 1 },
  { id: "OP01-089", name: "Crescent Cutlass", set: "Romance Dawn", setCode: "OP01", number: "089", type: "Event", color: "Blue", rarity: "C", cost: 3 },
  { id: "OP01-090", name: "Baroque Works", set: "Romance Dawn", setCode: "OP01", number: "090", type: "Event", color: "Blue", rarity: "UC", cost: 1 },
  { id: "OP01-091", name: "King", set: "Romance Dawn", setCode: "OP01", number: "091", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP01-092", name: "Urashima", set: "Romance Dawn", setCode: "OP01", number: "092", type: "Character", color: "Purple", rarity: "C", cost: 7, power: 9000, attribute: "Strike" },
  { id: "OP01-093", name: "Ulti", set: "Romance Dawn", setCode: "OP01", number: "093", type: "Character", color: "Purple", rarity: "R", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP01-094", name: "Kaido", set: "Romance Dawn", setCode: "OP01", number: "094", type: "Character", color: "Purple", rarity: "SuperRare", cost: 10, power: 12000, attribute: "Strike" },
  { id: "OP01-095", name: "Kyoshirou", set: "Romance Dawn", setCode: "OP01", number: "095", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP01-096", name: "King", set: "Romance Dawn", setCode: "OP01", number: "096", type: "Character", color: "Purple", rarity: "SuperRare", cost: 7, power: 7000, attribute: "Special" },
  { id: "OP01-097", name: "Queen", set: "Romance Dawn", setCode: "OP01", number: "097", type: "Character", color: "Purple", rarity: "R", cost: 6, power: 5000, attribute: "Strike" },
  { id: "OP01-098", name: "Kurozumi Orochi", set: "Romance Dawn", setCode: "OP01", number: "098", type: "Character", color: "Purple", rarity: "UC", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP01-099", name: "Kurozumi Semimaru", set: "Romance Dawn", setCode: "OP01", number: "099", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP01-100", name: "Kurozumi Higurashi", set: "Romance Dawn", setCode: "OP01", number: "100", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP01-101", name: "Sasaki", set: "Romance Dawn", setCode: "OP01", number: "101", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP01-102", name: "Jack", set: "Romance Dawn", setCode: "OP01", number: "102", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP01-103", name: "Scratchmen Apoo", set: "Romance Dawn", setCode: "OP01", number: "103", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 6000, attribute: "Ranged" },
  { id: "OP01-104", name: "Speed", set: "Romance Dawn", setCode: "OP01", number: "104", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP01-105", name: "Bao Huang", set: "Romance Dawn", setCode: "OP01", number: "105", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000, attribute: "Wisdom" },
  { id: "OP01-106", name: "Basil Hawkins", set: "Romance Dawn", setCode: "OP01", number: "106", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 2000, attribute: "Slash" },
  { id: "OP01-107", name: "Babanuki", set: "Romance Dawn", setCode: "OP01", number: "107", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 7000, attribute: "Ranged" },
  { id: "OP01-108", name: "Hitokiri Kamazo", set: "Romance Dawn", setCode: "OP01", number: "108", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP01-109", name: "Who's.Who", set: "Romance Dawn", setCode: "OP01", number: "109", type: "Character", color: "Purple", rarity: "UC", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP01-110", name: "Fukurokuju", set: "Romance Dawn", setCode: "OP01", number: "110", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 8000, attribute: "Special" },
  { id: "OP01-111", name: "Black Maria", set: "Romance Dawn", setCode: "OP01", number: "111", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP01-112", name: "Page One", set: "Romance Dawn", setCode: "OP01", number: "112", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP01-113", name: "Holedem", set: "Romance Dawn", setCode: "OP01", number: "113", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP01-114", name: "X.Drake", set: "Romance Dawn", setCode: "OP01", number: "114", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP01-115", name: "Elephant's Marchoo", set: "Romance Dawn", setCode: "OP01", number: "115", type: "Event", color: "Purple", rarity: "C", cost: 4 },
  { id: "OP01-116", name: "Artificial Devil Fruit SMILE", set: "Romance Dawn", setCode: "OP01", number: "116", type: "Event", color: "Purple", rarity: "UC", cost: 2 },
  { id: "OP01-117", name: "Sheep's Horn", set: "Romance Dawn", setCode: "OP01", number: "117", type: "Event", color: "Purple", rarity: "C", cost: 2 },
  { id: "OP01-118", name: "Ulti-Mortar", set: "Romance Dawn", setCode: "OP01", number: "118", type: "Event", color: "Purple", rarity: "UC", cost: 1 },
  { id: "OP01-119", name: "Thunder Bagua", set: "Romance Dawn", setCode: "OP01", number: "119", type: "Event", color: "Purple", rarity: "R", cost: 2 },
  { id: "OP01-120", name: "Shanks", set: "Romance Dawn", setCode: "OP01", number: "120", type: "Character", color: "Red", rarity: "SecretRare", cost: 9, power: 10000, attribute: "Slash" },
  { id: "OP01-121", name: "Yamato", set: "Romance Dawn", setCode: "OP01", number: "121", type: "Character", color: "Green", rarity: "SecretRare", cost: 5, power: 5000, attribute: "Strike" },
];

export default OP01_CARDS;
