import { Card } from "./cards";

// Paramount War (OP02) - Key cards
export const OP02_CARDS: Card[] = [
  // Leaders
  { id: "OP02-001", name: "Edward Newgate (Whitebeard)", set: "Paramount War", setCode: "OP02", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-002", name: "Portgas D. Ace", set: "Paramount War", setCode: "OP02", number: "002", type: "Leader", color: "Red", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-003", name: "Marco", set: "Paramount War", setCode: "OP02", number: "003", type: "Leader", color: "Red/Blue", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-004", name: "Sakazuki (Akainu)", set: "Paramount War", setCode: "OP02", number: "004", type: "Leader", color: "Blue/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-005", name: "Kuzan (Aokiji)", set: "Paramount War", setCode: "OP02", number: "005", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-006", name: "Boa Hancock", set: "Paramount War", setCode: "OP02", number: "006", type: "Leader", color: "Blue/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-007", name: "Dracule Mihawk", set: "Paramount War", setCode: "OP02", number: "007", type: "Leader", color: "Blue/Green", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-008", name: "Marshall D. Teach (Blackbeard)", set: "Paramount War", setCode: "OP02", number: "008", type: "Leader", color: "Purple/Black", rarity: "L", cost: 0, power: 5000 },
  
  // Red Cards
  { id: "OP02-009", name: "Curly Dadan", set: "Paramount War", setCode: "OP02", number: "009", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP02-010", name: "Thatch", set: "Paramount War", setCode: "OP02", number: "010", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP02-011", name: "Jozu", set: "Paramount War", setCode: "OP02", number: "011", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-012", name: "Squard", set: "Paramount War", setCode: "OP02", number: "012", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000 },
  { id: "OP02-013", name: "Speed Jiru", set: "Paramount War", setCode: "OP02", number: "013", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-014", name: "Namule", set: "Paramount War", setCode: "OP02", number: "014", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-015", name: "Vista", set: "Paramount War", setCode: "OP02", number: "015", type: "Character", color: "Red", rarity: "R", cost: 3, power: 5000 },
  { id: "OP02-016", name: "Fossa", set: "Paramount War", setCode: "OP02", number: "016", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-017", name: "Blamenco", set: "Paramount War", setCode: "OP02", number: "017", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP02-018", name: "Marco (SR)", set: "Paramount War", setCode: "OP02", number: "018", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP02-019", name: "Izou", set: "Paramount War", setCode: "OP02", number: "019", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-020", name: "Rakuyo", set: "Paramount War", setCode: "OP02", number: "020", type: "Character", color: "Red", rarity: "C", cost: 3, power: 3000 },
  { id: "OP02-021", name: "Kingdew", set: "Paramount War", setCode: "OP02", number: "021", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP02-022", name: "Haruta", set: "Paramount War", setCode: "OP02", number: "022", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-023", name: "Edward Newgate (SR)", set: "Paramount War", setCode: "OP02", number: "023", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP02-024", name: "Atmos", set: "Paramount War", setCode: "OP02", number: "024", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000 },
  { id: "OP02-025", name: "Blenheim", set: "Paramount War", setCode: "OP02", number: "025", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-026", name: "Curiel", set: "Paramount War", setCode: "OP02", number: "026", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-027", name: "Whitey Bay", set: "Paramount War", setCode: "OP02", number: "027", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 3000 },
  { id: "OP02-028", name: "Little Oars Jr.", set: "Paramount War", setCode: "OP02", number: "028", type: "Character", color: "Red", rarity: "R", cost: 7, power: 7000 },
  { id: "OP02-029", name: "Flower Sword Vista", set: "Paramount War", setCode: "OP02", number: "029", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 7000 },
  { id: "OP02-030", name: "Fire Fist", set: "Paramount War", setCode: "OP02", number: "030", type: "Event", color: "Red", rarity: "R", cost: 2 },
  { id: "OP02-031", name: "Great Earthquake", set: "Paramount War", setCode: "OP02", number: "031", type: "Event", color: "Red", rarity: "UC", cost: 4 },
  
  // Green Cards
  { id: "OP02-032", name: "Emporio Ivankov", set: "Paramount War", setCode: "OP02", number: "032", type: "Leader", color: "Green/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-033", name: "Buggy", set: "Paramount War", setCode: "OP02", number: "033", type: "Leader", color: "Green/Blue", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-034", name: "Daz Bonez (Mr. 1)", set: "Paramount War", setCode: "OP02", number: "034", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-035", name: "Galdino (Mr. 3)", set: "Paramount War", setCode: "OP02", number: "035", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP02-036", name: "Bentham (Mr. 2 Bon Clay)", set: "Paramount War", setCode: "OP02", number: "036", type: "Character", color: "Green", rarity: "R", cost: 3, power: 4000 },
  { id: "OP02-037", name: "Crocodile", set: "Paramount War", setCode: "OP02", number: "037", type: "Character", color: "Green", rarity: "SR", cost: 7, power: 7000 },
  { id: "OP02-038", name: "Doma", set: "Paramount War", setCode: "OP02", number: "038", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-039", name: "Emporio Ivankov", set: "Paramount War", setCode: "OP02", number: "039", type: "Character", color: "Green", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP02-040", name: "Inazuma", set: "Paramount War", setCode: "OP02", number: "040", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 3000 },
  { id: "OP02-041", name: "Crocodile (R)", set: "Paramount War", setCode: "OP02", number: "041", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-042", name: "Decalvan Brothers", set: "Paramount War", setCode: "OP02", number: "042", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-043", name: "Andre", set: "Paramount War", setCode: "OP02", number: "043", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-044", name: "Oimo & Kashii", set: "Paramount War", setCode: "OP02", number: "044", type: "Character", color: "Green", rarity: "UC", cost: 6, power: 8000 },
  { id: "OP02-045", name: "Buggy", set: "Paramount War", setCode: "OP02", number: "045", type: "Character", color: "Green", rarity: "R", cost: 2, power: 3000 },
  { id: "OP02-046", name: "Hannyabal", set: "Paramount War", setCode: "OP02", number: "046", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-047", name: "Whitebeard Pirates", set: "Paramount War", setCode: "OP02", number: "047", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP02-048", name: "New Kama Land", set: "Paramount War", setCode: "OP02", number: "048", type: "Stage", color: "Green", rarity: "R", cost: 1 },
  
  // Blue Cards
  { id: "OP02-049", name: "Koby", set: "Paramount War", setCode: "OP02", number: "049", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000 },
  { id: "OP02-050", name: "Tashigi", set: "Paramount War", setCode: "OP02", number: "050", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-051", name: "Smoker", set: "Paramount War", setCode: "OP02", number: "051", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-052", name: "Kuzan (Aokiji)", set: "Paramount War", setCode: "OP02", number: "052", type: "Character", color: "Blue", rarity: "SR", cost: 8, power: 9000 },
  { id: "OP02-053", name: "Borsalino (Kizaru)", set: "Paramount War", setCode: "OP02", number: "053", type: "Character", color: "Blue", rarity: "SR", cost: 8, power: 9000 },
  { id: "OP02-054", name: "Hina", set: "Paramount War", setCode: "OP02", number: "054", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP02-055", name: "Momonga", set: "Paramount War", setCode: "OP02", number: "055", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-056", name: "Jango", set: "Paramount War", setCode: "OP02", number: "056", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-057", name: "Fullbody", set: "Paramount War", setCode: "OP02", number: "057", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 2000 },
  { id: "OP02-058", name: "Garp", set: "Paramount War", setCode: "OP02", number: "058", type: "Character", color: "Blue", rarity: "SR", cost: 7, power: 8000 },
  { id: "OP02-059", name: "Sentomaru", set: "Paramount War", setCode: "OP02", number: "059", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-060", name: "Sengoku", set: "Paramount War", setCode: "OP02", number: "060", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000 },
  { id: "OP02-061", name: "Sakazuki (Akainu)", set: "Paramount War", setCode: "OP02", number: "061", type: "Character", color: "Blue", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP02-062", name: "Tsuru", set: "Paramount War", setCode: "OP02", number: "062", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-063", name: "Doberman", set: "Paramount War", setCode: "OP02", number: "063", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-064", name: "Onigumo", set: "Paramount War", setCode: "OP02", number: "064", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-065", name: "Strawberry", set: "Paramount War", setCode: "OP02", number: "065", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-066", name: "Yamakaji", set: "Paramount War", setCode: "OP02", number: "066", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-067", name: "Monkey D. Garp", set: "Paramount War", setCode: "OP02", number: "067", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 5000 },
  { id: "OP02-068", name: "Great Pirate Colosseum", set: "Paramount War", setCode: "OP02", number: "068", type: "Stage", color: "Blue", rarity: "R", cost: 1 },
  { id: "OP02-069", name: "Meteor Volcano", set: "Paramount War", setCode: "OP02", number: "069", type: "Event", color: "Blue", rarity: "R", cost: 3 },
  
  // Purple Cards
  { id: "OP02-070", name: "Gecko Moria", set: "Paramount War", setCode: "OP02", number: "070", type: "Leader", color: "Purple/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP02-071", name: "Absalom", set: "Paramount War", setCode: "OP02", number: "071", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-072", name: "Oars", set: "Paramount War", setCode: "OP02", number: "072", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 7000 },
  { id: "OP02-073", name: "Gecko Moria", set: "Paramount War", setCode: "OP02", number: "073", type: "Character", color: "Purple", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP02-074", name: "Perona", set: "Paramount War", setCode: "OP02", number: "074", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 3000 },
  { id: "OP02-075", name: "Hogback", set: "Paramount War", setCode: "OP02", number: "075", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-076", name: "Victoria Cindry", set: "Paramount War", setCode: "OP02", number: "076", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-077", name: "Kumashi", set: "Paramount War", setCode: "OP02", number: "077", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-078", name: "Shimotsuki Ryuma", set: "Paramount War", setCode: "OP02", number: "078", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 6000 },
  { id: "OP02-079", name: "Thriller Bark", set: "Paramount War", setCode: "OP02", number: "079", type: "Stage", color: "Purple", rarity: "UC", cost: 1 },
  { id: "OP02-080", name: "Shadows Asgard", set: "Paramount War", setCode: "OP02", number: "080", type: "Event", color: "Purple", rarity: "R", cost: 3 },
  
  // Black Cards
  { id: "OP02-081", name: "Magellan", set: "Paramount War", setCode: "OP02", number: "081", type: "Character", color: "Black", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP02-082", name: "Sadi", set: "Paramount War", setCode: "OP02", number: "082", type: "Character", color: "Black", rarity: "R", cost: 4, power: 4000 },
  { id: "OP02-083", name: "Saldeath", set: "Paramount War", setCode: "OP02", number: "083", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000 },
  { id: "OP02-084", name: "Minotaurus", set: "Paramount War", setCode: "OP02", number: "084", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000 },
  { id: "OP02-085", name: "Hannyabal", set: "Paramount War", setCode: "OP02", number: "085", type: "Character", color: "Black", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP02-086", name: "Impel Down", set: "Paramount War", setCode: "OP02", number: "086", type: "Stage", color: "Black", rarity: "R", cost: 1 },
  { id: "OP02-087", name: "Hydra", set: "Paramount War", setCode: "OP02", number: "087", type: "Event", color: "Black", rarity: "R", cost: 2 },
  
  // Yellow Cards
  { id: "OP02-088", name: "Duval", set: "Paramount War", setCode: "OP02", number: "088", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-089", name: "Silvers Rayleigh", set: "Paramount War", setCode: "OP02", number: "089", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 7000 },
  { id: "OP02-090", name: "Disciple of Darkness", set: "Paramount War", setCode: "OP02", number: "090", type: "Event", color: "Yellow", rarity: "R", cost: 2 },
  
  // Secret Rares
  { id: "OP02-091", name: "Portgas D. Ace", set: "Paramount War", setCode: "OP02", number: "091", type: "Character", color: "Red", rarity: "SEC", cost: 8, power: 9000 },
  { id: "OP02-092", name: "Boa Hancock", set: "Paramount War", setCode: "OP02", number: "092", type: "Character", color: "Blue", rarity: "SEC", cost: 5, power: 6000 },
  { id: "OP02-093", name: "Marshall D. Teach", set: "Paramount War", setCode: "OP02", number: "093", type: "Character", color: "Purple", rarity: "SEC", cost: 8, power: 9000 },
  { id: "OP02-094", name: "Monkey D. Luffy", set: "Paramount War", setCode: "OP02", number: "094", type: "Character", color: "Green", rarity: "SEC", cost: 8, power: 9000 },
  { id: "OP02-095", name: "Jinbe", set: "Paramount War", setCode: "OP02", number: "095", type: "Character", color: "Red", rarity: "SEC", cost: 5, power: 6000 },
  { id: "OP02-096", name: "Kuzan", set: "Paramount War", setCode: "OP02", number: "096", type: "Character", color: "Blue", rarity: "SEC", cost: 8, power: 9000 },
  { id: "OP02-097", name: "Sakazuki", set: "Paramount War", setCode: "OP02", number: "097", type: "Character", color: "Blue", rarity: "SEC", cost: 9, power: 10000 },
  { id: "OP02-098", name: "Monkey D. Garp", set: "Paramount War", setCode: "OP02", number: "098", type: "Character", color: "Blue", rarity: "SEC", cost: 7, power: 8000 },
  { id: "OP02-099", name: "Trafalgar Law", set: "Paramount War", setCode: "OP02", number: "099", type: "Character", color: "Green", rarity: "SEC", cost: 5, power: 6000 },
  { id: "OP02-100", name: "Eustass Kid", set: "Paramount War", setCode: "OP02", number: "100", type: "Character", color: "Green", rarity: "SEC", cost: 8, power: 8000 },
  { id: "OP02-101", name: "Shanks", set: "Paramount War", setCode: "OP02", number: "101", type: "Character", color: "Red", rarity: "SEC", cost: 9, power: 10000 },
  { id: "OP02-102", name: "Silvers Rayleigh", set: "Paramount War", setCode: "OP02", number: "102", type: "Character", color: "Yellow", rarity: "SEC", cost: 5, power: 7000 }
];
