// OP02: PARAMOUNT WAR - Synced from official cardlist
// 154 entries including variants
const OP02_CARDS = [
  { id: "OP02-001", name: "Edward.Newgate", set: "PARAMOUNT WAR", setCode: "OP02", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 6, power: 6000 },
  { id: "OP02-001_p1", name: "Edward.Newgate (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 6, power: 6000, imageUrl: "/api/card-image?id=OP02-001&variant=p1" },
  { id: "OP02-002", name: "Monkey.D.Garp", set: "PARAMOUNT WAR", setCode: "OP02", number: "002", type: "Leader", color: "Red/Black", rarity: "L", cost: 4, power: 5000 },
  { id: "OP02-002_p1", name: "Monkey.D.Garp (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "002", type: "Leader", color: "Red/Black", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP02-002&variant=p1" },
  { id: "OP02-003", name: "Atmos", set: "PARAMOUNT WAR", setCode: "OP02", number: "003", type: "Character", color: "Red", rarity: "C", cost: 4, power: 6000 },
  { id: "OP02-004", name: "Edward.Newgate", set: "PARAMOUNT WAR", setCode: "OP02", number: "004", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP02-004_p1", name: "Edward.Newgate (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "004", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000, imageUrl: "/api/card-image?id=OP02-004&variant=p1" },
  { id: "OP02-005", name: "Curly.Dadan", set: "PARAMOUNT WAR", setCode: "OP02", number: "005", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP02-006", name: "Kingdew", set: "PARAMOUNT WAR", setCode: "OP02", number: "006", type: "Character", color: "Red", rarity: "C", cost: 5, power: 7000 },
  { id: "OP02-007", name: "Thatch", set: "PARAMOUNT WAR", setCode: "OP02", number: "007", type: "Character", color: "Red", rarity: "C", cost: 6, power: 8000 },
  { id: "OP02-008", name: "Jozu", set: "PARAMOUNT WAR", setCode: "OP02", number: "008", type: "Character", color: "Red", rarity: "R", cost: 4, power: 4000 },
  { id: "OP02-009", name: "Squard", set: "PARAMOUNT WAR", setCode: "OP02", number: "009", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 5000 },
  { id: "OP02-009_p1", name: "Squard (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "009", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 5000, imageUrl: "/api/card-image?id=OP02-009&variant=p1" },
  { id: "OP02-010", name: "Dogura", set: "PARAMOUNT WAR", setCode: "OP02", number: "010", type: "Character", color: "Red", rarity: "C", cost: 1, power: 2000 },
  { id: "OP02-011", name: "Vista", set: "PARAMOUNT WAR", setCode: "OP02", number: "011", type: "Character", color: "Red", rarity: "R", cost: 3, power: 3000 },
  { id: "OP02-012", name: "Blenheim", set: "PARAMOUNT WAR", setCode: "OP02", number: "012", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-013", name: "Portgas.D.Ace", set: "PARAMOUNT WAR", setCode: "OP02", number: "013", type: "Character", color: "Red", rarity: "SR", cost: 7, power: 7000 },
  { id: "OP02-013_p1", name: "Portgas.D.Ace (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "013", type: "Character", color: "Red", rarity: "SR", cost: 7, power: 7000, imageUrl: "/api/card-image?id=OP02-013&variant=p1" },
  { id: "OP02-013_p2", name: "Portgas.D.Ace (Manga)", set: "PARAMOUNT WAR", setCode: "OP02", number: "013", type: "Character", color: "Red", rarity: "SR", cost: 7, power: 7000, imageUrl: "/api/card-image?id=OP02-013&variant=p2" },
  { id: "OP02-014", name: "Whitey Bay", set: "PARAMOUNT WAR", setCode: "OP02", number: "014", type: "Character", color: "Red", rarity: "UC", cost: 1, power: 2000 },
  { id: "OP02-015", name: "Makino", set: "PARAMOUNT WAR", setCode: "OP02", number: "015", type: "Character", color: "Red", rarity: "UC", cost: 1 },
  { id: "OP02-016", name: "Magura", set: "PARAMOUNT WAR", setCode: "OP02", number: "016", type: "Character", color: "Red", rarity: "C", cost: 1, power: 2000 },
  { id: "OP02-017", name: "Masked Deuce", set: "PARAMOUNT WAR", setCode: "OP02", number: "017", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000 },
  { id: "OP02-017_p1", name: "Masked Deuce (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "017", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000, imageUrl: "/api/card-image?id=OP02-017&variant=p1" },
  { id: "OP02-018", name: "Marco", set: "PARAMOUNT WAR", setCode: "OP02", number: "018", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-018_p1", name: "Marco (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "018", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP02-018&variant=p1" },
  { id: "OP02-019", name: "Rakuyo", set: "PARAMOUNT WAR", setCode: "OP02", number: "019", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP02-020", name: "LittleOars Jr.", set: "PARAMOUNT WAR", setCode: "OP02", number: "020", type: "Character", color: "Red", rarity: "C", cost: 7, power: 9000 },
  { id: "OP02-021", name: "Seaquake", set: "PARAMOUNT WAR", setCode: "OP02", number: "021", type: "Event", color: "Red", rarity: "R", cost: 1 },
  { id: "OP02-022", name: "Whitebeard Pirates", set: "PARAMOUNT WAR", setCode: "OP02", number: "022", type: "Event", color: "Red", rarity: "UC", cost: 1 },
  { id: "OP02-023", name: "You May Be a Fool...but I Still Love You", set: "PARAMOUNT WAR", setCode: "OP02", number: "023", type: "Event", color: "Red", rarity: "C", cost: 1 },
  { id: "OP02-024", name: "Moby Dick", set: "PARAMOUNT WAR", setCode: "OP02", number: "024", type: "Stage", color: "Red", rarity: "C", cost: 2 },
  { id: "OP02-025", name: "Kin'emon", set: "PARAMOUNT WAR", setCode: "OP02", number: "025", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000 },
  { id: "OP02-025_p1", name: "Kin'emon (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "025", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP02-025&variant=p1" },
  { id: "OP02-026", name: "Sanji", set: "PARAMOUNT WAR", setCode: "OP02", number: "026", type: "Leader", color: "Green/Blue", rarity: "L", cost: 4, power: 5000 },
  { id: "OP02-026_p1", name: "Sanji (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "026", type: "Leader", color: "Green/Blue", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP02-026&variant=p1" },
  { id: "OP02-027", name: "Inuarashi", set: "PARAMOUNT WAR", setCode: "OP02", number: "027", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP02-028", name: "Usopp", set: "PARAMOUNT WAR", setCode: "OP02", number: "028", type: "Character", color: "Green", rarity: "C", cost: 3, power: 5000 },
  { id: "OP02-029", name: "Carrot", set: "PARAMOUNT WAR", setCode: "OP02", number: "029", type: "Character", color: "Green", rarity: "R", cost: 5, power: 5000 },
  { id: "OP02-030", name: "Kouzuki Oden", set: "PARAMOUNT WAR", setCode: "OP02", number: "030", type: "Character", color: "Green", rarity: "SR", cost: 8, power: 8000 },
  { id: "OP02-030_p1", name: "Kouzuki Oden (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "030", type: "Character", color: "Green", rarity: "SR", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP02-030&variant=p1" },
  { id: "OP02-031", name: "Kouzuki Toki", set: "PARAMOUNT WAR", setCode: "OP02", number: "031", type: "Character", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP02-031_p1", name: "Kouzuki Toki (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "031", type: "Character", color: "Green", rarity: "UC", cost: 1, imageUrl: "/api/card-image?id=OP02-031&variant=p1" },
  { id: "OP02-032", name: "Shishilian", set: "PARAMOUNT WAR", setCode: "OP02", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP02-033", name: "Jinbe", set: "PARAMOUNT WAR", setCode: "OP02", number: "033", type: "Character", color: "Green", rarity: "C", cost: 2, power: 4000 },
  { id: "OP02-034", name: "Tony Tony.Chopper", set: "PARAMOUNT WAR", setCode: "OP02", number: "034", type: "Character", color: "Green", rarity: "UC", cost: 2, power: 2000 },
  { id: "OP02-035", name: "Trafalgar Law", set: "PARAMOUNT WAR", setCode: "OP02", number: "035", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-036", name: "Nami", set: "PARAMOUNT WAR", setCode: "OP02", number: "036", type: "Character", color: "Green", rarity: "SR", cost: 3, power: 5000 },
  { id: "OP02-036_p1", name: "Nami (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "036", type: "Character", color: "Green", rarity: "SR", cost: 3, power: 5000, imageUrl: "/api/card-image?id=OP02-036&variant=p1" },
  { id: "OP02-037", name: "Nico Robin", set: "PARAMOUNT WAR", setCode: "OP02", number: "037", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP02-038", name: "Nekomamushi", set: "PARAMOUNT WAR", setCode: "OP02", number: "038", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "OP02-039", name: "Franky", set: "PARAMOUNT WAR", setCode: "OP02", number: "039", type: "Character", color: "Green", rarity: "C", cost: 5, power: 7000 },
  { id: "OP02-040", name: "Brook", set: "PARAMOUNT WAR", setCode: "OP02", number: "040", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-041", name: "Monkey.D.Luffy", set: "PARAMOUNT WAR", setCode: "OP02", number: "041", type: "Character", color: "Green", rarity: "R", cost: 7, power: 7000 },
  { id: "OP02-041_p1", name: "Monkey.D.Luffy (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "041", type: "Character", color: "Green", rarity: "R", cost: 7, power: 7000, imageUrl: "/api/card-image?id=OP02-041&variant=p1" },
  { id: "OP02-042", name: "Yamato", set: "PARAMOUNT WAR", setCode: "OP02", number: "042", type: "Character", color: "Green", rarity: "R", cost: 4, power: 6000 },
  { id: "OP02-043", name: "Roronoa Zoro", set: "PARAMOUNT WAR", setCode: "OP02", number: "043", type: "Character", color: "Green", rarity: "C", cost: 4, power: 6000 },
  { id: "OP02-044", name: "Wanda", set: "PARAMOUNT WAR", setCode: "OP02", number: "044", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-045", name: "Three Sword Style Oni Giri", set: "PARAMOUNT WAR", setCode: "OP02", number: "045", type: "Event", color: "Green", rarity: "C", cost: 3 },
  { id: "OP02-046", name: "Diable Jambe Venaison Shoot", set: "PARAMOUNT WAR", setCode: "OP02", number: "046", type: "Event", color: "Green", rarity: "UC", cost: 2 },
  { id: "OP02-047", name: "Paradise Totsuka", set: "PARAMOUNT WAR", setCode: "OP02", number: "047", type: "Event", color: "Green", rarity: "R", cost: 1 },
  { id: "OP02-048", name: "Land of Wano", set: "PARAMOUNT WAR", setCode: "OP02", number: "048", type: "Stage", color: "Green", rarity: "C", cost: 1 },
  { id: "OP02-049", name: "Emporio.Ivankov", set: "PARAMOUNT WAR", setCode: "OP02", number: "049", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000 },
  { id: "OP02-049_p1", name: "Emporio.Ivankov (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "049", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP02-049&variant=p1" },
  { id: "OP02-050", name: "Inazuma", set: "PARAMOUNT WAR", setCode: "OP02", number: "050", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-051", name: "Emporio.Ivankov", set: "PARAMOUNT WAR", setCode: "OP02", number: "051", type: "Character", color: "Blue", rarity: "SR", cost: 7, power: 7000 },
  { id: "OP02-051_p1", name: "Emporio.Ivankov (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "051", type: "Character", color: "Blue", rarity: "SR", cost: 7, power: 7000, imageUrl: "/api/card-image?id=OP02-051&variant=p1" },
  { id: "OP02-052", name: "Cabaji", set: "PARAMOUNT WAR", setCode: "OP02", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-053", name: "Crocodile", set: "PARAMOUNT WAR", setCode: "OP02", number: "053", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 7000 },
  { id: "OP02-054", name: "Gecko Moria", set: "PARAMOUNT WAR", setCode: "OP02", number: "054", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 6000 },
  { id: "OP02-055", name: "Dracule Mihawk", set: "PARAMOUNT WAR", setCode: "OP02", number: "055", type: "Character", color: "Blue", rarity: "C", cost: 6, power: 8000 },
  { id: "OP02-056", name: "Donquixote Doflamingo", set: "PARAMOUNT WAR", setCode: "OP02", number: "056", type: "Character", color: "Blue", rarity: "UC", cost: 1, power: 2000 },
  { id: "OP02-057", name: "Bartholomew Kuma", set: "PARAMOUNT WAR", setCode: "OP02", number: "057", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 3000 },
  { id: "OP02-058", name: "Buggy", set: "PARAMOUNT WAR", setCode: "OP02", number: "058", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000 },
  { id: "OP02-058_p1", name: "Buggy (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "058", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP02-058&variant=p1" },
  { id: "OP02-059", name: "Boa Hancock", set: "PARAMOUNT WAR", setCode: "OP02", number: "059", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP02-059_p1", name: "Boa Hancock (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "059", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP02-059&variant=p1" },
  { id: "OP02-060", name: "Mohji", set: "PARAMOUNT WAR", setCode: "OP02", number: "060", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 3000 },
  { id: "OP02-061", name: "Morley", set: "PARAMOUNT WAR", setCode: "OP02", number: "061", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP02-062", name: "Monkey.D.Luffy", set: "PARAMOUNT WAR", setCode: "OP02", number: "062", type: "Character", color: "Blue", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP02-062_p1", name: "Monkey.D.Luffy (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "062", type: "Character", color: "Blue", rarity: "SR", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP02-062&variant=p1" },
  { id: "OP02-063", name: "Mr.1(Daz.Bonez)", set: "PARAMOUNT WAR", setCode: "OP02", number: "063", type: "Character", color: "Blue", rarity: "UC", cost: 1, power: 1000 },
  { id: "OP02-064", name: "Mr.2.Bon.Kurei(Bentham)", set: "PARAMOUNT WAR", setCode: "OP02", number: "064", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 5000 },
  { id: "OP02-065", name: "Mr.3(Galdino)", set: "PARAMOUNT WAR", setCode: "OP02", number: "065", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-066", name: "Impel Down All Stars", set: "PARAMOUNT WAR", setCode: "OP02", number: "066", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP02-067", name: "Arabesque Brick Fist", set: "PARAMOUNT WAR", setCode: "OP02", number: "067", type: "Event", color: "Blue", rarity: "UC", cost: 2 },
  { id: "OP02-068", name: "Gum-Gum Rain", set: "PARAMOUNT WAR", setCode: "OP02", number: "068", type: "Event", color: "Blue", rarity: "R" },
  { id: "OP02-069", name: "DEATH WINK", set: "PARAMOUNT WAR", setCode: "OP02", number: "069", type: "Event", color: "Blue", rarity: "C", cost: 3 },
  { id: "OP02-070", name: "New Kama Land", set: "PARAMOUNT WAR", setCode: "OP02", number: "070", type: "Stage", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP02-071", name: "Magellan", set: "PARAMOUNT WAR", setCode: "OP02", number: "071", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000 },
  { id: "OP02-071_p1", name: "Magellan (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "071", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP02-071&variant=p1" },
  { id: "OP02-072", name: "Zephyr", set: "PARAMOUNT WAR", setCode: "OP02", number: "072", type: "Leader", color: "Purple/Black", rarity: "L", cost: 4, power: 5000 },
  { id: "OP02-072_p1", name: "Zephyr (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "072", type: "Leader", color: "Purple/Black", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP02-072&variant=p1" },
  { id: "OP02-073", name: "Little Sadi", set: "PARAMOUNT WAR", setCode: "OP02", number: "073", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 3000 },
  { id: "OP02-073_p1", name: "Little Sadi (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "073", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 3000, imageUrl: "/api/card-image?id=OP02-073&variant=p1" },
  { id: "OP02-074", name: "Saldeath", set: "PARAMOUNT WAR", setCode: "OP02", number: "074", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 2000 },
  { id: "OP02-075", name: "Shiki", set: "PARAMOUNT WAR", setCode: "OP02", number: "075", type: "Character", color: "Purple", rarity: "R", cost: 2, power: 3000 },
  { id: "OP02-076", name: "Shiryu", set: "PARAMOUNT WAR", setCode: "OP02", number: "076", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000 },
  { id: "OP02-077", name: "Solitaire", set: "PARAMOUNT WAR", setCode: "OP02", number: "077", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 5000 },
  { id: "OP02-078", name: "Daifugo", set: "PARAMOUNT WAR", setCode: "OP02", number: "078", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 5000 },
  { id: "OP02-079", name: "Douglas Bullet", set: "PARAMOUNT WAR", setCode: "OP02", number: "079", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP02-080", name: "Dobon", set: "PARAMOUNT WAR", setCode: "OP02", number: "080", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 4000 },
  { id: "OP02-081", name: "Domino", set: "PARAMOUNT WAR", setCode: "OP02", number: "081", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000 },
  { id: "OP02-082", name: "Byrnndi World", set: "PARAMOUNT WAR", setCode: "OP02", number: "082", type: "Character", color: "Purple", rarity: "UC", cost: 8, power: 8000 },
  { id: "OP02-083", name: "Hannyabal", set: "PARAMOUNT WAR", setCode: "OP02", number: "083", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 2000 },
  { id: "OP02-084", name: "Blugori", set: "PARAMOUNT WAR", setCode: "OP02", number: "084", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 3000 },
  { id: "OP02-085", name: "Magellan", set: "PARAMOUNT WAR", setCode: "OP02", number: "085", type: "Character", color: "Purple", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP02-085_p1", name: "Magellan (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "085", type: "Character", color: "Purple", rarity: "SR", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP02-085&variant=p1" },
  { id: "OP02-086", name: "Minokoala", set: "PARAMOUNT WAR", setCode: "OP02", number: "086", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP02-086_p1", name: "Minokoala (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "086", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP02-086&variant=p1" },
  { id: "OP02-087", name: "Minotaur", set: "PARAMOUNT WAR", setCode: "OP02", number: "087", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP02-088", name: "Sphinx", set: "PARAMOUNT WAR", setCode: "OP02", number: "088", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 6000 },
  { id: "OP02-089", name: "Judgment of Hell", set: "PARAMOUNT WAR", setCode: "OP02", number: "089", type: "Event", color: "Purple", rarity: "R", cost: 2 },
  { id: "OP02-090", name: "Hydra", set: "PARAMOUNT WAR", setCode: "OP02", number: "090", type: "Event", color: "Purple", rarity: "UC", cost: 1 },
  { id: "OP02-091", name: "Venom Road", set: "PARAMOUNT WAR", setCode: "OP02", number: "091", type: "Event", color: "Purple", rarity: "C", cost: 3 },
  { id: "OP02-092", name: "Impel Down", set: "PARAMOUNT WAR", setCode: "OP02", number: "092", type: "Stage", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP02-093", name: "Smoker", set: "PARAMOUNT WAR", setCode: "OP02", number: "093", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000 },
  { id: "OP02-093_p1", name: "Smoker (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "093", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP02-093&variant=p1" },
  { id: "OP02-094", name: "Isuka", set: "PARAMOUNT WAR", setCode: "OP02", number: "094", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP02-095", name: "Onigumo", set: "PARAMOUNT WAR", setCode: "OP02", number: "095", type: "Character", color: "Black", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP02-096", name: "Kuzan", set: "PARAMOUNT WAR", setCode: "OP02", number: "096", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP02-096_p1", name: "Kuzan (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "096", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP02-096&variant=p1" },
  { id: "OP02-097", name: "Komille", set: "PARAMOUNT WAR", setCode: "OP02", number: "097", type: "Character", color: "Black", rarity: "C", cost: 1, power: 3000 },
  { id: "OP02-098", name: "Koby", set: "PARAMOUNT WAR", setCode: "OP02", number: "098", type: "Character", color: "Black", rarity: "R", cost: 3, power: 4000 },
  { id: "OP02-099", name: "Sakazuki", set: "PARAMOUNT WAR", setCode: "OP02", number: "099", type: "Character", color: "Black", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP02-099_p1", name: "Sakazuki (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "099", type: "Character", color: "Black", rarity: "SR", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP02-099&variant=p1" },
  { id: "OP02-100", name: "Jango", set: "PARAMOUNT WAR", setCode: "OP02", number: "100", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-101", name: "Strawberry", set: "PARAMOUNT WAR", setCode: "OP02", number: "101", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000 },
  { id: "OP02-102", name: "Smoker", set: "PARAMOUNT WAR", setCode: "OP02", number: "102", type: "Character", color: "Black", rarity: "R", cost: 3, power: 4000 },
  { id: "OP02-103", name: "Sengoku", set: "PARAMOUNT WAR", setCode: "OP02", number: "103", type: "Character", color: "Black", rarity: "R", cost: 2, power: 3000 },
  { id: "OP02-104", name: "Sentomaru", set: "PARAMOUNT WAR", setCode: "OP02", number: "104", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-105", name: "Tashigi", set: "PARAMOUNT WAR", setCode: "OP02", number: "105", type: "Character", color: "Black", rarity: "C", cost: 3, power: 5000 },
  { id: "OP02-105_p1", name: "Tashigi (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "105", type: "Character", color: "Black", rarity: "C", cost: 3, power: 5000, imageUrl: "/api/card-image?id=OP02-105&variant=p1" },
  { id: "OP02-106", name: "Tsuru", set: "PARAMOUNT WAR", setCode: "OP02", number: "106", type: "Character", color: "Black", rarity: "UC", cost: 1 },
  { id: "OP02-107", name: "Doberman", set: "PARAMOUNT WAR", setCode: "OP02", number: "107", type: "Character", color: "Black", rarity: "C", cost: 2, power: 4000 },
  { id: "OP02-108", name: "Donquixote Rosinante", set: "PARAMOUNT WAR", setCode: "OP02", number: "108", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000 },
  { id: "OP02-108_p1", name: "Donquixote Rosinante (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "108", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000, imageUrl: "/api/card-image?id=OP02-108&variant=p1" },
  { id: "OP02-109", name: "Jaguar.D.Saul", set: "PARAMOUNT WAR", setCode: "OP02", number: "109", type: "Character", color: "Black", rarity: "C", cost: 4, power: 6000 },
  { id: "OP02-110", name: "Hina", set: "PARAMOUNT WAR", setCode: "OP02", number: "110", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000 },
  { id: "OP02-111", name: "Fullbody", set: "PARAMOUNT WAR", setCode: "OP02", number: "111", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP02-112", name: "Bell-mère", set: "PARAMOUNT WAR", setCode: "OP02", number: "112", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 1000 },
  { id: "OP02-113", name: "Helmeppo", set: "PARAMOUNT WAR", setCode: "OP02", number: "113", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 3000 },
  { id: "OP02-114", name: "Borsalino", set: "PARAMOUNT WAR", setCode: "OP02", number: "114", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP02-114_p1", name: "Borsalino (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "114", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP02-114&variant=p1" },
  { id: "OP02-115", name: "Monkey.D.Garp", set: "PARAMOUNT WAR", setCode: "OP02", number: "115", type: "Character", color: "Black", rarity: "R", cost: 2, power: 3000 },
  { id: "OP02-115_p1", name: "Monkey.D.Garp (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "115", type: "Character", color: "Black", rarity: "R", cost: 2, power: 3000, imageUrl: "/api/card-image?id=OP02-115&variant=p1" },
  { id: "OP02-116", name: "Yamakaji", set: "PARAMOUNT WAR", setCode: "OP02", number: "116", type: "Character", color: "Black", rarity: "C", cost: 3, power: 5000 },
  { id: "OP02-117", name: "Ice Age", set: "PARAMOUNT WAR", setCode: "OP02", number: "117", type: "Event", color: "Black", rarity: "UC", cost: 1 },
  { id: "OP02-118", name: "Yasakani Sacred Jewel", set: "PARAMOUNT WAR", setCode: "OP02", number: "118", type: "Event", color: "Black", rarity: "C", cost: 1 },
  { id: "OP02-119", name: "Meteor Volcano", set: "PARAMOUNT WAR", setCode: "OP02", number: "119", type: "Event", color: "Black", rarity: "R", cost: 2 },
  { id: "OP02-120", name: "Uta", set: "PARAMOUNT WAR", setCode: "OP02", number: "120", type: "Character", color: "Purple", rarity: "SEC", cost: 8, power: 8000 },
  { id: "OP02-120_p1", name: "Uta (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "120", type: "Character", color: "Purple", rarity: "SEC", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP02-120&variant=p1" },
  { id: "OP02-121", name: "Kuzan", set: "PARAMOUNT WAR", setCode: "OP02", number: "121", type: "Character", color: "Black", rarity: "SEC", cost: 10, power: 10000 },
  { id: "OP02-121_p1", name: "Kuzan (Alt Art)", set: "PARAMOUNT WAR", setCode: "OP02", number: "121", type: "Character", color: "Black", rarity: "SEC", cost: 10, power: 10000, imageUrl: "/api/card-image?id=OP02-121&variant=p1" },
];

export default OP02_CARDS;
