import type { Card } from './cards';

const OP03_CARDS: Card[] = [
  { id: "OP03-001", name: "Portgas.D.Ace", set: "Pillars of Strength", setCode: "OP03", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP03-002", name: "Adio", set: "Pillars of Strength", setCode: "OP03", number: "002", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP03-003", name: "Izo", set: "Pillars of Strength", setCode: "OP03", number: "003", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000, attribute: "Ranged" },
  { id: "OP03-004", name: "Curiel", set: "Pillars of Strength", setCode: "OP03", number: "004", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000, attribute: "Ranged" },
  { id: "OP03-005", name: "Thatch", set: "Pillars of Strength", setCode: "OP03", number: "005", type: "Character", color: "Red", rarity: "UC", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP03-006", name: "Speed Jil", set: "Pillars of Strength", setCode: "OP03", number: "006", type: "Character", color: "Red", rarity: "C", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP03-007", name: "Namule", set: "Pillars of Strength", setCode: "OP03", number: "007", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP03-008", name: "Buggy", set: "Pillars of Strength", setCode: "OP03", number: "008", type: "Character", color: "Red", rarity: "UC", cost: 1, power: 3000, attribute: "Slash" },
  { id: "OP03-009", name: "Haruta", set: "Pillars of Strength", setCode: "OP03", number: "009", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP03-010", name: "Fossa", set: "Pillars of Strength", setCode: "OP03", number: "010", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000, attribute: "Slash" },
  { id: "OP03-011", name: "Blamenco", set: "Pillars of Strength", setCode: "OP03", number: "011", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP03-012", name: "Marshall.D.Teach", set: "Pillars of Strength", setCode: "OP03", number: "012", type: "Character", color: "Red", rarity: "R", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP03-013", name: "Marco", set: "Pillars of Strength", setCode: "OP03", number: "013", type: "Character", color: "Red", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP03-014", name: "Monkey.D.Garp", set: "Pillars of Strength", setCode: "OP03", number: "014", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP03-015", name: "Lim", set: "Pillars of Strength", setCode: "OP03", number: "015", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 2000, attribute: "Wisdom" },
  { id: "OP03-016", name: "Flame Emperor", set: "Pillars of Strength", setCode: "OP03", number: "016", type: "Event", color: "Red", rarity: "R", cost: 7 },
  { id: "OP03-017", name: "Cross Fire", set: "Pillars of Strength", setCode: "OP03", number: "017", type: "Event", color: "Red", rarity: "UC", cost: 2 },
  { id: "OP03-018", name: "Fire Fist", set: "Pillars of Strength", setCode: "OP03", number: "018", type: "Event", color: "Red", rarity: "R", cost: 3 },
  { id: "OP03-019", name: "Fiery Doll", set: "Pillars of Strength", setCode: "OP03", number: "019", type: "Event", color: "Red", rarity: "C", cost: 2 },
  { id: "OP03-020", name: "Striker", set: "Pillars of Strength", setCode: "OP03", number: "020", type: "Stage", color: "Red", rarity: "C", cost: 1 },
  { id: "OP03-021", name: "Kuro", set: "Pillars of Strength", setCode: "OP03", number: "021", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP03-022", name: "Arlong", set: "Pillars of Strength", setCode: "OP03", number: "022", type: "Leader", color: "Green/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP03-023", name: "Alvida", set: "Pillars of Strength", setCode: "OP03", number: "023", type: "Character", color: "Green", rarity: "C", cost: 1, power: 3000, attribute: "Strike" },
  { id: "OP03-024", name: "Gin", set: "Pillars of Strength", setCode: "OP03", number: "024", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP03-025", name: "Krieg", set: "Pillars of Strength", setCode: "OP03", number: "025", type: "Character", color: "Green", rarity: "SuperRare", cost: 6, power: 7000, attribute: "Ranged" },
  { id: "OP03-026", name: "Kuroobi", set: "Pillars of Strength", setCode: "OP03", number: "026", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 3000, attribute: "Strike" },
  { id: "OP03-027", name: "Sham", set: "Pillars of Strength", setCode: "OP03", number: "027", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP03-028", name: "Jango", set: "Pillars of Strength", setCode: "OP03", number: "028", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP03-029", name: "Chew", set: "Pillars of Strength", setCode: "OP03", number: "029", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 3000, attribute: "Ranged" },
  { id: "OP03-030", name: "Nami", set: "Pillars of Strength", setCode: "OP03", number: "030", type: "Character", color: "Green", rarity: "R", cost: 2, power: 2000, attribute: "Wisdom" },
  { id: "OP03-031", name: "Pearl", set: "Pillars of Strength", setCode: "OP03", number: "031", type: "Character", color: "Green", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP03-032", name: "Buggy", set: "Pillars of Strength", setCode: "OP03", number: "032", type: "Character", color: "Green", rarity: "C", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP03-033", name: "Hatchan", set: "Pillars of Strength", setCode: "OP03", number: "033", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 4000, attribute: "Slash" },
  { id: "OP03-034", name: "Buchi", set: "Pillars of Strength", setCode: "OP03", number: "034", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP03-035", name: "Momoo", set: "Pillars of Strength", setCode: "OP03", number: "035", type: "Character", color: "Green", rarity: "C", cost: 2, power: 4000, attribute: "Strike" },
  { id: "OP03-036", name: "Out-of-the-Bag", set: "Pillars of Strength", setCode: "OP03", number: "036", type: "Event", color: "Green", rarity: "C", cost: 3 },
  { id: "OP03-037", name: "Tooth Attack", set: "Pillars of Strength", setCode: "OP03", number: "037", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "OP03-038", name: "Deathly Poison Gas Bomb MH5", set: "Pillars of Strength", setCode: "OP03", number: "038", type: "Event", color: "Green", rarity: "R", cost: 1 },
  { id: "OP03-039", name: "One, Two, Jango", set: "Pillars of Strength", setCode: "OP03", number: "039", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP03-040", name: "Nami", set: "Pillars of Strength", setCode: "OP03", number: "040", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000, attribute: "Wisdom" },
  { id: "OP03-041", name: "Usopp", set: "Pillars of Strength", setCode: "OP03", number: "041", type: "Character", color: "Blue", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP03-042", name: "Usopp's Pirate Crew", set: "Pillars of Strength", setCode: "OP03", number: "042", type: "Character", color: "Blue", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP03-043", name: "Gaimon", set: "Pillars of Strength", setCode: "OP03", number: "043", type: "Character", color: "Blue", rarity: "C", cost: 2, attribute: "Wisdom" },
  { id: "OP03-044", name: "Kaya", set: "Pillars of Strength", setCode: "OP03", number: "044", type: "Character", color: "Blue", rarity: "R", cost: 1, attribute: "Wisdom" },
  { id: "OP03-045", name: "Carne", set: "Pillars of Strength", setCode: "OP03", number: "045", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 3000, attribute: "Slash" },
  { id: "OP03-046", name: "Genzo", set: "Pillars of Strength", setCode: "OP03", number: "046", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 4000, attribute: "Wisdom" },
  { id: "OP03-047", name: "Zeff", set: "Pillars of Strength", setCode: "OP03", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP03-048", name: "Nojiko", set: "Pillars of Strength", setCode: "OP03", number: "048", type: "Character", color: "Blue", rarity: "UC", cost: 2, attribute: "Wisdom" },
  { id: "OP03-049", name: "Patty", set: "Pillars of Strength", setCode: "OP03", number: "049", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP03-050", name: "Boodle", set: "Pillars of Strength", setCode: "OP03", number: "050", type: "Character", color: "Blue", rarity: "UC", cost: 2, attribute: "Wisdom" },
  { id: "OP03-051", name: "Bell-mère", set: "Pillars of Strength", setCode: "OP03", number: "051", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP03-052", name: "Merry", set: "Pillars of Strength", setCode: "OP03", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 3000, attribute: "Wisdom" },
  { id: "OP03-053", name: "Yosaku &amp; Johnny", set: "Pillars of Strength", setCode: "OP03", number: "053", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 3000, attribute: "Slash" },
  { id: "OP03-054", name: "Usopp's Rubber Band of Doom!!!", set: "Pillars of Strength", setCode: "OP03", number: "054", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP03-055", name: "Gum-Gum Giant Gavel", set: "Pillars of Strength", setCode: "OP03", number: "055", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP03-056", name: "Sanji's Pilaf", set: "Pillars of Strength", setCode: "OP03", number: "056", type: "Event", color: "Blue", rarity: "UC", cost: 3 },
  { id: "OP03-057", name: "Three Thousand Worlds", set: "Pillars of Strength", setCode: "OP03", number: "057", type: "Event", color: "Blue", rarity: "R", cost: 4 },
  { id: "OP03-058", name: "Iceburg", set: "Pillars of Strength", setCode: "OP03", number: "058", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000, attribute: "Wisdom" },
  { id: "OP03-059", name: "Kaku", set: "Pillars of Strength", setCode: "OP03", number: "059", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP03-060", name: "Kalifa", set: "Pillars of Strength", setCode: "OP03", number: "060", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 4000, attribute: "Wisdom" },
  { id: "OP03-061", name: "Kiwi &amp; Mozu", set: "Pillars of Strength", setCode: "OP03", number: "061", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 4000, attribute: "Slash" },
  { id: "OP03-062", name: "Kokoro", set: "Pillars of Strength", setCode: "OP03", number: "062", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP03-063", name: "Zambai", set: "Pillars of Strength", setCode: "OP03", number: "063", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 2000, attribute: "Slash" },
  { id: "OP03-064", name: "Tilestone", set: "Pillars of Strength", setCode: "OP03", number: "064", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP03-065", name: "Chimney &amp; Gonbe", set: "Pillars of Strength", setCode: "OP03", number: "065", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000, attribute: "Wisdom" },
  { id: "OP03-066", name: "Paulie", set: "Pillars of Strength", setCode: "OP03", number: "066", type: "Character", color: "Purple", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP03-067", name: "Peepley Lulu", set: "Pillars of Strength", setCode: "OP03", number: "067", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 5000, attribute: "Ranged" },
  { id: "OP03-068", name: "Minozebra", set: "Pillars of Strength", setCode: "OP03", number: "068", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP03-069", name: "Minorhinoceros", set: "Pillars of Strength", setCode: "OP03", number: "069", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP03-070", name: "Monkey.D.Luffy", set: "Pillars of Strength", setCode: "OP03", number: "070", type: "Character", color: "Purple", rarity: "R", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP03-071", name: "Rob Lucci", set: "Pillars of Strength", setCode: "OP03", number: "071", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP03-072", name: "Gum-Gum Jet Gatling", set: "Pillars of Strength", setCode: "OP03", number: "072", type: "Event", color: "Purple", rarity: "R" },
  { id: "OP03-073", name: "Hull Dismantler Slash", set: "Pillars of Strength", setCode: "OP03", number: "073", type: "Event", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP03-074", name: "Top Knot", set: "Pillars of Strength", setCode: "OP03", number: "074", type: "Event", color: "Purple", rarity: "UC", cost: 2 },
  { id: "OP03-075", name: "Galley-La Company", set: "Pillars of Strength", setCode: "OP03", number: "075", type: "Stage", color: "Purple", rarity: "C", cost: 3 },
  { id: "OP03-076", name: "Rob Lucci", set: "Pillars of Strength", setCode: "OP03", number: "076", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000, attribute: "Strike" },
  { id: "OP03-077", name: "Charlotte Linlin", set: "Pillars of Strength", setCode: "OP03", number: "077", type: "Leader", color: "Black/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP03-078", name: "Issho", set: "Pillars of Strength", setCode: "OP03", number: "078", type: "Character", color: "Black", rarity: "SuperRare", cost: 8, power: 9000, attribute: "Slash" },
  { id: "OP03-079", name: "Vergo", set: "Pillars of Strength", setCode: "OP03", number: "079", type: "Character", color: "Black", rarity: "UC", cost: 5, power: 5000, attribute: "Strike" },
  { id: "OP03-080", name: "Kaku", set: "Pillars of Strength", setCode: "OP03", number: "080", type: "Character", color: "Black", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP03-081", name: "Kalifa", set: "Pillars of Strength", setCode: "OP03", number: "081", type: "Character", color: "Black", rarity: "R", cost: 4, power: 4000, attribute: "Special" },
  { id: "OP03-082", name: "Kumadori", set: "Pillars of Strength", setCode: "OP03", number: "082", type: "Character", color: "Black", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP03-083", name: "Corgy", set: "Pillars of Strength", setCode: "OP03", number: "083", type: "Character", color: "Black", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP03-084", name: "Jerry", set: "Pillars of Strength", setCode: "OP03", number: "084", type: "Character", color: "Black", rarity: "C", cost: 2, power: 4000, attribute: "Strike" },
  { id: "OP03-085", name: "Jabra", set: "Pillars of Strength", setCode: "OP03", number: "085", type: "Character", color: "Black", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "OP03-086", name: "Spandam", set: "Pillars of Strength", setCode: "OP03", number: "086", type: "Character", color: "Black", rarity: "R", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP03-087", name: "Nero", set: "Pillars of Strength", setCode: "OP03", number: "087", type: "Character", color: "Black", rarity: "C", cost: 3, power: 5000, attribute: "Ranged" },
  { id: "OP03-088", name: "Fukurou", set: "Pillars of Strength", setCode: "OP03", number: "088", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 3000, attribute: "Strike" },
  { id: "OP03-089", name: "Brannew", set: "Pillars of Strength", setCode: "OP03", number: "089", type: "Character", color: "Black", rarity: "R", cost: 2, power: 3000, attribute: "Wisdom" },
  { id: "OP03-090", name: "Blueno", set: "Pillars of Strength", setCode: "OP03", number: "090", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP03-091", name: "Helmeppo", set: "Pillars of Strength", setCode: "OP03", number: "091", type: "Character", color: "Black", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP03-092", name: "Rob Lucci", set: "Pillars of Strength", setCode: "OP03", number: "092", type: "Character", color: "Black", rarity: "SuperRare", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP03-093", name: "Wanze", set: "Pillars of Strength", setCode: "OP03", number: "093", type: "Character", color: "Black", rarity: "UC", cost: 2, power: 4000, attribute: "Slash" },
  { id: "OP03-094", name: "Air Door", set: "Pillars of Strength", setCode: "OP03", number: "094", type: "Event", color: "Black", rarity: "UC", cost: 4 },
  { id: "OP03-095", name: "Soap Sheep", set: "Pillars of Strength", setCode: "OP03", number: "095", type: "Event", color: "Black", rarity: "C", cost: 1 },
  { id: "OP03-096", name: "Tempest Kick Sky Slicer", set: "Pillars of Strength", setCode: "OP03", number: "096", type: "Event", color: "Black", rarity: "UC", cost: 2 },
  { id: "OP03-097", name: "Six King Pistol", set: "Pillars of Strength", setCode: "OP03", number: "097", type: "Event", color: "Black", rarity: "R" },
  { id: "OP03-098", name: "Enies Lobby", set: "Pillars of Strength", setCode: "OP03", number: "098", type: "Stage", color: "Black", rarity: "C", cost: 2 },
  { id: "OP03-099", name: "Charlotte Katakuri", set: "Pillars of Strength", setCode: "OP03", number: "099", type: "Leader", color: "Yellow", rarity: "L", cost: 5, power: 5000, attribute: "Strike" },
  { id: "OP03-100", name: "Kingbaum", set: "Pillars of Strength", setCode: "OP03", number: "100", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP03-101", name: "Camie", set: "Pillars of Strength", setCode: "OP03", number: "101", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 3000, attribute: "Wisdom" },
  { id: "OP03-102", name: "Sanji", set: "Pillars of Strength", setCode: "OP03", number: "102", type: "Character", color: "Yellow", rarity: "R", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP03-103", name: "Bobbin the Disposer", set: "Pillars of Strength", setCode: "OP03", number: "103", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 4000, attribute: "Slash" },
  { id: "OP03-104", name: "Shirley", set: "Pillars of Strength", setCode: "OP03", number: "104", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 3000, attribute: "Wisdom" },
  { id: "OP03-105", name: "Charlotte Oven", set: "Pillars of Strength", setCode: "OP03", number: "105", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP03-106", name: "Charlotte Opera", set: "Pillars of Strength", setCode: "OP03", number: "106", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 6000, attribute: "Special" },
  { id: "OP03-107", name: "Charlotte Galette", set: "Pillars of Strength", setCode: "OP03", number: "107", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000, attribute: "Special" },
  { id: "OP03-108", name: "Charlotte Cracker", set: "Pillars of Strength", setCode: "OP03", number: "108", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP03-109", name: "Charlotte Chiffon", set: "Pillars of Strength", setCode: "OP03", number: "109", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000, attribute: "Wisdom" },
  { id: "OP03-110", name: "Charlotte Smoothie", set: "Pillars of Strength", setCode: "OP03", number: "110", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP03-111", name: "Charlotte Praline", set: "Pillars of Strength", setCode: "OP03", number: "111", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000, attribute: "Wisdom" },
  { id: "OP03-112", name: "Charlotte Pudding", set: "Pillars of Strength", setCode: "OP03", number: "112", type: "Character", color: "Yellow", rarity: "R", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP03-113", name: "Charlotte Perospero", set: "Pillars of Strength", setCode: "OP03", number: "113", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP03-114", name: "Charlotte Linlin", set: "Pillars of Strength", setCode: "OP03", number: "114", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 10, power: 12000, attribute: "Special" },
  { id: "OP03-115", name: "Streusen", set: "Pillars of Strength", setCode: "OP03", number: "115", type: "Character", color: "Yellow", rarity: "R", cost: 1, power: 1000, attribute: "Slash" },
  { id: "OP03-116", name: "Shirahoshi", set: "Pillars of Strength", setCode: "OP03", number: "116", type: "Character", color: "Yellow", rarity: "UC", cost: 5, attribute: "Wisdom" },
  { id: "OP03-117", name: "Napoleon", set: "Pillars of Strength", setCode: "OP03", number: "117", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 3000, attribute: "Slash" },
  { id: "OP03-118", name: "Ikoku Sovereignty", set: "Pillars of Strength", setCode: "OP03", number: "118", type: "Event", color: "Yellow", rarity: "UC", cost: 2 },
  { id: "OP03-119", name: "Buzz Cut Mochi", set: "Pillars of Strength", setCode: "OP03", number: "119", type: "Event", color: "Yellow", rarity: "R", cost: 2 },
  { id: "OP03-120", name: "Tropical Torment", set: "Pillars of Strength", setCode: "OP03", number: "120", type: "Event", color: "Yellow", rarity: "C", cost: 3 },
  { id: "OP03-121", name: "Thunder Bolt", set: "Pillars of Strength", setCode: "OP03", number: "121", type: "Event", color: "Yellow", rarity: "C", cost: 2 },
  { id: "OP03-122", name: "Sogeking", set: "Pillars of Strength", setCode: "OP03", number: "122", type: "Character", color: "Blue", rarity: "SecretRare", cost: 7, power: 6000, attribute: "Ranged" },
  { id: "OP03-123", name: "Charlotte Katakuri", set: "Pillars of Strength", setCode: "OP03", number: "123", type: "Character", color: "Yellow", rarity: "SecretRare", cost: 8, power: 8000, attribute: "Strike" },
];

export default OP03_CARDS;
