import type { Card } from './cards';

const OP04_CARDS: Card[] = [
  { id: "OP04-001", name: "Nefeltari Vivi", set: "Kingdoms of Intrigue", setCode: "OP04", number: "001", type: "Leader", color: "Red/Blue", rarity: "L", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP04-002", name: "Igaram", set: "Kingdoms of Intrigue", setCode: "OP04", number: "002", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000, attribute: "Ranged" },
  { id: "OP04-003", name: "Usopp", set: "Kingdoms of Intrigue", setCode: "OP04", number: "003", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 5000, attribute: "Wisdom" },
  { id: "OP04-004", name: "Karoo", set: "Kingdoms of Intrigue", setCode: "OP04", number: "004", type: "Character", color: "Red", rarity: "C", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP04-005", name: "Kung Fu Jugon", set: "Kingdoms of Intrigue", setCode: "OP04", number: "005", type: "Character", color: "Red", rarity: "C", cost: 1, power: 1000, attribute: "Strike" },
  { id: "OP04-006", name: "Koza", set: "Kingdoms of Intrigue", setCode: "OP04", number: "006", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 3000, attribute: "Slash" },
  { id: "OP04-007", name: "Sanji", set: "Kingdoms of Intrigue", setCode: "OP04", number: "007", type: "Character", color: "Red", rarity: "C", cost: 1, power: 3000, attribute: "Strike" },
  { id: "OP04-008", name: "Chaka", set: "Kingdoms of Intrigue", setCode: "OP04", number: "008", type: "Character", color: "Red", rarity: "R", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP04-009", name: "Super Spot-Billed Duck Troops", set: "Kingdoms of Intrigue", setCode: "OP04", number: "009", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP04-010", name: "Tony Tony.Chopper", set: "Kingdoms of Intrigue", setCode: "OP04", number: "010", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP04-011", name: "Nami", set: "Kingdoms of Intrigue", setCode: "OP04", number: "011", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Wisdom" },
  { id: "OP04-012", name: "Nefeltari Cobra", set: "Kingdoms of Intrigue", setCode: "OP04", number: "012", type: "Character", color: "Red", rarity: "C", cost: 2, attribute: "Wisdom" },
  { id: "OP04-013", name: "Pell", set: "Kingdoms of Intrigue", setCode: "OP04", number: "013", type: "Character", color: "Red", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP04-014", name: "Monkey.D.Luffy", set: "Kingdoms of Intrigue", setCode: "OP04", number: "014", type: "Character", color: "Red", rarity: "UC", cost: 8, power: 9000, attribute: "Strike" },
  { id: "OP04-015", name: "Roronoa Zoro", set: "Kingdoms of Intrigue", setCode: "OP04", number: "015", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP04-016", name: "Bad Manners Kick Course", set: "Kingdoms of Intrigue", setCode: "OP04", number: "016", type: "Event", color: "Red", rarity: "R" },
  { id: "OP04-017", name: "Happiness Punch", set: "Kingdoms of Intrigue", setCode: "OP04", number: "017", type: "Event", color: "Red", rarity: "C", cost: 1 },
  { id: "OP04-018", name: "Enchanting Vertigo Dance", set: "Kingdoms of Intrigue", setCode: "OP04", number: "018", type: "Event", color: "Red", rarity: "UC", cost: 3 },
  { id: "OP04-019", name: "Donquixote Doflamingo", set: "Kingdoms of Intrigue", setCode: "OP04", number: "019", type: "Leader", color: "Green/Purple", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP04-020", name: "Issho", set: "Kingdoms of Intrigue", setCode: "OP04", number: "020", type: "Leader", color: "Green/Black", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP04-021", name: "Viola", set: "Kingdoms of Intrigue", setCode: "OP04", number: "021", type: "Character", color: "Green", rarity: "C", cost: 3, power: 3000, attribute: "Special" },
  { id: "OP04-022", name: "Eric", set: "Kingdoms of Intrigue", setCode: "OP04", number: "022", type: "Character", color: "Green", rarity: "UC", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP04-023", name: "Kuro", set: "Kingdoms of Intrigue", setCode: "OP04", number: "023", type: "Character", color: "Green", rarity: "C", cost: 6, power: 8000, attribute: "Slash" },
  { id: "OP04-024", name: "Sugar", set: "Kingdoms of Intrigue", setCode: "OP04", number: "024", type: "Character", color: "Green", rarity: "SuperRare", cost: 2, attribute: "Special" },
  { id: "OP04-025", name: "Giolla", set: "Kingdoms of Intrigue", setCode: "OP04", number: "025", type: "Character", color: "Green", rarity: "C", cost: 4, power: 4000, attribute: "Special" },
  { id: "OP04-026", name: "Senor Pink", set: "Kingdoms of Intrigue", setCode: "OP04", number: "026", type: "Character", color: "Green", rarity: "R", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP04-027", name: "Daddy Masterson", set: "Kingdoms of Intrigue", setCode: "OP04", number: "027", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP04-028", name: "Diamante", set: "Kingdoms of Intrigue", setCode: "OP04", number: "028", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP04-029", name: "Dellinger", set: "Kingdoms of Intrigue", setCode: "OP04", number: "029", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP04-030", name: "Trebol", set: "Kingdoms of Intrigue", setCode: "OP04", number: "030", type: "Character", color: "Green", rarity: "R", cost: 6, power: 6000, attribute: "Special" },
  { id: "OP04-031", name: "Donquixote Doflamingo", set: "Kingdoms of Intrigue", setCode: "OP04", number: "031", type: "Character", color: "Green", rarity: "SuperRare", cost: 10, power: 10000, attribute: "Special" },
  { id: "OP04-032", name: "Baby 5", set: "Kingdoms of Intrigue", setCode: "OP04", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 1, power: 1000, attribute: "Special" },
  { id: "OP04-033", name: "Machvise", set: "Kingdoms of Intrigue", setCode: "OP04", number: "033", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP04-034", name: "Lao.G", set: "Kingdoms of Intrigue", setCode: "OP04", number: "034", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP04-035", name: "Spiderweb", set: "Kingdoms of Intrigue", setCode: "OP04", number: "035", type: "Event", color: "Green", rarity: "R", cost: 2 },
  { id: "OP04-036", name: "Donquixote Family", set: "Kingdoms of Intrigue", setCode: "OP04", number: "036", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "OP04-037", name: "Flapping Thread", set: "Kingdoms of Intrigue", setCode: "OP04", number: "037", type: "Event", color: "Green", rarity: "UC", cost: 2 },
  { id: "OP04-038", name: "The Weak Do Not Have the Right to Choose How They Die!!!", set: "Kingdoms of Intrigue", setCode: "OP04", number: "038", type: "Event", color: "Green", rarity: "C", cost: 5 },
  { id: "OP04-039", name: "Rebecca", set: "Kingdoms of Intrigue", setCode: "OP04", number: "039", type: "Leader", color: "Blue/Black", rarity: "L", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP04-040", name: "Queen", set: "Kingdoms of Intrigue", setCode: "OP04", number: "040", type: "Leader", color: "Blue/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP04-041", name: "Apis", set: "Kingdoms of Intrigue", setCode: "OP04", number: "041", type: "Character", color: "Blue", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP04-042", name: "Ipponmatsu", set: "Kingdoms of Intrigue", setCode: "OP04", number: "042", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 1000, attribute: "Wisdom" },
  { id: "OP04-043", name: "Ulti", set: "Kingdoms of Intrigue", setCode: "OP04", number: "043", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP04-044", name: "Kaido", set: "Kingdoms of Intrigue", setCode: "OP04", number: "044", type: "Character", color: "Blue", rarity: "SuperRare", cost: 10, power: 12000, attribute: "Strike" },
  { id: "OP04-045", name: "King", set: "Kingdoms of Intrigue", setCode: "OP04", number: "045", type: "Character", color: "Blue", rarity: "R", cost: 7, power: 8000, attribute: "Slash" },
  { id: "OP04-046", name: "Queen", set: "Kingdoms of Intrigue", setCode: "OP04", number: "046", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP04-047", name: "Ice Oni", set: "Kingdoms of Intrigue", setCode: "OP04", number: "047", type: "Character", color: "Blue", rarity: "C", cost: 8, attribute: "Special" },
  { id: "OP04-048", name: "Sasaki", set: "Kingdoms of Intrigue", setCode: "OP04", number: "048", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP04-049", name: "Jack", set: "Kingdoms of Intrigue", setCode: "OP04", number: "049", type: "Character", color: "Blue", rarity: "UC", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP04-050", name: "Hanger", set: "Kingdoms of Intrigue", setCode: "OP04", number: "050", type: "Character", color: "Blue", rarity: "C", cost: 2, attribute: "Wisdom" },
  { id: "OP04-051", name: "Who's.Who", set: "Kingdoms of Intrigue", setCode: "OP04", number: "051", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP04-052", name: "Black Maria", set: "Kingdoms of Intrigue", setCode: "OP04", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 3000, attribute: "Special" },
  { id: "OP04-053", name: "Page One", set: "Kingdoms of Intrigue", setCode: "OP04", number: "053", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP04-054", name: "Rokki", set: "Kingdoms of Intrigue", setCode: "OP04", number: "054", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "OP04-055", name: "Plague Rounds", set: "Kingdoms of Intrigue", setCode: "OP04", number: "055", type: "Event", color: "Blue", rarity: "C", cost: 2 },
  { id: "OP04-056", name: "Gum-Gum Red Roc", set: "Kingdoms of Intrigue", setCode: "OP04", number: "056", type: "Event", color: "Blue", rarity: "R", cost: 6 },
  { id: "OP04-057", name: "Dragon Twister Demolition Breath", set: "Kingdoms of Intrigue", setCode: "OP04", number: "057", type: "Event", color: "Blue", rarity: "UC", cost: 2 },
  { id: "OP04-058", name: "Crocodile", set: "Kingdoms of Intrigue", setCode: "OP04", number: "058", type: "Leader", color: "Purple/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP04-059", name: "Iceburg", set: "Kingdoms of Intrigue", setCode: "OP04", number: "059", type: "Character", color: "Purple", rarity: "UC", cost: 1, attribute: "Wisdom" },
  { id: "OP04-060", name: "Crocodile", set: "Kingdoms of Intrigue", setCode: "OP04", number: "060", type: "Character", color: "Purple", rarity: "SuperRare", cost: 8, power: 9000, attribute: "Special" },
  { id: "OP04-061", name: "Tom", set: "Kingdoms of Intrigue", setCode: "OP04", number: "061", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000, attribute: "Wisdom" },
  { id: "OP04-062", name: "Bananagator", set: "Kingdoms of Intrigue", setCode: "OP04", number: "062", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "OP04-063", name: "Franky", set: "Kingdoms of Intrigue", setCode: "OP04", number: "063", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 1000, attribute: "Wisdom" },
  { id: "OP04-064", name: "Ms. All Sunday", set: "Kingdoms of Intrigue", setCode: "OP04", number: "064", type: "Character", color: "Purple", rarity: "SuperRare", cost: 5, power: 5000, attribute: "Wisdom" },
  { id: "OP04-065", name: "Miss.Goldenweek(Marianne)", set: "Kingdoms of Intrigue", setCode: "OP04", number: "065", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000, attribute: "Wisdom" },
  { id: "OP04-066", name: "Miss.Valentine(Mikita)", set: "Kingdoms of Intrigue", setCode: "OP04", number: "066", type: "Character", color: "Purple", rarity: "R", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP04-067", name: "Miss.MerryChristmas(Drophy)", set: "Kingdoms of Intrigue", setCode: "OP04", number: "067", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 4000, attribute: "Slash" },
  { id: "OP04-068", name: "Yokozuna", set: "Kingdoms of Intrigue", setCode: "OP04", number: "068", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 3000, attribute: "Strike" },
  { id: "OP04-069", name: "Mr.2.Bon.Kurei(Bentham)", set: "Kingdoms of Intrigue", setCode: "OP04", number: "069", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP04-070", name: "Mr.3(Galdino)", set: "Kingdoms of Intrigue", setCode: "OP04", number: "070", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP04-071", name: "Mr.4(Babe)", set: "Kingdoms of Intrigue", setCode: "OP04", number: "071", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP04-072", name: "Mr.5(Gem)", set: "Kingdoms of Intrigue", setCode: "OP04", number: "072", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 8000, attribute: "Special" },
  { id: "OP04-073", name: "Mr.13 &amp; Ms.Friday", set: "Kingdoms of Intrigue", setCode: "OP04", number: "073", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 1000, attribute: "Wisdom" },
  { id: "OP04-074", name: "Colors Trap", set: "Kingdoms of Intrigue", setCode: "OP04", number: "074", type: "Event", color: "Purple", rarity: "R", cost: 1 },
  { id: "OP04-075", name: "Nez-Palm Cannon", set: "Kingdoms of Intrigue", setCode: "OP04", number: "075", type: "Event", color: "Purple", rarity: "UC", cost: 3 },
  { id: "OP04-076", name: "Weakness...Is an Unforgivable Sin.", set: "Kingdoms of Intrigue", setCode: "OP04", number: "076", type: "Event", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP04-077", name: "Ideo", set: "Kingdoms of Intrigue", setCode: "OP04", number: "077", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP04-078", name: "Oimo &amp; Kashii", set: "Kingdoms of Intrigue", setCode: "OP04", number: "078", type: "Character", color: "Black", rarity: "C", cost: 6, power: 8000, attribute: "Strike" },
  { id: "OP04-079", name: "Orlumbus", set: "Kingdoms of Intrigue", setCode: "OP04", number: "079", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP04-080", name: "Gyats", set: "Kingdoms of Intrigue", setCode: "OP04", number: "080", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 1000, attribute: "Wisdom" },
  { id: "OP04-081", name: "Cavendish", set: "Kingdoms of Intrigue", setCode: "OP04", number: "081", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP04-082", name: "Kyros", set: "Kingdoms of Intrigue", setCode: "OP04", number: "082", type: "Character", color: "Black", rarity: "R", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP04-083", name: "Sabo", set: "Kingdoms of Intrigue", setCode: "OP04", number: "083", type: "Character", color: "Black", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP04-084", name: "Stussy", set: "Kingdoms of Intrigue", setCode: "OP04", number: "084", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP04-085", name: "Suleiman", set: "Kingdoms of Intrigue", setCode: "OP04", number: "085", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP04-086", name: "Chinjao", set: "Kingdoms of Intrigue", setCode: "OP04", number: "086", type: "Character", color: "Black", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP04-087", name: "Trafalgar Law", set: "Kingdoms of Intrigue", setCode: "OP04", number: "087", type: "Character", color: "Black", rarity: "C", cost: 5, power: 7000, attribute: "Slash" },
  { id: "OP04-088", name: "Hajrudin", set: "Kingdoms of Intrigue", setCode: "OP04", number: "088", type: "Character", color: "Black", rarity: "UC", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP04-089", name: "Bartolomeo", set: "Kingdoms of Intrigue", setCode: "OP04", number: "089", type: "Character", color: "Black", rarity: "R", cost: 3, power: 3000, attribute: "Special" },
  { id: "OP04-090", name: "Monkey.D.Luffy", set: "Kingdoms of Intrigue", setCode: "OP04", number: "090", type: "Character", color: "Black", rarity: "SuperRare", cost: 7, power: 7000, attribute: "Strike" },
  { id: "OP04-091", name: "Leo", set: "Kingdoms of Intrigue", setCode: "OP04", number: "091", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP04-092", name: "Rebecca", set: "Kingdoms of Intrigue", setCode: "OP04", number: "092", type: "Character", color: "Black", rarity: "R", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP04-093", name: "Gum-Gum King Kong Gun", set: "Kingdoms of Intrigue", setCode: "OP04", number: "093", type: "Event", color: "Black", rarity: "UC", cost: 3 },
  { id: "OP04-094", name: "Trueno Bastardo", set: "Kingdoms of Intrigue", setCode: "OP04", number: "094", type: "Event", color: "Black", rarity: "R", cost: 4 },
  { id: "OP04-095", name: "Barrier!!", set: "Kingdoms of Intrigue", setCode: "OP04", number: "095", type: "Event", color: "Black", rarity: "C", cost: 1 },
  { id: "OP04-096", name: "Corrida Coliseum", set: "Kingdoms of Intrigue", setCode: "OP04", number: "096", type: "Stage", color: "Black", rarity: "C", cost: 1 },
  { id: "OP04-097", name: "Otama", set: "Kingdoms of Intrigue", setCode: "OP04", number: "097", type: "Character", color: "Yellow", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP04-098", name: "Toko", set: "Kingdoms of Intrigue", setCode: "OP04", number: "098", type: "Character", color: "Yellow", rarity: "UC", cost: 2, attribute: "Wisdom" },
  { id: "OP04-099", name: "Olin", set: "Kingdoms of Intrigue", setCode: "OP04", number: "099", type: "Character", color: "Yellow", rarity: "R", cost: 7, power: 7000, attribute: "Special" },
  { id: "OP04-100", name: "Capone\"Gang\"Bege", set: "Kingdoms of Intrigue", setCode: "OP04", number: "100", type: "Character", color: "Yellow", rarity: "R", cost: 3, power: 3000, attribute: "Ranged" },
  { id: "OP04-101", name: "Carmel", set: "Kingdoms of Intrigue", setCode: "OP04", number: "101", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 1000, attribute: "Wisdom" },
  { id: "OP04-102", name: "Kin'emon", set: "Kingdoms of Intrigue", setCode: "OP04", number: "102", type: "Character", color: "Yellow", rarity: "R", cost: 6, power: 6000, attribute: "Slash" },
  { id: "OP04-103", name: "Kouzuki Hiyori", set: "Kingdoms of Intrigue", setCode: "OP04", number: "103", type: "Character", color: "Yellow", rarity: "UC", cost: 2, attribute: "Wisdom" },
  { id: "OP04-104", name: "Sanji", set: "Kingdoms of Intrigue", setCode: "OP04", number: "104", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP04-105", name: "Charlotte Amande", set: "Kingdoms of Intrigue", setCode: "OP04", number: "105", type: "Character", color: "Yellow", rarity: "R", cost: 3, power: 3000, attribute: "Slash" },
  { id: "OP04-106", name: "Charlotte Bavarois", set: "Kingdoms of Intrigue", setCode: "OP04", number: "106", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP04-107", name: "Charlotte Perospero", set: "Kingdoms of Intrigue", setCode: "OP04", number: "107", type: "Character", color: "Yellow", rarity: "C", cost: 6, power: 8000, attribute: "Special" },
  { id: "OP04-108", name: "Charlotte Moscato", set: "Kingdoms of Intrigue", setCode: "OP04", number: "108", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP04-109", name: "Tonoyasu", set: "Kingdoms of Intrigue", setCode: "OP04", number: "109", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000, attribute: "Wisdom" },
  { id: "OP04-110", name: "Pound", set: "Kingdoms of Intrigue", setCode: "OP04", number: "110", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 3000, attribute: "Wisdom" },
  { id: "OP04-111", name: "Hera", set: "Kingdoms of Intrigue", setCode: "OP04", number: "111", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 3000, attribute: "Special" },
  { id: "OP04-112", name: "Yamato", set: "Kingdoms of Intrigue", setCode: "OP04", number: "112", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 9, power: 9000, attribute: "Strike" },
  { id: "OP04-113", name: "Rabiyan", set: "Kingdoms of Intrigue", setCode: "OP04", number: "113", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP04-114", name: "Randolph", set: "Kingdoms of Intrigue", setCode: "OP04", number: "114", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 7000, attribute: "Slash" },
  { id: "OP04-115", name: "Gun Modoki", set: "Kingdoms of Intrigue", setCode: "OP04", number: "115", type: "Event", color: "Yellow", rarity: "C", cost: 1 },
  { id: "OP04-116", name: "Diable Jambe Joue Shot", set: "Kingdoms of Intrigue", setCode: "OP04", number: "116", type: "Event", color: "Yellow", rarity: "UC", cost: 3 },
  { id: "OP04-117", name: "Heavenly Fire", set: "Kingdoms of Intrigue", setCode: "OP04", number: "117", type: "Event", color: "Yellow", rarity: "R", cost: 1 },
  { id: "OP04-118", name: "Nefeltari Vivi", set: "Kingdoms of Intrigue", setCode: "OP04", number: "118", type: "Character", color: "Red", rarity: "SecretRare", cost: 7, power: 4000, attribute: "Wisdom" },
  { id: "OP04-119", name: "Donquixote Rosinante", set: "Kingdoms of Intrigue", setCode: "OP04", number: "119", type: "Character", color: "Green", rarity: "SecretRare", cost: 8, power: 8000, attribute: "Special" },
];

export default OP04_CARDS;
