import { Card } from "./cards";

// Awakening of the New Era (OP05) - Key cards
export const OP05_CARDS: Card[] = [
  // Leaders
  { id: "OP05-001", name: "Monkey D. Luffy", set: "Awakening of the New Era", setCode: "OP05", number: "001", type: "Leader", color: "Red/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP05-002", name: "Sabo", set: "Awakening of the New Era", setCode: "OP05", number: "002", type: "Leader", color: "Red/Green", rarity: "L", cost: 0, power: 5000 },
  { id: "OP05-003", name: "Uta", set: "Awakening of the New Era", setCode: "OP05", number: "003", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 0, power: 5000 },
  { id: "OP05-004", name: "Sakazuki", set: "Awakening of the New Era", setCode: "OP05", number: "004", type: "Leader", color: "Blue/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP05-005", name: "Eustass Captain Kid", set: "Awakening of the New Era", setCode: "OP05", number: "005", type: "Leader", color: "Green/Red", rarity: "L", cost: 0, power: 5000 },
  { id: "OP05-006", name: "Trafalgar Law", set: "Awakening of the New Era", setCode: "OP05", number: "006", type: "Leader", color: "Green/Blue", rarity: "L", cost: 0, power: 5000 },
  { id: "OP05-007", name: "Yamato", set: "Awakening of the New Era", setCode: "OP05", number: "007", type: "Leader", color: "Purple/Green", rarity: "L", cost: 0, power: 5000 },
  { id: "OP05-008", name: "Kaido", set: "Awakening of the New Era", setCode: "OP05", number: "008", type: "Leader", color: "Purple/Blue", rarity: "L", cost: 0, power: 5000 },
  
  // Red Cards (Straw Hats)
  { id: "OP05-009", name: "Monkey D. Luffy", set: "Awakening of the New Era", setCode: "OP05", number: "009", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP05-010", name: "Roronoa Zoro", set: "Awakening of the New Era", setCode: "OP05", number: "010", type: "Character", color: "Red", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP05-011", name: "Nami", set: "Awakening of the New Era", setCode: "OP05", number: "011", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000 },
  { id: "OP05-012", name: "Usopp", set: "Awakening of the New Era", setCode: "OP05", number: "012", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000 },
  { id: "OP05-013", name: "Sanji", set: "Awakening of the New Era", setCode: "OP05", number: "013", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP05-014", name: "Tony Tony Chopper", set: "Awakening of the New Era", setCode: "OP05", number: "014", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000 },
  { id: "OP05-015", name: "Nico Robin", set: "Awakening of the New Era", setCode: "OP05", number: "015", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000 },
  { id: "OP05-016", name: "Franky", set: "Awakening of the New Era", setCode: "OP05", number: "016", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000 },
  { id: "OP05-017", name: "Brook", set: "Awakening of the New Era", setCode: "OP05", number: "017", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000 },
  { id: "OP05-018", name: "Jinbe", set: "Awakening of the New Era", setCode: "OP05", number: "018", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000 },
  { id: "OP05-019", name: "Carrot", set: "Awakening of the New Era", setCode: "OP05", number: "019", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP05-020", name: "Wanda", set: "Awakening of the New Era", setCode: "OP05", number: "020", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP05-021", name: "Pedro", set: "Awakening of the New Era", setCode: "OP05", number: "021", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000 },
  { id: "OP05-022", name: "Shishilian", set: "Awakening of the New Era", setCode: "OP05", number: "022", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-023", name: "Concelot", set: "Awakening of the New Era", setCode: "OP05", number: "023", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-024", name: "Giovanni", set: "Awakening of the New Era", setCode: "OP05", number: "024", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-025", name: "Sunacchi", set: "Awakening of the New Era", setCode: "OP05", number: "025", type: "Event", color: "Red", rarity: "R", cost: 1 },
  
  // Green Cards (Supernovas)
  { id: "OP05-026", name: "Trafalgar Law", set: "Awakening of the New Era", setCode: "OP05", number: "026", type: "Character", color: "Green", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP05-027", name: "Eustass Kid", set: "Awakening of the New Era", setCode: "OP05", number: "027", type: "Character", color: "Green", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP05-028", name: "Killer", set: "Awakening of the New Era", setCode: "OP05", number: "028", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000 },
  { id: "OP05-029", name: "Scratchmen Apoo", set: "Awakening of the New Era", setCode: "OP05", number: "029", type: "Character", color: "Green", rarity: "R", cost: 3, power: 4000 },
  { id: "OP05-030", name: "Capone Bege", set: "Awakening of the New Era", setCode: "OP05", number: "030", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000 },
  { id: "OP05-031", name: "X Drake", set: "Awakening of the New Era", setCode: "OP05", number: "031", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP05-032", name: "Basil Hawkins", set: "Awakening of the New Era", setCode: "OP05", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP05-033", name: "Jewelry Bonney", set: "Awakening of the New Era", setCode: "OP05", number: "033", type: "Character", color: "Green", rarity: "R", cost: 2, power: 2000 },
  { id: "OP05-034", name: "Urouge", set: "Awakening of the New Era", setCode: "OP05", number: "034", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-035", name: "Heat", set: "Awakening of the New Era", setCode: "OP05", number: "035", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-036", name: "Wire", set: "Awakening of the New Era", setCode: "OP05", number: "036", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-037", name: "Punk Gibson", set: "Awakening of the New Era", setCode: "OP05", number: "037", type: "Event", color: "Green", rarity: "R", cost: 2 },
  { id: "OP05-038", name: "Gamma Knife", set: "Awakening of the New Era", setCode: "OP05", number: "038", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  
  // Blue Cards (Film Red)
  { id: "OP05-039", name: "Uta", set: "Awakening of the New Era", setCode: "OP05", number: "039", type: "Character", color: "Blue", rarity: "SR", cost: 7, power: 7000 },
  { id: "OP05-040", name: "Shanks", set: "Awakening of the New Era", setCode: "OP05", number: "040", type: "Character", color: "Blue", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP05-041", name: "Benn Beckman", set: "Awakening of the New Era", setCode: "OP05", number: "041", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP05-042", name: "Lucky Roux", set: "Awakening of the New Era", setCode: "OP05", number: "042", type: "Character", color: "Blue", rarity: "R", cost: 2, power: 3000 },
  { id: "OP05-043", name: "Yasopp", set: "Awakening of the New Era", setCode: "OP05", number: "043", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 4000 },
  { id: "OP05-044", name: "Limejuice", set: "Awakening of the New Era", setCode: "OP05", number: "044", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-045", name: "Bonk Punch", set: "Awakening of the New Era", setCode: "OP05", number: "045", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-046", name: "Building Snake", set: "Awakening of the New Era", setCode: "OP05", number: "046", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-047", name: "Hongo", set: "Awakening of the New Era", setCode: "OP05", number: "047", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-048", name: "Howling Gab", set: "Awakening of the New Era", setCode: "OP05", number: "048", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-049", name: "Rockstar", set: "Awakening of the New Era", setCode: "OP05", number: "049", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP05-050", name: "Tot Musica", set: "Awakening of the New Era", setCode: "OP05", number: "050", type: "Stage", color: "Blue", rarity: "R", cost: 1 },
  { id: "OP05-051", name: "I'm Invincible", set: "Awakening of the New Era", setCode: "OP05", number: "051", type: "Event", color: "Blue", rarity: "R", cost: 2 },
  
  // Purple Cards (Beast Pirates)
  { id: "OP05-052", name: "Yamato", set: "Awakening of the New Era", setCode: "OP05", number: "052", type: "Character", color: "Purple", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP05-053", name: "Kaido", set: "Awakening of the New Era", setCode: "OP05", number: "053", type: "Character", color: "Purple", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP05-054", name: "King", set: "Awakening of the New Era", setCode: "OP05", number: "054", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 6000 },
  { id: "OP05-055", name: "Queen", set: "Awakening of the New Era", setCode: "OP05", number: "055", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000 },
  { id: "OP05-056", name: "Jack", set: "Awakening of the New Era", setCode: "OP05", number: "056", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000 },
  { id: "OP05-057", name: "Sasaki", set: "Awakening of the New Era", setCode: "OP05", number: "057", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 4000 },
  { id: "OP05-058", name: "Ulti", set: "Awakening of the New Era", setCode: "OP05", number: "058", type: "Character", color: "Purple", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP05-059", name: "Black Maria", set: "Awakening of the New Era", setCode: "OP05", number: "059", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP05-060", name: "Page One", set: "Awakening of the New Era", setCode: "OP05", number: "060", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP05-061", name: "Who's-Who", set: "Awakening of the New Era", setCode: "OP05", number: "061", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP05-062", name: "Fuza", set: "Awakening of the New Era", setCode: "OP05", number: "062", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 3000 },
  { id: "OP05-063", name: "Onimaru", set: "Awakening of the New Era", setCode: "OP05", number: "063", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 2000 },
  { id: "OP05-064", name: "Sparking Queen", set: "Awakening of the New Era", setCode: "OP05", number: "064", type: "Stage", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP05-065", name: "Blast Breath", set: "Awakening of the New Era", setCode: "OP05", number: "065", type: "Event", color: "Purple", rarity: "R", cost: 2 },
  
  // Black Cards (Marines)
  { id: "OP05-066", name: "Sakazuki", set: "Awakening of the New Era", setCode: "OP05", number: "066", type: "Character", color: "Black", rarity: "SR", cost: 8, power: 9000 },
  { id: "OP05-067", name: "Issho", set: "Awakening of the New Era", setCode: "OP05", number: "067", type: "Character", color: "Black", rarity: "SR", cost: 7, power: 8000 },
  { id: "OP05-068", name: "Ryokugyu", set: "Awakening of the New Era", setCode: "OP05", number: "068", type: "Character", color: "Black", rarity: "R", cost: 6, power: 7000 },
  { id: "OP05-069", name: "Borsalino", set: "Awakening of the New Era", setCode: "OP05", number: "069", type: "Character", color: "Black", rarity: "R", cost: 6, power: 7000 },
  { id: "OP05-070", name: "Aramaki", set: "Awakening of the New Era", setCode: "OP05", number: "070", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP05-071", name: "Sengoku", set: "Awakening of the New Era", setCode: "OP05", number: "071", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000 },
  { id: "OP05-072", name: "Garp", set: "Awakening of the New Era", setCode: "OP05", number: "072", type: "Character", color: "Black", rarity: "R", cost: 6, power: 7000 },
  { id: "OP05-073", name: "Tsuru", set: "Awakening of the New Era", setCode: "OP05", number: "073", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP05-074", name: "Kuzan", set: "Awakening of the New Era", setCode: "OP05", number: "074", type: "Character", color: "Black", rarity: "SR", cost: 7, power: 8000 },
  { id: "OP05-075", name: "Hina", set: "Awakening of the New Era", setCode: "OP05", number: "075", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-076", name: "Fullbody", set: "Awakening of the New Era", setCode: "OP05", number: "076", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000 },
  { id: "OP05-077", name: "Jango", set: "Awakening of the New Era", setCode: "OP05", number: "077", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-078", name: "Tashigi", set: "Awakening of the New Era", setCode: "OP05", number: "078", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-079", name: "Naguri", set: "Awakening of the New Era", setCode: "OP05", number: "079", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-080", name: "Greatness", set: "Awakening of the New Era", setCode: "OP05", number: "080", type: "Event", color: "Black", rarity: "R", cost: 1 },
  
  // Yellow Cards (Revolutionary Army)
  { id: "OP05-081", name: "Sabo", set: "Awakening of the New Era", setCode: "OP05", number: "081", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP05-082", name: "Emporio Ivankov", set: "Awakening of the New Era", setCode: "OP05", number: "082", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000 },
  { id: "OP05-083", name: "Karasu", set: "Awakening of the New Era", setCode: "OP05", number: "083", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000 },
  { id: "OP05-084", name: "Morley", set: "Awakening of the New Era", setCode: "OP05", number: "084", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000 },
  { id: "OP05-085", name: "Belo Betty", set: "Awakening of the New Era", setCode: "OP05", number: "085", type: "Character", color: "Yellow", rarity: "R", cost: 2, power: 3000 },
  { id: "OP05-086", name: "Lindbergh", set: "Awakening of the New Era", setCode: "OP05", number: "086", type: "Character", color: "Yellow", rarity: "R", cost: 3, power: 4000 },
  { id: "OP05-087", name: "Inazuma", set: "Awakening of the New Era", setCode: "OP05", number: "087", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP05-088", name: "Koala", set: "Awakening of the New Era", setCode: "OP05", number: "088", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000 },
  { id: "OP05-089", name: "Hack", set: "Awakening of the New Era", setCode: "OP05", number: "089", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-090", name: "Ahiru", set: "Awakening of the New Era", setCode: "OP05", number: "090", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-091", name: "Ushiano", set: "Awakening of the New Era", setCode: "OP05", number: "091", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-092", name: "Gambo", set: "Awakening of the New Era", setCode: "OP05", number: "092", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000 },
  { id: "OP05-093", name: "Moda", set: "Awakening of the New Era", setCode: "OP05", number: "093", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000 },
  { id: "OP05-094", name: "Village People's Dream", set: "Awakening of the New Era", setCode: "OP05", number: "094", type: "Event", color: "Yellow", rarity: "R", cost: 1 },
  
  // Secret Rares
  { id: "OP05-095", name: "Uta", set: "Awakening of the New Era", setCode: "OP05", number: "095", type: "Character", color: "Blue", rarity: "SEC", cost: 7, power: 7000 },
  { id: "OP05-096", name: "Shanks", set: "Awakening of the New Era", setCode: "OP05", number: "096", type: "Character", color: "Blue", rarity: "SEC", cost: 9, power: 10000 },
  { id: "OP05-097", name: "Monkey D. Luffy", set: "Awakening of the New Era", setCode: "OP05", number: "097", type: "Character", color: "Red", rarity: "SEC", cost: 9, power: 10000 },
  { id: "OP05-098", name: "Sakazuki", set: "Awakening of the New Era", setCode: "OP05", number: "098", type: "Character", color: "Black", rarity: "SEC", cost: 8, power: 9000 },
  { id: "OP05-099", name: "Gol.D.Roger", set: "Awakening of the New Era", setCode: "OP05", number: "099", type: "Character", color: "Red", rarity: "SEC", cost: 10, power: 12000 },
  { id: "OP05-100", name: "Silvers Rayleigh", set: "Awakening of the New Era", setCode: "OP05", number: "100", type: "Character", color: "Yellow", rarity: "SEC", cost: 5, power: 7000 }
];
