import type { Card } from './cards';

const OP05_CARDS: Card[] = [
  { id: "OP05-001", name: "Sabo", set: "Awakening of the New Era", setCode: "OP05", number: "001", type: "Leader", color: "Red/Black", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP05-002", name: "Belo Betty", set: "Awakening of the New Era", setCode: "OP05", number: "002", type: "Leader", color: "Red/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP05-003", name: "Inazuma", set: "Awakening of the New Era", setCode: "OP05", number: "003", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP05-004", name: "Emporio.Ivankov", set: "Awakening of the New Era", setCode: "OP05", number: "004", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP05-005", name: "Karasu", set: "Awakening of the New Era", setCode: "OP05", number: "005", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP05-006", name: "Koala", set: "Awakening of the New Era", setCode: "OP05", number: "006", type: "Character", color: "Red", rarity: "SuperRare", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP05-007", name: "Sabo", set: "Awakening of the New Era", setCode: "OP05", number: "007", type: "Character", color: "Red", rarity: "SuperRare", cost: 6, power: 7000, attribute: "Special" },
  { id: "OP05-008", name: "Chaka", set: "Awakening of the New Era", setCode: "OP05", number: "008", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP05-009", name: "Toh-Toh", set: "Awakening of the New Era", setCode: "OP05", number: "009", type: "Character", color: "Red", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP05-010", name: "Nico Robin", set: "Awakening of the New Era", setCode: "OP05", number: "010", type: "Character", color: "Red", rarity: "UC", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP05-011", name: "Bartholomew Kuma", set: "Awakening of the New Era", setCode: "OP05", number: "011", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP05-012", name: "Hack", set: "Awakening of the New Era", setCode: "OP05", number: "012", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP05-013", name: "Bunny Joe", set: "Awakening of the New Era", setCode: "OP05", number: "013", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000, attribute: "Ranged" },
  { id: "OP05-014", name: "Pell", set: "Awakening of the New Era", setCode: "OP05", number: "014", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP05-015", name: "Belo Betty", set: "Awakening of the New Era", setCode: "OP05", number: "015", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000, attribute: "Special" },
  { id: "OP05-016", name: "Morley", set: "Awakening of the New Era", setCode: "OP05", number: "016", type: "Character", color: "Red", rarity: "R", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP05-017", name: "Lindbergh", set: "Awakening of the New Era", setCode: "OP05", number: "017", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP05-018", name: "Emporio Energy Hormone", set: "Awakening of the New Era", setCode: "OP05", number: "018", type: "Event", color: "Red", rarity: "C", cost: 3 },
  { id: "OP05-019", name: "Fire Fist", set: "Awakening of the New Era", setCode: "OP05", number: "019", type: "Event", color: "Red", rarity: "R", cost: 2 },
  { id: "OP05-020", name: "Four Thousand-Brick Fist", set: "Awakening of the New Era", setCode: "OP05", number: "020", type: "Event", color: "Red", rarity: "UC", cost: 2 },
  { id: "OP05-021", name: "Revolutionary Army HQ", set: "Awakening of the New Era", setCode: "OP05", number: "021", type: "Stage", color: "Red", rarity: "UC", cost: 1 },
  { id: "OP05-022", name: "Donquixote Rosinante", set: "Awakening of the New Era", setCode: "OP05", number: "022", type: "Leader", color: "Green/Blue", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP05-023", name: "Vergo", set: "Awakening of the New Era", setCode: "OP05", number: "023", type: "Character", color: "Green", rarity: "R", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP05-024", name: "Kuween", set: "Awakening of the New Era", setCode: "OP05", number: "024", type: "Character", color: "Green", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP05-025", name: "Gladius", set: "Awakening of the New Era", setCode: "OP05", number: "025", type: "Character", color: "Green", rarity: "C", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP05-026", name: "Sarquiss", set: "Awakening of the New Era", setCode: "OP05", number: "026", type: "Character", color: "Green", rarity: "C", cost: 4, power: 4000, attribute: "Slash" },
  { id: "OP05-027", name: "Trafalgar Law", set: "Awakening of the New Era", setCode: "OP05", number: "027", type: "Character", color: "Green", rarity: "UC", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP05-028", name: "Donquixote Doflamingo", set: "Awakening of the New Era", setCode: "OP05", number: "028", type: "Character", color: "Green", rarity: "C", cost: 1, power: 2000, attribute: "Ranged" },
  { id: "OP05-029", name: "Donquixote Doflamingo", set: "Awakening of the New Era", setCode: "OP05", number: "029", type: "Character", color: "Green", rarity: "UC", cost: 7, power: 8000, attribute: "Special" },
  { id: "OP05-030", name: "Donquixote Rosinante", set: "Awakening of the New Era", setCode: "OP05", number: "030", type: "Character", color: "Green", rarity: "R", cost: 2, power: 1000, attribute: "Special" },
  { id: "OP05-031", name: "Buffalo", set: "Awakening of the New Era", setCode: "OP05", number: "031", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP05-032", name: "Pica", set: "Awakening of the New Era", setCode: "OP05", number: "032", type: "Character", color: "Green", rarity: "SuperRare", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP05-033", name: "Baby 5", set: "Awakening of the New Era", setCode: "OP05", number: "033", type: "Character", color: "Green", rarity: "C", cost: 1, power: 1000, attribute: "Special" },
  { id: "OP05-034", name: "Baby 5", set: "Awakening of the New Era", setCode: "OP05", number: "034", type: "Character", color: "Green", rarity: "R", cost: 1, power: 1000, attribute: "Special" },
  { id: "OP05-035", name: "Bellamy", set: "Awakening of the New Era", setCode: "OP05", number: "035", type: "Character", color: "Green", rarity: "C", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP05-036", name: "Monet", set: "Awakening of the New Era", setCode: "OP05", number: "036", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 1000, attribute: "Special" },
  { id: "OP05-037", name: "Because the Side of Justice Will Be Whichever Side Wins!!", set: "Awakening of the New Era", setCode: "OP05", number: "037", type: "Event", color: "Green", rarity: "R" },
  { id: "OP05-038", name: "Charlestone", set: "Awakening of the New Era", setCode: "OP05", number: "038", type: "Event", color: "Green", rarity: "C", cost: 2 },
  { id: "OP05-039", name: "Stick-Stickem Meteora", set: "Awakening of the New Era", setCode: "OP05", number: "039", type: "Event", color: "Green", rarity: "UC", cost: 2 },
  { id: "OP05-040", name: "Birdcage", set: "Awakening of the New Era", setCode: "OP05", number: "040", type: "Stage", color: "Green", rarity: "C", cost: 5 },
  { id: "OP05-041", name: "Sakazuki", set: "Awakening of the New Era", setCode: "OP05", number: "041", type: "Leader", color: "Blue/Black", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP05-042", name: "Issho", set: "Awakening of the New Era", setCode: "OP05", number: "042", type: "Character", color: "Blue", rarity: "R", cost: 6, power: 6000, attribute: "Special" },
  { id: "OP05-043", name: "Ulti", set: "Awakening of the New Era", setCode: "OP05", number: "043", type: "Character", color: "Blue", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP05-044", name: "John Giant", set: "Awakening of the New Era", setCode: "OP05", number: "044", type: "Character", color: "Blue", rarity: "C", cost: 8, power: 10000, attribute: "Slash" },
  { id: "OP05-045", name: "Stainless", set: "Awakening of the New Era", setCode: "OP05", number: "045", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP05-046", name: "Dalmatian", set: "Awakening of the New Era", setCode: "OP05", number: "046", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP05-047", name: "Basil Hawkins", set: "Awakening of the New Era", setCode: "OP05", number: "047", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP05-048", name: "Bastille", set: "Awakening of the New Era", setCode: "OP05", number: "048", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP05-049", name: "Haccha", set: "Awakening of the New Era", setCode: "OP05", number: "049", type: "Character", color: "Blue", rarity: "UC", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP05-050", name: "Hina", set: "Awakening of the New Era", setCode: "OP05", number: "050", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP05-051", name: "Borsalino", set: "Awakening of the New Era", setCode: "OP05", number: "051", type: "Character", color: "Blue", rarity: "SuperRare", cost: 7, power: 8000, attribute: "Special" },
  { id: "OP05-052", name: "Maynard", set: "Awakening of the New Era", setCode: "OP05", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 2000, attribute: "Wisdom" },
  { id: "OP05-053", name: "Mozambia", set: "Awakening of the New Era", setCode: "OP05", number: "053", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP05-054", name: "Monkey.D.Garp", set: "Awakening of the New Era", setCode: "OP05", number: "054", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 3000, attribute: "Strike" },
  { id: "OP05-055", name: "X.Drake", set: "Awakening of the New Era", setCode: "OP05", number: "055", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP05-056", name: "X.Barrels", set: "Awakening of the New Era", setCode: "OP05", number: "056", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP05-057", name: "Hound Blaze", set: "Awakening of the New Era", setCode: "OP05", number: "057", type: "Event", color: "Blue", rarity: "R", cost: 2 },
  { id: "OP05-058", name: "It's a Waste of Human Life!!", set: "Awakening of the New Era", setCode: "OP05", number: "058", type: "Event", color: "Blue", rarity: "C", cost: 8 },
  { id: "OP05-059", name: "Let Us Begin the World of Violence!!!", set: "Awakening of the New Era", setCode: "OP05", number: "059", type: "Event", color: "Blue", rarity: "UC", cost: 5 },
  { id: "OP05-060", name: "Monkey.D.Luffy", set: "Awakening of the New Era", setCode: "OP05", number: "060", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000, attribute: "Strike" },
  { id: "OP05-061", name: "Uso-Hachi", set: "Awakening of the New Era", setCode: "OP05", number: "061", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000, attribute: "Ranged" },
  { id: "OP05-062", name: "O-Nami", set: "Awakening of the New Era", setCode: "OP05", number: "062", type: "Character", color: "Purple", rarity: "UC", cost: 1, power: 1000, attribute: "Special" },
  { id: "OP05-063", name: "O-Robi", set: "Awakening of the New Era", setCode: "OP05", number: "063", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP05-064", name: "Killer", set: "Awakening of the New Era", setCode: "OP05", number: "064", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP05-065", name: "San-Gorou", set: "Awakening of the New Era", setCode: "OP05", number: "065", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 8000, attribute: "Strike" },
  { id: "OP05-066", name: "Jinbe", set: "Awakening of the New Era", setCode: "OP05", number: "066", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP05-067", name: "Zoro-Juurou", set: "Awakening of the New Era", setCode: "OP05", number: "067", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP05-068", name: "Chopa-Emon", set: "Awakening of the New Era", setCode: "OP05", number: "068", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000, attribute: "Wisdom" },
  { id: "OP05-069", name: "Trafalgar Law", set: "Awakening of the New Era", setCode: "OP05", number: "069", type: "Character", color: "Purple", rarity: "SuperRare", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP05-070", name: "Fra-Nosuke", set: "Awakening of the New Era", setCode: "OP05", number: "070", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 4000, attribute: "Strike" },
  { id: "OP05-071", name: "Bepo", set: "Awakening of the New Era", setCode: "OP05", number: "071", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP05-072", name: "Hone-Kichi", set: "Awakening of the New Era", setCode: "OP05", number: "072", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP05-073", name: "Miss Doublefinger(Zala)", set: "Awakening of the New Era", setCode: "OP05", number: "073", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 4000, attribute: "Slash" },
  { id: "OP05-074", name: "Eustass\"Captain\"Kid", set: "Awakening of the New Era", setCode: "OP05", number: "074", type: "Character", color: "Purple", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP05-075", name: "Mr.1(Daz.Bonez)", set: "Awakening of the New Era", setCode: "OP05", number: "075", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 1000, attribute: "Slash" },
  { id: "OP05-076", name: "When You're at Sea You Fight against Pirates!!", set: "Awakening of the New Era", setCode: "OP05", number: "076", type: "Event", color: "Purple", rarity: "R", cost: 1 },
  { id: "OP05-077", name: "Gamma Knife", set: "Awakening of the New Era", setCode: "OP05", number: "077", type: "Event", color: "Purple", rarity: "C", cost: 2 },
  { id: "OP05-078", name: "Punk Rotten", set: "Awakening of the New Era", setCode: "OP05", number: "078", type: "Event", color: "Purple", rarity: "UC", cost: 2 },
  { id: "OP05-079", name: "Viola", set: "Awakening of the New Era", setCode: "OP05", number: "079", type: "Character", color: "Black", rarity: "UC", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP05-080", name: "Elizabello II", set: "Awakening of the New Era", setCode: "OP05", number: "080", type: "Character", color: "Black", rarity: "UC", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP05-081", name: "One-Legged Toy Soldier", set: "Awakening of the New Era", setCode: "OP05", number: "081", type: "Character", color: "Black", rarity: "UC", cost: 2, attribute: "Strike" },
  { id: "OP05-082", name: "Shirahoshi", set: "Awakening of the New Era", setCode: "OP05", number: "082", type: "Character", color: "Black", rarity: "R", cost: 1, attribute: "Wisdom" },
  { id: "OP05-083", name: "Sterry", set: "Awakening of the New Era", setCode: "OP05", number: "083", type: "Character", color: "Black", rarity: "C", cost: 2, power: 4000, attribute: "Wisdom" },
  { id: "OP05-084", name: "Saint Charlos", set: "Awakening of the New Era", setCode: "OP05", number: "084", type: "Character", color: "Black", rarity: "C", cost: 3, attribute: "Ranged" },
  { id: "OP05-085", name: "Nefeltari Cobra", set: "Awakening of the New Era", setCode: "OP05", number: "085", type: "Character", color: "Black", rarity: "UC", cost: 2, power: 1000, attribute: "Wisdom" },
  { id: "OP05-086", name: "Nefeltari Vivi", set: "Awakening of the New Era", setCode: "OP05", number: "086", type: "Character", color: "Black", rarity: "R", cost: 1, power: 1000, attribute: "Wisdom" },
  { id: "OP05-087", name: "Hakuba", set: "Awakening of the New Era", setCode: "OP05", number: "087", type: "Character", color: "Black", rarity: "C", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP05-088", name: "Mansherry", set: "Awakening of the New Era", setCode: "OP05", number: "088", type: "Character", color: "Black", rarity: "R", cost: 1, attribute: "Special" },
  { id: "OP05-089", name: "Saint Mjosgard", set: "Awakening of the New Era", setCode: "OP05", number: "089", type: "Character", color: "Black", rarity: "C", cost: 5, power: 1000, attribute: "Wisdom" },
  { id: "OP05-090", name: "Riku Doldo III", set: "Awakening of the New Era", setCode: "OP05", number: "090", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000, attribute: "Wisdom" },
  { id: "OP05-091", name: "Rebecca", set: "Awakening of the New Era", setCode: "OP05", number: "091", type: "Character", color: "Black", rarity: "SuperRare", cost: 4, attribute: "Wisdom" },
  { id: "OP05-092", name: "Saint Rosward", set: "Awakening of the New Era", setCode: "OP05", number: "092", type: "Character", color: "Black", rarity: "C", cost: 5, attribute: "Ranged" },
  { id: "OP05-093", name: "Rob Lucci", set: "Awakening of the New Era", setCode: "OP05", number: "093", type: "Character", color: "Black", rarity: "SuperRare", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP05-094", name: "Haute Couture Patch★Work", set: "Awakening of the New Era", setCode: "OP05", number: "094", type: "Event", color: "Black", rarity: "R", cost: 1 },
  { id: "OP05-095", name: "Dragon Claw", set: "Awakening of the New Era", setCode: "OP05", number: "095", type: "Event", color: "Black", rarity: "C", cost: 2 },
  { id: "OP05-096", name: "I Bid 500 Million!!", set: "Awakening of the New Era", setCode: "OP05", number: "096", type: "Event", color: "Black", rarity: "UC", cost: 3 },
  { id: "OP05-097", name: "Mary Geoise", set: "Awakening of the New Era", setCode: "OP05", number: "097", type: "Stage", color: "Black", rarity: "C", cost: 1 },
  { id: "OP05-098", name: "Enel", set: "Awakening of the New Era", setCode: "OP05", number: "098", type: "Leader", color: "Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP05-099", name: "Amazon", set: "Awakening of the New Era", setCode: "OP05", number: "099", type: "Character", color: "Yellow", rarity: "UC", cost: 3, attribute: "Wisdom" },
  { id: "OP05-100", name: "Enel", set: "Awakening of the New Era", setCode: "OP05", number: "100", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 7, power: 7000, attribute: "Special" },
  { id: "OP05-101", name: "Ohm", set: "Awakening of the New Era", setCode: "OP05", number: "101", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP05-102", name: "Gedatsu", set: "Awakening of the New Era", setCode: "OP05", number: "102", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP05-103", name: "Kotori", set: "Awakening of the New Era", setCode: "OP05", number: "103", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 3000, attribute: "Special" },
  { id: "OP05-104", name: "Conis", set: "Awakening of the New Era", setCode: "OP05", number: "104", type: "Character", color: "Yellow", rarity: "UC", cost: 1, attribute: "Wisdom" },
  { id: "OP05-105", name: "Satori", set: "Awakening of the New Era", setCode: "OP05", number: "105", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 5000, attribute: "Strike" },
  { id: "OP05-106", name: "Shura", set: "Awakening of the New Era", setCode: "OP05", number: "106", type: "Character", color: "Yellow", rarity: "R", cost: 2, power: 2000, attribute: "Slash" },
  { id: "OP05-107", name: "Lieutenant Spacey", set: "Awakening of the New Era", setCode: "OP05", number: "107", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Ranged" },
  { id: "OP05-108", name: "Nola", set: "Awakening of the New Era", setCode: "OP05", number: "108", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "OP05-109", name: "Pagaya", set: "Awakening of the New Era", setCode: "OP05", number: "109", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 1000, attribute: "Wisdom" },
  { id: "OP05-110", name: "Holly", set: "Awakening of the New Era", setCode: "OP05", number: "110", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP05-111", name: "Hotori", set: "Awakening of the New Era", setCode: "OP05", number: "111", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 3000, attribute: "Special" },
  { id: "OP05-112", name: "Captain McKinley", set: "Awakening of the New Era", setCode: "OP05", number: "112", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 3000, attribute: "Wisdom" },
  { id: "OP05-113", name: "Yama", set: "Awakening of the New Era", setCode: "OP05", number: "113", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000, attribute: "Slash" },
  { id: "OP05-114", name: "El Thor", set: "Awakening of the New Era", setCode: "OP05", number: "114", type: "Event", color: "Yellow", rarity: "UC", cost: 1 },
  { id: "OP05-115", name: "Two-Hundred Million Volts Amaru", set: "Awakening of the New Era", setCode: "OP05", number: "115", type: "Event", color: "Yellow", rarity: "R", cost: 2 },
  { id: "OP05-116", name: "Hino Bird Zap", set: "Awakening of the New Era", setCode: "OP05", number: "116", type: "Event", color: "Yellow", rarity: "C", cost: 2 },
  { id: "OP05-117", name: "Upper Yard", set: "Awakening of the New Era", setCode: "OP05", number: "117", type: "Stage", color: "Yellow", rarity: "UC", cost: 1 },
  { id: "OP05-118", name: "Kaido", set: "Awakening of the New Era", setCode: "OP05", number: "118", type: "Character", color: "Blue", rarity: "SecretRare", cost: 10, power: 12000, attribute: "Special" },
  { id: "OP05-119", name: "Monkey.D.Luffy", set: "Awakening of the New Era", setCode: "OP05", number: "119", type: "Character", color: "Purple", rarity: "SecretRare", cost: 10, power: 12000, attribute: "Strike" },
];

export default OP05_CARDS;
