import type { Card } from './cards';

const OP06_CARDS: Card[] = [
  { id: "OP06-001", name: "Uta", set: "Wings of the Captain", setCode: "OP06", number: "001", type: "Leader", color: "Red/Purple", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP06-002", name: "Inazuma", set: "Wings of the Captain", setCode: "OP06", number: "002", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP06-003", name: "Emporio.Ivankov", set: "Wings of the Captain", setCode: "OP06", number: "003", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP06-004", name: "Baron Omatsuri", set: "Wings of the Captain", setCode: "OP06", number: "004", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP06-005", name: "Gasparde", set: "Wings of the Captain", setCode: "OP06", number: "005", type: "Character", color: "Red", rarity: "C", cost: 6, power: 8000, attribute: "Special" },
  { id: "OP06-006", name: "Saga", set: "Wings of the Captain", setCode: "OP06", number: "006", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP06-007", name: "Shanks", set: "Wings of the Captain", setCode: "OP06", number: "007", type: "Character", color: "Red", rarity: "SuperRare", cost: 10, power: 12000, attribute: "Slash" },
  { id: "OP06-008", name: "Schneider", set: "Wings of the Captain", setCode: "OP06", number: "008", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000, attribute: "Wisdom" },
  { id: "OP06-009", name: "Shuraiya", set: "Wings of the Captain", setCode: "OP06", number: "009", type: "Character", color: "Red", rarity: "SuperRare", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP06-010", name: "Douglas Bullet", set: "Wings of the Captain", setCode: "OP06", number: "010", type: "Character", color: "Red", rarity: "R", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP06-011", name: "Tot Musica", set: "Wings of the Captain", setCode: "OP06", number: "011", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP06-012", name: "Bear.King", set: "Wings of the Captain", setCode: "OP06", number: "012", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP06-013", name: "Monkey.D.Luffy", set: "Wings of the Captain", setCode: "OP06", number: "013", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP06-014", name: "Ratchet", set: "Wings of the Captain", setCode: "OP06", number: "014", type: "Character", color: "Red", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP06-015", name: "Lily Carnation", set: "Wings of the Captain", setCode: "OP06", number: "015", type: "Character", color: "Red", rarity: "C", cost: 4, attribute: "Special" },
  { id: "OP06-016", name: "Raise Max", set: "Wings of the Captain", setCode: "OP06", number: "016", type: "Character", color: "Red", rarity: "UC", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP06-017", name: "Meteor-Strike of Love", set: "Wings of the Captain", setCode: "OP06", number: "017", type: "Event", color: "Red", rarity: "C", cost: 2 },
  { id: "OP06-018", name: "Gum-Gum King Kong Gatling", set: "Wings of the Captain", setCode: "OP06", number: "018", type: "Event", color: "Red", rarity: "R", cost: 2 },
  { id: "OP06-019", name: "Blue Dragon Seal Water Stream", set: "Wings of the Captain", setCode: "OP06", number: "019", type: "Event", color: "Red", rarity: "UC", cost: 3 },
  { id: "OP06-020", name: "Hody Jones", set: "Wings of the Captain", setCode: "OP06", number: "020", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, attribute: "Strike" },
  { id: "OP06-021", name: "Perona", set: "Wings of the Captain", setCode: "OP06", number: "021", type: "Leader", color: "Green/Black", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP06-022", name: "Yamato", set: "Wings of the Captain", setCode: "OP06", number: "022", type: "Leader", color: "Green/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP06-023", name: "Arlong", set: "Wings of the Captain", setCode: "OP06", number: "023", type: "Character", color: "Green", rarity: "R", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP06-024", name: "Ikaros Much", set: "Wings of the Captain", setCode: "OP06", number: "024", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP06-025", name: "Camie", set: "Wings of the Captain", setCode: "OP06", number: "025", type: "Character", color: "Green", rarity: "R", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP06-026", name: "Koushirou", set: "Wings of the Captain", setCode: "OP06", number: "026", type: "Character", color: "Green", rarity: "C", cost: 3, attribute: "Slash" },
  { id: "OP06-027", name: "Gyro", set: "Wings of the Captain", setCode: "OP06", number: "027", type: "Character", color: "Green", rarity: "C", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP06-028", name: "Zeo", set: "Wings of the Captain", setCode: "OP06", number: "028", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000, attribute: "Wisdom" },
  { id: "OP06-029", name: "Daruma", set: "Wings of the Captain", setCode: "OP06", number: "029", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP06-030", name: "Dosun", set: "Wings of the Captain", setCode: "OP06", number: "030", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP06-031", name: "Hatchan", set: "Wings of the Captain", setCode: "OP06", number: "031", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP06-032", name: "Hammond", set: "Wings of the Captain", setCode: "OP06", number: "032", type: "Character", color: "Green", rarity: "C", cost: 2, power: 2000, attribute: "Slash" },
  { id: "OP06-033", name: "Vander Decken IX", set: "Wings of the Captain", setCode: "OP06", number: "033", type: "Character", color: "Green", rarity: "R", cost: 2, power: 2000, attribute: "Ranged" },
  { id: "OP06-034", name: "Hyouzou", set: "Wings of the Captain", setCode: "OP06", number: "034", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP06-035", name: "Hody Jones", set: "Wings of the Captain", setCode: "OP06", number: "035", type: "Character", color: "Green", rarity: "SuperRare", cost: 7, power: 8000, attribute: "Strike" },
  { id: "OP06-036", name: "Ryuma", set: "Wings of the Captain", setCode: "OP06", number: "036", type: "Character", color: "Green", rarity: "R", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP06-037", name: "Wadatsumi", set: "Wings of the Captain", setCode: "OP06", number: "037", type: "Character", color: "Green", rarity: "C", cost: 6, power: 8000, attribute: "Strike" },
  { id: "OP06-038", name: "The Billion-fold World Trichiliocosm", set: "Wings of the Captain", setCode: "OP06", number: "038", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP06-039", name: "You Ain't Even Worth Killing Time!!", set: "Wings of the Captain", setCode: "OP06", number: "039", type: "Event", color: "Green", rarity: "R", cost: 4 },
  { id: "OP06-040", name: "Shark Arrows", set: "Wings of the Captain", setCode: "OP06", number: "040", type: "Event", color: "Green", rarity: "C", cost: 2 },
  { id: "OP06-041", name: "The Ark Noah", set: "Wings of the Captain", setCode: "OP06", number: "041", type: "Stage", color: "Green", rarity: "C", cost: 6 },
  { id: "OP06-042", name: "Vinsmoke Reiju", set: "Wings of the Captain", setCode: "OP06", number: "042", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP06-043", name: "Aramaki", set: "Wings of the Captain", setCode: "OP06", number: "043", type: "Character", color: "Blue", rarity: "SuperRare", cost: 8, power: 8000, attribute: "Special" },
  { id: "OP06-044", name: "Gion", set: "Wings of the Captain", setCode: "OP06", number: "044", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP06-045", name: "Kuzan", set: "Wings of the Captain", setCode: "OP06", number: "045", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP06-046", name: "Sakazuki", set: "Wings of the Captain", setCode: "OP06", number: "046", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP06-047", name: "Charlotte Pudding", set: "Wings of the Captain", setCode: "OP06", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 4000, attribute: "Wisdom" },
  { id: "OP06-048", name: "Zeff", set: "Wings of the Captain", setCode: "OP06", number: "048", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 3000, attribute: "Strike" },
  { id: "OP06-049", name: "Sengoku", set: "Wings of the Captain", setCode: "OP06", number: "049", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "OP06-050", name: "Tashigi", set: "Wings of the Captain", setCode: "OP06", number: "050", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP06-051", name: "Tsuru", set: "Wings of the Captain", setCode: "OP06", number: "051", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 4000, attribute: "Special" },
  { id: "OP06-052", name: "Tokikake", set: "Wings of the Captain", setCode: "OP06", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP06-053", name: "Jaguar.D.Saul", set: "Wings of the Captain", setCode: "OP06", number: "053", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP06-054", name: "Borsalino", set: "Wings of the Captain", setCode: "OP06", number: "054", type: "Character", color: "Blue", rarity: "UC", cost: 2, power: 4000, attribute: "Special" },
  { id: "OP06-055", name: "Monkey.D.Garp", set: "Wings of the Captain", setCode: "OP06", number: "055", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "OP06-056", name: "Ama no Murakumo Sword", set: "Wings of the Captain", setCode: "OP06", number: "056", type: "Event", color: "Blue", rarity: "UC", cost: 2 },
  { id: "OP06-057", name: "But I Will Never Doubt a Woman's Tears!!!!", set: "Wings of the Captain", setCode: "OP06", number: "057", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP06-058", name: "Gravity Blade Raging Tiger", set: "Wings of the Captain", setCode: "OP06", number: "058", type: "Event", color: "Blue", rarity: "R", cost: 7 },
  { id: "OP06-059", name: "White Snake", set: "Wings of the Captain", setCode: "OP06", number: "059", type: "Event", color: "Blue", rarity: "UC", cost: 2 },
  { id: "OP06-060", name: "Vinsmoke Ichiji", set: "Wings of the Captain", setCode: "OP06", number: "060", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 4000, attribute: "Strike" },
  { id: "OP06-061", name: "Vinsmoke Ichiji", set: "Wings of the Captain", setCode: "OP06", number: "061", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 7000, attribute: "Strike" },
  { id: "OP06-062", name: "Vinsmoke Judge", set: "Wings of the Captain", setCode: "OP06", number: "062", type: "Character", color: "Purple", rarity: "SuperRare", cost: 8, power: 8000, attribute: "Slash" },
  { id: "OP06-063", name: "Vinsmoke Sora", set: "Wings of the Captain", setCode: "OP06", number: "063", type: "Character", color: "Purple", rarity: "UC", cost: 1, attribute: "Wisdom" },
  { id: "OP06-064", name: "Vinsmoke Niji", set: "Wings of the Captain", setCode: "OP06", number: "064", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 3000, attribute: "Special" },
  { id: "OP06-065", name: "Vinsmoke Niji", set: "Wings of the Captain", setCode: "OP06", number: "065", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP06-066", name: "Vinsmoke Yonji", set: "Wings of the Captain", setCode: "OP06", number: "066", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP06-067", name: "Vinsmoke Yonji", set: "Wings of the Captain", setCode: "OP06", number: "067", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP06-068", name: "Vinsmoke Reiju", set: "Wings of the Captain", setCode: "OP06", number: "068", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000, attribute: "Special" },
  { id: "OP06-069", name: "Vinsmoke Reiju", set: "Wings of the Captain", setCode: "OP06", number: "069", type: "Character", color: "Purple", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP06-070", name: "Eldoraggo", set: "Wings of the Captain", setCode: "OP06", number: "070", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 7000, attribute: "Special" },
  { id: "OP06-071", name: "Gild Tesoro", set: "Wings of the Captain", setCode: "OP06", number: "071", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP06-072", name: "Cosette", set: "Wings of the Captain", setCode: "OP06", number: "072", type: "Character", color: "Purple", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP06-073", name: "Shiki", set: "Wings of the Captain", setCode: "OP06", number: "073", type: "Character", color: "Purple", rarity: "UC", cost: 2, power: 1000, attribute: "Special" },
  { id: "OP06-074", name: "Zephyr (Navy)", set: "Wings of the Captain", setCode: "OP06", number: "074", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 7000, attribute: "Strike" },
  { id: "OP06-075", name: "Count Battler", set: "Wings of the Captain", setCode: "OP06", number: "075", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP06-076", name: "Hitokiri Kamazo", set: "Wings of the Captain", setCode: "OP06", number: "076", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP06-077", name: "Black Bug", set: "Wings of the Captain", setCode: "OP06", number: "077", type: "Event", color: "Purple", rarity: "R", cost: 4 },
  { id: "OP06-078", name: "GERMA 66", set: "Wings of the Captain", setCode: "OP06", number: "078", type: "Event", color: "Purple", rarity: "UC", cost: 1 },
  { id: "OP06-079", name: "Kingdom of GERMA", set: "Wings of the Captain", setCode: "OP06", number: "079", type: "Stage", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP06-080", name: "Gecko Moria", set: "Wings of the Captain", setCode: "OP06", number: "080", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP06-081", name: "Absalom", set: "Wings of the Captain", setCode: "OP06", number: "081", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP06-082", name: "Inuppe", set: "Wings of the Captain", setCode: "OP06", number: "082", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP06-083", name: "Oars", set: "Wings of the Captain", setCode: "OP06", number: "083", type: "Character", color: "Black", rarity: "UC", cost: 4, power: 7000, attribute: "Strike" },
  { id: "OP06-084", name: "Jigoro of the Wind", set: "Wings of the Captain", setCode: "OP06", number: "084", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP06-085", name: "Kumacy", set: "Wings of the Captain", setCode: "OP06", number: "085", type: "Character", color: "Black", rarity: "UC", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP06-086", name: "Gecko Moria", set: "Wings of the Captain", setCode: "OP06", number: "086", type: "Character", color: "Black", rarity: "SuperRare", cost: 8, power: 9000, attribute: "Special" },
  { id: "OP06-087", name: "Cerberus", set: "Wings of the Captain", setCode: "OP06", number: "087", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP06-088", name: "Sai", set: "Wings of the Captain", setCode: "OP06", number: "088", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP06-089", name: "Taralan", set: "Wings of the Captain", setCode: "OP06", number: "089", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP06-090", name: "Dr. Hogback", set: "Wings of the Captain", setCode: "OP06", number: "090", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, attribute: "Wisdom" },
  { id: "OP06-091", name: "Victoria Cindry", set: "Wings of the Captain", setCode: "OP06", number: "091", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP06-092", name: "Brook", set: "Wings of the Captain", setCode: "OP06", number: "092", type: "Character", color: "Black", rarity: "R", cost: 6, power: 6000, attribute: "Slash" },
  { id: "OP06-093", name: "Perona", set: "Wings of the Captain", setCode: "OP06", number: "093", type: "Character", color: "Black", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP06-094", name: "Lola", set: "Wings of the Captain", setCode: "OP06", number: "094", type: "Character", color: "Black", rarity: "C", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP06-095", name: "Shadows Asgard", set: "Wings of the Captain", setCode: "OP06", number: "095", type: "Event", color: "Black", rarity: "UC", cost: 2 },
  { id: "OP06-096", name: "...Nothing...at All!!!", set: "Wings of the Captain", setCode: "OP06", number: "096", type: "Event", color: "Black", rarity: "C", cost: 3 },
  { id: "OP06-097", name: "Negative Hollow", set: "Wings of the Captain", setCode: "OP06", number: "097", type: "Event", color: "Black", rarity: "R", cost: 2 },
  { id: "OP06-098", name: "Thriller Bark", set: "Wings of the Captain", setCode: "OP06", number: "098", type: "Stage", color: "Black", rarity: "C", cost: 1 },
  { id: "OP06-099", name: "Aisa", set: "Wings of the Captain", setCode: "OP06", number: "099", type: "Character", color: "Yellow", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP06-100", name: "Inuarashi", set: "Wings of the Captain", setCode: "OP06", number: "100", type: "Character", color: "Yellow", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP06-101", name: "O-Nami", set: "Wings of the Captain", setCode: "OP06", number: "101", type: "Character", color: "Yellow", rarity: "R", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP06-102", name: "Kamakiri", set: "Wings of the Captain", setCode: "OP06", number: "102", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP06-103", name: "Kawamatsu", set: "Wings of the Captain", setCode: "OP06", number: "103", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP06-104", name: "Kikunojo", set: "Wings of the Captain", setCode: "OP06", number: "104", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP06-105", name: "Genbo", set: "Wings of the Captain", setCode: "OP06", number: "105", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP06-106", name: "Kouzuki Hiyori", set: "Wings of the Captain", setCode: "OP06", number: "106", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 2, attribute: "Wisdom" },
  { id: "OP06-107", name: "Kouzuki Momonosuke", set: "Wings of the Captain", setCode: "OP06", number: "107", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Wisdom" },
  { id: "OP06-108", name: "Tenguyama Hitetsu", set: "Wings of the Captain", setCode: "OP06", number: "108", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP06-109", name: "Denjiro", set: "Wings of the Captain", setCode: "OP06", number: "109", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP06-110", name: "Nekomamushi", set: "Wings of the Captain", setCode: "OP06", number: "110", type: "Character", color: "Yellow", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP06-111", name: "Braham", set: "Wings of the Captain", setCode: "OP06", number: "111", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Ranged" },
  { id: "OP06-112", name: "Raizo", set: "Wings of the Captain", setCode: "OP06", number: "112", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP06-113", name: "Raki", set: "Wings of the Captain", setCode: "OP06", number: "113", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 1000, attribute: "Ranged" },
  { id: "OP06-114", name: "Wyper", set: "Wings of the Captain", setCode: "OP06", number: "114", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 7000, attribute: "Ranged" },
  { id: "OP06-115", name: "You're the One Who Should Disappear.", set: "Wings of the Captain", setCode: "OP06", number: "115", type: "Event", color: "Yellow", rarity: "R" },
  { id: "OP06-116", name: "Reject", set: "Wings of the Captain", setCode: "OP06", number: "116", type: "Event", color: "Yellow", rarity: "R", cost: 4 },
  { id: "OP06-117", name: "The Ark Maxim", set: "Wings of the Captain", setCode: "OP06", number: "117", type: "Stage", color: "Yellow", rarity: "C", cost: 1 },
  { id: "OP06-118", name: "Roronoa Zoro", set: "Wings of the Captain", setCode: "OP06", number: "118", type: "Character", color: "Green", rarity: "SecretRare", cost: 9, power: 9000, attribute: "Slash" },
  { id: "OP06-119", name: "Sanji", set: "Wings of the Captain", setCode: "OP06", number: "119", type: "Character", color: "Blue", rarity: "SecretRare", cost: 9, power: 9000, attribute: "Strike" },
];

export default OP06_CARDS;
