// OP06: WINGS OF THE CAPTAIN - Synced from official cardlist
// 151 entries including variants and cross-set SP/TR cards
const OP06_CARDS = [
  { id: "OP06-001", name: "Uta", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "001", type: "Leader", color: "Red/Purple", rarity: "L", cost: 4, power: 5000 },
  { id: "OP06-001_p1", name: "Uta (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "001", type: "Leader", color: "Red/Purple", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP06-001&variant=p1" },
  { id: "OP06-002", name: "Inazuma", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "002", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000 },
  { id: "OP06-003", name: "Emporio.Ivankov", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "003", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP06-004", name: "Baron Omatsuri", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "004", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP06-005", name: "Gasparde", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "005", type: "Character", color: "Red", rarity: "C", cost: 6, power: 8000 },
  { id: "OP06-006", name: "Saga", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "006", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP06-007", name: "Shanks", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "007", type: "Character", color: "Red", rarity: "SR", cost: 10, power: 12000 },
  { id: "OP06-007_p1", name: "Shanks (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "007", type: "Character", color: "Red", rarity: "SR", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP06-007&variant=p1" },
  { id: "OP06-008", name: "Schneider", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "008", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000 },
  { id: "OP06-009", name: "Shuraiya", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "009", type: "Character", color: "Red", rarity: "SR", cost: 3, power: 4000 },
  { id: "OP06-009_p1", name: "Shuraiya (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "009", type: "Character", color: "Red", rarity: "SR", cost: 3, power: 4000, imageUrl: "/api/card-image?id=OP06-009&variant=p1" },
  { id: "OP06-010", name: "Douglas Bullet", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "010", type: "Character", color: "Red", rarity: "R", cost: 6, power: 7000 },
  { id: "OP06-011", name: "Tot Musica", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "011", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000 },
  { id: "OP06-012", name: "Bear.King", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "012", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP06-013", name: "Monkey.D.Luffy", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "013", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000 },
  { id: "OP06-013_p1", name: "Monkey.D.Luffy (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "013", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000, imageUrl: "/api/card-image?id=OP06-013&variant=p1" },
  { id: "OP06-014", name: "Ratchet", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "014", type: "Character", color: "Red", rarity: "C", cost: 1 },
  { id: "OP06-015", name: "Lily Carnation", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "015", type: "Character", color: "Red", rarity: "C", cost: 4 },
  { id: "OP06-016", name: "Raise Max", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "016", type: "Character", color: "Red", rarity: "UC", cost: 1, power: 2000 },
  { id: "OP06-017", name: "Meteor-Strike of Love", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "017", type: "Event", color: "Red", rarity: "C", cost: 2 },
  { id: "OP06-018", name: "Gum-Gum King Kong Gatling", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "018", type: "Event", color: "Red", rarity: "R", cost: 2 },
  { id: "OP06-019", name: "Blue Dragon Seal Water Stream", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "019", type: "Event", color: "Red", rarity: "UC", cost: 3 },
  { id: "OP06-020", name: "Hody Jones", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "020", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000 },
  { id: "OP06-020_p1", name: "Hody Jones (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "020", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP06-020&variant=p1" },
  { id: "OP06-021", name: "Perona", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "021", type: "Leader", color: "Green/Black", rarity: "L", cost: 4, power: 5000 },
  { id: "OP06-021_p1", name: "Perona (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "021", type: "Leader", color: "Green/Black", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP06-021&variant=p1" },
  { id: "OP06-022", name: "Yamato", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "022", type: "Leader", color: "Green/Yellow", rarity: "L", cost: 4, power: 5000 },
  { id: "OP06-022_p1", name: "Yamato (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "022", type: "Leader", color: "Green/Yellow", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP06-022&variant=p1" },
  { id: "OP06-023", name: "Arlong", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "023", type: "Character", color: "Green", rarity: "R", cost: 4, power: 6000 },
  { id: "OP06-024", name: "Ikaros Much", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "024", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP06-025", name: "Camie", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "025", type: "Character", color: "Green", rarity: "R", cost: 1, power: 2000 },
  { id: "OP06-025_p1", name: "Camie (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "025", type: "Character", color: "Green", rarity: "R", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP06-025&variant=p1" },
  { id: "OP06-026", name: "Koushirou", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "026", type: "Character", color: "Green", rarity: "C", cost: 3 },
  { id: "OP06-027", name: "Gyro", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "027", type: "Character", color: "Green", rarity: "C", cost: 1, power: 2000 },
  { id: "OP06-028", name: "Zeo", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "028", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP06-029", name: "Daruma", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "029", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP06-030", name: "Dosun", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "030", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "OP06-031", name: "Hatchan", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "031", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP06-032", name: "Hammond", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "032", type: "Character", color: "Green", rarity: "C", cost: 2, power: 2000 },
  { id: "OP06-033", name: "Vander Decken IX", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "033", type: "Character", color: "Green", rarity: "R", cost: 2, power: 2000 },
  { id: "OP06-034", name: "Hyouzou", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "034", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 6000 },
  { id: "OP06-035", name: "Hody Jones", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "035", type: "Character", color: "Green", rarity: "SR", cost: 7, power: 8000 },
  { id: "OP06-035_p1", name: "Hody Jones (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "035", type: "Character", color: "Green", rarity: "SR", cost: 7, power: 8000, imageUrl: "/api/card-image?id=OP06-035&variant=p1" },
  { id: "OP06-036", name: "Ryuma", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "036", type: "Character", color: "Green", rarity: "R", cost: 4, power: 6000 },
  { id: "OP06-037", name: "Wadatsumi", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "037", type: "Character", color: "Green", rarity: "C", cost: 6, power: 8000 },
  { id: "OP06-038", name: "The Billion-fold World Trichiliocosm", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "038", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP06-039", name: "You Ain't Even Worth Killing Time!!", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "039", type: "Event", color: "Green", rarity: "R", cost: 4 },
  { id: "OP06-040", name: "Shark Arrows", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "040", type: "Event", color: "Green", rarity: "C", cost: 2 },
  { id: "OP06-041", name: "The Ark Noah", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "041", type: "Stage", color: "Green", rarity: "C", cost: 6 },
  { id: "OP06-042", name: "Vinsmoke Reiju", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "042", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 4, power: 5000 },
  { id: "OP06-042_p1", name: "Vinsmoke Reiju (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "042", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP06-042&variant=p1" },
  { id: "OP06-043", name: "Aramaki", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "043", type: "Character", color: "Blue", rarity: "SR", cost: 8, power: 8000 },
  { id: "OP06-043_p1", name: "Aramaki (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "043", type: "Character", color: "Blue", rarity: "SR", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP06-043&variant=p1" },
  { id: "OP06-044", name: "Gion", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "044", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP06-045", name: "Kuzan", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "045", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 5000 },
  { id: "OP06-046", name: "Sakazuki", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "046", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP06-047", name: "Charlotte Pudding", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 4000 },
  { id: "OP06-048", name: "Zeff", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "048", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 3000 },
  { id: "OP06-049", name: "Sengoku", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "049", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 7000 },
  { id: "OP06-050", name: "Tashigi", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "050", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000 },
  { id: "OP06-050_p1", name: "Tashigi (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "050", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP06-050&variant=p1" },
  { id: "OP06-051", name: "Tsuru", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "051", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 4000 },
  { id: "OP06-052", name: "Tokikake", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP06-053", name: "Jaguar.D.Saul", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "053", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP06-054", name: "Borsalino", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "054", type: "Character", color: "Blue", rarity: "UC", cost: 2, power: 4000 },
  { id: "OP06-055", name: "Monkey.D.Garp", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "055", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 7000 },
  { id: "OP06-056", name: "Ama no Murakumo Sword", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "056", type: "Event", color: "Blue", rarity: "UC", cost: 2 },
  { id: "OP06-057", name: "But I Will Never Doubt a Woman's Tears!!!!", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "057", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP06-058", name: "Gravity Blade Raging Tiger", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "058", type: "Event", color: "Blue", rarity: "R", cost: 7 },
  { id: "OP06-059", name: "White Snake", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "059", type: "Event", color: "Blue", rarity: "UC", cost: 2 },
  { id: "OP06-060", name: "Vinsmoke Ichiji", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "060", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 4000 },
  { id: "OP06-061", name: "Vinsmoke Ichiji", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "061", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 7000 },
  { id: "OP06-061_p1", name: "Vinsmoke Ichiji (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "061", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 7000, imageUrl: "/api/card-image?id=OP06-061&variant=p1" },
  { id: "OP06-062", name: "Vinsmoke Judge", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "062", type: "Character", color: "Purple", rarity: "SR", cost: 8, power: 8000 },
  { id: "OP06-062_p1", name: "Vinsmoke Judge (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "062", type: "Character", color: "Purple", rarity: "SR", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP06-062&variant=p1" },
  { id: "OP06-063", name: "Vinsmoke Sora", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "063", type: "Character", color: "Purple", rarity: "UC", cost: 1 },
  { id: "OP06-064", name: "Vinsmoke Niji", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "064", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 3000 },
  { id: "OP06-065", name: "Vinsmoke Niji", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "065", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 6000 },
  { id: "OP06-066", name: "Vinsmoke Yonji", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "066", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000 },
  { id: "OP06-067", name: "Vinsmoke Yonji", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "067", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000 },
  { id: "OP06-068", name: "Vinsmoke Reiju", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "068", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000 },
  { id: "OP06-069", name: "Vinsmoke Reiju", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "069", type: "Character", color: "Purple", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP06-069_p1", name: "Vinsmoke Reiju (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "069", type: "Character", color: "Purple", rarity: "SR", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP06-069&variant=p1" },
  { id: "OP06-070", name: "Eldoraggo", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "070", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 7000 },
  { id: "OP06-071", name: "Gild Tesoro", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "071", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP06-072", name: "Cosette", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "072", type: "Character", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP06-073", name: "Shiki", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "073", type: "Character", color: "Purple", rarity: "UC", cost: 2, power: 1000 },
  { id: "OP06-074", name: "Zephyr (Navy)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "074", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 7000 },
  { id: "OP06-075", name: "Count Battler", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "075", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP06-076", name: "Hitokiri Kamazo", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "076", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP06-077", name: "Black Bug", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "077", type: "Event", color: "Purple", rarity: "R", cost: 4 },
  { id: "OP06-078", name: "GERMA 66", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "078", type: "Event", color: "Purple", rarity: "UC", cost: 1 },
  { id: "OP06-079", name: "Kingdom of GERMA", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "079", type: "Stage", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP06-080", name: "Gecko Moria", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "080", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000 },
  { id: "OP06-080_p1", name: "Gecko Moria (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "080", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP06-080&variant=p1" },
  { id: "OP06-081", name: "Absalom", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "081", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000 },
  { id: "OP06-081_p1", name: "Absalom (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "081", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP06-081&variant=p1" },
  { id: "OP06-082", name: "Inuppe", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "082", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP06-083", name: "Oars", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "083", type: "Character", color: "Black", rarity: "UC", cost: 4, power: 7000 },
  { id: "OP06-084", name: "Jigoro of the Wind", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "084", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP06-085", name: "Kumacy", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "085", type: "Character", color: "Black", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP06-086", name: "Gecko Moria", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "086", type: "Character", color: "Black", rarity: "SR", cost: 8, power: 9000 },
  { id: "OP06-086_p1", name: "Gecko Moria (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "086", type: "Character", color: "Black", rarity: "SR", cost: 8, power: 9000, imageUrl: "/api/card-image?id=OP06-086&variant=p1" },
  { id: "OP06-087", name: "Cerberus", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "087", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000 },
  { id: "OP06-088", name: "Sai", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "088", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP06-089", name: "Taralan", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "089", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP06-090", name: "Dr. Hogback", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "090", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000 },
  { id: "OP06-091", name: "Victoria Cindry", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "091", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 2000 },
  { id: "OP06-092", name: "Brook", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "092", type: "Character", color: "Black", rarity: "R", cost: 6, power: 6000 },
  { id: "OP06-093", name: "Perona", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "093", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP06-093_p1", name: "Perona (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "093", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP06-093&variant=p1" },
  { id: "OP06-094", name: "Lola", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "094", type: "Character", color: "Black", rarity: "C", cost: 4, power: 6000 },
  { id: "OP06-095", name: "Shadows Asgard", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "095", type: "Event", color: "Black", rarity: "UC", cost: 2 },
  { id: "OP06-096", name: "...Nothing...at All!!!", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "096", type: "Event", color: "Black", rarity: "C", cost: 3 },
  { id: "OP06-097", name: "Negative Hollow", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "097", type: "Event", color: "Black", rarity: "R", cost: 2 },
  { id: "OP06-098", name: "Thriller Bark", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "098", type: "Stage", color: "Black", rarity: "C", cost: 1 },
  { id: "OP06-099", name: "Aisa", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "099", type: "Character", color: "Yellow", rarity: "C", cost: 1 },
  { id: "OP06-100", name: "Inuarashi", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "100", type: "Character", color: "Yellow", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP06-101", name: "O-Nami", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "101", type: "Character", color: "Yellow", rarity: "R", cost: 2, power: 3000 },
  { id: "OP06-101_p1", name: "O-Nami (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "101", type: "Character", color: "Yellow", rarity: "R", cost: 2, power: 3000, imageUrl: "/api/card-image?id=OP06-101&variant=p1" },
  { id: "OP06-102", name: "Kamakiri", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "102", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000 },
  { id: "OP06-103", name: "Kawamatsu", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "103", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000 },
  { id: "OP06-104", name: "Kikunojo", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "104", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 6000 },
  { id: "OP06-105", name: "Genbo", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "105", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000 },
  { id: "OP06-106", name: "Kouzuki Hiyori", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "106", type: "Character", color: "Yellow", rarity: "SR", cost: 2 },
  { id: "OP06-106_p1", name: "Kouzuki Hiyori (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "106", type: "Character", color: "Yellow", rarity: "SR", cost: 2, imageUrl: "/api/card-image?id=OP06-106&variant=p1" },
  { id: "OP06-107", name: "Kouzuki Momonosuke", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "107", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP06-107_p1", name: "Kouzuki Momonosuke (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "107", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP06-107&variant=p1" },
  { id: "OP06-108", name: "Tenguyama Hitetsu", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "108", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 2000 },
  { id: "OP06-109", name: "Denjiro", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "109", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP06-110", name: "Nekomamushi", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "110", type: "Character", color: "Yellow", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP06-111", name: "Braham", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "111", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000 },
  { id: "OP06-112", name: "Raizo", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "112", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000 },
  { id: "OP06-113", name: "Raki", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "113", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 1000 },
  { id: "OP06-114", name: "Wyper", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "114", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 7000 },
  { id: "OP06-115", name: "You're the One Who Should Disappear.", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "115", type: "Event", color: "Yellow", rarity: "R" },
  { id: "OP06-116", name: "Reject", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "116", type: "Event", color: "Yellow", rarity: "R", cost: 4 },
  { id: "OP06-117", name: "The Ark Maxim", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "117", type: "Stage", color: "Yellow", rarity: "C", cost: 1 },
  { id: "OP06-118", name: "Roronoa Zoro", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 9, power: 9000 },
  { id: "OP06-118_p1", name: "Roronoa Zoro (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 9, power: 9000, imageUrl: "/api/card-image?id=OP06-118&variant=p1" },
  { id: "OP06-118_p2", name: "Roronoa Zoro (Manga)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 9, power: 9000, imageUrl: "/api/card-image?id=OP06-118&variant=p2" },
  { id: "OP06-119", name: "Sanji", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "119", type: "Character", color: "Blue", rarity: "SEC", cost: 9, power: 9000 },
  { id: "OP06-119_p1", name: "Sanji (Alt Art)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "119", type: "Character", color: "Blue", rarity: "SEC", cost: 9, power: 9000, imageUrl: "/api/card-image?id=OP06-119&variant=p1" },
  { id: "ST01-007_p3", name: "Nami (TR)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "007", type: "Character", color: "Red", rarity: "TR", cost: 1, power: 1000, imageUrl: "/api/card-image?id=ST01-007&variant=p3" },
  { id: "OP03-008_p1", name: "Buggy (SP)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "008", type: "Character", color: "Red", rarity: "SP", cost: 1, power: 3000, imageUrl: "/api/card-image?id=OP03-008&variant=p1" },
  { id: "OP03-114_p2", name: "Charlotte Linlin (SP)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "114", type: "Character", color: "Yellow", rarity: "SP", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP03-114&variant=p2" },
  { id: "OP04-024_p2", name: "Sugar (SP)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "024", type: "Character", color: "Green", rarity: "SP", cost: 2, imageUrl: "/api/card-image?id=OP04-024&variant=p2" },
  { id: "OP04-064_p2", name: "Ms. All Sunday (SP)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "064", type: "Character", color: "Purple", rarity: "SP", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP04-064&variant=p2" },
  { id: "OP05-051_p2", name: "Borsalino (SP)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "051", type: "Character", color: "Blue", rarity: "SP", cost: 7, power: 8000, imageUrl: "/api/card-image?id=OP05-051&variant=p2" },
  { id: "OP05-091_p2", name: "Rebecca (SP)", set: "WINGS OF THE CAPTAIN", setCode: "OP06", number: "091", type: "Character", color: "Black", rarity: "SP", cost: 4, imageUrl: "/api/card-image?id=OP05-091&variant=p2" },
];

export default OP06_CARDS;
