import type { Card } from './cards';

const OP07_CARDS: Card[] = [
  { id: "OP07-001", name: "Monkey.D.Dragon", set: "500 Years in the Future", setCode: "OP07", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP07-002", name: "Ain", set: "500 Years in the Future", setCode: "OP07", number: "002", type: "Character", color: "Red", rarity: "R", cost: 7, power: 6000, attribute: "Special" },
  { id: "OP07-003", name: "Outlook III", set: "500 Years in the Future", setCode: "OP07", number: "003", type: "Character", color: "Red", rarity: "R", cost: 2, attribute: "Wisdom" },
  { id: "OP07-004", name: "Curly.Dadan", set: "500 Years in the Future", setCode: "OP07", number: "004", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP07-005", name: "Carina", set: "500 Years in the Future", setCode: "OP07", number: "005", type: "Character", color: "Red", rarity: "R", cost: 3, attribute: "Wisdom" },
  { id: "OP07-006", name: "Sterry", set: "500 Years in the Future", setCode: "OP07", number: "006", type: "Character", color: "Red", rarity: "C", cost: 1, power: 1000, attribute: "Wisdom" },
  { id: "OP07-007", name: "Dice", set: "500 Years in the Future", setCode: "OP07", number: "007", type: "Character", color: "Red", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP07-008", name: "Mr. Tanaka", set: "500 Years in the Future", setCode: "OP07", number: "008", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 3000, attribute: "Special" },
  { id: "OP07-009", name: "Dogura &amp; Magura", set: "500 Years in the Future", setCode: "OP07", number: "009", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP07-010", name: "Baccarat", set: "500 Years in the Future", setCode: "OP07", number: "010", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP07-011", name: "Bluejam", set: "500 Years in the Future", setCode: "OP07", number: "011", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP07-012", name: "Porchemy", set: "500 Years in the Future", setCode: "OP07", number: "012", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP07-013", name: "Masked Deuce", set: "500 Years in the Future", setCode: "OP07", number: "013", type: "Character", color: "Red", rarity: "UC", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP07-014", name: "Moda", set: "500 Years in the Future", setCode: "OP07", number: "014", type: "Character", color: "Red", rarity: "UC", cost: 1, attribute: "Wisdom" },
  { id: "OP07-015", name: "Monkey.D.Dragon", set: "500 Years in the Future", setCode: "OP07", number: "015", type: "Character", color: "Red", rarity: "SuperRare", cost: 8, power: 9000, attribute: "Special" },
  { id: "OP07-016", name: "Galaxy Wink", set: "500 Years in the Future", setCode: "OP07", number: "016", type: "Event", color: "Red", rarity: "R", cost: 1 },
  { id: "OP07-017", name: "Dragon Breath", set: "500 Years in the Future", setCode: "OP07", number: "017", type: "Event", color: "Red", rarity: "UC", cost: 2 },
  { id: "OP07-018", name: "KEEP OUT", set: "500 Years in the Future", setCode: "OP07", number: "018", type: "Event", color: "Red", rarity: "C", cost: 1 },
  { id: "OP07-019", name: "Jewelry Bonney", set: "500 Years in the Future", setCode: "OP07", number: "019", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP07-020", name: "Aladine", set: "500 Years in the Future", setCode: "OP07", number: "020", type: "Character", color: "Green", rarity: "C", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP07-021", name: "Urouge", set: "500 Years in the Future", setCode: "OP07", number: "021", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP07-022", name: "Otama", set: "500 Years in the Future", setCode: "OP07", number: "022", type: "Character", color: "Green", rarity: "R", cost: 1, attribute: "Special" },
  { id: "OP07-023", name: "Caribou", set: "500 Years in the Future", setCode: "OP07", number: "023", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP07-024", name: "Koala", set: "500 Years in the Future", setCode: "OP07", number: "024", type: "Character", color: "Green", rarity: "C", cost: 3, attribute: "Wisdom" },
  { id: "OP07-025", name: "Coribou", set: "500 Years in the Future", setCode: "OP07", number: "025", type: "Character", color: "Green", rarity: "C", cost: 3, power: 3000, attribute: "Strike" },
  { id: "OP07-026", name: "Jewelry Bonney", set: "500 Years in the Future", setCode: "OP07", number: "026", type: "Character", color: "Green", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP07-027", name: "Jinbe", set: "500 Years in the Future", setCode: "OP07", number: "027", type: "Character", color: "Green", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP07-028", name: "Scratchmen Apoo", set: "500 Years in the Future", setCode: "OP07", number: "028", type: "Character", color: "Green", rarity: "C", cost: 6, power: 8000, attribute: "Ranged" },
  { id: "OP07-029", name: "Basil Hawkins", set: "500 Years in the Future", setCode: "OP07", number: "029", type: "Character", color: "Green", rarity: "SuperRare", cost: 6, power: 7000, attribute: "Slash" },
  { id: "OP07-030", name: "Pappag", set: "500 Years in the Future", setCode: "OP07", number: "030", type: "Character", color: "Green", rarity: "C", cost: 2, attribute: "Wisdom" },
  { id: "OP07-031", name: "Bartolomeo", set: "500 Years in the Future", setCode: "OP07", number: "031", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP07-032", name: "Fisher Tiger", set: "500 Years in the Future", setCode: "OP07", number: "032", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP07-033", name: "Monkey.D.Luffy", set: "500 Years in the Future", setCode: "OP07", number: "033", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP07-034", name: "Roronoa Zoro", set: "500 Years in the Future", setCode: "OP07", number: "034", type: "Character", color: "Green", rarity: "UC", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP07-035", name: "Karmic Punishment", set: "500 Years in the Future", setCode: "OP07", number: "035", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "OP07-036", name: "Demonic Aura Nine-Sword Style Asura Demon Nine Flash", set: "500 Years in the Future", setCode: "OP07", number: "036", type: "Event", color: "Green", rarity: "R", cost: 2 },
  { id: "OP07-037", name: "More Pizza!!", set: "500 Years in the Future", setCode: "OP07", number: "037", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP07-038", name: "Boa Hancock", set: "500 Years in the Future", setCode: "OP07", number: "038", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP07-039", name: "Edward Weevil", set: "500 Years in the Future", setCode: "OP07", number: "039", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP07-040", name: "Crocodile", set: "500 Years in the Future", setCode: "OP07", number: "040", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP07-041", name: "Gloriosa (Grandma Nyon)", set: "500 Years in the Future", setCode: "OP07", number: "041", type: "Character", color: "Blue", rarity: "UC", cost: 1, attribute: "Wisdom" },
  { id: "OP07-042", name: "Gecko Moria", set: "500 Years in the Future", setCode: "OP07", number: "042", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP07-043", name: "Salome", set: "500 Years in the Future", setCode: "OP07", number: "043", type: "Character", color: "Blue", rarity: "UC", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP07-044", name: "Dracule Mihawk", set: "500 Years in the Future", setCode: "OP07", number: "044", type: "Character", color: "Blue", rarity: "C", cost: 8, power: 10000, attribute: "Slash" },
  { id: "OP07-045", name: "Jinbe", set: "500 Years in the Future", setCode: "OP07", number: "045", type: "Character", color: "Blue", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP07-046", name: "Sengoku", set: "500 Years in the Future", setCode: "OP07", number: "046", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP07-047", name: "Trafalgar Law", set: "500 Years in the Future", setCode: "OP07", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 4000, attribute: "Slash" },
  { id: "OP07-048", name: "Donquixote Doflamingo", set: "500 Years in the Future", setCode: "OP07", number: "048", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP07-049", name: "Buckin", set: "500 Years in the Future", setCode: "OP07", number: "049", type: "Character", color: "Blue", rarity: "C", cost: 2, attribute: "Wisdom" },
  { id: "OP07-050", name: "Boa Sandersonia", set: "500 Years in the Future", setCode: "OP07", number: "050", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 3000, attribute: "Strike" },
  { id: "OP07-051", name: "Boa Hancock", set: "500 Years in the Future", setCode: "OP07", number: "051", type: "Character", color: "Blue", rarity: "SuperRare", cost: 6, power: 8000, attribute: "Special" },
  { id: "OP07-052", name: "Boa Marigold", set: "500 Years in the Future", setCode: "OP07", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP07-053", name: "Portgas.D.Ace", set: "500 Years in the Future", setCode: "OP07", number: "053", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP07-054", name: "Marguerite", set: "500 Years in the Future", setCode: "OP07", number: "054", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 2000, attribute: "Wisdom" },
  { id: "OP07-055", name: "Snake Dance", set: "500 Years in the Future", setCode: "OP07", number: "055", type: "Event", color: "Blue", rarity: "C", cost: 2 },
  { id: "OP07-056", name: "Slave Arrow", set: "500 Years in the Future", setCode: "OP07", number: "056", type: "Event", color: "Blue", rarity: "UC", cost: 1 },
  { id: "OP07-057", name: "Perfume Femur", set: "500 Years in the Future", setCode: "OP07", number: "057", type: "Event", color: "Blue", rarity: "R", cost: 2 },
  { id: "OP07-058", name: "Island of Women", set: "500 Years in the Future", setCode: "OP07", number: "058", type: "Stage", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP07-059", name: "Foxy", set: "500 Years in the Future", setCode: "OP07", number: "059", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP07-060", name: "Itomimizu", set: "500 Years in the Future", setCode: "OP07", number: "060", type: "Character", color: "Purple", rarity: "UC", cost: 3, attribute: "Wisdom" },
  { id: "OP07-061", name: "Vinsmoke Sanji", set: "500 Years in the Future", setCode: "OP07", number: "061", type: "Character", color: "Purple", rarity: "C", cost: 1, attribute: "Strike" },
  { id: "OP07-062", name: "Vinsmoke Reiju", set: "500 Years in the Future", setCode: "OP07", number: "062", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP07-063", name: "Capote", set: "500 Years in the Future", setCode: "OP07", number: "063", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP07-064", name: "Sanji", set: "500 Years in the Future", setCode: "OP07", number: "064", type: "Character", color: "Purple", rarity: "SuperRare", cost: 6, power: 6000, attribute: "Strike" },
  { id: "OP07-065", name: "Gina", set: "500 Years in the Future", setCode: "OP07", number: "065", type: "Character", color: "Purple", rarity: "UC", cost: 1, attribute: "Wisdom" },
  { id: "OP07-066", name: "Tony Tony.Chopper", set: "500 Years in the Future", setCode: "OP07", number: "066", type: "Character", color: "Purple", rarity: "R", cost: 2, attribute: "Strike" },
  { id: "OP07-067", name: "Tonjit", set: "500 Years in the Future", setCode: "OP07", number: "067", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 3000, attribute: "Wisdom" },
  { id: "OP07-068", name: "Hamburg", set: "500 Years in the Future", setCode: "OP07", number: "068", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP07-069", name: "Pickles", set: "500 Years in the Future", setCode: "OP07", number: "069", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP07-070", name: "Big Bun", set: "500 Years in the Future", setCode: "OP07", number: "070", type: "Character", color: "Purple", rarity: "UC", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP07-071", name: "Foxy", set: "500 Years in the Future", setCode: "OP07", number: "071", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 7000, attribute: "Special" },
  { id: "OP07-072", name: "Porche", set: "500 Years in the Future", setCode: "OP07", number: "072", type: "Character", color: "Purple", rarity: "SuperRare", cost: 3, power: 5000, attribute: "Wisdom" },
  { id: "OP07-073", name: "Monkey.D.Luffy", set: "500 Years in the Future", setCode: "OP07", number: "073", type: "Character", color: "Purple", rarity: "R", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP07-074", name: "Monda", set: "500 Years in the Future", setCode: "OP07", number: "074", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP07-075", name: "Slow-Slow Beam", set: "500 Years in the Future", setCode: "OP07", number: "075", type: "Event", color: "Purple", rarity: "UC", cost: 1 },
  { id: "OP07-076", name: "Slow-Slow Beam Sword", set: "500 Years in the Future", setCode: "OP07", number: "076", type: "Event", color: "Purple", rarity: "C", cost: 2 },
  { id: "OP07-077", name: "We're Going to Claim the One Piece!!!", set: "500 Years in the Future", setCode: "OP07", number: "077", type: "Event", color: "Purple", rarity: "R", cost: 1 },
  { id: "OP07-078", name: "Megaton Nine-Tails Rush", set: "500 Years in the Future", setCode: "OP07", number: "078", type: "Event", color: "Purple", rarity: "C", cost: 3 },
  { id: "OP07-079", name: "Rob Lucci", set: "500 Years in the Future", setCode: "OP07", number: "079", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000, attribute: "Strike" },
  { id: "OP07-080", name: "Kaku", set: "500 Years in the Future", setCode: "OP07", number: "080", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP07-081", name: "Kalifa", set: "500 Years in the Future", setCode: "OP07", number: "081", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP07-082", name: "Captain John", set: "500 Years in the Future", setCode: "OP07", number: "082", type: "Character", color: "Black", rarity: "UC", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP07-083", name: "Gecko Moria", set: "500 Years in the Future", setCode: "OP07", number: "083", type: "Character", color: "Black", rarity: "UC", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP07-084", name: "Gismonda", set: "500 Years in the Future", setCode: "OP07", number: "084", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP07-085", name: "Stussy", set: "500 Years in the Future", setCode: "OP07", number: "085", type: "Character", color: "Black", rarity: "SuperRare", cost: 9, power: 9000, attribute: "Special" },
  { id: "OP07-086", name: "Spandam", set: "500 Years in the Future", setCode: "OP07", number: "086", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP07-087", name: "Baskerville", set: "500 Years in the Future", setCode: "OP07", number: "087", type: "Character", color: "Black", rarity: "C", cost: 3, power: 3000, attribute: "Slash" },
  { id: "OP07-088", name: "Hattori", set: "500 Years in the Future", setCode: "OP07", number: "088", type: "Character", color: "Black", rarity: "UC", cost: 1, attribute: "Strike" },
  { id: "OP07-089", name: "Maha", set: "500 Years in the Future", setCode: "OP07", number: "089", type: "Character", color: "Black", rarity: "C", cost: 6, power: 8000, attribute: "Strike" },
  { id: "OP07-090", name: "Morgans", set: "500 Years in the Future", setCode: "OP07", number: "090", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000, attribute: "Wisdom" },
  { id: "OP07-091", name: "Monkey.D.Luffy", set: "500 Years in the Future", setCode: "OP07", number: "091", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP07-092", name: "Joseph", set: "500 Years in the Future", setCode: "OP07", number: "092", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP07-093", name: "Rob Lucci", set: "500 Years in the Future", setCode: "OP07", number: "093", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP07-094", name: "Shave", set: "500 Years in the Future", setCode: "OP07", number: "094", type: "Event", color: "Black", rarity: "UC", cost: 1 },
  { id: "OP07-095", name: "Iron Body", set: "500 Years in the Future", setCode: "OP07", number: "095", type: "Event", color: "Black", rarity: "C", cost: 2 },
  { id: "OP07-096", name: "Tempest Kick", set: "500 Years in the Future", setCode: "OP07", number: "096", type: "Event", color: "Black", rarity: "R", cost: 1 },
  { id: "OP07-097", name: "Vegapunk", set: "500 Years in the Future", setCode: "OP07", number: "097", type: "Leader", color: "Yellow", rarity: "L", cost: 2, power: 5000, attribute: "Wisdom" },
  { id: "OP07-098", name: "Atlas", set: "500 Years in the Future", setCode: "OP07", number: "098", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000, attribute: "Wisdom" },
  { id: "OP07-099", name: "Usopp", set: "500 Years in the Future", setCode: "OP07", number: "099", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 2000, attribute: "Ranged" },
  { id: "OP07-100", name: "Edison", set: "500 Years in the Future", setCode: "OP07", number: "100", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 5000, attribute: "Wisdom" },
  { id: "OP07-101", name: "Shaka", set: "500 Years in the Future", setCode: "OP07", number: "101", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000, attribute: "Wisdom" },
  { id: "OP07-102", name: "Jinbe", set: "500 Years in the Future", setCode: "OP07", number: "102", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP07-103", name: "Tony Tony.Chopper", set: "500 Years in the Future", setCode: "OP07", number: "103", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000, attribute: "Wisdom" },
  { id: "OP07-104", name: "Nico Robin", set: "500 Years in the Future", setCode: "OP07", number: "104", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP07-105", name: "Pythagoras", set: "500 Years in the Future", setCode: "OP07", number: "105", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000, attribute: "Wisdom" },
  { id: "OP07-106", name: "Fuza", set: "500 Years in the Future", setCode: "OP07", number: "106", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 6000, attribute: "Special" },
  { id: "OP07-107", name: "Franky", set: "500 Years in the Future", setCode: "OP07", number: "107", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP07-108", name: "Vega Force 01", set: "500 Years in the Future", setCode: "OP07", number: "108", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP07-109", name: "Monkey.D.Luffy", set: "500 Years in the Future", setCode: "OP07", number: "109", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP07-110", name: "York", set: "500 Years in the Future", setCode: "OP07", number: "110", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 6000, attribute: "Wisdom" },
  { id: "OP07-111", name: "Lilith", set: "500 Years in the Future", setCode: "OP07", number: "111", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 3, power: 5000, attribute: "Wisdom" },
  { id: "OP07-112", name: "Lucy", set: "500 Years in the Future", setCode: "OP07", number: "112", type: "Character", color: "Yellow", rarity: "R", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP07-113", name: "Roronoa Zoro", set: "500 Years in the Future", setCode: "OP07", number: "113", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP07-114", name: "He Possesses the World's Most Brilliant Mind", set: "500 Years in the Future", setCode: "OP07", number: "114", type: "Event", color: "Yellow", rarity: "UC", cost: 1 },
  { id: "OP07-115", name: "I Re-Quasar Helllp!!", set: "500 Years in the Future", setCode: "OP07", number: "115", type: "Event", color: "Yellow", rarity: "C", cost: 1 },
  { id: "OP07-116", name: "Blaze Slice", set: "500 Years in the Future", setCode: "OP07", number: "116", type: "Event", color: "Yellow", rarity: "R", cost: 1 },
  { id: "OP07-117", name: "Egghead", set: "500 Years in the Future", setCode: "OP07", number: "117", type: "Stage", color: "Yellow", rarity: "C", cost: 2 },
  { id: "OP07-118", name: "Sabo", set: "500 Years in the Future", setCode: "OP07", number: "118", type: "Character", color: "Black", rarity: "SecretRare", cost: 8, power: 9000, attribute: "Special" },
  { id: "OP07-119", name: "Portgas.D.Ace", set: "500 Years in the Future", setCode: "OP07", number: "119", type: "Character", color: "Yellow", rarity: "SecretRare", cost: 10, power: 10000, attribute: "Special" },
];

export default OP07_CARDS;
