import { Card } from "./cards";

// Two Legends (OP08) - Key cards
export const OP08_CARDS: Card[] = [
  // Leaders
  { id: "OP08-001", name: "Monkey D. Luffy", set: "Two Legends", setCode: "OP08", number: "001", type: "Leader", color: "Red/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP08-002", name: "Shanks", set: "Two Legends", setCode: "OP08", number: "002", type: "Leader", color: "Red/Purple", rarity: "L", cost: 0, power: 5000 },
  { id: "OP08-003", name: "Nefeltari Vivi", set: "Two Legends", setCode: "OP08", number: "003", type: "Leader", color: "Red/Blue", rarity: "L", cost: 0, power: 5000 },
  { id: "OP08-004", name: "Buggy", set: "Two Legends", setCode: "OP08", number: "004", type: "Leader", color: "Blue/Green", rarity: "L", cost: 0, power: 5000 },
  { id: "OP08-005", name: "Dracule Mihawk", set: "Two Legends", setCode: "OP08", number: "005", type: "Leader", color: "Blue", rarity: "L", cost: 0, power: 5000 },
  { id: "OP08-006", name: "Crocodile", set: "Two Legends", setCode: "OP08", number: "006", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 0, power: 5000 },
  { id: "OP08-007", name: "Gecko Moria", set: "Two Legends", setCode: "OP08", number: "007", type: "Leader", color: "Purple/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP08-008", name: "Perona", set: "Two Legends", setCode: "OP08", number: "008", type: "Leader", color: "Purple/Yellow", rarity: "L", cost: 0, power: 5000 },
  
  // Red Cards (Roger Pirates)
  { id: "OP08-009", name: "Gol.D.Roger", set: "Two Legends", setCode: "OP08", number: "009", type: "Character", color: "Red", rarity: "SR", cost: 10, power: 12000 },
  { id: "OP08-010", name: "Silvers Rayleigh", set: "Two Legends", setCode: "OP08", number: "010", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 7000 },
  { id: "OP08-011", name: "Scopper Gaban", set: "Two Legends", setCode: "OP08", number: "011", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000 },
  { id: "OP08-012", name: "Crocus", set: "Two Legends", setCode: "OP08", number: "012", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000 },
  { id: "OP08-013", name: "Seagull Guns Nozdon", set: "Two Legends", setCode: "OP08", number: "013", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP08-014", name: "Sun Bell Grount", set: "Two Legends", setCode: "OP08", number: "014", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-015", name: "Moon Catcher Taro", set: "Two Legends", setCode: "OP08", number: "015", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-016", name: "Tongari Den", set: "Two Legends", setCode: "OP08", number: "016", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-017", name: "Shanks", set: "Two Legends", setCode: "OP08", number: "017", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP08-018", name: "Benn Beckman", set: "Two Legends", setCode: "OP08", number: "018", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000 },
  { id: "OP08-019", name: "Yasopp", set: "Two Legends", setCode: "OP08", number: "019", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000 },
  { id: "OP08-020", name: "Lucky Roux", set: "Two Legends", setCode: "OP08", number: "020", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000 },
  { id: "OP08-021", name: "Building Snake", set: "Two Legends", setCode: "OP08", number: "021", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-022", name: "Hongo", set: "Two Legends", setCode: "OP08", number: "022", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-023", name: "Howling Gab", set: "Two Legends", setCode: "OP08", number: "023", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-024", name: "Limejuice", set: "Two Legends", setCode: "OP08", number: "024", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-025", name: "Bonk Punch", set: "Two Legends", setCode: "OP08", number: "025", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-026", name: "Rockstar", set: "Two Legends", setCode: "OP08", number: "026", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP08-027", name: "Monkey D. Luffy", set: "Two Legends", setCode: "OP08", number: "027", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP08-028", name: "Nefeltari Vivi", set: "Two Legends", setCode: "OP08", number: "028", type: "Character", color: "Red", rarity: "R", cost: 3, power: 3000 },
  { id: "OP08-029", name: "Nefeltari Cobra", set: "Two Legends", setCode: "OP08", number: "029", type: "Character", color: "Red", rarity: "C", cost: 2, power: 0 },
  { id: "OP08-030", name: "Nefeltari Vivi", set: "Two Legends", setCode: "OP08", number: "030", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 4000 },
  { id: "OP08-031", name: "Oro Jackson", set: "Two Legends", setCode: "OP08", number: "031", type: "Stage", color: "Red", rarity: "R", cost: 2 },
  
  // Blue Cards (Cross Guild)
  { id: "OP08-032", name: "Buggy", set: "Two Legends", setCode: "OP08", number: "032", type: "Character", color: "Blue", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP08-033", name: "Dracule Mihawk", set: "Two Legends", setCode: "OP08", number: "033", type: "Character", color: "Blue", rarity: "SR", cost: 7, power: 8000 },
  { id: "OP08-034", name: "Crocodile", set: "Two Legends", setCode: "OP08", number: "034", type: "Character", color: "Blue", rarity: "SR", cost: 7, power: 7000 },
  { id: "OP08-035", name: "Daz Bonez", set: "Two Legends", setCode: "OP08", number: "035", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 4000 },
  { id: "OP08-036", name: "Galdino", set: "Two Legends", setCode: "OP08", number: "036", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP08-037", name: "Bentham", set: "Two Legends", setCode: "OP08", number: "037", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 4000 },
  { id: "OP08-038", name: "Mr. 4 & Lassoo", set: "Two Legends", setCode: "OP08", number: "038", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP08-039", name: "Miss Doublefinger", set: "Two Legends", setCode: "OP08", number: "039", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP08-040", name: "Miss Merry Christmas", set: "Two Legends", setCode: "OP08", number: "040", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-041", name: "Miss Goldenweek", set: "Two Legends", setCode: "OP08", number: "041", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-042", name: "Mr. 5", set: "Two Legends", setCode: "OP08", number: "042", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP08-043", name: "Miss Valentine", set: "Two Legends", setCode: "OP08", number: "043", type: "Character", color: "Blue", rarity: "UC", cost: 2, power: 2000 },
  { id: "OP08-044", name: "Cabaji", set: "Two Legends", setCode: "OP08", number: "044", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-045", name: "Mohji", set: "Two Legends", setCode: "OP08", number: "045", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-046", name: "Richie", set: "Two Legends", setCode: "OP08", number: "046", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-047", name: "Alvida", set: "Two Legends", setCode: "OP08", number: "047", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-048", name: "Cross Guild", set: "Two Legends", setCode: "OP08", number: "048", type: "Stage", color: "Blue", rarity: "R", cost: 1 },
  
  // Green Cards (Former Warlords)
  { id: "OP08-049", name: "Boa Hancock", set: "Two Legends", setCode: "OP08", number: "049", type: "Character", color: "Green", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP08-050", name: "Edward Weevil", set: "Two Legends", setCode: "OP08", number: "050", type: "Character", color: "Green", rarity: "R", cost: 6, power: 7000 },
  { id: "OP08-051", name: "Buggy", set: "Two Legends", setCode: "OP08", number: "051", type: "Character", color: "Green", rarity: "R", cost: 3, power: 4000 },
  { id: "OP08-052", name: "Trafalgar Law", set: "Two Legends", setCode: "OP08", number: "052", type: "Character", color: "Green", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP08-053", name: "Eustass Kid", set: "Two Legends", setCode: "OP08", number: "053", type: "Character", color: "Green", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP08-054", name: "Bepo", set: "Two Legends", setCode: "OP08", number: "054", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP08-055", name: "Penguin", set: "Two Legends", setCode: "OP08", number: "055", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-056", name: "Shachi", set: "Two Legends", setCode: "OP08", number: "056", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-057", name: "Killer", set: "Two Legends", setCode: "OP08", number: "057", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000 },
  { id: "OP08-058", name: "Heat", set: "Two Legends", setCode: "OP08", number: "058", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-059", name: "Wire", set: "Two Legends", setCode: "OP08", number: "059", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-060", name: "Jewelry Bonney", set: "Two Legends", setCode: "OP08", number: "060", type: "Character", color: "Green", rarity: "R", cost: 2, power: 2000 },
  
  // Purple Cards (Thriller Bark)
  { id: "OP08-061", name: "Gecko Moria", set: "Two Legends", setCode: "OP08", number: "061", type: "Character", color: "Purple", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP08-062", name: "Absalom", set: "Two Legends", setCode: "OP08", number: "062", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 4000 },
  { id: "OP08-063", name: "Perona", set: "Two Legends", setCode: "OP08", number: "063", type: "Character", color: "Purple", rarity: "SR", cost: 3, power: 3000 },
  { id: "OP08-064", name: "Hogback", set: "Two Legends", setCode: "OP08", number: "064", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-065", name: "Victoria Cindry", set: "Two Legends", setCode: "OP08", number: "065", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-066", name: "Kumashi", set: "Two Legends", setCode: "OP08", number: "066", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-067", name: "Shimotsuki Ryuma", set: "Two Legends", setCode: "OP08", number: "067", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000 },
  { id: "OP08-068", name: "Oars", set: "Two Legends", setCode: "OP08", number: "068", type: "Character", color: "Purple", rarity: "R", cost: 6, power: 6000 },
  { id: "OP08-069", name: "Jigoro", set: "Two Legends", setCode: "OP08", number: "069", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-070", name: "Dog Penguin", set: "Two Legends", setCode: "OP08", number: "070", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-071", name: "Crocus", set: "Two Legends", setCode: "OP08", number: "071", type: "Character", color: "Purple", rarity: "R", cost: 2, power: 2000 },
  { id: "OP08-072", name: "Shirahoshi", set: "Two Legends", setCode: "OP08", number: "072", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 0 },
  
  // Yellow Cards
  { id: "OP08-073", name: "Sabo", set: "Two Legends", setCode: "OP08", number: "073", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP08-074", name: "Monkey D. Dragon", set: "Two Legends", setCode: "OP08", number: "074", type: "Character", color: "Yellow", rarity: "SR", cost: 7, power: 7000 },
  { id: "OP08-075", name: "Emporio Ivankov", set: "Two Legends", setCode: "OP08", number: "075", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000 },
  { id: "OP08-076", name: "Koala", set: "Two Legends", setCode: "OP08", number: "076", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000 },
  { id: "OP08-077", name: "Hack", set: "Two Legends", setCode: "OP08", number: "077", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-078", name: "Belo Betty", set: "Two Legends", setCode: "OP08", number: "078", type: "Character", color: "Yellow", rarity: "R", cost: 2, power: 3000 },
  { id: "OP08-079", name: "Lindbergh", set: "Two Legends", setCode: "OP08", number: "079", type: "Character", color: "Yellow", rarity: "R", cost: 3, power: 4000 },
  { id: "OP08-080", name: "Karasu", set: "Two Legends", setCode: "OP08", number: "080", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000 },
  { id: "OP08-081", name: "Morley", set: "Two Legends", setCode: "OP08", number: "081", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000 },
  { id: "OP08-082", name: "Inazuma", set: "Two Legends", setCode: "OP08", number: "082", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP08-083", name: "Ahiru", set: "Two Legends", setCode: "OP08", number: "083", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-084", name: "Ushiano", set: "Two Legends", setCode: "OP08", number: "084", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-085", name: "Gambo", set: "Two Legends", setCode: "OP08", number: "085", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-086", name: "Moda", set: "Two Legends", setCode: "OP08", number: "086", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000 },
  
  // Black Cards (Cipher Pol)
  { id: "OP08-087", name: "Rob Lucci", set: "Two Legends", setCode: "OP08", number: "087", type: "Character", color: "Black", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP08-088", name: "Kaku", set: "Two Legends", setCode: "OP08", number: "088", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000 },
  { id: "OP08-089", name: "Stussy", set: "Two Legends", setCode: "OP08", number: "089", type: "Character", color: "Black", rarity: "R", cost: 3, power: 3000 },
  { id: "OP08-090", name: "Jabra", set: "Two Legends", setCode: "OP08", number: "090", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP08-091", name: "Blueno", set: "Two Legends", setCode: "OP08", number: "091", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-092", name: "Kalifa", set: "Two Legends", setCode: "OP08", number: "092", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000 },
  { id: "OP08-093", name: "Fukurou", set: "Two Legends", setCode: "OP08", number: "093", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-094", name: "Kumadori", set: "Two Legends", setCode: "OP08", number: "094", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP08-095", name: "Hattori", set: "Two Legends", setCode: "OP08", number: "095", type: "Character", color: "Black", rarity: "C", cost: 1, power: 0 },
  { id: "OP08-096", name: "Spandam", set: "Two Legends", setCode: "OP08", number: "096", type: "Character", color: "Black", rarity: "C", cost: 1, power: 2000 },
  
  // Secret Rares
  { id: "OP08-097", name: "Gol.D.Roger", set: "Two Legends", setCode: "OP08", number: "097", type: "Character", color: "Red", rarity: "SEC", cost: 10, power: 12000 },
  { id: "OP08-098", name: "Shanks", set: "Two Legends", setCode: "OP08", number: "098", type: "Character", color: "Red", rarity: "SEC", cost: 9, power: 10000 },
  { id: "OP08-099", name: "Silvers Rayleigh", set: "Two Legends", setCode: "OP08", number: "099", type: "Character", color: "Red", rarity: "SEC", cost: 5, power: 7000 },
  { id: "OP08-100", name: "Dracule Mihawk", set: "Two Legends", setCode: "OP08", number: "100", type: "Character", color: "Blue", rarity: "SEC", cost: 7, power: 8000 },
  { id: "OP08-101", name: "Crocodile", set: "Two Legends", setCode: "OP08", number: "101", type: "Character", color: "Blue", rarity: "SEC", cost: 7, power: 7000 },
  { id: "OP08-102", name: "Boa Hancock", set: "Two Legends", setCode: "OP08", number: "102", type: "Character", color: "Green", rarity: "SEC", cost: 5, power: 6000 },
  { id: "OP08-103", name: "Gecko Moria", set: "Two Legends", setCode: "OP08", number: "103", type: "Character", color: "Purple", rarity: "SEC", cost: 5, power: 6000 },
  { id: "OP08-104", name: "Perona", set: "Two Legends", setCode: "OP08", number: "104", type: "Character", color: "Purple", rarity: "SEC", cost: 3, power: 3000 }
];
