import type { Card } from './cards';

const OP08_CARDS: Card[] = [
  { id: "OP08-001", name: "Tony Tony.Chopper", set: "Two Legends", setCode: "OP08", number: "001", type: "Leader", color: "Red/Green", rarity: "L", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP08-002", name: "Marco", set: "Two Legends", setCode: "OP08", number: "002", type: "Leader", color: "Red/Blue", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP08-003", name: "Twenty Doctors", set: "Two Legends", setCode: "OP08", number: "003", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000, attribute: "Wisdom" },
  { id: "OP08-004", name: "Kuromarimo", set: "Two Legends", setCode: "OP08", number: "004", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP08-005", name: "Chess", set: "Two Legends", setCode: "OP08", number: "005", type: "Character", color: "Red", rarity: "C", cost: 3, power: 3000, attribute: "Ranged" },
  { id: "OP08-006", name: "Chessmarimo", set: "Two Legends", setCode: "OP08", number: "006", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP08-007", name: "Tony Tony.Chopper", set: "Two Legends", setCode: "OP08", number: "007", type: "Character", color: "Red", rarity: "SuperRare", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP08-008", name: "Dalton", set: "Two Legends", setCode: "OP08", number: "008", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP08-009", name: "Maria Onion Bear", set: "Two Legends", setCode: "OP08", number: "009", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000, attribute: "Wisdom" },
  { id: "OP08-010", name: "Hiking Bear", set: "Two Legends", setCode: "OP08", number: "010", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 3000, attribute: "Wisdom" },
  { id: "OP08-011", name: "Musshuru", set: "Two Legends", setCode: "OP08", number: "011", type: "Character", color: "Red", rarity: "C", cost: 6, power: 8000, attribute: "Special" },
  { id: "OP08-012", name: "Lapins", set: "Two Legends", setCode: "OP08", number: "012", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 3000, attribute: "Strike" },
  { id: "OP08-013", name: "Robson", set: "Two Legends", setCode: "OP08", number: "013", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000, attribute: "Wisdom" },
  { id: "OP08-014", name: "Wapol", set: "Two Legends", setCode: "OP08", number: "014", type: "Character", color: "Red", rarity: "R", cost: 6, power: 6000, attribute: "Strike" },
  { id: "OP08-015", name: "Dr.Kureha", set: "Two Legends", setCode: "OP08", number: "015", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP08-016", name: "Dr.Hiriluk", set: "Two Legends", setCode: "OP08", number: "016", type: "Character", color: "Red", rarity: "R", cost: 3, attribute: "Wisdom" },
  { id: "OP08-017", name: "I'd Never Shoot You!!!!", set: "Two Legends", setCode: "OP08", number: "017", type: "Event", color: "Red", rarity: "C", cost: 2 },
  { id: "OP08-018", name: "Cloven Rose", set: "Two Legends", setCode: "OP08", number: "018", type: "Event", color: "Red", rarity: "R", cost: 2 },
  { id: "OP08-019", name: "Munch-Munch Mutation", set: "Two Legends", setCode: "OP08", number: "019", type: "Event", color: "Red", rarity: "UC", cost: 3 },
  { id: "OP08-020", name: "Drum Kingdom", set: "Two Legends", setCode: "OP08", number: "020", type: "Stage", color: "Red", rarity: "C", cost: 1 },
  { id: "OP08-021", name: "Carrot", set: "Two Legends", setCode: "OP08", number: "021", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP08-022", name: "Inuarashi", set: "Two Legends", setCode: "OP08", number: "022", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP08-023", name: "Carrot", set: "Two Legends", setCode: "OP08", number: "023", type: "Character", color: "Green", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP08-024", name: "Concelot", set: "Two Legends", setCode: "OP08", number: "024", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP08-025", name: "Shishilian", set: "Two Legends", setCode: "OP08", number: "025", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP08-026", name: "Giovanni", set: "Two Legends", setCode: "OP08", number: "026", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP08-027", name: "Tristan", set: "Two Legends", setCode: "OP08", number: "027", type: "Character", color: "Green", rarity: "C", cost: 1, power: 3000, attribute: "Wisdom" },
  { id: "OP08-028", name: "Nekomamushi", set: "Two Legends", setCode: "OP08", number: "028", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP08-029", name: "Pekoms", set: "Two Legends", setCode: "OP08", number: "029", type: "Character", color: "Green", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP08-030", name: "Pedro", set: "Two Legends", setCode: "OP08", number: "030", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP08-031", name: "Miyagi", set: "Two Legends", setCode: "OP08", number: "031", type: "Character", color: "Green", rarity: "C", cost: 3, power: 1000, attribute: "Wisdom" },
  { id: "OP08-032", name: "Milky", set: "Two Legends", setCode: "OP08", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 2, attribute: "Wisdom" },
  { id: "OP08-033", name: "Roddy", set: "Two Legends", setCode: "OP08", number: "033", type: "Character", color: "Green", rarity: "C", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP08-034", name: "Wanda", set: "Two Legends", setCode: "OP08", number: "034", type: "Character", color: "Green", rarity: "R", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP08-035", name: "BB", set: "Two Legends", setCode: "OP08", number: "035", type: "Character", color: "Green", rarity: "C", cost: 2, power: 4000, attribute: "Strike" },
  { id: "OP08-036", name: "Electrical Luna", set: "Two Legends", setCode: "OP08", number: "036", type: "Event", color: "Green", rarity: "R", cost: 3 },
  { id: "OP08-037", name: "Garchu", set: "Two Legends", setCode: "OP08", number: "037", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP08-038", name: "We Would Never Sell a Comrade to an Enemy!!!", set: "Two Legends", setCode: "OP08", number: "038", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "OP08-039", name: "Zou", set: "Two Legends", setCode: "OP08", number: "039", type: "Stage", color: "Green", rarity: "R", cost: 3 },
  { id: "OP08-040", name: "Atmos", set: "Two Legends", setCode: "OP08", number: "040", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP08-041", name: "Aphelandra", set: "Two Legends", setCode: "OP08", number: "041", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP08-042", name: "Edward Weevil", set: "Two Legends", setCode: "OP08", number: "042", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP08-043", name: "Edward.Newgate", set: "Two Legends", setCode: "OP08", number: "043", type: "Character", color: "Blue", rarity: "SuperRare", cost: 10, power: 12000, attribute: "Special" },
  { id: "OP08-044", name: "Kingdew", set: "Two Legends", setCode: "OP08", number: "044", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 4000, attribute: "Strike" },
  { id: "OP08-045", name: "Thatch", set: "Two Legends", setCode: "OP08", number: "045", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP08-046", name: "Shakuyaku", set: "Two Legends", setCode: "OP08", number: "046", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000, attribute: "Wisdom" },
  { id: "OP08-047", name: "Jozu", set: "Two Legends", setCode: "OP08", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP08-048", name: "Sweetpea", set: "Two Legends", setCode: "OP08", number: "048", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP08-049", name: "Speed Jil", set: "Two Legends", setCode: "OP08", number: "049", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP08-050", name: "Namule", set: "Two Legends", setCode: "OP08", number: "050", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 2000, attribute: "Strike" },
  { id: "OP08-051", name: "Buckin", set: "Two Legends", setCode: "OP08", number: "051", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP08-052", name: "Portgas.D.Ace", set: "Two Legends", setCode: "OP08", number: "052", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP08-053", name: "Thank You...for Loving Me!!", set: "Two Legends", setCode: "OP08", number: "053", type: "Event", color: "Blue", rarity: "R", cost: 1 },
  { id: "OP08-054", name: "You Can't Take Our King This Early in the Game.", set: "Two Legends", setCode: "OP08", number: "054", type: "Event", color: "Blue", rarity: "C", cost: 3 },
  { id: "OP08-055", name: "Phoenix Brand", set: "Two Legends", setCode: "OP08", number: "055", type: "Event", color: "Blue", rarity: "UC", cost: 4 },
  { id: "OP08-056", name: "Moby Dick", set: "Two Legends", setCode: "OP08", number: "056", type: "Stage", color: "Blue", rarity: "C", cost: 2 },
  { id: "OP08-057", name: "King", set: "Two Legends", setCode: "OP08", number: "057", type: "Leader", color: "Purple/Black", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP08-058", name: "Charlotte Pudding", set: "Two Legends", setCode: "OP08", number: "058", type: "Leader", color: "Purple/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Wisdom" },
  { id: "OP08-059", name: "Alber", set: "Two Legends", setCode: "OP08", number: "059", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP08-060", name: "King", set: "Two Legends", setCode: "OP08", number: "060", type: "Character", color: "Purple", rarity: "R", cost: 7, power: 8000, attribute: "Special" },
  { id: "OP08-061", name: "Charlotte Oven", set: "Two Legends", setCode: "OP08", number: "061", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP08-062", name: "Charlotte Katakuri", set: "Two Legends", setCode: "OP08", number: "062", type: "Character", color: "Purple", rarity: "UC", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP08-063", name: "Charlotte Katakuri", set: "Two Legends", setCode: "OP08", number: "063", type: "Character", color: "Purple", rarity: "R", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP08-064", name: "Charlotte Cracker", set: "Two Legends", setCode: "OP08", number: "064", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP08-065", name: "Charlotte Smoothie", set: "Two Legends", setCode: "OP08", number: "065", type: "Character", color: "Purple", rarity: "C", cost: 7, power: 9000, attribute: "Special" },
  { id: "OP08-066", name: "Charlotte Brulee", set: "Two Legends", setCode: "OP08", number: "066", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 1000, attribute: "Special" },
  { id: "OP08-067", name: "Charlotte Pudding", set: "Two Legends", setCode: "OP08", number: "067", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 4000, attribute: "Wisdom" },
  { id: "OP08-068", name: "Charlotte Perospero", set: "Two Legends", setCode: "OP08", number: "068", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP08-069", name: "Charlotte Linlin", set: "Two Legends", setCode: "OP08", number: "069", type: "Character", color: "Purple", rarity: "SuperRare", cost: 9, power: 9000, attribute: "Special" },
  { id: "OP08-070", name: "Baron Tamago", set: "Two Legends", setCode: "OP08", number: "070", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP08-071", name: "Count Niwatori", set: "Two Legends", setCode: "OP08", number: "071", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP08-072", name: "Biscuit Warrior", set: "Two Legends", setCode: "OP08", number: "072", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP08-073", name: "Viscount Hiyoko", set: "Two Legends", setCode: "OP08", number: "073", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP08-074", name: "Black Maria", set: "Two Legends", setCode: "OP08", number: "074", type: "Character", color: "Purple", rarity: "SuperRare", cost: 3, power: 2000, attribute: "Special" },
  { id: "OP08-075", name: "Candy Maiden", set: "Two Legends", setCode: "OP08", number: "075", type: "Event", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP08-076", name: "It's to Die For...", set: "Two Legends", setCode: "OP08", number: "076", type: "Event", color: "Purple", rarity: "UC", cost: 3 },
  { id: "OP08-077", name: "Conquest of the Sea", set: "Two Legends", setCode: "OP08", number: "077", type: "Event", color: "Purple", rarity: "R", cost: 6 },
  { id: "OP08-078", name: "Ulti", set: "Two Legends", setCode: "OP08", number: "078", type: "Character", color: "Black", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP08-079", name: "Kaido", set: "Two Legends", setCode: "OP08", number: "079", type: "Character", color: "Black", rarity: "SuperRare", cost: 9, power: 9000, attribute: "Strike" },
  { id: "OP08-080", name: "Queen", set: "Two Legends", setCode: "OP08", number: "080", type: "Character", color: "Black", rarity: "R", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP08-081", name: "Guernica", set: "Two Legends", setCode: "OP08", number: "081", type: "Character", color: "Black", rarity: "C", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP08-082", name: "Sasaki", set: "Two Legends", setCode: "OP08", number: "082", type: "Character", color: "Black", rarity: "R", cost: 1, power: 1000, attribute: "Slash" },
  { id: "OP08-083", name: "Sheepshead", set: "Two Legends", setCode: "OP08", number: "083", type: "Character", color: "Black", rarity: "UC", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP08-084", name: "Jack", set: "Two Legends", setCode: "OP08", number: "084", type: "Character", color: "Black", rarity: "SuperRare", cost: 7, power: 8000, attribute: "Slash" },
  { id: "OP08-085", name: "Jinbe", set: "Two Legends", setCode: "OP08", number: "085", type: "Character", color: "Black", rarity: "UC", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP08-086", name: "Ginrummy", set: "Two Legends", setCode: "OP08", number: "086", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP08-087", name: "Scratchmen Apoo", set: "Two Legends", setCode: "OP08", number: "087", type: "Character", color: "Black", rarity: "UC", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP08-088", name: "Duval", set: "Two Legends", setCode: "OP08", number: "088", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 2000, attribute: "Ranged" },
  { id: "OP08-089", name: "Basil Hawkins", set: "Two Legends", setCode: "OP08", number: "089", type: "Character", color: "Black", rarity: "C", cost: 7, power: 9000, attribute: "Slash" },
  { id: "OP08-090", name: "Hamlet", set: "Two Legends", setCode: "OP08", number: "090", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP08-091", name: "Who's.Who", set: "Two Legends", setCode: "OP08", number: "091", type: "Character", color: "Black", rarity: "R", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP08-092", name: "Page One", set: "Two Legends", setCode: "OP08", number: "092", type: "Character", color: "Black", rarity: "R", cost: 5, power: 5000, attribute: "Strike" },
  { id: "OP08-093", name: "X.Drake", set: "Two Legends", setCode: "OP08", number: "093", type: "Character", color: "Black", rarity: "C", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP08-094", name: "Imperial Flame", set: "Two Legends", setCode: "OP08", number: "094", type: "Event", color: "Black", rarity: "R", cost: 2 },
  { id: "OP08-095", name: "Iron Body Fang Flash", set: "Two Legends", setCode: "OP08", number: "095", type: "Event", color: "Black", rarity: "UC", cost: 2 },
  { id: "OP08-096", name: "People's Dreams Don't Ever End!!", set: "Two Legends", setCode: "OP08", number: "096", type: "Event", color: "Black", rarity: "C", cost: 1 },
  { id: "OP08-097", name: "Heliceratops", set: "Two Legends", setCode: "OP08", number: "097", type: "Event", color: "Black", rarity: "C", cost: 3 },
  { id: "OP08-098", name: "Kalgara", set: "Two Legends", setCode: "OP08", number: "098", type: "Leader", color: "Yellow", rarity: "L", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP08-099", name: "Kalgara", set: "Two Legends", setCode: "OP08", number: "099", type: "Character", color: "Yellow", rarity: "C", cost: 6, power: 8000, attribute: "Slash" },
  { id: "OP08-100", name: "South Bird", set: "Two Legends", setCode: "OP08", number: "100", type: "Character", color: "Yellow", rarity: "UC", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP08-101", name: "Charlotte Angel", set: "Two Legends", setCode: "OP08", number: "101", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP08-102", name: "Charlotte Opera", set: "Two Legends", setCode: "OP08", number: "102", type: "Character", color: "Yellow", rarity: "UC", cost: 6, power: 6000, attribute: "Special" },
  { id: "OP08-103", name: "Charlotte Custard", set: "Two Legends", setCode: "OP08", number: "103", type: "Character", color: "Yellow", rarity: "UC", cost: 2, power: 3000, attribute: "Slash" },
  { id: "OP08-104", name: "Charlotte Poire", set: "Two Legends", setCode: "OP08", number: "104", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 2000, attribute: "Wisdom" },
  { id: "OP08-105", name: "Jewelry Bonney", set: "Two Legends", setCode: "OP08", number: "105", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP08-106", name: "Nami", set: "Two Legends", setCode: "OP08", number: "106", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP08-107", name: "Nitro", set: "Two Legends", setCode: "OP08", number: "107", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 2000, attribute: "Special" },
  { id: "OP08-108", name: "Mont Blanc Cricket", set: "Two Legends", setCode: "OP08", number: "108", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP08-109", name: "Mont Blanc Noland", set: "Two Legends", setCode: "OP08", number: "109", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP08-110", name: "Wyper", set: "Two Legends", setCode: "OP08", number: "110", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP08-111", name: "S-Shark", set: "Two Legends", setCode: "OP08", number: "111", type: "Character", color: "Yellow", rarity: "UC", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP08-112", name: "S-Snake", set: "Two Legends", setCode: "OP08", number: "112", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP08-113", name: "S-Bear", set: "Two Legends", setCode: "OP08", number: "113", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP08-114", name: "S-Hawk", set: "Two Legends", setCode: "OP08", number: "114", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP08-115", name: "The Earth Will Not Lose!", set: "Two Legends", setCode: "OP08", number: "115", type: "Event", color: "Yellow", rarity: "R", cost: 1 },
  { id: "OP08-116", name: "Burn Bazooka", set: "Two Legends", setCode: "OP08", number: "116", type: "Event", color: "Yellow", rarity: "C", cost: 2 },
  { id: "OP08-117", name: "Burn Blade", set: "Two Legends", setCode: "OP08", number: "117", type: "Event", color: "Yellow", rarity: "UC", cost: 5 },
  { id: "OP08-118", name: "Silvers Rayleigh", set: "Two Legends", setCode: "OP08", number: "118", type: "Character", color: "Red", rarity: "SecretRare", cost: 8, power: 8000, attribute: "Slash" },
  { id: "OP08-119", name: "Kaido &amp; Linlin", set: "Two Legends", setCode: "OP08", number: "119", type: "Character", color: "Purple", rarity: "SecretRare", cost: 10, power: 12000, attribute: "Strike" },
];

export default OP08_CARDS;
