import { Card } from "./cards";

// Emperors in the New World (OP09) - Key cards
export const OP09_CARDS: Card[] = [
  // Leaders
  { id: "OP09-001", name: "Monkey D. Luffy", set: "Emperors in the New World", setCode: "OP09", number: "001", type: "Leader", color: "Red/Green", rarity: "L", cost: 0, power: 5000 },
  { id: "OP09-002", name: "Shanks", set: "Emperors in the New World", setCode: "OP09", number: "002", type: "Leader", color: "Red/Blue", rarity: "L", cost: 0, power: 5000 },
  { id: "OP09-003", name: "Marshall D. Teach", set: "Emperors in the New World", setCode: "OP09", number: "003", type: "Leader", color: "Blue/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP09-004", name: "Trafalgar Law", set: "Emperors in the New World", setCode: "OP09", number: "004", type: "Leader", color: "Green/Red", rarity: "L", cost: 0, power: 5000 },
  { id: "OP09-005", name: "Eustass Kid", set: "Emperors in the New World", setCode: "OP09", number: "005", type: "Leader", color: "Green/Purple", rarity: "L", cost: 0, power: 5000 },
  { id: "OP09-006", name: "Buggy", set: "Emperors in the New World", setCode: "OP09", number: "006", type: "Leader", color: "Blue/Green", rarity: "L", cost: 0, power: 5000 },
  { id: "OP09-007", name: "Kaido", set: "Emperors in the New World", setCode: "OP09", number: "007", type: "Leader", color: "Purple/Black", rarity: "L", cost: 0, power: 5000 },
  { id: "OP09-008", name: "Charlotte Linlin", set: "Emperors in the New World", setCode: "OP09", number: "008", type: "Leader", color: "Purple/Blue", rarity: "L", cost: 0, power: 5000 },
  
  // Red Cards (Straw Hats)
  { id: "OP09-009", name: "Monkey D. Luffy", set: "Emperors in the New World", setCode: "OP09", number: "009", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP09-010", name: "Roronoa Zoro", set: "Emperors in the New World", setCode: "OP09", number: "010", type: "Character", color: "Red", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP09-011", name: "Sanji", set: "Emperors in the New World", setCode: "OP09", number: "011", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP09-012", name: "Jinbe", set: "Emperors in the New World", setCode: "OP09", number: "012", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000 },
  { id: "OP09-013", name: "Yamato", set: "Emperors in the New World", setCode: "OP09", number: "013", type: "Character", color: "Red", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP09-014", name: "Carrot", set: "Emperors in the New World", setCode: "OP09", number: "014", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP09-015", name: "Momonosuke", set: "Emperors in the New World", setCode: "OP09", number: "015", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000 },
  { id: "OP09-016", name: "Kin'emon", set: "Emperors in the New World", setCode: "OP09", number: "016", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000 },
  { id: "OP09-017", name: "Denjiro", set: "Emperors in the New World", setCode: "OP09", number: "017", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-018", name: "Kawamatsu", set: "Emperors in the New World", setCode: "OP09", number: "018", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-019", name: "Ashura Doji", set: "Emperors in the New World", setCode: "OP09", number: "019", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-020", name: "Inuarashi", set: "Emperors in the New World", setCode: "OP09", number: "020", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000 },
  { id: "OP09-021", name: "Nekomamushi", set: "Emperors in the New World", setCode: "OP09", number: "021", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000 },
  { id: "OP09-022", name: "Raizo", set: "Emperors in the New World", setCode: "OP09", number: "022", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-023", name: "Shinobu", set: "Emperors in the New World", setCode: "OP09", number: "023", type: "Character", color: "Red", rarity: "R", cost: 2, power: 3000 },
  { id: "OP09-024", name: "Kikunojo", set: "Emperors in the New World", setCode: "OP09", number: "024", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-025", name: "Onimaru", set: "Emperors in the New World", setCode: "OP09", number: "025", type: "Character", color: "Red", rarity: "C", cost: 1, power: 2000 },
  { id: "OP09-026", name: "Shanks", set: "Emperors in the New World", setCode: "OP09", number: "026", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP09-027", name: "Benn Beckman", set: "Emperors in the New World", setCode: "OP09", number: "027", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000 },
  { id: "OP09-028", name: "Yasopp", set: "Emperors in the New World", setCode: "OP09", number: "028", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000 },
  { id: "OP09-029", name: "Lucky Roux", set: "Emperors in the New World", setCode: "OP09", number: "029", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000 },
  
  // Blue Cards (Blackbeard Pirates)
  { id: "OP09-030", name: "Marshall D. Teach", set: "Emperors in the New World", setCode: "OP09", number: "030", type: "Character", color: "Blue", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP09-031", name: "Jesus Burgess", set: "Emperors in the New World", setCode: "OP09", number: "031", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP09-032", name: "Shiryu", set: "Emperors in the New World", setCode: "OP09", number: "032", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000 },
  { id: "OP09-033", name: "Van Augur", set: "Emperors in the New World", setCode: "OP09", number: "033", type: "Character", color: "Blue", rarity: "R", cost: 2, power: 3000 },
  { id: "OP09-034", name: "Laffitte", set: "Emperors in the New World", setCode: "OP09", number: "034", type: "Character", color: "Blue", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP09-035", name: "Doc Q", set: "Emperors in the New World", setCode: "OP09", number: "035", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 3000 },
  { id: "OP09-036", name: "Stronger", set: "Emperors in the New World", setCode: "OP09", number: "036", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 1000 },
  { id: "OP09-037", name: "Avalo Pizarro", set: "Emperors in the New World", setCode: "OP09", number: "037", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP09-038", name: "Catarina Devon", set: "Emperors in the New World", setCode: "OP09", number: "038", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP09-039", name: "Sanjuan Wolf", set: "Emperors in the New World", setCode: "OP09", number: "039", type: "Character", color: "Blue", rarity: "C", cost: 6, power: 7000 },
  { id: "OP09-040", name: "Vasco Shot", set: "Emperors in the New World", setCode: "OP09", number: "040", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP09-041", name: "Kuzan", set: "Emperors in the New World", setCode: "OP09", number: "041", type: "Character", color: "Blue", rarity: "SR", cost: 7, power: 8000 },
  { id: "OP09-042", name: "Gekko Moriah", set: "Emperors in the New World", setCode: "OP09", number: "042", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP09-043", name: "Absalom", set: "Emperors in the New World", setCode: "OP09", number: "043", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-044", name: "Perona", set: "Emperors in the New World", setCode: "OP09", number: "044", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 3000 },
  { id: "OP09-045", name: "Hogback", set: "Emperors in the New World", setCode: "OP09", number: "045", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-046", name: "Sabo", set: "Emperors in the New World", setCode: "OP09", number: "046", type: "Character", color: "Blue", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP09-047", name: "Emporio Ivankov", set: "Emperors in the New World", setCode: "OP09", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP09-048", name: "Inazuma", set: "Emperors in the New World", setCode: "OP09", number: "048", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-049", name: "Koala", set: "Emperors in the New World", setCode: "OP09", number: "049", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 4000 },
  { id: "OP09-050", name: "Hack", set: "Emperors in the New World", setCode: "OP09", number: "050", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP09-051", name: "Bartholomew Kuma", set: "Emperors in the New World", setCode: "OP09", number: "051", type: "Character", color: "Blue", rarity: "R", cost: 5, power: 6000 },
  { id: "OP09-052", name: "Jewelry Bonney", set: "Emperors in the New World", setCode: "OP09", number: "052", type: "Character", color: "Blue", rarity: "R", cost: 2, power: 2000 },
  
  // Green Cards (Kid Pirates)
  { id: "OP09-053", name: "Eustass Kid", set: "Emperors in the New World", setCode: "OP09", number: "053", type: "Character", color: "Green", rarity: "SR", cost: 7, power: 8000 },
  { id: "OP09-054", name: "Killer", set: "Emperors in the New World", setCode: "OP09", number: "054", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000 },
  { id: "OP09-055", name: "Heat", set: "Emperors in the New World", setCode: "OP09", number: "055", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-056", name: "Wire", set: "Emperors in the New World", setCode: "OP09", number: "056", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-057", name: "Trafalgar Law", set: "Emperors in the New World", setCode: "OP09", number: "057", type: "Character", color: "Green", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP09-058", name: "Bepo", set: "Emperors in the New World", setCode: "OP09", number: "058", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-059", name: "Penguin", set: "Emperors in the New World", setCode: "OP09", number: "059", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-060", name: "Shachi", set: "Emperors in the New World", setCode: "OP09", number: "060", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-061", name: "Jean Bart", set: "Emperors in the New World", setCode: "OP09", number: "061", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000 },
  { id: "OP09-062", name: "Clione", set: "Emperors in the New World", setCode: "OP09", number: "062", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-063", name: "Uni", set: "Emperors in the New World", setCode: "OP09", number: "063", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-064", name: "Hakugan", set: "Emperors in the New World", setCode: "OP09", number: "064", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-065", name: "Ikkaku", set: "Emperors in the New World", setCode: "OP09", number: "065", type: "Character", color: "Green", rarity: "C", cost: 1, power: 1000 },
  { id: "OP09-066", name: "Buggy", set: "Emperors in the New World", setCode: "OP09", number: "066", type: "Character", color: "Green", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP09-067", name: "Alvida", set: "Emperors in the New World", setCode: "OP09", number: "067", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-068", name: "Cabaji", set: "Emperors in the New World", setCode: "OP09", number: "068", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "OP09-069", name: "Mohji", set: "Emperors in the New World", setCode: "OP09", number: "069", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-070", name: "Richie", set: "Emperors in the New World", setCode: "OP09", number: "070", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "OP09-071", name: "Galdino", set: "Emperors in the New World", setCode: "OP09", number: "071", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  
  // Purple Cards (Beast Pirates)
  { id: "OP09-072", name: "Kaido", set: "Emperors in the New World", setCode: "OP09", number: "072", type: "Character", color: "Purple", rarity: "SR", cost: 10, power: 12000 },
  { id: "OP09-073", name: "King", set: "Emperors in the New World", setCode: "OP09", number: "073", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 6000 },
  { id: "OP09-074", name: "Queen", set: "Emperors in the New World", setCode: "OP09", number: "074", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000 },
  { id: "OP09-075", name: "Jack", set: "Emperors in the New World", setCode: "OP09", number: "075", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000 },
  { id: "OP09-076", name: "Who's-Who", set: "Emperors in the New World", setCode: "OP09", number: "076", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-077", name: "Sasaki", set: "Emperors in the New World", setCode: "OP09", number: "077", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-078", name: "Black Maria", set: "Emperors in the New World", setCode: "OP09", number: "078", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-079", name: "Ulti", set: "Emperors in the New World", setCode: "OP09", number: "079", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-080", name: "Page One", set: "Emperors in the New World", setCode: "OP09", number: "080", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP09-081", name: "Babanuki", set: "Emperors in the New World", setCode: "OP09", number: "081", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000 },
  { id: "OP09-082", name: "Daifugo", set: "Emperors in the New World", setCode: "OP09", number: "082", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP09-083", name: "Solitaire", set: "Emperors in the New World", setCode: "OP09", number: "083", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP09-084", name: "Poker", set: "Emperors in the New World", setCode: "OP09", number: "084", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-085", name: "Mizerka", set: "Emperors in the New World", setCode: "OP09", number: "085", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-086", name: "Briscola", set: "Emperors in the New World", setCode: "OP09", number: "086", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-087", name: "Hamlet", set: "Emperors in the New World", setCode: "OP09", number: "087", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP09-088", name: "Hatcha", set: "Emperors in the New World", setCode: "OP09", number: "088", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000 },
  
  // Black Cards (Marines)
  { id: "OP09-089", name: "Sakazuki", set: "Emperors in the New World", setCode: "OP09", number: "089", type: "Character", color: "Black", rarity: "SR", cost: 8, power: 9000 },
  { id: "OP09-090", name: "Borsalino", set: "Emperors in the New World", setCode: "OP09", number: "090", type: "Character", color: "Black", rarity: "R", cost: 6, power: 7000 },
  { id: "OP09-091", name: "Issho", set: "Emperors in the New World", setCode: "OP09", number: "091", type: "Character", color: "Black", rarity: "R", cost: 7, power: 8000 },
  { id: "OP09-092", name: "Ryokugyu", set: "Emperors in the New World", setCode: "OP09", number: "092", type: "Character", color: "Black", rarity: "R", cost: 6, power: 7000 },
  { id: "OP09-093", name: "Sengoku", set: "Emperors in the New World", setCode: "OP09", number: "093", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000 },
  { id: "OP09-094", name: "Garp", set: "Emperors in the New World", setCode: "OP09", number: "094", type: "Character", color: "Black", rarity: "R", cost: 6, power: 7000 },
  { id: "OP09-095", name: "Kuzan", set: "Emperors in the New World", setCode: "OP09", number: "095", type: "Character", color: "Black", rarity: "SR", cost: 7, power: 8000 },
  
  // Secret Rares
  { id: "OP09-096", name: "Monkey D. Luffy", set: "Emperors in the New World", setCode: "OP09", number: "096", type: "Character", color: "Red", rarity: "SEC", cost: 9, power: 10000 },
  { id: "OP09-097", name: "Shanks", set: "Emperors in the New World", setCode: "OP09", number: "097", type: "Character", color: "Red", rarity: "SEC", cost: 9, power: 10000 },
  { id: "OP09-098", name: "Marshall D. Teach", set: "Emperors in the New World", setCode: "OP09", number: "098", type: "Character", color: "Blue", rarity: "SEC", cost: 9, power: 10000 },
  { id: "OP09-099", name: "Sabo", set: "Emperors in the New World", setCode: "OP09", number: "099", type: "Character", color: "Blue", rarity: "SEC", cost: 5, power: 6000 },
  { id: "OP09-100", name: "Trafalgar Law", set: "Emperors in the New World", setCode: "OP09", number: "100", type: "Character", color: "Green", rarity: "SEC", cost: 6, power: 7000 },
  { id: "OP09-101", name: "Eustass Kid", set: "Emperors in the New World", setCode: "OP09", number: "101", type: "Character", color: "Green", rarity: "SEC", cost: 7, power: 8000 },
  { id: "OP09-102", name: "Buggy", set: "Emperors in the New World", setCode: "OP09", number: "102", type: "Character", color: "Green", rarity: "SEC", cost: 4, power: 5000 },
  { id: "OP09-103", name: "Kaido", set: "Emperors in the New World", setCode: "OP09", number: "103", type: "Character", color: "Purple", rarity: "SEC", cost: 10, power: 12000 },
  { id: "OP09-104", name: "Charlotte Linlin", set: "Emperors in the New World", setCode: "OP09", number: "104", type: "Character", color: "Purple", rarity: "SEC", cost: 10, power: 12000 }
];
