import type { Card } from './cards';

const OP09_CARDS: Card[] = [
  { id: "OP09-001", name: "Shanks", set: "Emperors in the New World", setCode: "OP09", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP09-002", name: "Uta", set: "Emperors in the New World", setCode: "OP09", number: "002", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000, attribute: "Special" },
  { id: "OP09-003", name: "Shachi &amp; Penguin", set: "Emperors in the New World", setCode: "OP09", number: "003", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP09-004", name: "Shanks", set: "Emperors in the New World", setCode: "OP09", number: "004", type: "Character", color: "Red", rarity: "SuperRare", cost: 10, power: 12000, attribute: "Slash" },
  { id: "OP09-005", name: "Silvers Rayleigh", set: "Emperors in the New World", setCode: "OP09", number: "005", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP09-006", name: "Howling Gab", set: "Emperors in the New World", setCode: "OP09", number: "006", type: "Character", color: "Red", rarity: "C", cost: 5, power: 7000, attribute: "Special" },
  { id: "OP09-007", name: "Heat", set: "Emperors in the New World", setCode: "OP09", number: "007", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP09-008", name: "Building Snake", set: "Emperors in the New World", setCode: "OP09", number: "008", type: "Character", color: "Red", rarity: "UC", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP09-009", name: "Benn.Beckman", set: "Emperors in the New World", setCode: "OP09", number: "009", type: "Character", color: "Red", rarity: "SuperRare", cost: 7, power: 7000, attribute: "Ranged" },
  { id: "OP09-010", name: "Bonk Punch", set: "Emperors in the New World", setCode: "OP09", number: "010", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP09-011", name: "Hongo", set: "Emperors in the New World", setCode: "OP09", number: "011", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 3000, attribute: "Strike" },
  { id: "OP09-012", name: "Monster", set: "Emperors in the New World", setCode: "OP09", number: "012", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP09-013", name: "Yasopp", set: "Emperors in the New World", setCode: "OP09", number: "013", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000, attribute: "Ranged" },
  { id: "OP09-014", name: "Limejuice", set: "Emperors in the New World", setCode: "OP09", number: "014", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 3000, attribute: "Special" },
  { id: "OP09-015", name: "Lucky.Roux", set: "Emperors in the New World", setCode: "OP09", number: "015", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP09-016", name: "Rockstar", set: "Emperors in the New World", setCode: "OP09", number: "016", type: "Character", color: "Red", rarity: "C", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP09-017", name: "Wire", set: "Emperors in the New World", setCode: "OP09", number: "017", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 4000, attribute: "Slash" },
  { id: "OP09-018", name: "Get Out of Here!", set: "Emperors in the New World", setCode: "OP09", number: "018", type: "Event", color: "Red", rarity: "UC", cost: 3 },
  { id: "OP09-019", name: "Nobody Hurts a Friend of Mine!!!!", set: "Emperors in the New World", setCode: "OP09", number: "019", type: "Event", color: "Red", rarity: "C", cost: 2 },
  { id: "OP09-020", name: "Come On!! We'll Fight You!!", set: "Emperors in the New World", setCode: "OP09", number: "020", type: "Event", color: "Red", rarity: "R", cost: 1 },
  { id: "OP09-021", name: "Red Force", set: "Emperors in the New World", setCode: "OP09", number: "021", type: "Stage", color: "Red", rarity: "C", cost: 2 },
  { id: "OP09-022", name: "Lim", set: "Emperors in the New World", setCode: "OP09", number: "022", type: "Leader", color: "Green/Purple", rarity: "L", cost: 4, power: 5000, attribute: "Wisdom" },
  { id: "OP09-023", name: "Adio", set: "Emperors in the New World", setCode: "OP09", number: "023", type: "Character", color: "Green", rarity: "SuperRare", cost: 9, power: 9000, attribute: "Special" },
  { id: "OP09-024", name: "Usopp", set: "Emperors in the New World", setCode: "OP09", number: "024", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP09-025", name: "Crocodile", set: "Emperors in the New World", setCode: "OP09", number: "025", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP09-026", name: "Sakazuki", set: "Emperors in the New World", setCode: "OP09", number: "026", type: "Character", color: "Green", rarity: "R", cost: 6, power: 7000, attribute: "Special" },
  { id: "OP09-027", name: "Sabo", set: "Emperors in the New World", setCode: "OP09", number: "027", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP09-028", name: "Sanji", set: "Emperors in the New World", setCode: "OP09", number: "028", type: "Character", color: "Green", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP09-029", name: "Tony Tony.Chopper", set: "Emperors in the New World", setCode: "OP09", number: "029", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP09-030", name: "Trafalgar Law", set: "Emperors in the New World", setCode: "OP09", number: "030", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP09-031", name: "Donquixote Doflamingo", set: "Emperors in the New World", setCode: "OP09", number: "031", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP09-032", name: "Donquixote Rosinante", set: "Emperors in the New World", setCode: "OP09", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP09-033", name: "Nico Robin", set: "Emperors in the New World", setCode: "OP09", number: "033", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP09-034", name: "Perona", set: "Emperors in the New World", setCode: "OP09", number: "034", type: "Character", color: "Green", rarity: "R", cost: 1, power: 2000, attribute: "Special" },
  { id: "OP09-035", name: "Portgas.D.Ace", set: "Emperors in the New World", setCode: "OP09", number: "035", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP09-036", name: "Monkey.D.Luffy", set: "Emperors in the New World", setCode: "OP09", number: "036", type: "Character", color: "Green", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP09-037", name: "Lim", set: "Emperors in the New World", setCode: "OP09", number: "037", type: "Character", color: "Green", rarity: "SuperRare", cost: 3, power: 5000, attribute: "Wisdom" },
  { id: "OP09-038", name: "Rob Lucci", set: "Emperors in the New World", setCode: "OP09", number: "038", type: "Character", color: "Green", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP09-039", name: "Gum-Gum Cuatro Jet Cross Shock Bazooka", set: "Emperors in the New World", setCode: "OP09", number: "039", type: "Event", color: "Green", rarity: "R", cost: 1 },
  { id: "OP09-040", name: "Thunder Lance Flip Caliber Phoenix Shot", set: "Emperors in the New World", setCode: "OP09", number: "040", type: "Event", color: "Green", rarity: "UC", cost: 3 },
  { id: "OP09-041", name: "Soul Franky Swing Arm Boxing Solid", set: "Emperors in the New World", setCode: "OP09", number: "041", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "OP09-042", name: "Buggy", set: "Emperors in the New World", setCode: "OP09", number: "042", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP09-043", name: "Alvida", set: "Emperors in the New World", setCode: "OP09", number: "043", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP09-044", name: "Izo", set: "Emperors in the New World", setCode: "OP09", number: "044", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 4000, attribute: "Ranged" },
  { id: "OP09-045", name: "Cabaji", set: "Emperors in the New World", setCode: "OP09", number: "045", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP09-046", name: "Crocodile", set: "Emperors in the New World", setCode: "OP09", number: "046", type: "Character", color: "Blue", rarity: "SuperRare", cost: 7, power: 7000, attribute: "Special" },
  { id: "OP09-047", name: "Kouzuki Oden", set: "Emperors in the New World", setCode: "OP09", number: "047", type: "Character", color: "Blue", rarity: "C", cost: 9, power: 10000, attribute: "Slash" },
  { id: "OP09-048", name: "Dracule Mihawk", set: "Emperors in the New World", setCode: "OP09", number: "048", type: "Character", color: "Blue", rarity: "SuperRare", cost: 6, power: 7000, attribute: "Slash" },
  { id: "OP09-049", name: "Jozu", set: "Emperors in the New World", setCode: "OP09", number: "049", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP09-050", name: "Nami", set: "Emperors in the New World", setCode: "OP09", number: "050", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 1000, attribute: "Wisdom" },
  { id: "OP09-051", name: "Buggy", set: "Emperors in the New World", setCode: "OP09", number: "051", type: "Character", color: "Blue", rarity: "R", cost: 10, power: 12000, attribute: "Slash" },
  { id: "OP09-052", name: "Marco", set: "Emperors in the New World", setCode: "OP09", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP09-053", name: "Mohji", set: "Emperors in the New World", setCode: "OP09", number: "053", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 5000, attribute: "Wisdom" },
  { id: "OP09-054", name: "Richie", set: "Emperors in the New World", setCode: "OP09", number: "054", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP09-055", name: "Mr.1(Daz.Bonez)", set: "Emperors in the New World", setCode: "OP09", number: "055", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 7000, attribute: "Slash" },
  { id: "OP09-056", name: "Mr.3(Galdino)", set: "Emperors in the New World", setCode: "OP09", number: "056", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000, attribute: "Special" },
  { id: "OP09-057", name: "Cross Guild", set: "Emperors in the New World", setCode: "OP09", number: "057", type: "Event", color: "Blue", rarity: "R", cost: 1 },
  { id: "OP09-058", name: "Special Muggy Ball", set: "Emperors in the New World", setCode: "OP09", number: "058", type: "Event", color: "Blue", rarity: "C", cost: 2 },
  { id: "OP09-059", name: "Murder at the Steam Bath", set: "Emperors in the New World", setCode: "OP09", number: "059", type: "Event", color: "Blue", rarity: "UC", cost: 2 },
  { id: "OP09-060", name: "Emptee Bluffs Island", set: "Emperors in the New World", setCode: "OP09", number: "060", type: "Stage", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP09-061", name: "Monkey.D.Luffy", set: "Emperors in the New World", setCode: "OP09", number: "061", type: "Leader", color: "Purple/Black", rarity: "L", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP09-062", name: "Nico Robin", set: "Emperors in the New World", setCode: "OP09", number: "062", type: "Leader", color: "Purple/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP09-063", name: "Usopp", set: "Emperors in the New World", setCode: "OP09", number: "063", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 6000, attribute: "Ranged" },
  { id: "OP09-064", name: "Killer", set: "Emperors in the New World", setCode: "OP09", number: "064", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 5000, attribute: "Slash" },
  { id: "OP09-065", name: "Sanji", set: "Emperors in the New World", setCode: "OP09", number: "065", type: "Character", color: "Purple", rarity: "SuperRare", cost: 7, power: 7000, attribute: "Strike" },
  { id: "OP09-066", name: "Jean Bart", set: "Emperors in the New World", setCode: "OP09", number: "066", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP09-067", name: "Jinbe", set: "Emperors in the New World", setCode: "OP09", number: "067", type: "Character", color: "Purple", rarity: "C", cost: 7, power: 9000, attribute: "Strike" },
  { id: "OP09-068", name: "Tony Tony.Chopper", set: "Emperors in the New World", setCode: "OP09", number: "068", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP09-069", name: "Trafalgar Law", set: "Emperors in the New World", setCode: "OP09", number: "069", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP09-070", name: "Nami", set: "Emperors in the New World", setCode: "OP09", number: "070", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 2000, attribute: "Special" },
  { id: "OP09-071", name: "Nico Robin", set: "Emperors in the New World", setCode: "OP09", number: "071", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP09-072", name: "Franky", set: "Emperors in the New World", setCode: "OP09", number: "072", type: "Character", color: "Purple", rarity: "SuperRare", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP09-073", name: "Brook", set: "Emperors in the New World", setCode: "OP09", number: "073", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 7000, attribute: "Slash" },
  { id: "OP09-074", name: "Bepo", set: "Emperors in the New World", setCode: "OP09", number: "074", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP09-075", name: "Eustass\"Captain\"Kid", set: "Emperors in the New World", setCode: "OP09", number: "075", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP09-076", name: "Roronoa Zoro", set: "Emperors in the New World", setCode: "OP09", number: "076", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP09-077", name: "Gum-Gum Lightning", set: "Emperors in the New World", setCode: "OP09", number: "077", type: "Event", color: "Purple", rarity: "UC", cost: 2 },
  { id: "OP09-078", name: "Gum-Gum Giant", set: "Emperors in the New World", setCode: "OP09", number: "078", type: "Event", color: "Purple", rarity: "R", cost: 1 },
  { id: "OP09-079", name: "Gum-Gum Jump Rope", set: "Emperors in the New World", setCode: "OP09", number: "079", type: "Event", color: "Purple", rarity: "C", cost: 2 },
  { id: "OP09-080", name: "Thousand Sunny", set: "Emperors in the New World", setCode: "OP09", number: "080", type: "Stage", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP09-081", name: "Marshall.D.Teach", set: "Emperors in the New World", setCode: "OP09", number: "081", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP09-082", name: "Avalo Pizarro", set: "Emperors in the New World", setCode: "OP09", number: "082", type: "Character", color: "Black", rarity: "C", cost: 4, power: 6000, attribute: "Special" },
  { id: "OP09-083", name: "Van Augur", set: "Emperors in the New World", setCode: "OP09", number: "083", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000, attribute: "Ranged" },
  { id: "OP09-084", name: "Catarina Devon", set: "Emperors in the New World", setCode: "OP09", number: "084", type: "Character", color: "Black", rarity: "UC", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP09-085", name: "Gecko Moria", set: "Emperors in the New World", setCode: "OP09", number: "085", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP09-086", name: "Jesus Burgess", set: "Emperors in the New World", setCode: "OP09", number: "086", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP09-087", name: "Charlotte Pudding", set: "Emperors in the New World", setCode: "OP09", number: "087", type: "Character", color: "Black", rarity: "C", cost: 2, attribute: "Wisdom" },
  { id: "OP09-088", name: "Shiryu", set: "Emperors in the New World", setCode: "OP09", number: "088", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP09-089", name: "Stronger", set: "Emperors in the New World", setCode: "OP09", number: "089", type: "Character", color: "Black", rarity: "UC", cost: 1, attribute: "Wisdom" },
  { id: "OP09-090", name: "Doc Q", set: "Emperors in the New World", setCode: "OP09", number: "090", type: "Character", color: "Black", rarity: "R", cost: 2, attribute: "Special" },
  { id: "OP09-091", name: "Vasco Shot", set: "Emperors in the New World", setCode: "OP09", number: "091", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000, attribute: "Special" },
  { id: "OP09-092", name: "Marshall.D.Teach", set: "Emperors in the New World", setCode: "OP09", number: "092", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP09-093", name: "Marshall.D.Teach", set: "Emperors in the New World", setCode: "OP09", number: "093", type: "Character", color: "Black", rarity: "SuperRare", cost: 10, power: 12000, attribute: "Special" },
  { id: "OP09-094", name: "Peachbeard", set: "Emperors in the New World", setCode: "OP09", number: "094", type: "Character", color: "Black", rarity: "C", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP09-095", name: "Laffitte", set: "Emperors in the New World", setCode: "OP09", number: "095", type: "Character", color: "Black", rarity: "R", cost: 1, power: 1000, attribute: "Strike" },
  { id: "OP09-096", name: "My Era...Begins!!", set: "Emperors in the New World", setCode: "OP09", number: "096", type: "Event", color: "Black", rarity: "R", cost: 1 },
  { id: "OP09-097", name: "Black Vortex", set: "Emperors in the New World", setCode: "OP09", number: "097", type: "Event", color: "Black", rarity: "C", cost: 2 },
  { id: "OP09-098", name: "Black Hole", set: "Emperors in the New World", setCode: "OP09", number: "098", type: "Event", color: "Black", rarity: "UC", cost: 4 },
  { id: "OP09-099", name: "Fullalead", set: "Emperors in the New World", setCode: "OP09", number: "099", type: "Stage", color: "Black", rarity: "C", cost: 1 },
  { id: "OP09-100", name: "Karasu", set: "Emperors in the New World", setCode: "OP09", number: "100", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP09-101", name: "Kuzan", set: "Emperors in the New World", setCode: "OP09", number: "101", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP09-102", name: "Professor Clover", set: "Emperors in the New World", setCode: "OP09", number: "102", type: "Character", color: "Yellow", rarity: "R", cost: 1, attribute: "Wisdom" },
  { id: "OP09-103", name: "Koala", set: "Emperors in the New World", setCode: "OP09", number: "103", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 6, power: 6000, attribute: "Strike" },
  { id: "OP09-104", name: "Sabo", set: "Emperors in the New World", setCode: "OP09", number: "104", type: "Character", color: "Yellow", rarity: "R", cost: 7, power: 7000, attribute: "Special" },
  { id: "OP09-105", name: "Sanji", set: "Emperors in the New World", setCode: "OP09", number: "105", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP09-106", name: "Nico Olvia", set: "Emperors in the New World", setCode: "OP09", number: "106", type: "Character", color: "Yellow", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP09-107", name: "Nico Robin", set: "Emperors in the New World", setCode: "OP09", number: "107", type: "Character", color: "Yellow", rarity: "R", cost: 6, power: 6000, attribute: "Strike" },
  { id: "OP09-108", name: "Bartholomew Kuma", set: "Emperors in the New World", setCode: "OP09", number: "108", type: "Character", color: "Yellow", rarity: "UC", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP09-109", name: "Jaguar.D.Saul", set: "Emperors in the New World", setCode: "OP09", number: "109", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP09-110", name: "Pierre", set: "Emperors in the New World", setCode: "OP09", number: "110", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP09-111", name: "Brook", set: "Emperors in the New World", setCode: "OP09", number: "111", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP09-112", name: "Belo Betty", set: "Emperors in the New World", setCode: "OP09", number: "112", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP09-113", name: "Morley", set: "Emperors in the New World", setCode: "OP09", number: "113", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 6000, attribute: "Special" },
  { id: "OP09-114", name: "Lindbergh", set: "Emperors in the New World", setCode: "OP09", number: "114", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP09-115", name: "Ice Block Partisan", set: "Emperors in the New World", setCode: "OP09", number: "115", type: "Event", color: "Yellow", rarity: "UC", cost: 1 },
  { id: "OP09-116", name: "Never Underestimate the Power of Miracles!!", set: "Emperors in the New World", setCode: "OP09", number: "116", type: "Event", color: "Yellow", rarity: "C", cost: 1 },
  { id: "OP09-117", name: "Dereshi!", set: "Emperors in the New World", setCode: "OP09", number: "117", type: "Event", color: "Yellow", rarity: "R", cost: 3 },
  { id: "OP09-118", name: "Gol.D.Roger", set: "Emperors in the New World", setCode: "OP09", number: "118", type: "Character", color: "Red", rarity: "SecretRare", cost: 10, power: 13000, attribute: "Slash" },
  { id: "OP09-119", name: "Monkey.D.Luffy", set: "Emperors in the New World", setCode: "OP09", number: "119", type: "Character", color: "Purple", rarity: "SecretRare", cost: 9, power: 10000, attribute: "Strike" },
];

export default OP09_CARDS;
