import type { Card } from './cards';

const OP10_CARDS: Card[] = [
  { id: "OP10-001", name: "Smoker", set: "Royal Blood", setCode: "OP10", number: "001", type: "Leader", color: "Red/Green", rarity: "L", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP10-002", name: "Caesar Clown", set: "Royal Blood", setCode: "OP10", number: "002", type: "Leader", color: "Red/Blue", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP10-003", name: "Sugar", set: "Royal Blood", setCode: "OP10", number: "003", type: "Leader", color: "Red/Purple", rarity: "L", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP10-004", name: "Vergo", set: "Royal Blood", setCode: "OP10", number: "004", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP10-005", name: "Sanji", set: "Royal Blood", setCode: "OP10", number: "005", type: "Character", color: "Red", rarity: "SuperRare", cost: 3, power: 3000, attribute: "Special" },
  { id: "OP10-006", name: "Caesar Clown", set: "Royal Blood", setCode: "OP10", number: "006", type: "Character", color: "Red", rarity: "UC", cost: 7, power: 7000, attribute: "Special" },
  { id: "OP10-007", name: "Ceaser Soldier", set: "Royal Blood", setCode: "OP10", number: "007", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 4000, attribute: "Wisdom" },
  { id: "OP10-008", name: "Scotch", set: "Royal Blood", setCode: "OP10", number: "008", type: "Character", color: "Red", rarity: "C", cost: 2, power: 1000, attribute: "Ranged" },
  { id: "OP10-009", name: "Smiley", set: "Royal Blood", setCode: "OP10", number: "009", type: "Character", color: "Red", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP10-010", name: "Chadros.Higelyges (Brownbeard)", set: "Royal Blood", setCode: "OP10", number: "010", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP10-011", name: "Tony Tony.Chopper", set: "Royal Blood", setCode: "OP10", number: "011", type: "Character", color: "Red", rarity: "R", cost: 4, power: 4000, attribute: "Strike" },
  { id: "OP10-012", name: "Dragon Number Thirteen", set: "Royal Blood", setCode: "OP10", number: "012", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000, attribute: "Special" },
  { id: "OP10-013", name: "Nami", set: "Royal Blood", setCode: "OP10", number: "013", type: "Character", color: "Red", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "OP10-014", name: "Franky", set: "Royal Blood", setCode: "OP10", number: "014", type: "Character", color: "Red", rarity: "C", cost: 6, power: 8000, attribute: "Strike" },
  { id: "OP10-015", name: "Mocha", set: "Royal Blood", setCode: "OP10", number: "015", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 3000, attribute: "Strike" },
  { id: "OP10-016", name: "Monet", set: "Royal Blood", setCode: "OP10", number: "016", type: "Character", color: "Red", rarity: "SuperRare", cost: 2, power: 3000, attribute: "Special" },
  { id: "OP10-017", name: "Rock", set: "Royal Blood", setCode: "OP10", number: "017", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000, attribute: "Ranged" },
  { id: "OP10-018", name: "Ten-Layer Igloo", set: "Royal Blood", setCode: "OP10", number: "018", type: "Event", color: "Red", rarity: "C", cost: 2 },
  { id: "OP10-019", name: "Divine Departure", set: "Royal Blood", setCode: "OP10", number: "019", type: "Event", color: "Red", rarity: "R", cost: 1 },
  { id: "OP10-020", name: "Gum-Gum UFO", set: "Royal Blood", setCode: "OP10", number: "020", type: "Event", color: "Red", rarity: "UC", cost: 2 },
  { id: "OP10-021", name: "Punk Hazard", set: "Royal Blood", setCode: "OP10", number: "021", type: "Stage", color: "Red", rarity: "C", cost: 1 },
  { id: "OP10-022", name: "Trafalgar Law", set: "Royal Blood", setCode: "OP10", number: "022", type: "Leader", color: "Green/Yellow", rarity: "L", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP10-023", name: "Issho", set: "Royal Blood", setCode: "OP10", number: "023", type: "Character", color: "Green", rarity: "C", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP10-024", name: "Edward.Newgate", set: "Royal Blood", setCode: "OP10", number: "024", type: "Character", color: "Green", rarity: "C", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP10-025", name: "Enel", set: "Royal Blood", setCode: "OP10", number: "025", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP10-026", name: "Kin'emon", set: "Royal Blood", setCode: "OP10", number: "026", type: "Character", color: "Green", rarity: "C", cost: 2, power: 1000, attribute: "Slash" },
  { id: "OP10-027", name: "Kin'emon", set: "Royal Blood", setCode: "OP10", number: "027", type: "Character", color: "Green", rarity: "UC", cost: 2, attribute: "Slash" },
  { id: "OP10-028", name: "Kouzuki Momonosuke", set: "Royal Blood", setCode: "OP10", number: "028", type: "Character", color: "Green", rarity: "UC", cost: 1, power: 1000, attribute: "Special" },
  { id: "OP10-029", name: "Dracule Mihawk", set: "Royal Blood", setCode: "OP10", number: "029", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP10-030", name: "Smoker", set: "Royal Blood", setCode: "OP10", number: "030", type: "Character", color: "Green", rarity: "SuperRare", cost: 5, power: 7000, attribute: "Slash" },
  { id: "OP10-031", name: "Sengoku", set: "Royal Blood", setCode: "OP10", number: "031", type: "Character", color: "Green", rarity: "C", cost: 5, power: 7000, attribute: "Wisdom" },
  { id: "OP10-032", name: "Tashigi", set: "Royal Blood", setCode: "OP10", number: "032", type: "Character", color: "Green", rarity: "SuperRare", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP10-033", name: "Nami", set: "Royal Blood", setCode: "OP10", number: "033", type: "Character", color: "Green", rarity: "UC", cost: 2, power: 2000, attribute: "Special" },
  { id: "OP10-034", name: "Franky", set: "Royal Blood", setCode: "OP10", number: "034", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP10-035", name: "Brook", set: "Royal Blood", setCode: "OP10", number: "035", type: "Character", color: "Green", rarity: "C", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP10-036", name: "Perona", set: "Royal Blood", setCode: "OP10", number: "036", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP10-037", name: "Lim", set: "Royal Blood", setCode: "OP10", number: "037", type: "Character", color: "Green", rarity: "R", cost: 1, attribute: "Wisdom" },
  { id: "OP10-038", name: "Roronoa Zoro", set: "Royal Blood", setCode: "OP10", number: "038", type: "Character", color: "Green", rarity: "C", cost: 5, power: 6000, attribute: "Slash" },
  { id: "OP10-039", name: "Gum-Gum Dragon Fire Pistol Twister Star", set: "Royal Blood", setCode: "OP10", number: "039", type: "Event", color: "Green", rarity: "UC", cost: 3 },
  { id: "OP10-040", name: "The Weak Do Not Have the Right to Choose How They Die", set: "Royal Blood", setCode: "OP10", number: "040", type: "Event", color: "Green", rarity: "C", cost: 5 },
  { id: "OP10-041", name: "Radio Knife", set: "Royal Blood", setCode: "OP10", number: "041", type: "Event", color: "Green", rarity: "R", cost: 4 },
  { id: "OP10-042", name: "Usopp", set: "Royal Blood", setCode: "OP10", number: "042", type: "Leader", color: "Blue/Black", rarity: "L", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP10-043", name: "Moocy", set: "Royal Blood", setCode: "OP10", number: "043", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 2000, attribute: "Strike" },
  { id: "OP10-044", name: "Cub", set: "Royal Blood", setCode: "OP10", number: "044", type: "Character", color: "Blue", rarity: "UC", cost: 1, power: 2000, attribute: "Slash" },
  { id: "OP10-045", name: "Cavendish", set: "Royal Blood", setCode: "OP10", number: "045", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP10-046", name: "Kyros", set: "Royal Blood", setCode: "OP10", number: "046", type: "Character", color: "Blue", rarity: "SuperRare", cost: 7, power: 9000, attribute: "Slash" },
  { id: "OP10-047", name: "Koala", set: "Royal Blood", setCode: "OP10", number: "047", type: "Character", color: "Blue", rarity: "UC", cost: 2, power: 3000, attribute: "Strike" },
  { id: "OP10-048", name: "Sai", set: "Royal Blood", setCode: "OP10", number: "048", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP10-049", name: "Sabo", set: "Royal Blood", setCode: "OP10", number: "049", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP10-050", name: "Hajrudin", set: "Royal Blood", setCode: "OP10", number: "050", type: "Character", color: "Blue", rarity: "C", cost: 7, power: 9000, attribute: "Strike" },
  { id: "OP10-051", name: "Hack", set: "Royal Blood", setCode: "OP10", number: "051", type: "Character", color: "Blue", rarity: "UC", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP10-052", name: "Bartolomeo", set: "Royal Blood", setCode: "OP10", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP10-053", name: "Bian", set: "Royal Blood", setCode: "OP10", number: "053", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 1000, attribute: "Slash" },
  { id: "OP10-054", name: "Blue Gilly", set: "Royal Blood", setCode: "OP10", number: "054", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 5000, attribute: "Strike" },
  { id: "OP10-055", name: "Marco", set: "Royal Blood", setCode: "OP10", number: "055", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 5000, attribute: "Special" },
  { id: "OP10-056", name: "Mansherry", set: "Royal Blood", setCode: "OP10", number: "056", type: "Character", color: "Blue", rarity: "UC", cost: 2, attribute: "Special" },
  { id: "OP10-057", name: "Leo", set: "Royal Blood", setCode: "OP10", number: "057", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP10-058", name: "Rebecca", set: "Royal Blood", setCode: "OP10", number: "058", type: "Character", color: "Blue", rarity: "SuperRare", cost: 7, power: 4000, attribute: "Slash" },
  { id: "OP10-059", name: "Fo...llow...Me...and...I...Will...Gui...de...You", set: "Royal Blood", setCode: "OP10", number: "059", type: "Event", color: "Blue", rarity: "R", cost: 1 },
  { id: "OP10-060", name: "Barrier-Barrier Pistol", set: "Royal Blood", setCode: "OP10", number: "060", type: "Event", color: "Blue", rarity: "C", cost: 5 },
  { id: "OP10-061", name: "Special Long-Range Attack!! Bagworm", set: "Royal Blood", setCode: "OP10", number: "061", type: "Event", color: "Blue", rarity: "UC", cost: 3 },
  { id: "OP10-062", name: "Violet", set: "Royal Blood", setCode: "OP10", number: "062", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP10-063", name: "Vinsmoke Sanji", set: "Royal Blood", setCode: "OP10", number: "063", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP10-064", name: "Clone Soldier", set: "Royal Blood", setCode: "OP10", number: "064", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000, attribute: "Ranged" },
  { id: "OP10-065", name: "Sugar", set: "Royal Blood", setCode: "OP10", number: "065", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 1000, attribute: "Special" },
  { id: "OP10-066", name: "Giolla", set: "Royal Blood", setCode: "OP10", number: "066", type: "Character", color: "Purple", rarity: "UC", cost: 2, power: 2000, attribute: "Special" },
  { id: "OP10-067", name: "Senor Pink", set: "Royal Blood", setCode: "OP10", number: "067", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP10-068", name: "Diamante", set: "Royal Blood", setCode: "OP10", number: "068", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 7000, attribute: "Slash" },
  { id: "OP10-069", name: "Fighting Fish", set: "Royal Blood", setCode: "OP10", number: "069", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP10-070", name: "Trebol", set: "Royal Blood", setCode: "OP10", number: "070", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP10-071", name: "Donquixote Doflamingo", set: "Royal Blood", setCode: "OP10", number: "071", type: "Character", color: "Purple", rarity: "SuperRare", cost: 8, power: 9000, attribute: "Special" },
  { id: "OP10-072", name: "Donquixote Rosinante", set: "Royal Blood", setCode: "OP10", number: "072", type: "Character", color: "Purple", rarity: "SuperRare", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP10-073", name: "Buffalo", set: "Royal Blood", setCode: "OP10", number: "073", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 6000, attribute: "Strike" },
  { id: "OP10-074", name: "Pica", set: "Royal Blood", setCode: "OP10", number: "074", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP10-075", name: "Foxy", set: "Royal Blood", setCode: "OP10", number: "075", type: "Character", color: "Purple", rarity: "UC", cost: 2, power: 1000, attribute: "Special" },
  { id: "OP10-076", name: "Baby 5", set: "Royal Blood", setCode: "OP10", number: "076", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 1000, attribute: "Special" },
  { id: "OP10-077", name: "Bellamy", set: "Royal Blood", setCode: "OP10", number: "077", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000, attribute: "Strike" },
  { id: "OP10-078", name: "I Do Not Forgive Those Who Laugh at My Family!!!", set: "Royal Blood", setCode: "OP10", number: "078", type: "Event", color: "Purple", rarity: "R", cost: 1 },
  { id: "OP10-079", name: "God Thread", set: "Royal Blood", setCode: "OP10", number: "079", type: "Event", color: "Purple", rarity: "UC", cost: 5 },
  { id: "OP10-080", name: "Little Black Bears", set: "Royal Blood", setCode: "OP10", number: "080", type: "Event", color: "Purple", rarity: "C", cost: 3 },
  { id: "OP10-081", name: "Usopp", set: "Royal Blood", setCode: "OP10", number: "081", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000, attribute: "Ranged" },
  { id: "OP10-082", name: "Kuzan", set: "Royal Blood", setCode: "OP10", number: "082", type: "Character", color: "Black", rarity: "SuperRare", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP10-083", name: "Kouzuki Momonosuke", set: "Royal Blood", setCode: "OP10", number: "083", type: "Character", color: "Black", rarity: "UC", cost: 2, attribute: "Slash" },
  { id: "OP10-084", name: "Sanjuan.Wolf", set: "Royal Blood", setCode: "OP10", number: "084", type: "Character", color: "Black", rarity: "C", cost: 5, power: 7000, attribute: "Special" },
  { id: "OP10-085", name: "Jesus Burgess", set: "Royal Blood", setCode: "OP10", number: "085", type: "Character", color: "Black", rarity: "UC", cost: 5, power: 6000, attribute: "Strike" },
  { id: "OP10-086", name: "Shiryu", set: "Royal Blood", setCode: "OP10", number: "086", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP10-087", name: "Tony Tony.Chopper", set: "Royal Blood", setCode: "OP10", number: "087", type: "Character", color: "Black", rarity: "UC", cost: 2, attribute: "Strike" },
  { id: "OP10-088", name: "Nami", set: "Royal Blood", setCode: "OP10", number: "088", type: "Character", color: "Black", rarity: "UC", cost: 2, attribute: "Special" },
  { id: "OP10-089", name: "Nico Robin", set: "Royal Blood", setCode: "OP10", number: "089", type: "Character", color: "Black", rarity: "C", cost: 6, power: 8000, attribute: "Strike" },
  { id: "OP10-090", name: "Franky", set: "Royal Blood", setCode: "OP10", number: "090", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, attribute: "Strike" },
  { id: "OP10-091", name: "Brook", set: "Royal Blood", setCode: "OP10", number: "091", type: "Character", color: "Black", rarity: "C", cost: 3, attribute: "Slash" },
  { id: "OP10-092", name: "Perona", set: "Royal Blood", setCode: "OP10", number: "092", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP10-093", name: "Saint Homing", set: "Royal Blood", setCode: "OP10", number: "093", type: "Character", color: "Black", rarity: "C", cost: 1, attribute: "Wisdom" },
  { id: "OP10-094", name: "Ryuma", set: "Royal Blood", setCode: "OP10", number: "094", type: "Character", color: "Black", rarity: "UC", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP10-095", name: "Roronoa Zoro", set: "Royal Blood", setCode: "OP10", number: "095", type: "Character", color: "Black", rarity: "R", cost: 4, power: 6000, attribute: "Slash" },
  { id: "OP10-096", name: "There’s No Longer Any Need for the Seven Warlords of the Sea!!!", set: "Royal Blood", setCode: "OP10", number: "096", type: "Event", color: "Black", rarity: "UC", cost: 4 },
  { id: "OP10-097", name: "Gum-Gum Rhino Schneider", set: "Royal Blood", setCode: "OP10", number: "097", type: "Event", color: "Black", rarity: "C", cost: 1 },
  { id: "OP10-098", name: "Liberation", set: "Royal Blood", setCode: "OP10", number: "098", type: "Event", color: "Black", rarity: "R", cost: 6 },
  { id: "OP10-099", name: "Eustass\"Captain\"Kid", set: "Royal Blood", setCode: "OP10", number: "099", type: "Leader", color: "Yellow", rarity: "L", cost: 5, power: 5000, attribute: "Special" },
  { id: "OP10-100", name: "Inazuma", set: "Royal Blood", setCode: "OP10", number: "100", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP10-101", name: "Urouge", set: "Royal Blood", setCode: "OP10", number: "101", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 7000, attribute: "Strike" },
  { id: "OP10-102", name: "Emporio.Ivankov", set: "Royal Blood", setCode: "OP10", number: "102", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 6000, attribute: "Special" },
  { id: "OP10-103", name: "Capone\"Gang\"Bege", set: "Royal Blood", setCode: "OP10", number: "103", type: "Character", color: "Yellow", rarity: "R", cost: 1, attribute: "Ranged" },
  { id: "OP10-104", name: "Caribou", set: "Royal Blood", setCode: "OP10", number: "104", type: "Character", color: "Yellow", rarity: "UC", cost: 4, power: 5000, attribute: "Special" },
  { id: "OP10-105", name: "Cavendish", set: "Royal Blood", setCode: "OP10", number: "105", type: "Character", color: "Yellow", rarity: "C", cost: 6, power: 8000, attribute: "Slash" },
  { id: "OP10-106", name: "Killer", set: "Royal Blood", setCode: "OP10", number: "106", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP10-107", name: "Jewelry Bonney", set: "Royal Blood", setCode: "OP10", number: "107", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 4000, attribute: "Special" },
  { id: "OP10-108", name: "Scratchmen Apoo", set: "Royal Blood", setCode: "OP10", number: "108", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 1000, attribute: "Ranged" },
  { id: "OP10-109", name: "Basil Hawkins", set: "Royal Blood", setCode: "OP10", number: "109", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, attribute: "Slash" },
  { id: "OP10-110", name: "Heat &amp; Wire", set: "Royal Blood", setCode: "OP10", number: "110", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 4000, attribute: "Slash" },
  { id: "OP10-111", name: "Monkey.D.Luffy", set: "Royal Blood", setCode: "OP10", number: "111", type: "Character", color: "Yellow", rarity: "R", cost: 1, power: 2000, attribute: "Strike" },
  { id: "OP10-112", name: "Eustass\"Captain\"Kid", set: "Royal Blood", setCode: "OP10", number: "112", type: "Character", color: "Yellow", rarity: "SuperRare", cost: 8, power: 9000, attribute: "Special" },
  { id: "OP10-113", name: "Roronoa Zoro", set: "Royal Blood", setCode: "OP10", number: "113", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 5000, attribute: "Slash" },
  { id: "OP10-114", name: "X.Drake", set: "Royal Blood", setCode: "OP10", number: "114", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 3000, attribute: "Slash" },
  { id: "OP10-115", name: "Let's Meet Again in the New World", set: "Royal Blood", setCode: "OP10", number: "115", type: "Event", color: "Yellow", rarity: "C", cost: 2 },
  { id: "OP10-116", name: "Damned Punk", set: "Royal Blood", setCode: "OP10", number: "116", type: "Event", color: "Yellow", rarity: "R", cost: 4 },
  { id: "OP10-117", name: "ROOM", set: "Royal Blood", setCode: "OP10", number: "117", type: "Event", color: "Yellow", rarity: "UC", cost: 1 },
  { id: "OP10-118", name: "Monkey.D.Luffy", set: "Royal Blood", setCode: "OP10", number: "118", type: "Character", color: "Black", rarity: "SecretRare", cost: 6, power: 7000, attribute: "Strike" },
  { id: "OP10-119", name: "Trafalgar Law", set: "Royal Blood", setCode: "OP10", number: "119", type: "Character", color: "Yellow", rarity: "SecretRare", cost: 7, power: 9000, attribute: "Slash" },
];

export default OP10_CARDS;
