// OP11: A FIST OF DIVINE SPEED - Synced from official cardlist
// 156 entries including variants and cross-set SP/TR cards
const OP11_CARDS = [
  { id: "OP09-015_p1", name: "Lucky.Roux (TR)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "015", type: "Character", color: "Red", rarity: "TR", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP09-015&variant=p1" },
  { id: "OP11-001", name: "Koby", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "001", type: "Leader", color: "Red/Black", rarity: "L", cost: 4, power: 5000 },
  { id: "OP11-001_p1", name: "Koby (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "001", type: "Leader", color: "Red/Black", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP11-001&variant=p1" },
  { id: "OP11-002", name: "Ain", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "002", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP11-003", name: "Usopp", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "003", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP11-004", name: "Kujyaku", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "004", type: "Character", color: "Red", rarity: "SR", cost: 1 },
  { id: "OP11-004_p1", name: "Kujyaku (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "004", type: "Character", color: "Red", rarity: "SR", cost: 1, imageUrl: "/api/card-image?id=OP11-004&variant=p1" },
  { id: "OP11-005", name: "Smoker", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "005", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000 },
  { id: "OP11-006", name: "Zephyr", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "006", type: "Character", color: "Red", rarity: "C", cost: 5, power: 6000 },
  { id: "OP11-007", name: "Tashigi", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "007", type: "Character", color: "Red", rarity: "C", cost: 1, power: 1000 },
  { id: "OP11-008", name: "Doll", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "008", type: "Character", color: "Red", rarity: "R", cost: 4, power: 1000 },
  { id: "OP11-008_p1", name: "Doll (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "008", type: "Character", color: "Red", rarity: "R", cost: 4, power: 1000, imageUrl: "/api/card-image?id=OP11-008&variant=p1" },
  { id: "OP11-009", name: "Nico Robin", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "009", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "OP11-010", name: "Hibari", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "010", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP11-010_p1", name: "Hibari (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "010", type: "Character", color: "Red", rarity: "SR", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP11-010&variant=p1" },
  { id: "OP11-011", name: "Bins", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "011", type: "Character", color: "Red", rarity: "C", cost: 5, power: 7000 },
  { id: "OP11-012", name: "Franky", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "012", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 4000 },
  { id: "OP11-013", name: "Prince Grus", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "013", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000 },
  { id: "OP11-014", name: "Borsalino", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "014", type: "Character", color: "Red", rarity: "R", cost: 3, power: 3000 },
  { id: "OP11-015", name: "Mocha", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "015", type: "Character", color: "Red", rarity: "C", cost: 4, power: 6000 },
  { id: "OP11-016", name: "Roronoa Zoro", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "016", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP11-017", name: "X.Drake", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "017", type: "Character", color: "Red", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP11-018", name: "Honesty Impact", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "018", type: "Event", color: "Red", rarity: "R", cost: 6 },
  { id: "OP11-018_p1", name: "Honesty Impact (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "018", type: "Event", color: "Red", rarity: "R", cost: 6, imageUrl: "/api/card-image?id=OP11-018&variant=p1" },
  { id: "OP11-019", name: "Glorp Web!!", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "019", type: "Event", color: "Red", rarity: "C", cost: 2 },
  { id: "OP11-020", name: "X Calibur", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "020", type: "Event", color: "Red", rarity: "UC", cost: 2 },
  { id: "OP11-021", name: "Jinbe", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "021", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000 },
  { id: "OP11-021_p1", name: "Jinbe (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "021", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP11-021&variant=p1" },
  { id: "OP11-022", name: "Shirahoshi", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "022", type: "Leader", color: "Green/Yellow", rarity: "L", cost: 5, power: 5000 },
  { id: "OP11-022_p1", name: "Shirahoshi (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "022", type: "Leader", color: "Green/Yellow", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP11-022&variant=p1" },
  { id: "OP11-023", name: "Arlong", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "023", type: "Character", color: "Green", rarity: "R", cost: 7, power: 7000 },
  { id: "OP11-023_p1", name: "Arlong (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "023", type: "Character", color: "Green", rarity: "R", cost: 7, power: 7000, imageUrl: "/api/card-image?id=OP11-023&variant=p1" },
  { id: "OP11-024", name: "Aladine", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "024", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000 },
  { id: "OP11-025", name: "Ishilly", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "025", type: "Character", color: "Green", rarity: "C", cost: 2 },
  { id: "OP11-026", name: "Scaled Neptunian", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "026", type: "Character", color: "Green", rarity: "C", cost: 6, power: 8000 },
  { id: "OP11-027", name: "Bulge-Eyed Neptunian", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "027", type: "Character", color: "Green", rarity: "C", cost: 4, power: 6000 },
  { id: "OP11-028", name: "Lord of the Coast", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "028", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000 },
  { id: "OP11-029", name: "Charlotte Praline", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "029", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP11-030", name: "Shirahoshi", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "030", type: "Character", color: "Green", rarity: "R", cost: 1 },
  { id: "OP11-031", name: "Jinbe", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "031", type: "Character", color: "Green", rarity: "SR", cost: 6, power: 8000 },
  { id: "OP11-031_p1", name: "Jinbe (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "031", type: "Character", color: "Green", rarity: "SR", cost: 6, power: 8000, imageUrl: "/api/card-image?id=OP11-031&variant=p1" },
  { id: "OP11-032", name: "Surume", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP11-033", name: "Bird Neptunian", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "033", type: "Character", color: "Green", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP11-034", name: "Hatchan", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "034", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000 },
  { id: "OP11-035", name: "Fisher Tiger", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "035", type: "Character", color: "Green", rarity: "C", cost: 6, power: 7000 },
  { id: "OP11-036", name: "Spotted Neptunian", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "036", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP11-037", name: "Ancient Weapon Poseidon", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "037", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP11-038", name: "Gum-Gum Elephant Gatling", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "038", type: "Event", color: "Green", rarity: "R", cost: 1 },
  { id: "OP11-039", name: "Vagabond Drill", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "039", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "OP11-040", name: "Monkey.D.Luffy", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "040", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 3, power: 6000 },
  { id: "OP11-040_p1", name: "Monkey.D.Luffy (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "040", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 3, power: 6000, imageUrl: "/api/card-image?id=OP11-040&variant=p1" },
  { id: "OP11-041", name: "Nami", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "041", type: "Leader", color: "Blue/Yellow", rarity: "L", cost: 4, power: 5000 },
  { id: "OP11-041_p1", name: "Nami (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "041", type: "Leader", color: "Blue/Yellow", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP11-041&variant=p1" },
  { id: "OP11-042", name: "Vito", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "042", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP11-043", name: "Vinsmoke Ichiji", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "043", type: "Character", color: "Blue", rarity: "C", cost: 7, power: 7000 },
  { id: "OP11-044", name: "Vinsmoke Judge", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "044", type: "Character", color: "Blue", rarity: "C", cost: 6, power: 8000 },
  { id: "OP11-045", name: "Vinsmoke Niji", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "045", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP11-046", name: "Vinsmoke Yonji", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "046", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000 },
  { id: "OP11-047", name: "Vinsmoke Reiju", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP11-047_p1", name: "Vinsmoke Reiju (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP11-047&variant=p1" },
  { id: "OP11-048", name: "Capone\"Gang\"Bege", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "048", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 2000 },
  { id: "OP11-049", name: "Carrot", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "049", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 1000 },
  { id: "OP11-050", name: "Gotti", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "050", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP11-051", name: "Sanji", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "051", type: "Character", color: "Blue", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP11-051_p1", name: "Sanji (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "051", type: "Character", color: "Blue", rarity: "SR", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP11-051&variant=p1" },
  { id: "OP11-052", name: "Charlotte Lola", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 7000 },
  { id: "OP11-053", name: "Tony Tony.Chopper", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "053", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP11-054", name: "Nami", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "054", type: "Character", color: "Blue", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP11-054_p1", name: "Nami (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "054", type: "Character", color: "Blue", rarity: "SR", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP11-054&variant=p1" },
  { id: "OP11-055", name: "Bartolomeo", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "055", type: "Character", color: "Blue", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP11-056", name: "Brook", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "056", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 4000 },
  { id: "OP11-057", name: "Pedro", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "057", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 1000 },
  { id: "OP11-058", name: "Monkey.D.Luffy", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "058", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 7000 },
  { id: "OP11-059", name: "Gum-Gum King Cobra", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "059", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP11-060", name: "Let's Crash This Wedding!!!", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "060", type: "Event", color: "Blue", rarity: "R", cost: 1 },
  { id: "OP11-061", name: "Gum-Gum Jet Culverin", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "061", type: "Event", color: "Blue", rarity: "UC", cost: 3 },
  { id: "OP11-062", name: "Charlotte Katakuri", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "062", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000 },
  { id: "OP11-062_p1", name: "Charlotte Katakuri (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "062", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP11-062&variant=p1" },
  { id: "OP11-063", name: "Little Sadi", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "063", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000 },
  { id: "OP11-064", name: "Saldeath", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "064", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 8000 },
  { id: "OP11-065", name: "Charlotte Anana", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "065", type: "Character", color: "Purple", rarity: "UC", cost: 1, power: 1000 },
  { id: "OP11-066", name: "Charlotte Oven", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "066", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 5000 },
  { id: "OP11-067", name: "Charlotte Katakuri", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "067", type: "Character", color: "Purple", rarity: "SR", cost: 8, power: 8000 },
  { id: "OP11-067_p1", name: "Charlotte Katakuri (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "067", type: "Character", color: "Purple", rarity: "SR", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP11-067&variant=p1" },
  { id: "OP11-068", name: "Charlotte Daifuku", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "068", type: "Character", color: "Purple", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP11-069", name: "Charlotte Brulee", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "069", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 4000 },
  { id: "OP11-070", name: "Charlotte Pudding", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "070", type: "Character", color: "Purple", rarity: "SR", cost: 1 },
  { id: "OP11-070_p1", name: "Charlotte Pudding (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "070", type: "Character", color: "Purple", rarity: "SR", cost: 1, imageUrl: "/api/card-image?id=OP11-070&variant=p1" },
  { id: "OP11-071", name: "Charlotte Perospero", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "071", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 7000 },
  { id: "OP11-072", name: "Charlotte Mont-d'or", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "072", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP11-073", name: "Charlotte Linlin", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "073", type: "Character", color: "Purple", rarity: "R", cost: 10, power: 12000 },
  { id: "OP11-073_p1", name: "Charlotte Linlin (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "073", type: "Character", color: "Purple", rarity: "R", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP11-073&variant=p1" },
  { id: "OP11-074", name: "Streusen", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "074", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 3000 },
  { id: "OP11-075", name: "Jaguar.D.Saul", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "075", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 6000 },
  { id: "OP11-076", name: "Hannyabal", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "076", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 5000 },
  { id: "OP11-077", name: "Randolph", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "077", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 2000 },
  { id: "OP11-078", name: "Decuplets", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "078", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP11-079", name: "When Two Men Are Fighting the Last Thing I Need Is Some Half-Hearted Assistance!!!!", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "079", type: "Event", color: "Purple", rarity: "UC", cost: 1 },
  { id: "OP11-080", name: "Gear Two", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "080", type: "Event", color: "Purple", rarity: "R", cost: 1 },
  { id: "OP11-080_p1", name: "Gear Two (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "080", type: "Event", color: "Purple", rarity: "R", cost: 1, imageUrl: "/api/card-image?id=OP11-080&variant=p1" },
  { id: "OP11-081", name: "Cognac Mama-Mash", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "081", type: "Event", color: "Purple", rarity: "C", cost: 6 },
  { id: "OP11-082", name: "Aramaki", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "082", type: "Character", color: "Black", rarity: "R", cost: 1, power: 2000 },
  { id: "OP11-083", name: "Caribou", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "083", type: "Character", color: "Black", rarity: "R", cost: 1, power: 2000 },
  { id: "OP11-084", name: "Kuzan", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "084", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000 },
  { id: "OP11-084_p1", name: "Kuzan (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "084", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP11-084&variant=p1" },
  { id: "OP11-085", name: "Kurozumi Orochi", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "085", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000 },
  { id: "OP11-086", name: "Coribou", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "086", type: "Character", color: "Black", rarity: "C", cost: 3, power: 5000 },
  { id: "OP11-087", name: "Miss Sarahebi", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "087", type: "Character", color: "Black", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP11-088", name: "Shu", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "088", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000 },
  { id: "OP11-089", name: "Black Maria", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "089", type: "Character", color: "Black", rarity: "C", cost: 5, power: 7000 },
  { id: "OP11-090", name: "Briscola", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "090", type: "Character", color: "Black", rarity: "C", cost: 2, power: 2000 },
  { id: "OP11-091", name: "Berry Good", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "091", type: "Character", color: "Black", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP11-092", name: "Helmeppo", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "092", type: "Character", color: "Black", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP11-092_p1", name: "Helmeppo (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "092", type: "Character", color: "Black", rarity: "SR", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP11-092&variant=p1" },
  { id: "OP11-093", name: "Bogard", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "093", type: "Character", color: "Black", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP11-094", name: "Morgan", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "094", type: "Character", color: "Black", rarity: "C", cost: 6, power: 8000 },
  { id: "OP11-095", name: "Monkey.D.Garp", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "095", type: "Character", color: "Black", rarity: "SR", cost: 8, power: 8000 },
  { id: "OP11-095_p1", name: "Monkey.D.Garp (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "095", type: "Character", color: "Black", rarity: "SR", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP11-095&variant=p1" },
  { id: "OP11-096", name: "Ripper", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "096", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 1000 },
  { id: "OP11-097", name: "After All These Years I'm Losing My Edge!!!", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "097", type: "Event", color: "Black", rarity: "UC", cost: 1 },
  { id: "OP11-098", name: "Blue Hole", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "098", type: "Event", color: "Black", rarity: "C", cost: 3 },
  { id: "OP11-099", name: "I'm Gonna Be a Navy Officer!!!", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "099", type: "Event", color: "Black", rarity: "R", cost: 1 },
  { id: "OP11-100", name: "Otohime", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "100", type: "Character", color: "Yellow", rarity: "C", cost: 1 },
  { id: "OP11-101", name: "Capone\"Gang\"Bege", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "101", type: "Character", color: "Yellow", rarity: "SR", cost: 2, power: 1000 },
  { id: "OP11-101_p1", name: "Capone\"Gang\"Bege (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "101", type: "Character", color: "Yellow", rarity: "SR", cost: 2, power: 1000, imageUrl: "/api/card-image?id=OP11-101&variant=p1" },
  { id: "OP11-102", name: "Camie", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "102", type: "Character", color: "Yellow", rarity: "UC", cost: 1, power: 1000 },
  { id: "OP11-103", name: "Long-Jaw Neptunian", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "103", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 7000 },
  { id: "OP11-104", name: "Shirley", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "104", type: "Character", color: "Yellow", rarity: "R", cost: 3, power: 4000 },
  { id: "OP11-105", name: "Charlotte Chiffon", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "105", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP11-106", name: "Zeus", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "106", type: "Character", color: "Yellow", rarity: "R", cost: 2, power: 2000 },
  { id: "OP11-106_p1", name: "Zeus (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "106", type: "Character", color: "Yellow", rarity: "R", cost: 2, power: 2000, imageUrl: "/api/card-image?id=OP11-106&variant=p1" },
  { id: "OP11-107", name: "Topknot Neptunian", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "107", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 6000 },
  { id: "OP11-108", name: "Neptune", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "108", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 7000 },
  { id: "OP11-109", name: "Pappag", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "109", type: "Character", color: "Yellow", rarity: "C", cost: 1 },
  { id: "OP11-110", name: "Fukaboshi", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "110", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000 },
  { id: "OP11-111", name: "Mamboshi", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "111", type: "Character", color: "Yellow", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP11-112", name: "Megalo", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "112", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 2000 },
  { id: "OP11-113", name: "Ryuboshi", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "113", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 7000 },
  { id: "OP11-114", name: "Gum-Gum Fire-Fist Pistol Red Hawk", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "114", type: "Event", color: "Yellow", rarity: "R", cost: 1 },
  { id: "OP11-114_p1", name: "Gum-Gum Fire-Fist Pistol Red Hawk (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "114", type: "Event", color: "Yellow", rarity: "R", cost: 1, imageUrl: "/api/card-image?id=OP11-114&variant=p1" },
  { id: "OP11-115", name: "You're Just Not My Type!", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "115", type: "Event", color: "Yellow", rarity: "UC", cost: 1 },
  { id: "OP11-116", name: "Merman Combat Ultramarine", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "116", type: "Event", color: "Yellow", rarity: "C", cost: 6 },
  { id: "OP11-117", name: "Fish-Man Island", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "117", type: "Stage", color: "Yellow", rarity: "C", cost: 2 },
  { id: "OP11-118", name: "Monkey.D.Luffy", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "118", type: "Character", color: "Blue", rarity: "SEC", cost: 8, power: 8000 },
  { id: "OP11-118_p1", name: "Monkey.D.Luffy (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "118", type: "Character", color: "Blue", rarity: "SEC", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP11-118&variant=p1" },
  { id: "OP11-118_p2", name: "Monkey.D.Luffy (Manga)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "118", type: "Character", color: "Blue", rarity: "SEC", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP11-118&variant=p2" },
  { id: "OP11-119", name: "Koby", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "119", type: "Character", color: "Black", rarity: "SEC", cost: 8, power: 9000 },
  { id: "OP11-119_p1", name: "Koby (Alt Art)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "119", type: "Character", color: "Black", rarity: "SEC", cost: 8, power: 9000, imageUrl: "/api/card-image?id=OP11-119&variant=p1" },
  { id: "EB01-057_p2", name: "Shirahoshi (SP)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "057", type: "Character", color: "Yellow", rarity: "SP", cost: 2, imageUrl: "/api/card-image?id=EB01-057&variant=p2" },
  { id: "OP05-119_p7", name: "Monkey.D.Luffy (SP)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "119", type: "Character", color: "Purple", rarity: "SP", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP05-119&variant=p7" },
  { id: "OP05-119_p8", name: "Monkey.D.Luffy (SP)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "119", type: "Character", color: "Purple", rarity: "SP", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP05-119&variant=p8" },
  { id: "OP06-119_p2", name: "Sanji (SP)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "119", type: "Character", color: "Blue", rarity: "SP", cost: 9, power: 9000, imageUrl: "/api/card-image?id=OP06-119&variant=p2" },
  { id: "OP07-085_p2", name: "Stussy (SP)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "085", type: "Character", color: "Black", rarity: "SP", cost: 9, power: 9000, imageUrl: "/api/card-image?id=OP07-085&variant=p2" },
  { id: "OP09-005_p1", name: "Silvers Rayleigh (SP)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "005", type: "Character", color: "Red", rarity: "SP", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP09-005&variant=p1" },
  { id: "ST16-004_p1", name: "Shanks (SP)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "004", type: "Character", color: "Green", rarity: "SP", cost: 9, power: 11000, imageUrl: "/api/card-image?id=ST16-004&variant=p1" },
  { id: "ST18-005_p1", name: "Luffy-Tarou (SP)", set: "A FIST OF DIVINE SPEED", setCode: "OP11", number: "005", type: "Character", color: "Purple", rarity: "SP", cost: 7, power: 8000, imageUrl: "/api/card-image?id=ST18-005&variant=p1" },
];

export default OP11_CARDS;
