// OP12: LEGACY OF THE MASTER - Synced from official cardlist
// 155 entries including variants and cross-set SP/TR cards
const OP12_CARDS = [
  { id: "OP10-063_p1", name: "Vinsmoke Sanji (TR)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "063", type: "Character", color: "Purple", rarity: "TR", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP10-063&variant=p1" },
  { id: "OP12-001", name: "Silvers Rayleigh", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 5, power: 5000 },
  { id: "OP12-001_p1", name: "Silvers Rayleigh (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP12-001&variant=p1" },
  { id: "OP12-002", name: "Edward.Newgate", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "002", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP12-003", name: "Crocus", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "003", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP12-004", name: "Kouzuki Oden", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "004", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 3000 },
  { id: "OP12-005", name: "Shiki", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "005", type: "Character", color: "Red", rarity: "C", cost: 8, power: 10000 },
  { id: "OP12-006", name: "Shakuyaku", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "006", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000 },
  { id: "OP12-007", name: "Shanks", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "007", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000 },
  { id: "OP12-008", name: "Shanks", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "008", type: "Character", color: "Red", rarity: "R", cost: 4, power: 6000 },
  { id: "OP12-008_p1", name: "Shanks (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "008", type: "Character", color: "Red", rarity: "R", cost: 4, power: 6000, imageUrl: "/api/card-image?id=OP12-008&variant=p1" },
  { id: "OP12-009", name: "Jinbe", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "009", type: "Character", color: "Red", rarity: "R", cost: 3, power: 4000 },
  { id: "OP12-010", name: "Douglas Bullet", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "010", type: "Character", color: "Red", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP12-011", name: "Duval", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "011", type: "Character", color: "Red", rarity: "C", cost: 5, power: 7000 },
  { id: "OP12-012", name: "Buggy", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "012", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000 },
  { id: "OP12-013", name: "Hatchan", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "013", type: "Character", color: "Red", rarity: "C", cost: 1, power: 2000 },
  { id: "OP12-014", name: "Boa Hancock", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "014", type: "Character", color: "Red", rarity: "SR", cost: 2, power: 3000 },
  { id: "OP12-014_p1", name: "Boa Hancock (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "014", type: "Character", color: "Red", rarity: "SR", cost: 2, power: 3000, imageUrl: "/api/card-image?id=OP12-014&variant=p1" },
  { id: "OP12-015", name: "Monkey.D.Luffy", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "015", type: "Character", color: "Red", rarity: "SR", cost: 4, power: 4000 },
  { id: "OP12-015_p1", name: "Monkey.D.Luffy (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "015", type: "Character", color: "Red", rarity: "SR", cost: 4, power: 4000, imageUrl: "/api/card-image?id=OP12-015&variant=p1" },
  { id: "OP12-016", name: "To Never Doubt--That Is Power!", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "016", type: "Event", color: "Red", rarity: "C" },
  { id: "OP12-017", name: "Color of Observation Haki", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "017", type: "Event", color: "Red", rarity: "UC" },
  { id: "OP12-018", name: "Color of the Supreme King Haki", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "018", type: "Event", color: "Red", rarity: "R" },
  { id: "OP12-019", name: "Color of Arms Haki", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "019", type: "Event", color: "Red", rarity: "C" },
  { id: "OP12-020", name: "Roronoa Zoro", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "020", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000 },
  { id: "OP12-020_p1", name: "Roronoa Zoro (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "020", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP12-020&variant=p1" },
  { id: "OP12-021", name: "Ipponmatsu", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "021", type: "Character", color: "Green", rarity: "C", cost: 3 },
  { id: "OP12-022", name: "Inuarashi", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "022", type: "Character", color: "Green", rarity: "C", cost: 6, power: 7000 },
  { id: "OP12-023", name: "Kawamatsu", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "023", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP12-024", name: "Gyukimaru", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "024", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000 },
  { id: "OP12-025", name: "Kin'emon", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "025", type: "Character", color: "Green", rarity: "C", cost: 6, power: 8000 },
  { id: "OP12-026", name: "Kuina", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "026", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 1000 },
  { id: "OP12-027", name: "Koushirou", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "027", type: "Character", color: "Green", rarity: "UC", cost: 2, power: 1000 },
  { id: "OP12-028", name: "Kouzuki Hiyori", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "028", type: "Character", color: "Green", rarity: "R", cost: 1 },
  { id: "OP12-029", name: "Shimotsuki Kouzaburou", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "029", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 2000 },
  { id: "OP12-030", name: "Dracule Mihawk", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "030", type: "Character", color: "Green", rarity: "SR", cost: 8, power: 8000 },
  { id: "OP12-030_p1", name: "Dracule Mihawk (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "030", type: "Character", color: "Green", rarity: "SR", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP12-030&variant=p1" },
  { id: "OP12-031", name: "Tashigi", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "031", type: "Character", color: "Green", rarity: "R", cost: 5, power: 7000 },
  { id: "OP12-031_p1", name: "Tashigi (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "031", type: "Character", color: "Green", rarity: "R", cost: 5, power: 7000, imageUrl: "/api/card-image?id=OP12-031&variant=p1" },
  { id: "OP12-032", name: "Nekomamushi", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP12-033", name: "Helmeppo", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "033", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000 },
  { id: "OP12-034", name: "Perona", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "034", type: "Character", color: "Green", rarity: "SR", cost: 1, power: 2000 },
  { id: "OP12-034_p1", name: "Perona (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "034", type: "Character", color: "Green", rarity: "SR", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP12-034&variant=p1" },
  { id: "OP12-035", name: "Morgan", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "035", type: "Character", color: "Green", rarity: "C", cost: 3, power: 5000 },
  { id: "OP12-036", name: "Roronoa Zoro", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "036", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000 },
  { id: "OP12-037", name: "Demon Aura Nine Sword Style Asura Blades Drawn Dead Man's Game", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "037", type: "Event", color: "Green", rarity: "R", cost: 1 },
  { id: "OP12-037_p1", name: "Demon Aura Nine Sword Style Asura Blades Drawn Dead Man's Game (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "037", type: "Event", color: "Green", rarity: "R", cost: 1, imageUrl: "/api/card-image?id=OP12-037&variant=p1" },
  { id: "OP12-038", name: "Two-Sword Style Rashomon", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "038", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "OP12-039", name: "Luffy Is the Man Who Will Become the King of Pirates!!!", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "039", type: "Event", color: "Green", rarity: "R", cost: 3 },
  { id: "OP12-040", name: "Kuzan", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "040", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000 },
  { id: "OP12-040_p1", name: "Kuzan (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "040", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP12-040&variant=p1" },
  { id: "OP12-041", name: "Sanji", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "041", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 4, power: 5000 },
  { id: "OP12-041_p1", name: "Sanji (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "041", type: "Leader", color: "Blue/Purple", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP12-041&variant=p1" },
  { id: "OP12-042", name: "Alvida", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "042", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000 },
  { id: "OP12-043", name: "Kuzan", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "043", type: "Character", color: "Blue", rarity: "R", cost: 6, power: 8000 },
  { id: "OP12-043_p1", name: "Kuzan (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "043", type: "Character", color: "Blue", rarity: "R", cost: 6, power: 8000, imageUrl: "/api/card-image?id=OP12-043&variant=p1" },
  { id: "OP12-044", name: "Sakazuki", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "044", type: "Character", color: "Blue", rarity: "R", cost: 7, power: 8000 },
  { id: "OP12-045", name: "Jango", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "045", type: "Character", color: "Blue", rarity: "C", cost: 6, power: 8000 },
  { id: "OP12-046", name: "Zephyr(Navy)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "046", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 5000 },
  { id: "OP12-047", name: "Sengoku", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 3000 },
  { id: "OP12-048", name: "Donquixote Rosinante", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "048", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 1000 },
  { id: "OP12-049", name: "Buggy", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "049", type: "Character", color: "Blue", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP12-050", name: "Jaguar.D.Saul", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "050", type: "Character", color: "Blue", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP12-051", name: "Hina", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "051", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 3000 },
  { id: "OP12-052", name: "Fullbody", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 6000 },
  { id: "OP12-053", name: "Borsalino", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "053", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP12-054", name: "Marshall.D.Teach", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "054", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 2000 },
  { id: "OP12-055", name: "Mohji & Cabaji", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "055", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP12-056", name: "Monkey.D.Garp", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "056", type: "Character", color: "Blue", rarity: "SR", cost: 8, power: 8000 },
  { id: "OP12-056_p1", name: "Monkey.D.Garp (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "056", type: "Character", color: "Blue", rarity: "SR", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP12-056&variant=p1" },
  { id: "OP12-057", name: "Ice Block Pheasant Peck", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "057", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "OP12-058", name: "I Will Make Whitebeard the King of the Pirates", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "058", type: "Event", color: "Blue", rarity: "C", cost: 9 },
  { id: "OP12-059", name: "Concasser", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "059", type: "Event", color: "Blue", rarity: "UC", cost: 1 },
  { id: "OP12-060", name: "Boeuf Burst", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "060", type: "Event", color: "Blue", rarity: "R", cost: 3 },
  { id: "OP12-060_p1", name: "Boeuf Burst (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "060", type: "Event", color: "Blue", rarity: "R", cost: 3, imageUrl: "/api/card-image?id=OP12-060&variant=p1" },
  { id: "OP12-061", name: "Donquixote Rosinante", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "061", type: "Leader", color: "Purple/Yellow", rarity: "L", cost: 4, power: 5000 },
  { id: "OP12-061_p1", name: "Donquixote Rosinante (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "061", type: "Leader", color: "Purple/Yellow", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP12-061&variant=p1" },
  { id: "OP12-062", name: "Vinsmoke Sora", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "062", type: "Character", color: "Purple", rarity: "R", cost: 1 },
  { id: "OP12-063", name: "Vinsmoke Reiju", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "063", type: "Character", color: "Purple", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP12-063_p1", name: "Vinsmoke Reiju (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "063", type: "Character", color: "Purple", rarity: "SR", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP12-063&variant=p1" },
  { id: "OP12-064", name: "Vergo", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "064", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 7000 },
  { id: "OP12-065", name: "Emporio.Ivankov", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "065", type: "Character", color: "Purple", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP12-066", name: "Carne", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "066", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 1000 },
  { id: "OP12-067", name: "Carmen", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "067", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 5000 },
  { id: "OP12-068", name: "Gin", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "068", type: "Character", color: "Purple", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP12-069", name: "Crocodile", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "069", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 8000 },
  { id: "OP12-070", name: "Sanji", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "070", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 5000 },
  { id: "OP12-070_p1", name: "Sanji (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "070", type: "Character", color: "Purple", rarity: "R", cost: 3, power: 5000, imageUrl: "/api/card-image?id=OP12-070&variant=p1" },
  { id: "OP12-071", name: "Charlotte Pudding", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "071", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 2000 },
  { id: "OP12-072", name: "Zeff", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "072", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP12-073", name: "Trafalgar Law", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "073", type: "Character", color: "Purple", rarity: "SR", cost: 7, power: 8000 },
  { id: "OP12-073_p1", name: "Trafalgar Law (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "073", type: "Character", color: "Purple", rarity: "SR", cost: 7, power: 8000, imageUrl: "/api/card-image?id=OP12-073&variant=p1" },
  { id: "OP12-074", name: "Patty", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "074", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 2000 },
  { id: "OP12-075", name: "Ms. All Sunday", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "075", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000 },
  { id: "OP12-076", name: "Monet", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "076", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP12-077", name: "The \"Extinguishes All Sound Created by Your Influence\" Technique", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "077", type: "Event", color: "Purple", rarity: "C", cost: 2 },
  { id: "OP12-078", name: "Brochette Blow", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "078", type: "Event", color: "Purple", rarity: "UC", cost: 3 },
  { id: "OP12-079", name: "Luffy Is the Man Who Will Be King of the Pirates!!!", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "079", type: "Event", color: "Purple", rarity: "R", cost: 1 },
  { id: "OP12-080", name: "Baratie", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "080", type: "Stage", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP12-081", name: "Koala", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "081", type: "Leader", color: "Black/Yellow", rarity: "L", cost: 4, power: 5000 },
  { id: "OP12-081_p1", name: "Koala (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "081", type: "Leader", color: "Black/Yellow", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP12-081&variant=p1" },
  { id: "OP12-082", name: "Issho", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "082", type: "Character", color: "Black", rarity: "C", cost: 8, power: 10000 },
  { id: "OP12-083", name: "Inazuma", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "083", type: "Character", color: "Black", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP12-084", name: "Emporio.Ivankov", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "084", type: "Character", color: "Black", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP12-085", name: "Karasu", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "085", type: "Character", color: "Black", rarity: "C", cost: 5, power: 6000 },
  { id: "OP12-086", name: "Koala", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "086", type: "Character", color: "Black", rarity: "R", cost: 1, power: 2000 },
  { id: "OP12-086_p1", name: "Koala (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "086", type: "Character", color: "Black", rarity: "R", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP12-086&variant=p1" },
  { id: "OP12-087", name: "Nico Robin", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "087", type: "Character", color: "Black", rarity: "SR", cost: 6, power: 7000 },
  { id: "OP12-087_p1", name: "Nico Robin (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "087", type: "Character", color: "Black", rarity: "SR", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP12-087&variant=p1" },
  { id: "OP12-088", name: "Bastille", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "088", type: "Character", color: "Black", rarity: "C", cost: 6, power: 8000 },
  { id: "OP12-089", name: "Hack", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "089", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000 },
  { id: "OP12-090", name: "Belo Betty", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "090", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000 },
  { id: "OP12-091", name: "Poker", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "091", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000 },
  { id: "OP12-092", name: "Mizerka", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "092", type: "Character", color: "Black", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP12-093", name: "Morley", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "093", type: "Character", color: "Black", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP12-094", name: "Monkey.D.Dragon", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "094", type: "Character", color: "Black", rarity: "SR", cost: 8, power: 8000 },
  { id: "OP12-094_p1", name: "Monkey.D.Dragon (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "094", type: "Character", color: "Black", rarity: "SR", cost: 8, power: 8000, imageUrl: "/api/card-image?id=OP12-094&variant=p1" },
  { id: "OP12-095", name: "Lindbergh", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "095", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000 },
  { id: "OP12-096", name: "Ursa Shock", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "096", type: "Event", color: "Black", rarity: "C", cost: 4 },
  { id: "OP12-097", name: "Captains Assembled", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "097", type: "Event", color: "Black", rarity: "R", cost: 1 },
  { id: "OP12-098", name: "Hair Removal Fist", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "098", type: "Event", color: "Black", rarity: "UC", cost: 1 },
  { id: "OP12-099", name: "Kalgara", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "099", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000 },
  { id: "OP12-100", name: "Sabo", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "100", type: "Character", color: "Yellow", rarity: "R", cost: 5, power: 6000 },
  { id: "OP12-101", name: "Jewelry Bonney", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "101", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 1000 },
  { id: "OP12-102", name: "Shirahoshi", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "102", type: "Character", color: "Yellow", rarity: "SR", cost: 2 },
  { id: "OP12-102_p1", name: "Shirahoshi (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "102", type: "Character", color: "Yellow", rarity: "SR", cost: 2, imageUrl: "/api/card-image?id=OP12-102&variant=p1" },
  { id: "OP12-103", name: "Seto", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "103", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP12-104", name: "Sentomaru", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "104", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 5000 },
  { id: "OP12-105", name: "Trafalgar Lammy", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "105", type: "Character", color: "Yellow", rarity: "C", cost: 1 },
  { id: "OP12-106", name: "Trafalgar Law", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "106", type: "Character", color: "Yellow", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP12-107", name: "Donquixote Doflamingo", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "107", type: "Character", color: "Yellow", rarity: "R", cost: 8, power: 8000 },
  { id: "OP12-108", name: "Donquixote Rosinante", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "108", type: "Character", color: "Yellow", rarity: "R", cost: 1, power: 2000 },
  { id: "OP12-108_p1", name: "Donquixote Rosinante (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "108", type: "Character", color: "Yellow", rarity: "R", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP12-108&variant=p1" },
  { id: "OP12-109", name: "Pacifista", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "109", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 5000 },
  { id: "OP12-110", name: "Buffalo", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "110", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 5000 },
  { id: "OP12-111", name: "Baby 5", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "111", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 4000 },
  { id: "OP12-112", name: "Baby 5", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "112", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000 },
  { id: "OP12-113", name: "Roronoa Zoro", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "113", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP12-114", name: "Wyper", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "114", type: "Character", color: "Yellow", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP12-115", name: "I Love You!!", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "115", type: "Event", color: "Yellow", rarity: "UC", cost: 1 },
  { id: "OP12-116", name: "We'll Ring the Bell Waiting for You!!", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "116", type: "Event", color: "Yellow", rarity: "C", cost: 3 },
  { id: "OP12-117", name: "Slam Gibson", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "117", type: "Event", color: "Yellow", rarity: "R", cost: 1 },
  { id: "OP12-118", name: "Jewelry Bonney", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 5, power: 6000 },
  { id: "OP12-118_p1", name: "Jewelry Bonney (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP12-118&variant=p1" },
  { id: "OP12-118_p2", name: "Jewelry Bonney (Manga)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP12-118&variant=p2" },
  { id: "OP12-119", name: "Bartholomew Kuma", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "119", type: "Character", color: "Yellow", rarity: "SEC", cost: 6, power: 7000 },
  { id: "OP12-119_p1", name: "Bartholomew Kuma (Alt Art)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "119", type: "Character", color: "Yellow", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP12-119&variant=p1" },
  { id: "OP06-050_p2", name: "Tashigi (SP)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "050", type: "Character", color: "Blue", rarity: "SP", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP06-050&variant=p2" },
  { id: "OP09-013_p2", name: "Yasopp (SP)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "013", type: "Character", color: "Red", rarity: "SP", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP09-013&variant=p2" },
  { id: "OP09-037_p2", name: "Lim (SP)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "037", type: "Character", color: "Green", rarity: "SP", cost: 3, power: 5000, imageUrl: "/api/card-image?id=OP09-037&variant=p2" },
  { id: "OP09-093_p4", name: "Marshall.D.Teach (SP)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "093", type: "Character", color: "Black", rarity: "SP", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP09-093&variant=p4" },
  { id: "OP09-093_p5", name: "Marshall.D.Teach (SP)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "093", type: "Character", color: "Black", rarity: "SP", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP09-093&variant=p5" },
  { id: "OP10-082_p2", name: "Kuzan (SP)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "082", type: "Character", color: "Black", rarity: "SP", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP10-082&variant=p2" },
  { id: "ST13-011_p2", name: "Portgas.D.Ace (SP)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "011", type: "Character", color: "Yellow", rarity: "SP", cost: 5, power: 7000, imageUrl: "/api/card-image?id=ST13-011&variant=p2" },
  { id: "ST18-004_p2", name: "Zoro-Juurou (SP)", set: "LEGACY OF THE MASTER", setCode: "OP12", number: "004", type: "Character", color: "Purple", rarity: "SP", cost: 4, power: 6000, imageUrl: "/api/card-image?id=ST18-004&variant=p2" },
];

export default OP12_CARDS;
