// OP13: CARRYING ON HIS WILL - Synced from official cardlist
// 175 entries including variants and cross-set SP/TR cards
const OP13_CARDS = [
  { id: "OP11-058_p1", name: "Monkey.D.Luffy (TR)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "058", type: "Character", color: "Blue", rarity: "TR", cost: 5, power: 7000, imageUrl: "/api/card-image?id=OP11-058&variant=p1" },
  { id: "OP13-001", name: "Monkey.D.Luffy", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "001", type: "Leader", color: "Red/Green", rarity: "L", cost: 4, power: 5000 },
  { id: "OP13-001_p1", name: "Monkey.D.Luffy (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "001", type: "Leader", color: "Red/Green", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP13-001&variant=p1" },
  { id: "OP13-002", name: "Portgas.D.Ace", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "002", type: "Leader", color: "Red/Blue", rarity: "L", cost: 3, power: 6000 },
  { id: "OP13-002_p1", name: "Portgas.D.Ace (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "002", type: "Leader", color: "Red/Blue", rarity: "L", cost: 3, power: 6000, imageUrl: "/api/card-image?id=OP13-002&variant=p1" },
  { id: "OP13-003", name: "Gol.D.Roger", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "003", type: "Leader", color: "Red/Purple", rarity: "L", cost: 5, power: 7000 },
  { id: "OP13-003_p1", name: "Gol.D.Roger (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "003", type: "Leader", color: "Red/Purple", rarity: "L", cost: 5, power: 7000, imageUrl: "/api/card-image?id=OP13-003&variant=p1" },
  { id: "OP13-004", name: "Sabo", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "004", type: "Leader", color: "Red/Black", rarity: "L", cost: 5, power: 5000 },
  { id: "OP13-004_p1", name: "Sabo (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "004", type: "Leader", color: "Red/Black", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP13-004&variant=p1" },
  { id: "OP13-005", name: "Inazuma", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "005", type: "Character", color: "Red", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP13-006", name: "Woop Slap", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "006", type: "Character", color: "Red", rarity: "C", cost: 1 },
  { id: "OP13-007", name: "Ace & Sabo & Luffy", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "007", type: "Character", color: "Red", rarity: "SR", cost: 1, power: 1000 },
  { id: "OP13-007_p1", name: "Ace & Sabo & Luffy (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "007", type: "Character", color: "Red", rarity: "SR", cost: 1, power: 1000, imageUrl: "/api/card-image?id=OP13-007&variant=p1" },
  { id: "OP13-008", name: "Emporio.Ivankov", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "008", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "OP13-009", name: "Curly.Dadan", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "009", type: "Character", color: "Red", rarity: "C", cost: 1, power: 2000 },
  { id: "OP13-010", name: "Lord of the Coast", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "010", type: "Character", color: "Red", rarity: "C", cost: 6, power: 8000 },
  { id: "OP13-011", name: "Nefeltari Cobra", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "011", type: "Character", color: "Red", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-012", name: "Nefeltari Vivi", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "012", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000 },
  { id: "OP13-013", name: "Higuma", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "013", type: "Character", color: "Red", rarity: "C", cost: 1, power: 3000 },
  { id: "OP13-014", name: "Portgas.D.Rouge", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "014", type: "Character", color: "Red", rarity: "C", cost: 1 },
  { id: "OP13-015", name: "Makino", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "015", type: "Character", color: "Red", rarity: "UC", cost: 1 },
  { id: "OP13-016", name: "Monkey.D.Garp", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "016", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000 },
  { id: "OP13-016_p1", name: "Monkey.D.Garp (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "016", type: "Character", color: "Red", rarity: "R", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP13-016&variant=p1" },
  { id: "OP13-017", name: "Monkey.D.Dragon", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "017", type: "Character", color: "Red", rarity: "R", cost: 6, power: 7000 },
  { id: "OP13-018", name: "Wapol", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "018", type: "Character", color: "Red", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP13-019", name: "But Ace Here Said You Deserved It!!", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "019", type: "Event", color: "Red", rarity: "R", cost: 1 },
  { id: "OP13-020", name: "Meteor Fist", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "020", type: "Event", color: "Red", rarity: "UC", cost: 3 },
  { id: "OP13-021", name: "Gum-Gum Gatling Gun", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "021", type: "Event", color: "Red", rarity: "C", cost: 1 },
  { id: "OP13-022", name: "Windmill Village", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "022", type: "Stage", color: "Red", rarity: "C", cost: 1 },
  { id: "OP13-023", name: "Uta", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "023", type: "Character", color: "Green", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP13-023_p1", name: "Uta (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "023", type: "Character", color: "Green", rarity: "SR", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP13-023&variant=p1" },
  { id: "OP13-024", name: "Gordon", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "024", type: "Character", color: "Green", rarity: "C", cost: 1 },
  { id: "OP13-025", name: "Koby", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "025", type: "Character", color: "Green", rarity: "C", cost: 5, power: 6000 },
  { id: "OP13-026", name: "Sunny-Kun", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "026", type: "Character", color: "Green", rarity: "C", cost: 1, power: 2000 },
  { id: "OP13-027", name: "Sanji", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "027", type: "Character", color: "Green", rarity: "R", cost: 5, power: 7000 },
  { id: "OP13-027_p1", name: "Sanji (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "027", type: "Character", color: "Green", rarity: "R", cost: 5, power: 7000, imageUrl: "/api/card-image?id=OP13-027&variant=p1" },
  { id: "OP13-028", name: "Shanks", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "028", type: "Character", color: "Green", rarity: "SR", cost: 10, power: 12000 },
  { id: "OP13-028_p1", name: "Shanks (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "028", type: "Character", color: "Green", rarity: "SR", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP13-028&variant=p1" },
  { id: "OP13-029", name: "Jinbe", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "029", type: "Character", color: "Green", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP13-030", name: "Tony Tony.Chopper", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "030", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-031", name: "Trafalgar Law", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "031", type: "Character", color: "Green", rarity: "R", cost: 6, power: 6000 },
  { id: "OP13-032", name: "Nico Robin", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 7, power: 7000 },
  { id: "OP13-033", name: "Franky", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "033", type: "Character", color: "Green", rarity: "C", cost: 3, power: 5000 },
  { id: "OP13-034", name: "Brook", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "034", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "OP13-035", name: "Bepo", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "035", type: "Character", color: "Green", rarity: "C", cost: 5, power: 7000 },
  { id: "OP13-036", name: "Helmeppo", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "036", type: "Character", color: "Green", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-037", name: "Roronoa Zoro", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "037", type: "Character", color: "Green", rarity: "R", cost: 4, power: 5000 },
  { id: "OP13-038", name: "Gum-Gum Elephant Gun", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "038", type: "Event", color: "Green", rarity: "UC", cost: 2 },
  { id: "OP13-039", name: "Gum-Gum Snake Shot", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "039", type: "Event", color: "Green", rarity: "C", cost: 2 },
  { id: "OP13-040", name: "I Know You're Strong... So I'll Go All Out from the Very Start!!!", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "040", type: "Event", color: "Green", rarity: "R", cost: 1 },
  { id: "OP13-041", name: "Izo", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "041", type: "Character", color: "Blue", rarity: "UC", cost: 6, power: 6000 },
  { id: "OP13-042", name: "Edward.Newgate", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "042", type: "Character", color: "Blue", rarity: "SR", cost: 10, power: 12000 },
  { id: "OP13-042_p1", name: "Edward.Newgate (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "042", type: "Character", color: "Blue", rarity: "SR", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP13-042&variant=p1" },
  { id: "OP13-043", name: "Otama", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "043", type: "Character", color: "Blue", rarity: "R", cost: 1 },
  { id: "OP13-044", name: "Curiel", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "044", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP13-045", name: "Haruta", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "045", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 2000 },
  { id: "OP13-046", name: "Vista", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "046", type: "Character", color: "Blue", rarity: "R", cost: 6, power: 8000 },
  { id: "OP13-047", name: "Fossa", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "047", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP13-048", name: "Blamenco", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "048", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-049", name: "Blenheim", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "049", type: "Character", color: "Blue", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP13-050", name: "Boa Sandersonia", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "050", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "OP13-051", name: "Boa Hancock", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "051", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 5000 },
  { id: "OP13-051_p1", name: "Boa Hancock (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "051", type: "Character", color: "Blue", rarity: "R", cost: 3, power: 5000, imageUrl: "/api/card-image?id=OP13-051&variant=p1" },
  { id: "OP13-052", name: "Boa Marigold", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "052", type: "Character", color: "Blue", rarity: "UC", cost: 5, power: 4000 },
  { id: "OP13-053", name: "Marshall.D.Teach", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "053", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000 },
  { id: "OP13-054", name: "Yamato", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "054", type: "Character", color: "Blue", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP13-054_p1", name: "Yamato (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "054", type: "Character", color: "Blue", rarity: "SR", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP13-054&variant=p1" },
  { id: "OP13-055", name: "Rakuyo", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "055", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP13-056", name: "LittleOars Jr.", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "056", type: "Character", color: "Blue", rarity: "C", cost: 7, power: 7000 },
  { id: "OP13-057", name: "If I Bowed Down to Power, What's the Point in Living?", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "057", type: "Event", color: "Blue", rarity: "R", cost: 1 },
  { id: "OP13-058", name: "Phoenix Pyreapple", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "058", type: "Event", color: "Blue", rarity: "UC", cost: 1 },
  { id: "OP13-059", name: "Brilliant Punk", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "059", type: "Event", color: "Blue", rarity: "C", cost: 4 },
  { id: "OP13-060", name: "Amatsuki Toki", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "060", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "OP13-061", name: "Inuarashi", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "061", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 3000 },
  { id: "OP13-062", name: "Crocus", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "062", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-063", name: "Kouzuki Oden", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "063", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-064", name: "Gol.D.Roger", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "064", type: "Character", color: "Purple", rarity: "SR", cost: 10, power: 13000 },
  { id: "OP13-064_p1", name: "Gol.D.Roger (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "064", type: "Character", color: "Purple", rarity: "SR", cost: 10, power: 13000, imageUrl: "/api/card-image?id=OP13-064&variant=p1" },
  { id: "OP13-065", name: "Shanks", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "065", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 2000 },
  { id: "OP13-065_p1", name: "Shanks (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "065", type: "Character", color: "Purple", rarity: "R", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP13-065&variant=p1" },
  { id: "OP13-066", name: "Silvers Rayleigh", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "066", type: "Character", color: "Purple", rarity: "SR", cost: 8, power: 9000 },
  { id: "OP13-066_p1", name: "Silvers Rayleigh (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "066", type: "Character", color: "Purple", rarity: "SR", cost: 8, power: 9000, imageUrl: "/api/card-image?id=OP13-066&variant=p1" },
  { id: "OP13-067", name: "Scopper Gaban", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "067", type: "Character", color: "Purple", rarity: "R", cost: 6, power: 7000 },
  { id: "OP13-068", name: "Douglas Bullet", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "068", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP13-069", name: "Tom", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "069", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000 },
  { id: "OP13-070", name: "Napoleon", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "070", type: "Character", color: "Purple", rarity: "C", cost: 5, power: 7000 },
  { id: "OP13-071", name: "Nekomamushi", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "071", type: "Character", color: "Purple", rarity: "UC", cost: 3, power: 3000 },
  { id: "OP13-072", name: "Buggy", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "072", type: "Character", color: "Purple", rarity: "R", cost: 2, power: 2000 },
  { id: "OP13-073", name: "Prometheus", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "073", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-074", name: "Hera", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "074", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000 },
  { id: "OP13-075", name: "Guess We'll Have Another Scrap. You Can Only Risk Death While You're Still Alive!!", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "075", type: "Event", color: "Purple", rarity: "UC", cost: 1 },
  { id: "OP13-076", name: "Divine Departure", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "076", type: "Event", color: "Purple", rarity: "R" },
  { id: "OP13-076_p1", name: "Divine Departure (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "076", type: "Event", color: "Purple", rarity: "R", imageUrl: "/api/card-image?id=OP13-076&variant=p1" },
  { id: "OP13-077", name: "Go All the Way to the Top!!", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "077", type: "Event", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP13-078", name: "Oro Jackson", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "078", type: "Stage", color: "Purple", rarity: "C", cost: 1 },
  { id: "OP13-079", name: "Imu", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "079", type: "Leader", color: "Black", rarity: "L", cost: 4, power: 5000 },
  { id: "OP13-079_p1", name: "Imu (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "079", type: "Leader", color: "Black", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP13-079&variant=p1" },
  { id: "OP13-080", name: "St. Ethanbaron V. Nusjuro", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "080", type: "Character", color: "Black", rarity: "R", cost: 6, power: 5000 },
  { id: "OP13-080_p1", name: "St. Ethanbaron V. Nusjuro (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "080", type: "Character", color: "Black", rarity: "R", cost: 6, power: 5000, imageUrl: "/api/card-image?id=OP13-080&variant=p1" },
  { id: "OP13-080_p2", name: "St. Ethanbaron V. Nusjuro (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "080", type: "Character", color: "Black", rarity: "R", cost: 6, power: 5000, imageUrl: "/api/card-image?id=OP13-080&variant=p2" },
  { id: "OP13-081", name: "Koala", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "081", type: "Character", color: "Black", rarity: "C", cost: 5, power: 6000 },
  { id: "OP13-082", name: "Five Elders", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "082", type: "Character", color: "Black", rarity: "SR", cost: 10, power: 12000 },
  { id: "OP13-082_p1", name: "Five Elders (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "082", type: "Character", color: "Black", rarity: "SR", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP13-082&variant=p1" },
  { id: "OP13-083", name: "St. Jaygarcia Saturn", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "083", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000 },
  { id: "OP13-083_p1", name: "St. Jaygarcia Saturn (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "083", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP13-083&variant=p1" },
  { id: "OP13-083_p2", name: "St. Jaygarcia Saturn (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "083", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP13-083&variant=p2" },
  { id: "OP13-084", name: "St. Shepherd Ju Peter", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "084", type: "Character", color: "Black", rarity: "R", cost: 7, power: 5000 },
  { id: "OP13-084_p1", name: "St. Shepherd Ju Peter (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "084", type: "Character", color: "Black", rarity: "R", cost: 7, power: 5000, imageUrl: "/api/card-image?id=OP13-084&variant=p1" },
  { id: "OP13-084_p2", name: "St. Shepherd Ju Peter (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "084", type: "Character", color: "Black", rarity: "R", cost: 7, power: 5000, imageUrl: "/api/card-image?id=OP13-084&variant=p2" },
  { id: "OP13-085", name: "Saint Jalmac", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "085", type: "Character", color: "Black", rarity: "C", cost: 2, power: 4000 },
  { id: "OP13-086", name: "Saint Shalria", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "086", type: "Character", color: "Black", rarity: "UC", cost: 1 },
  { id: "OP13-087", name: "Saint Charlos", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "087", type: "Character", color: "Black", rarity: "UC", cost: 2 },
  { id: "OP13-088", name: "Terry Gilteo", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "088", type: "Character", color: "Black", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-089", name: "St. Topman Warcury", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "089", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000 },
  { id: "OP13-089_p1", name: "St. Topman Warcury (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "089", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP13-089&variant=p1" },
  { id: "OP13-089_p2", name: "St. Topman Warcury (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "089", type: "Character", color: "Black", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP13-089&variant=p2" },
  { id: "OP13-090", name: "Hack", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "090", type: "Character", color: "Black", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP13-091", name: "St. Marcus Mars", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "091", type: "Character", color: "Black", rarity: "R", cost: 6, power: 5000 },
  { id: "OP13-091_p1", name: "St. Marcus Mars (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "091", type: "Character", color: "Black", rarity: "R", cost: 6, power: 5000, imageUrl: "/api/card-image?id=OP13-091&variant=p1" },
  { id: "OP13-091_p2", name: "St. Marcus Mars (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "091", type: "Character", color: "Black", rarity: "R", cost: 6, power: 5000, imageUrl: "/api/card-image?id=OP13-091&variant=p2" },
  { id: "OP13-092", name: "Saint Mjosgard", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "092", type: "Character", color: "Black", rarity: "C", cost: 2 },
  { id: "OP13-093", name: "Morgans", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "093", type: "Character", color: "Black", rarity: "C", cost: 3, power: 4000 },
  { id: "OP13-094", name: "York", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "094", type: "Character", color: "Black", rarity: "C", cost: 1, power: 1000 },
  { id: "OP13-095", name: "Saint Rosward", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "095", type: "Character", color: "Black", rarity: "C", cost: 3 },
  { id: "OP13-096", name: "The Five Elders Are at Your Service!!!", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "096", type: "Event", color: "Black", rarity: "R", cost: 1 },
  { id: "OP13-097", name: "The World's Equilibrium Cannot Be Maintained Forever", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "097", type: "Event", color: "Black", rarity: "C", cost: 1 },
  { id: "OP13-098", name: "Never Existed... in the First Place...", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "098", type: "Event", color: "Black", rarity: "UC", cost: 1 },
  { id: "OP13-099", name: "The Empty Throne", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "099", type: "Stage", color: "Black", rarity: "C", cost: 7 },
  { id: "OP13-100", name: "Jewelry Bonney", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "100", type: "Leader", color: "Yellow", rarity: "L", cost: 5, power: 5000 },
  { id: "OP13-100_p1", name: "Jewelry Bonney (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "100", type: "Leader", color: "Yellow", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP13-100&variant=p1" },
  { id: "OP13-101", name: "Atlas", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "101", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-102", name: "Edison", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "102", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 2000 },
  { id: "OP13-103", name: "Gyogyo", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "103", type: "Character", color: "Yellow", rarity: "C", cost: 4, power: 6000 },
  { id: "OP13-104", name: "Kouzuki Hiyori", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "104", type: "Character", color: "Yellow", rarity: "R", cost: 4 },
  { id: "OP13-105", name: "Kouzuki Momonosuke", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "105", type: "Character", color: "Yellow", rarity: "C", cost: 3 },
  { id: "OP13-106", name: "Conney", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "106", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 1000 },
  { id: "OP13-107", name: "Shaka", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "107", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 7000 },
  { id: "OP13-108", name: "Jewelry Bonney", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "108", type: "Character", color: "Yellow", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP13-108_p1", name: "Jewelry Bonney (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "108", type: "Character", color: "Yellow", rarity: "SR", cost: 9, power: 10000, imageUrl: "/api/card-image?id=OP13-108&variant=p1" },
  { id: "OP13-109", name: "Jewelry Bonney", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "109", type: "Character", color: "Yellow", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP13-110", name: "Stussy", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "110", type: "Character", color: "Yellow", rarity: "SR", cost: 7, power: 7000 },
  { id: "OP13-110_p1", name: "Stussy (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "110", type: "Character", color: "Yellow", rarity: "SR", cost: 7, power: 7000, imageUrl: "/api/card-image?id=OP13-110&variant=p1" },
  { id: "OP13-111", name: "Pythagoras", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "111", type: "Character", color: "Yellow", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP13-112", name: "Vegapunk", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "112", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 1000 },
  { id: "OP13-113", name: "Lilith", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "113", type: "Character", color: "Yellow", rarity: "R", cost: 1, power: 2000 },
  { id: "OP13-113_p1", name: "Lilith (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "113", type: "Character", color: "Yellow", rarity: "R", cost: 1, power: 2000, imageUrl: "/api/card-image?id=OP13-113&variant=p1" },
  { id: "OP13-114", name: "S-Snake", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "114", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000 },
  { id: "OP13-114_p1", name: "S-Snake (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "114", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP13-114&variant=p1" },
  { id: "OP13-115", name: "Paper Art Afterimage", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "115", type: "Event", color: "Yellow", rarity: "C", cost: 2 },
  { id: "OP13-116", name: "The One Who Is the Most Free Is the Pirate King!!!", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "116", type: "Event", color: "Yellow", rarity: "UC", cost: 1 },
  { id: "OP13-117", name: "Gum-Gum Dawn Stamp", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "117", type: "Event", color: "Yellow", rarity: "R", cost: 5 },
  { id: "OP13-118", name: "Monkey.D.Luffy", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 6, power: 7000 },
  { id: "OP13-118_p1", name: "Monkey.D.Luffy (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-118&variant=p1" },
  { id: "OP13-118_p2", name: "Monkey.D.Luffy (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-118&variant=p2" },
  { id: "OP13-118_p3", name: "Monkey.D.Luffy (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "118", type: "Character", color: "Green", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-118&variant=p3" },
  { id: "OP13-119", name: "Portgas.D.Ace", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "119", type: "Character", color: "Blue", rarity: "SEC", cost: 6, power: 7000 },
  { id: "OP13-119_p1", name: "Portgas.D.Ace (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "119", type: "Character", color: "Blue", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-119&variant=p1" },
  { id: "OP13-119_p2", name: "Portgas.D.Ace (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "119", type: "Character", color: "Blue", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-119&variant=p2" },
  { id: "OP13-119_p3", name: "Portgas.D.Ace (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "119", type: "Character", color: "Blue", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-119&variant=p3" },
  { id: "OP13-120", name: "Sabo", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "120", type: "Character", color: "Black", rarity: "SEC", cost: 6, power: 7000 },
  { id: "OP13-120_p1", name: "Sabo (Alt Art)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "120", type: "Character", color: "Black", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-120&variant=p1" },
  { id: "OP13-120_p2", name: "Sabo (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "120", type: "Character", color: "Black", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-120&variant=p2" },
  { id: "OP13-120_p3", name: "Sabo (Manga)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "120", type: "Character", color: "Black", rarity: "SEC", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-120&variant=p3" },
  { id: "EB02-028_p1", name: "Portgas.D.Ace (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "028", type: "Character", color: "Blue", rarity: "SP", cost: 5, power: 5000, imageUrl: "/api/card-image?id=EB02-028&variant=p1" },
  { id: "OP07-111_p2", name: "Lilith (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "111", type: "Character", color: "Yellow", rarity: "SP", cost: 3, power: 5000, imageUrl: "/api/card-image?id=OP07-111&variant=p2" },
  { id: "OP07-118_p2", name: "Sabo (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "118", type: "Character", color: "Black", rarity: "SP", cost: 8, power: 9000, imageUrl: "/api/card-image?id=OP07-118&variant=p2" },
  { id: "OP09-004_p5", name: "Shanks (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "004", type: "Character", color: "Red", rarity: "SP", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP09-004&variant=p5" },
  { id: "OP09-004_p6", name: "Shanks (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "004", type: "Character", color: "Red", rarity: "SP", cost: 10, power: 12000, imageUrl: "/api/card-image?id=OP09-004&variant=p6" },
  { id: "OP09-009_p3", name: "Benn.Beckman (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "009", type: "Character", color: "Red", rarity: "SP", cost: 7, power: 7000, imageUrl: "/api/card-image?id=OP09-009&variant=p3" },
  { id: "OP09-118_p3", name: "Gol.D.Roger (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "118", type: "Character", color: "Red", rarity: "SP", cost: 10, power: 13000, imageUrl: "/api/card-image?id=OP09-118&variant=p3" },
  { id: "OP09-119_p3", name: "Monkey.D.Luffy (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "119", type: "Character", color: "Purple", rarity: "SP", cost: 9, power: 10000, imageUrl: "/api/card-image?id=OP09-119&variant=p3" },
  { id: "OP10-030_p2", name: "Smoker (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "030", type: "Character", color: "Green", rarity: "SP", cost: 5, power: 7000, imageUrl: "/api/card-image?id=OP10-030&variant=p2" },
  { id: "OP13-118_p4", name: "Monkey.D.Luffy (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "118", type: "Character", color: "Green", rarity: "SP", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-118&variant=p4" },
  { id: "OP13-119_p4", name: "Portgas.D.Ace (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "119", type: "Character", color: "Blue", rarity: "SP", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-119&variant=p4" },
  { id: "OP13-120_p4", name: "Sabo (SP)", set: "CARRYING ON HIS WILL", setCode: "OP13", number: "120", type: "Character", color: "Black", rarity: "SP", cost: 6, power: 7000, imageUrl: "/api/card-image?id=OP13-120&variant=p4" },
];

export default OP13_CARDS;
