// OP14: THE AZURE SEA'S SEVEN - Synced from official cardlist
// 149 entries including variants
const OP14_CARDS = [
  { id: "OP14-001", name: "Trafalgar Law", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 5, power: 5000 },
  { id: "OP14-001_p1", name: "Trafalgar Law (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP14-001&variant=p1" },
  { id: "OP14-002", name: "Urouge", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "002", type: "Character", color: "Red", rarity: "UC", cost: 3, power: 2000 },
  { id: "OP14-003", name: "Capone\"Gang\"Bege", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "003", type: "Character", color: "Red", rarity: "C", cost: 1, power: 2000 },
  { id: "OP14-004", name: "Cavendish", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "004", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 2000 },
  { id: "OP14-005", name: "Killer", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "005", type: "Character", color: "Red", rarity: "C", cost: 1, power: 1000 },
  { id: "OP14-006", name: "Shachi & Penguin", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "006", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000 },
  { id: "OP14-007", name: "Jewelry Bonney", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "007", type: "Character", color: "Red", rarity: "C", cost: 6, power: 7000 },
  { id: "OP14-008", name: "Scratchmen Apoo", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "008", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000 },
  { id: "OP14-009", name: "Trafalgar Law", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "009", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP14-009_p1", name: "Trafalgar Law (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "009", type: "Character", color: "Red", rarity: "SR", cost: 9, power: 10000, imageUrl: "/api/card-image?id=OP14-009&variant=p1" },
  { id: "OP14-010", name: "Basil Hawkins", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "010", type: "Character", color: "Red", rarity: "UC", cost: 1, power: 2000 },
  { id: "OP14-011", name: "Bartolomeo", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "011", type: "Character", color: "Red", rarity: "UC", cost: 2, power: 2000 },
  { id: "OP14-012", name: "Bepo", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "012", type: "Character", color: "Red", rarity: "C", cost: 2, power: 2000 },
  { id: "OP14-013", name: "Monkey.D.Luffy", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "013", type: "Character", color: "Red", rarity: "SR", cost: 1 },
  { id: "OP14-013_p1", name: "Monkey.D.Luffy (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "013", type: "Character", color: "Red", rarity: "SR", cost: 1, imageUrl: "/api/card-image?id=OP14-013&variant=p1" },
  { id: "OP14-014", name: "Eustass\"Captain\"Kid", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "014", type: "Character", color: "Red", rarity: "R", cost: 4, power: 5000 },
  { id: "OP14-015", name: "Roronoa Zoro", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "015", type: "Character", color: "Red", rarity: "R", cost: 7, power: 8000 },
  { id: "OP14-015_p1", name: "Roronoa Zoro (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "015", type: "Character", color: "Red", rarity: "R", cost: 7, power: 8000, imageUrl: "/api/card-image?id=OP14-015&variant=p1" },
  { id: "OP14-016", name: "X.Drake", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "016", type: "Character", color: "Red", rarity: "R", cost: 5, power: 7000 },
  { id: "OP14-017", name: "Chambres", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "017", type: "Event", color: "Red", rarity: "C", cost: 3 },
  { id: "OP14-018", name: "Time for the Counterattack", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "018", type: "Event", color: "Red", rarity: "R", cost: 1 },
  { id: "OP14-019", name: "I Have a Plan to Take Down One of the Four Emperors!!", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "019", type: "Event", color: "Red", rarity: "UC", cost: 1 },
  { id: "OP14-020", name: "Dracule Mihawk", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "020", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000 },
  { id: "OP14-020_p1", name: "Dracule Mihawk (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "020", type: "Leader", color: "Green", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP14-020&variant=p1" },
  { id: "OP14-021", name: "Issho", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "021", type: "Character", color: "Green", rarity: "C", cost: 6, power: 7000 },
  { id: "OP14-022", name: "Usopp", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "022", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP14-023", name: "Kikunojo", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "023", type: "Character", color: "Green", rarity: "R", cost: 1, power: 2000 },
  { id: "OP14-024", name: "Kin'emon", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "024", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000 },
  { id: "OP14-025", name: "Kuro", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "025", type: "Character", color: "Green", rarity: "C", cost: 7, power: 8000 },
  { id: "OP14-026", name: "Kouzuki Oden", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "026", type: "Character", color: "Green", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP14-027", name: "Shanks", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "027", type: "Character", color: "Green", rarity: "R", cost: 7, power: 9000 },
  { id: "OP14-027_p1", name: "Shanks (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "027", type: "Character", color: "Green", rarity: "R", cost: 7, power: 9000, imageUrl: "/api/card-image?id=OP14-027&variant=p1" },
  { id: "OP14-028", name: "Johnny", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "028", type: "Character", color: "Green", rarity: "C", cost: 2, power: 2000 },
  { id: "OP14-029", name: "Tashigi", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "029", type: "Character", color: "Green", rarity: "R", cost: 5, power: 6000 },
  { id: "OP14-030", name: "Chaka & Pell", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "030", type: "Character", color: "Green", rarity: "C", cost: 6, power: 7000 },
  { id: "OP14-031", name: "Nami", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "031", type: "Character", color: "Green", rarity: "SR", cost: 4, power: 2000 },
  { id: "OP14-031_p1", name: "Nami (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "031", type: "Character", color: "Green", rarity: "SR", cost: 4, power: 2000, imageUrl: "/api/card-image?id=OP14-031&variant=p1" },
  { id: "OP14-032", name: "Humandrill", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "032", type: "Character", color: "Green", rarity: "UC", cost: 3, power: 4000 },
  { id: "OP14-033", name: "Perona", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "033", type: "Character", color: "Green", rarity: "SR", cost: 5, power: 6000 },
  { id: "OP14-033_p1", name: "Perona (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "033", type: "Character", color: "Green", rarity: "SR", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP14-033&variant=p1" },
  { id: "OP14-034", name: "Monkey.D.Luffy", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "034", type: "Character", color: "Green", rarity: "R", cost: 3, power: 3000 },
  { id: "OP14-035", name: "Yosaku", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "035", type: "Character", color: "Green", rarity: "C", cost: 2, power: 2000 },
  { id: "OP14-036", name: "Strive to Surpass me, Roronoa Zoro!!!", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "036", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "OP14-037", name: "For Fun", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "037", type: "Event", color: "Green", rarity: "R", cost: 1 },
  { id: "OP14-038", name: "I Never Bother to Remember the Faces of Trash", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "038", type: "Event", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP14-039", name: "Coffin Boat", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "039", type: "Stage", color: "Green", rarity: "UC", cost: 1 },
  { id: "OP14-040", name: "Jinbe", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "040", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000 },
  { id: "OP14-040_p1", name: "Jinbe (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "040", type: "Leader", color: "Blue", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP14-040&variant=p1" },
  { id: "OP14-041", name: "Boa Hancock", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "041", type: "Leader", color: "Blue/Yellow", rarity: "L", cost: 4, power: 5000 },
  { id: "OP14-041_p1", name: "Boa Hancock (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "041", type: "Leader", color: "Blue/Yellow", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP14-041&variant=p1" },
  { id: "OP14-042", name: "Arlong", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "042", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 3000 },
  { id: "OP14-042_p1", name: "Arlong (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "042", type: "Character", color: "Blue", rarity: "R", cost: 1, power: 3000, imageUrl: "/api/card-image?id=OP14-042&variant=p1" },
  { id: "OP14-043", name: "Aladine", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "043", type: "Character", color: "Blue", rarity: "R", cost: 4, power: 5000 },
  { id: "OP14-044", name: "Edward.Newgate", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "044", type: "Character", color: "Blue", rarity: "C", cost: 8, power: 8000 },
  { id: "OP14-045", name: "Kuroobi", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "045", type: "Character", color: "Blue", rarity: "UC", cost: 3, power: 3000 },
  { id: "OP14-046", name: "Koala", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "046", type: "Character", color: "Blue", rarity: "UC", cost: 2 },
  { id: "OP14-047", name: "Shirahoshi", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "047", type: "Character", color: "Blue", rarity: "R", cost: 4 },
  { id: "OP14-048", name: "Shiryu", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "048", type: "Character", color: "Blue", rarity: "C", cost: 8, power: 10000 },
  { id: "OP14-049", name: "Jinbe", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "049", type: "Character", color: "Blue", rarity: "SR", cost: 8, power: 10000 },
  { id: "OP14-049_p1", name: "Jinbe (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "049", type: "Character", color: "Blue", rarity: "SR", cost: 8, power: 10000, imageUrl: "/api/card-image?id=OP14-049&variant=p1" },
  { id: "OP14-050", name: "Chew", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "050", type: "Character", color: "Blue", rarity: "UC", cost: 1, power: 3000 },
  { id: "OP14-051", name: "Hatchan", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "051", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 3000 },
  { id: "OP14-052", name: "Hannyabal", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "052", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000 },
  { id: "OP14-053", name: "Vista", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "053", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "OP14-054", name: "Fisher Tiger", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "054", type: "Character", color: "Blue", rarity: "UC", cost: 6, power: 7000 },
  { id: "OP14-055", name: "The Macro Gang", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "055", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000 },
  { id: "OP14-056", name: "Wadatsumi", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "056", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 5000 },
  { id: "OP14-057", name: "Don't Worry!! I'm Here!!", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "057", type: "Event", color: "Blue", rarity: "C", cost: 2 },
  { id: "OP14-058", name: "Ocean Current Shoulder Throw", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "058", type: "Event", color: "Blue", rarity: "R", cost: 2 },
  { id: "OP14-059", name: "Please Take Me with You!! I Can Be of Great Help to You!!", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "059", type: "Event", color: "Blue", rarity: "UC", cost: 1 },
  { id: "OP14-060", name: "Donquixote Doflamingo", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "060", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000 },
  { id: "OP14-060_p1", name: "Donquixote Doflamingo (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "060", type: "Leader", color: "Purple", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP14-060&variant=p1" },
  { id: "OP14-061", name: "Vergo", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "061", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 7000 },
  { id: "OP14-061_p1", name: "Vergo (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "061", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 7000, imageUrl: "/api/card-image?id=OP14-061&variant=p1" },
  { id: "OP14-062", name: "Gladius", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "062", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP14-063", name: "Sugar", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "063", type: "Character", color: "Purple", rarity: "R", cost: 4, power: 1000 },
  { id: "OP14-064", name: "Giolla", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "064", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 1000 },
  { id: "OP14-065", name: "Senor Pink", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "065", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000 },
  { id: "OP14-066", name: "Diamante", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "066", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 8000 },
  { id: "OP14-067", name: "Dellinger", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "067", type: "Character", color: "Purple", rarity: "UC", cost: 1, power: 2000 },
  { id: "OP14-068", name: "Trebol", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "068", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 5000 },
  { id: "OP14-069", name: "Donquixote Doflamingo", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "069", type: "Character", color: "Purple", rarity: "SR", cost: 10, power: 10000 },
  { id: "OP14-069_p1", name: "Donquixote Doflamingo (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "069", type: "Character", color: "Purple", rarity: "SR", cost: 10, power: 10000, imageUrl: "/api/card-image?id=OP14-069&variant=p1" },
  { id: "OP14-070", name: "Buffalo", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "070", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 1000 },
  { id: "OP14-071", name: "Pica", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "071", type: "Character", color: "Purple", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP14-072", name: "Baby 5", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "072", type: "Character", color: "Purple", rarity: "UC", cost: 4, power: 1000 },
  { id: "OP14-073", name: "Machvise", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "073", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 7000 },
  { id: "OP14-074", name: "Monet", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "074", type: "Character", color: "Purple", rarity: "R", cost: 5, power: 6000 },
  { id: "OP14-075", name: "Lao.G", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "075", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "OP14-076", name: "Ever White", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "076", type: "Event", color: "Purple", rarity: "R", cost: 1 },
  { id: "OP14-077", name: "Penta-Chromatic String", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "077", type: "Event", color: "Purple", rarity: "UC", cost: 2 },
  { id: "OP14-078", name: "Bullet String", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "078", type: "Event", color: "Purple", rarity: "C", cost: 2 },
  { id: "OP14-079", name: "Crocodile", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "079", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000 },
  { id: "OP14-079_p1", name: "Crocodile (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "079", type: "Leader", color: "Black", rarity: "L", cost: 5, power: 5000, imageUrl: "/api/card-image?id=OP14-079&variant=p1" },
  { id: "OP14-080", name: "Gecko Moria", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "080", type: "Leader", color: "Black/Yellow", rarity: "L", cost: 4, power: 5000 },
  { id: "OP14-080_p1", name: "Gecko Moria (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "080", type: "Leader", color: "Black/Yellow", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP14-080&variant=p1" },
  { id: "OP14-081", name: "Spider Mice", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "081", type: "Character", color: "Black", rarity: "C", cost: 1, power: 1000 },
  { id: "OP14-082", name: "Oinkchuck", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "082", type: "Character", color: "Black", rarity: "C", cost: 2, power: 3000 },
  { id: "OP14-083", name: "Ms. Wednesday", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "083", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 1000 },
  { id: "OP14-084", name: "Ms. All Sunday", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "084", type: "Character", color: "Black", rarity: "SR", cost: 7, power: 8000 },
  { id: "OP14-084_p1", name: "Ms. All Sunday (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "084", type: "Character", color: "Black", rarity: "SR", cost: 7, power: 8000, imageUrl: "/api/card-image?id=OP14-084&variant=p1" },
  { id: "OP14-085", name: "Miss.Goldenweek(Marianne)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "085", type: "Character", color: "Black", rarity: "UC", cost: 1, power: 2000 },
  { id: "OP14-086", name: "Miss Doublefinger(Zala)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "086", type: "Character", color: "Black", rarity: "C", cost: 5, power: 6000 },
  { id: "OP14-087", name: "Miss.Valentine(Mikita)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "087", type: "Character", color: "Black", rarity: "R", cost: 1, power: 2000 },
  { id: "OP14-088", name: "Miss.MerryChristmas(Drophy)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "088", type: "Character", color: "Black", rarity: "C", cost: 1, power: 2000 },
  { id: "OP14-089", name: "Ryuma", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "089", type: "Character", color: "Black", rarity: "C", cost: 3, power: 5000 },
  { id: "OP14-090", name: "Mr.1(Daz.Bonez)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "090", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000 },
  { id: "OP14-090_p1", name: "Mr.1(Daz.Bonez) (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "090", type: "Character", color: "Black", rarity: "R", cost: 5, power: 6000, imageUrl: "/api/card-image?id=OP14-090&variant=p1" },
  { id: "OP14-091", name: "Mr.2.Bon.Kurei(Bentham)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "091", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000 },
  { id: "OP14-091_p1", name: "Mr.2.Bon.Kurei(Bentham) (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "091", type: "Character", color: "Black", rarity: "SR", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP14-091&variant=p1" },
  { id: "OP14-092", name: "Mr.3(Galdino)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "092", type: "Character", color: "Black", rarity: "R", cost: 4, power: 6000 },
  { id: "OP14-093", name: "Mr.4(Babe)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "093", type: "Character", color: "Black", rarity: "C", cost: 4, power: 5000 },
  { id: "OP14-094", name: "Mr.5(Gem)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "094", type: "Character", color: "Black", rarity: "UC", cost: 5, power: 6000 },
  { id: "OP14-095", name: "Mr.9", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "095", type: "Character", color: "Black", rarity: "C", cost: 5, power: 6000 },
  { id: "OP14-096", name: "Ground Death", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "096", type: "Event", color: "Black", rarity: "R", cost: 1 },
  { id: "OP14-096_p1", name: "Ground Death (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "096", type: "Event", color: "Black", rarity: "R", cost: 1, imageUrl: "/api/card-image?id=OP14-096&variant=p1" },
  { id: "OP14-097", name: "Hurry Up and Make Me the Pirate King!", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "097", type: "Event", color: "Black", rarity: "UC", cost: 1 },
  { id: "OP14-098", name: "Crescent Cutlass", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "098", type: "Event", color: "Black", rarity: "C", cost: 1 },
  { id: "OP14-099", name: "Disappointed?", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "099", type: "Event", color: "Black", rarity: "UC", cost: 1 },
  { id: "OP14-100", name: "Absalom", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "100", type: "Character", color: "Yellow", rarity: "R", cost: 3, power: 5000 },
  { id: "OP14-101", name: "Oars", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "101", type: "Character", color: "Yellow", rarity: "C", cost: 8, power: 10000 },
  { id: "OP14-102", name: "Kumacy", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "102", type: "Character", color: "Yellow", rarity: "C", cost: 1, power: 2000 },
  { id: "OP14-103", name: "Gloriosa (Grandma Nyon)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "103", type: "Character", color: "Yellow", rarity: "C", cost: 2 },
  { id: "OP14-104", name: "Gecko Moria", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "104", type: "Character", color: "Yellow", rarity: "SR", cost: 8, power: 10000 },
  { id: "OP14-104_p1", name: "Gecko Moria (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "104", type: "Character", color: "Yellow", rarity: "SR", cost: 8, power: 10000, imageUrl: "/api/card-image?id=OP14-104&variant=p1" },
  { id: "OP14-105", name: "Gorgon Sisters", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "105", type: "Character", color: "Yellow", rarity: "UC", cost: 6, power: 5000 },
  { id: "OP14-106", name: "Salome", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "106", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 1000 },
  { id: "OP14-107", name: "Shakuyaku", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "107", type: "Character", color: "Yellow", rarity: "UC", cost: 6, power: 5000 },
  { id: "OP14-108", name: "Silvers Rayleigh", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "108", type: "Character", color: "Yellow", rarity: "R", cost: 6, power: 6000 },
  { id: "OP14-109", name: "Victoria Cindry", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "109", type: "Character", color: "Yellow", rarity: "C", cost: 3, power: 1000 },
  { id: "OP14-110", name: "Dr. Hogback", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "110", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000 },
  { id: "OP14-111", name: "Perona", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "111", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000 },
  { id: "OP14-111_p1", name: "Perona (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "111", type: "Character", color: "Yellow", rarity: "R", cost: 4, power: 5000, imageUrl: "/api/card-image?id=OP14-111&variant=p1" },
  { id: "OP14-112", name: "Boa Hancock", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "112", type: "Character", color: "Yellow", rarity: "SR", cost: 9, power: 10000 },
  { id: "OP14-112_p1", name: "Boa Hancock (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "112", type: "Character", color: "Yellow", rarity: "SR", cost: 9, power: 10000, imageUrl: "/api/card-image?id=OP14-112&variant=p1" },
  { id: "OP14-113", name: "Marguerite", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "113", type: "Character", color: "Yellow", rarity: "UC", cost: 3, power: 5000 },
  { id: "OP14-114", name: "Ran", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "114", type: "Character", color: "Yellow", rarity: "UC", cost: 4, power: 5000 },
  { id: "OP14-115", name: "Rindo", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "115", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 5000 },
  { id: "OP14-116", name: "Salamander", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "116", type: "Event", color: "Yellow", rarity: "C", cost: 4 },
  { id: "OP14-117", name: "Brick Bat", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "117", type: "Event", color: "Yellow", rarity: "UC", cost: 1 },
  { id: "OP14-118", name: "You'll Frighten Me... \u2661", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "118", type: "Event", color: "Yellow", rarity: "R", cost: 1 },
  { id: "OP14-118_p1", name: "You'll Frighten Me... \u2661 (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "118", type: "Event", color: "Yellow", rarity: "R", cost: 1, imageUrl: "/api/card-image?id=OP14-118&variant=p1" },
  { id: "OP14-119", name: "Dracule Mihawk", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "119", type: "Character", color: "Green", rarity: "SEC", cost: 9, power: 10000 },
  { id: "OP14-119_p1", name: "Dracule Mihawk (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "119", type: "Character", color: "Green", rarity: "SEC", cost: 9, power: 10000, imageUrl: "/api/card-image?id=OP14-119&variant=p1" },
  { id: "OP14-119_p2", name: "Dracule Mihawk (SP)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "119", type: "Character", color: "Green", rarity: "SEC", cost: 9, power: 10000, imageUrl: "/api/card-image?id=OP14-119&variant=p2" },
  { id: "OP14-120", name: "Crocodile", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "120", type: "Character", color: "Black", rarity: "SEC", cost: 8, power: 10000 },
  { id: "OP14-120_p1", name: "Crocodile (Alt Art)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "120", type: "Character", color: "Black", rarity: "SEC", cost: 8, power: 10000, imageUrl: "/api/card-image?id=OP14-120&variant=p1" },
  { id: "OP14-112_p2", name: "Boa Hancock (SP)", set: "THE AZURE SEA'S SEVEN", setCode: "OP14", number: "112", type: "Character", color: "Yellow", rarity: "SP", cost: 9, power: 10000, imageUrl: "/api/card-image?id=OP14-112&variant=p2" },
];

export default OP14_CARDS;
