// P: PROMOTION CARD - Synced from official cardlist
// 133 entries including variants
const P_CARDS = [
  { id: "P-001", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "001", type: "Character", color: "Red", rarity: "P", cost: 6, power: 7000 },
  { id: "P-001_p1", name: "Monkey.D.Luffy (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "001", type: "Character", color: "Red", rarity: "P", cost: 6, power: 7000, imageUrl: "/api/card-image?id=P-001&variant=p1" },
  { id: "P-001_p2", name: "Monkey.D.Luffy (Manga)", set: "PROMOTION CARD", setCode: "P", number: "001", type: "Character", color: "Red", rarity: "P", cost: 6, power: 7000, imageUrl: "/api/card-image?id=P-001&variant=p2" },
  { id: "P-001_p5", name: "Monkey.D.Luffy (Manga)", set: "PROMOTION CARD", setCode: "P", number: "001", type: "Character", color: "Red", rarity: "P", cost: 6, power: 7000, imageUrl: "/api/card-image?id=P-001&variant=p5" },
  { id: "P-002", name: "I Smell Adventure!!!", set: "PROMOTION CARD", setCode: "P", number: "002", type: "Event", color: "Red", rarity: "P", cost: 1 },
  { id: "P-003", name: "Eustass\"Captain\"Kid", set: "PROMOTION CARD", setCode: "P", number: "003", type: "Character", color: "Green", rarity: "P", cost: 3, power: 4000 },
  { id: "P-003_p1", name: "Eustass\"Captain\"Kid (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "003", type: "Character", color: "Green", rarity: "P", cost: 3, power: 4000, imageUrl: "/api/card-image?id=P-003&variant=p1" },
  { id: "P-004", name: "Crocodile", set: "PROMOTION CARD", setCode: "P", number: "004", type: "Character", color: "Blue", rarity: "P", cost: 4, power: 5000 },
  { id: "P-005", name: "Kaido", set: "PROMOTION CARD", setCode: "P", number: "005", type: "Character", color: "Purple", rarity: "P", cost: 7, power: 8000 },
  { id: "P-006", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "006", type: "Character", color: "Red", rarity: "P", cost: 3, power: 3000 },
  { id: "P-007", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "007", type: "Character", color: "Red", rarity: "P", cost: 4, power: 5000 },
  { id: "P-008", name: "Yamato", set: "PROMOTION CARD", setCode: "P", number: "008", type: "Character", color: "Green", rarity: "P", cost: 3, power: 5000 },
  { id: "P-009", name: "Trafalgar Law", set: "PROMOTION CARD", setCode: "P", number: "009", type: "Character", color: "Blue", rarity: "P", cost: 6, power: 7000 },
  { id: "P-010", name: "Kaido", set: "PROMOTION CARD", setCode: "P", number: "010", type: "Character", color: "Purple", rarity: "P", cost: 8, power: 9000 },
  { id: "P-011", name: "Uta", set: "PROMOTION CARD", setCode: "P", number: "011", type: "Leader", color: "Red", rarity: "L", cost: 5, power: 5000 },
  { id: "P-012", name: "Jellyfish Pirates", set: "PROMOTION CARD", setCode: "P", number: "012", type: "Character", color: "Red", rarity: "P", cost: 3, power: 5000 },
  { id: "P-013", name: "Gordon", set: "PROMOTION CARD", setCode: "P", number: "013", type: "Character", color: "Red", rarity: "P", cost: 1, power: 2000 },
  { id: "P-014", name: "Koby", set: "PROMOTION CARD", setCode: "P", number: "014", type: "Character", color: "Red", rarity: "P", cost: 3, power: 3000 },
  { id: "P-015", name: "Sunny-Kun", set: "PROMOTION CARD", setCode: "P", number: "015", type: "Character", color: "Red", rarity: "P", cost: 1, power: 3000 },
  { id: "P-016", name: "Shanks", set: "PROMOTION CARD", setCode: "P", number: "016", type: "Character", color: "Red", rarity: "P", cost: 8, power: 10000 },
  { id: "P-017", name: "Trafalgar Law", set: "PROMOTION CARD", setCode: "P", number: "017", type: "Character", color: "Red", rarity: "P", cost: 4, power: 5000 },
  { id: "P-017_p1", name: "Trafalgar Law (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "017", type: "Character", color: "Red", rarity: "P", cost: 4, power: 5000, imageUrl: "/api/card-image?id=P-017&variant=p1" },
  { id: "P-018", name: "Bartolomeo", set: "PROMOTION CARD", setCode: "P", number: "018", type: "Character", color: "Red", rarity: "P", cost: 2, power: 3000 },
  { id: "P-019", name: "Bepo", set: "PROMOTION CARD", setCode: "P", number: "019", type: "Character", color: "Red", rarity: "P", cost: 3, power: 2000 },
  { id: "P-019_p1", name: "Bepo (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "019", type: "Character", color: "Red", rarity: "P", cost: 3, power: 2000, imageUrl: "/api/card-image?id=P-019&variant=p1" },
  { id: "P-020", name: "Helmeppo", set: "PROMOTION CARD", setCode: "P", number: "020", type: "Character", color: "Red", rarity: "P", cost: 1, power: 2000 },
  { id: "P-021", name: "Benn.Beckman", set: "PROMOTION CARD", setCode: "P", number: "021", type: "Character", color: "Red", rarity: "P", cost: 7, power: 9000 },
  { id: "P-022", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "022", type: "Character", color: "Red", rarity: "P", cost: 4, power: 6000 },
  { id: "P-023", name: "Yasopp", set: "PROMOTION CARD", setCode: "P", number: "023", type: "Character", color: "Red", rarity: "P", cost: 6, power: 8000 },
  { id: "P-024", name: "I'm Gonna Be King of the Pirates!!", set: "PROMOTION CARD", setCode: "P", number: "024", type: "Event", color: "Green", rarity: "P", cost: 2 },
  { id: "P-025", name: "Smoker", set: "PROMOTION CARD", setCode: "P", number: "025", type: "Character", color: "Black", rarity: "P", cost: 3, power: 5000 },
  { id: "P-026", name: "Morgan", set: "PROMOTION CARD", setCode: "P", number: "026", type: "Character", color: "Black", rarity: "P", cost: 4, power: 5000 },
  { id: "P-027", name: "General Franky", set: "PROMOTION CARD", setCode: "P", number: "027", type: "Character", color: "Red", rarity: "P", cost: 2, power: 4000 },
  { id: "P-028", name: "Portgas.D.Ace", set: "PROMOTION CARD", setCode: "P", number: "028", type: "Character", color: "Red", rarity: "P", cost: 5, power: 6000 },
  { id: "P-029", name: "Bartolomeo", set: "PROMOTION CARD", setCode: "P", number: "029", type: "Character", color: "Green", rarity: "P", cost: 2, power: 3000 },
  { id: "P-030", name: "Jinbe", set: "PROMOTION CARD", setCode: "P", number: "030", type: "Character", color: "Blue", rarity: "P", cost: 4, power: 5000 },
  { id: "P-031", name: "Uta", set: "PROMOTION CARD", setCode: "P", number: "031", type: "Character", color: "Purple", rarity: "P", cost: 5, power: 6000 },
  { id: "P-032", name: "Sengoku", set: "PROMOTION CARD", setCode: "P", number: "032", type: "Character", color: "Black", rarity: "P", cost: 5, power: 6000 },
  { id: "P-033", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "033", type: "Character", color: "Blue", rarity: "P", cost: 4, power: 5000 },
  { id: "P-034", name: "Sanji", set: "PROMOTION CARD", setCode: "P", number: "034", type: "Character", color: "Yellow", rarity: "P", cost: 3, power: 4000 },
  { id: "P-035", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "035", type: "Character", color: "Black", rarity: "P", cost: 6, power: 6000 },
  { id: "P-036", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "036", type: "Character", color: "Yellow", rarity: "P", cost: 3, power: 4000 },
  { id: "P-037", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "037", type: "Character", color: "Green", rarity: "P", cost: 2, power: 4000 },
  { id: "P-039", name: "Bellamy", set: "PROMOTION CARD", setCode: "P", number: "039", type: "Character", color: "Yellow", rarity: "P", cost: 5, power: 6000 },
  { id: "P-041", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "041", type: "Character", color: "Purple", rarity: "P", cost: 10, power: 12000 },
  { id: "P-041_p1", name: "Monkey.D.Luffy (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "041", type: "Character", color: "Purple", rarity: "P", cost: 10, power: 12000, imageUrl: "/api/card-image?id=P-041&variant=p1" },
  { id: "P-042", name: "Roronoa Zoro", set: "PROMOTION CARD", setCode: "P", number: "042", type: "Character", color: "Yellow", rarity: "P", cost: 4, power: 5000 },
  { id: "P-043", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "043", type: "Character", color: "Blue", rarity: "P", cost: 7, power: 7000 },
  { id: "P-045", name: "Roronoa Zoro", set: "PROMOTION CARD", setCode: "P", number: "045", type: "Character", color: "Purple", rarity: "P", cost: 6, power: 7000 },
  { id: "P-045_p1", name: "Roronoa Zoro (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "045", type: "Character", color: "Purple", rarity: "P", cost: 6, power: 7000, imageUrl: "/api/card-image?id=P-045&variant=p1" },
  { id: "P-046", name: "Yamato", set: "PROMOTION CARD", setCode: "P", number: "046", type: "Character", color: "Purple", rarity: "P", cost: 1, power: 2000 },
  { id: "P-047", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "047", type: "Leader", color: "Blue", rarity: "P", cost: 5, power: 5000 },
  { id: "P-048", name: "Arlong", set: "PROMOTION CARD", setCode: "P", number: "048", type: "Character", color: "Blue", rarity: "P", cost: 3, power: 4000 },
  { id: "P-049", name: "Usopp", set: "PROMOTION CARD", setCode: "P", number: "049", type: "Character", color: "Blue", rarity: "P", cost: 2, power: 3000 },
  { id: "P-050", name: "Sanji", set: "PROMOTION CARD", setCode: "P", number: "050", type: "Character", color: "Blue", rarity: "P", cost: 3, power: 2000 },
  { id: "P-051", name: "Shanks", set: "PROMOTION CARD", setCode: "P", number: "051", type: "Character", color: "Blue", rarity: "P", cost: 7, power: 9000 },
  { id: "P-052", name: "Dracule Mihawk", set: "PROMOTION CARD", setCode: "P", number: "052", type: "Character", color: "Blue", rarity: "P", cost: 6, power: 7000 },
  { id: "P-053", name: "Nami", set: "PROMOTION CARD", setCode: "P", number: "053", type: "Character", color: "Blue", rarity: "P", cost: 1, power: 1000 },
  { id: "P-054", name: "Monkey.D.Garp", set: "PROMOTION CARD", setCode: "P", number: "054", type: "Character", color: "Blue", rarity: "P", cost: 6, power: 7000 },
  { id: "P-055", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "055", type: "Character", color: "Blue", rarity: "P", cost: 4, power: 5000 },
  { id: "P-056", name: "Roronoa Zoro", set: "PROMOTION CARD", setCode: "P", number: "056", type: "Character", color: "Blue", rarity: "P", cost: 4, power: 6000 },
  { id: "P-057", name: "Fleeting Lullaby", set: "PROMOTION CARD", setCode: "P", number: "057", type: "Event", color: "Green", rarity: "P", cost: 3 },
  { id: "P-058", name: "Where the Wind Blows", set: "PROMOTION CARD", setCode: "P", number: "058", type: "Event", color: "Green", rarity: "P", cost: 2 },
  { id: "P-059", name: "The World's Continuation", set: "PROMOTION CARD", setCode: "P", number: "059", type: "Event", color: "Green", rarity: "P", cost: 2 },
  { id: "P-060", name: "Tot Musica", set: "PROMOTION CARD", setCode: "P", number: "060", type: "Event", color: "Green", rarity: "P", cost: 2 },
  { id: "P-061", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "061", type: "Character", color: "Green", rarity: "P", cost: 8, power: 10000 },
  { id: "P-062", name: "Hody & Hyouzou", set: "PROMOTION CARD", setCode: "P", number: "062", type: "Character", color: "Green", rarity: "P", cost: 4, power: 6000 },
  { id: "P-065", name: "Tony Tony.Chopper", set: "PROMOTION CARD", setCode: "P", number: "065", type: "Character", color: "Black", rarity: "P", cost: 3, power: 4000 },
  { id: "P-065_p1", name: "Tony Tony.Chopper (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "065", type: "Character", color: "Black", rarity: "P", cost: 3, power: 4000, imageUrl: "/api/card-image?id=P-065&variant=p1" },
  { id: "P-065_p2", name: "Tony Tony.Chopper (Manga)", set: "PROMOTION CARD", setCode: "P", number: "065", type: "Character", color: "Black", rarity: "P", cost: 3, power: 4000, imageUrl: "/api/card-image?id=P-065&variant=p2" },
  { id: "P-068", name: "Sanji", set: "PROMOTION CARD", setCode: "P", number: "068", type: "Character", color: "Blue", rarity: "P", cost: 3, power: 4000 },
  { id: "P-069", name: "Koala", set: "PROMOTION CARD", setCode: "P", number: "069", type: "Character", color: "Red", rarity: "P", cost: 1, power: 1000 },
  { id: "P-069_p1", name: "Koala (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "069", type: "Character", color: "Red", rarity: "P", cost: 1, power: 1000, imageUrl: "/api/card-image?id=P-069&variant=p1" },
  { id: "P-069_p2", name: "Koala (Manga)", set: "PROMOTION CARD", setCode: "P", number: "069", type: "Character", color: "Red", rarity: "P", cost: 1, power: 1000, imageUrl: "/api/card-image?id=P-069&variant=p2" },
  { id: "P-069_p4", name: "Koala (Manga)", set: "PROMOTION CARD", setCode: "P", number: "069", type: "Character", color: "Red", rarity: "P", cost: 1, power: 1000, imageUrl: "/api/card-image?id=P-069&variant=p4" },
  { id: "P-069_p5", name: "Koala (Manga)", set: "PROMOTION CARD", setCode: "P", number: "069", type: "Character", color: "Red", rarity: "P", cost: 1, power: 1000, imageUrl: "/api/card-image?id=P-069&variant=p5" },
  { id: "P-069_p6", name: "Koala (Manga)", set: "PROMOTION CARD", setCode: "P", number: "069", type: "Character", color: "Red", rarity: "P", cost: 1, power: 1000, imageUrl: "/api/card-image?id=P-069&variant=p6" },
  { id: "P-070", name: "Carrot", set: "PROMOTION CARD", setCode: "P", number: "070", type: "Character", color: "Green", rarity: "P", cost: 2, power: 2000 },
  { id: "P-070_p1", name: "Carrot (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "070", type: "Character", color: "Green", rarity: "P", cost: 2, power: 2000, imageUrl: "/api/card-image?id=P-070&variant=p1" },
  { id: "P-070_p2", name: "Carrot (Manga)", set: "PROMOTION CARD", setCode: "P", number: "070", type: "Character", color: "Green", rarity: "P", cost: 2, power: 2000, imageUrl: "/api/card-image?id=P-070&variant=p2" },
  { id: "P-071", name: "Marco", set: "PROMOTION CARD", setCode: "P", number: "071", type: "Character", color: "Blue", rarity: "P", cost: 4, power: 6000 },
  { id: "P-076", name: "Sakazuki", set: "PROMOTION CARD", setCode: "P", number: "076", type: "Leader", color: "Blue/Black", rarity: "P", cost: 4, power: 5000 },
  { id: "P-077", name: "Ulti", set: "PROMOTION CARD", setCode: "P", number: "077", type: "Character", color: "Purple", rarity: "P", cost: 6, power: 6000 },
  { id: "P-077_p1", name: "Ulti (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "077", type: "Character", color: "Purple", rarity: "P", cost: 6, power: 6000, imageUrl: "/api/card-image?id=P-077&variant=p1" },
  { id: "P-077_p2", name: "Ulti (Manga)", set: "PROMOTION CARD", setCode: "P", number: "077", type: "Character", color: "Purple", rarity: "P", cost: 6, power: 6000, imageUrl: "/api/card-image?id=P-077&variant=p2" },
  { id: "P-078", name: "Adio", set: "PROMOTION CARD", setCode: "P", number: "078", type: "Character", color: "Green", rarity: "P", cost: 4, power: 5000 },
  { id: "P-078_p1", name: "Adio (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "078", type: "Character", color: "Green", rarity: "P", cost: 4, power: 5000, imageUrl: "/api/card-image?id=P-078&variant=p1" },
  { id: "P-078_p2", name: "Adio (Manga)", set: "PROMOTION CARD", setCode: "P", number: "078", type: "Character", color: "Green", rarity: "P", cost: 4, power: 5000, imageUrl: "/api/card-image?id=P-078&variant=p2" },
  { id: "P-078_p3", name: "Adio (Manga)", set: "PROMOTION CARD", setCode: "P", number: "078", type: "Character", color: "Green", rarity: "P", cost: 4, power: 5000, imageUrl: "/api/card-image?id=P-078&variant=p3" },
  { id: "P-078_p4", name: "Adio (Manga)", set: "PROMOTION CARD", setCode: "P", number: "078", type: "Character", color: "Green", rarity: "P", cost: 4, power: 5000, imageUrl: "/api/card-image?id=P-078&variant=p4" },
  { id: "P-078_p5", name: "Adio (Manga)", set: "PROMOTION CARD", setCode: "P", number: "078", type: "Character", color: "Green", rarity: "P", cost: 4, power: 5000, imageUrl: "/api/card-image?id=P-078&variant=p5" },
  { id: "P-079", name: "Lim", set: "PROMOTION CARD", setCode: "P", number: "079", type: "Character", color: "Green", rarity: "P", cost: 2 },
  { id: "P-079_p1", name: "Lim (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "079", type: "Character", color: "Green", rarity: "P", cost: 2, imageUrl: "/api/card-image?id=P-079&variant=p1" },
  { id: "P-079_p2", name: "Lim (Manga)", set: "PROMOTION CARD", setCode: "P", number: "079", type: "Character", color: "Green", rarity: "P", cost: 2, imageUrl: "/api/card-image?id=P-079&variant=p2" },
  { id: "P-081", name: "Dracule Mihawk", set: "PROMOTION CARD", setCode: "P", number: "081", type: "Character", color: "Blue", rarity: "P", cost: 4, power: 5000 },
  { id: "P-081_p1", name: "Dracule Mihawk (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "081", type: "Character", color: "Blue", rarity: "P", cost: 4, power: 5000, imageUrl: "/api/card-image?id=P-081&variant=p1" },
  { id: "P-082", name: "Crocodile", set: "PROMOTION CARD", setCode: "P", number: "082", type: "Character", color: "Blue", rarity: "P", cost: 5, power: 7000 },
  { id: "P-082_p1", name: "Crocodile (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "082", type: "Character", color: "Blue", rarity: "P", cost: 5, power: 7000, imageUrl: "/api/card-image?id=P-082&variant=p1" },
  { id: "P-083", name: "Shanks", set: "PROMOTION CARD", setCode: "P", number: "083", type: "Character", color: "Red", rarity: "P", cost: 6, power: 7000 },
  { id: "P-083_p1", name: "Shanks (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "083", type: "Character", color: "Red", rarity: "P", cost: 6, power: 7000, imageUrl: "/api/card-image?id=P-083&variant=p1" },
  { id: "P-083_p2", name: "Shanks (Manga)", set: "PROMOTION CARD", setCode: "P", number: "083", type: "Character", color: "Red", rarity: "P", cost: 6, power: 7000, imageUrl: "/api/card-image?id=P-083&variant=p2" },
  { id: "P-085", name: "Jewelry Bonney", set: "PROMOTION CARD", setCode: "P", number: "085", type: "Character", color: "Yellow", rarity: "P", cost: 5, power: 6000 },
  { id: "P-085_p1", name: "Jewelry Bonney (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "085", type: "Character", color: "Yellow", rarity: "P", cost: 5, power: 6000, imageUrl: "/api/card-image?id=P-085&variant=p1" },
  { id: "P-085_p2", name: "Jewelry Bonney (Manga)", set: "PROMOTION CARD", setCode: "P", number: "085", type: "Character", color: "Yellow", rarity: "P", cost: 5, power: 6000, imageUrl: "/api/card-image?id=P-085&variant=p2" },
  { id: "P-088", name: "Trafalgar Law", set: "PROMOTION CARD", setCode: "P", number: "088", type: "Character", color: "Yellow", rarity: "P", cost: 4, power: 5000 },
  { id: "P-089", name: "Tony Tony.Chopper", set: "PROMOTION CARD", setCode: "P", number: "089", type: "Character", color: "Yellow", rarity: "P", cost: 5, power: 7000 },
  { id: "P-089_p1", name: "Tony Tony.Chopper (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "089", type: "Character", color: "Yellow", rarity: "P", cost: 5, power: 7000, imageUrl: "/api/card-image?id=P-089&variant=p1" },
  { id: "P-089_p2", name: "Tony Tony.Chopper (Manga)", set: "PROMOTION CARD", setCode: "P", number: "089", type: "Character", color: "Yellow", rarity: "P", cost: 5, power: 7000, imageUrl: "/api/card-image?id=P-089&variant=p2" },
  { id: "P-090", name: "Charlotte Smoothie", set: "PROMOTION CARD", setCode: "P", number: "090", type: "Character", color: "Purple", rarity: "P", cost: 7, power: 7000 },
  { id: "P-091", name: "Shirahoshi", set: "PROMOTION CARD", setCode: "P", number: "091", type: "Character", color: "Green", rarity: "P", cost: 4 },
  { id: "P-092", name: "Koby", set: "PROMOTION CARD", setCode: "P", number: "092", type: "Character", color: "Red", rarity: "P", cost: 7, power: 7000 },
  { id: "P-092_p1", name: "Koby (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "092", type: "Character", color: "Red", rarity: "P", cost: 7, power: 7000, imageUrl: "/api/card-image?id=P-092&variant=p1" },
  { id: "P-092_p2", name: "Koby (Manga)", set: "PROMOTION CARD", setCode: "P", number: "092", type: "Character", color: "Red", rarity: "P", cost: 7, power: 7000, imageUrl: "/api/card-image?id=P-092&variant=p2" },
  { id: "P-096", name: "Girl", set: "PROMOTION CARD", setCode: "P", number: "096", type: "Character", color: "Blue", rarity: "P", cost: 2 },
  { id: "P-096_p1", name: "Girl (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "096", type: "Character", color: "Blue", rarity: "P", cost: 2, imageUrl: "/api/card-image?id=P-096&variant=p1" },
  { id: "P-097", name: "Shanks", set: "PROMOTION CARD", setCode: "P", number: "097", type: "Character", color: "Red", rarity: "P", cost: 10, power: 12000 },
  { id: "P-098", name: "Buggy", set: "PROMOTION CARD", setCode: "P", number: "098", type: "Character", color: "Blue", rarity: "P", cost: 10, power: 12000 },
  { id: "P-099", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "099", type: "Character", color: "Purple", rarity: "P", cost: 10, power: 12000 },
  { id: "P-100", name: "Marshall.D.Teach", set: "PROMOTION CARD", setCode: "P", number: "100", type: "Character", color: "Black", rarity: "P", cost: 10, power: 12000 },
  { id: "P-101", name: "Tony Tony.Chopper", set: "PROMOTION CARD", setCode: "P", number: "101", type: "Character", color: "Red", rarity: "P", cost: 4, power: 5000 },
  { id: "P-102", name: "Nami", set: "PROMOTION CARD", setCode: "P", number: "102", type: "Character", color: "Green", rarity: "P", cost: 4, power: 4000 },
  { id: "P-103", name: "Portgas.D.Ace", set: "PROMOTION CARD", setCode: "P", number: "103", type: "Character", color: "Blue", rarity: "P", cost: 4, power: 6000 },
  { id: "P-104", name: "Shanks", set: "PROMOTION CARD", setCode: "P", number: "104", type: "Character", color: "Purple", rarity: "P", cost: 8, power: 10000 },
  { id: "P-105", name: "Sabo", set: "PROMOTION CARD", setCode: "P", number: "105", type: "Character", color: "Black", rarity: "P", cost: 4, power: 6000 },
  { id: "P-106", name: "Monkey.D.Luffy", set: "PROMOTION CARD", setCode: "P", number: "106", type: "Character", color: "Yellow", rarity: "P", cost: 5, power: 6000 },
  { id: "P-107", name: "Gol.D.Roger", set: "PROMOTION CARD", setCode: "P", number: "107", type: "Character", color: "Purple", rarity: "P", cost: 8, power: 10000 },
  { id: "P-111", name: "Nico Robin", set: "PROMOTION CARD", setCode: "P", number: "111", type: "Character", color: "Green", rarity: "P", cost: 3, power: 4000 },
  { id: "P-111_p1", name: "Nico Robin (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "111", type: "Character", color: "Green", rarity: "P", cost: 3, power: 4000, imageUrl: "/api/card-image?id=P-111&variant=p1" },
  { id: "P-112", name: "Nami", set: "PROMOTION CARD", setCode: "P", number: "112", type: "Character", color: "Blue", rarity: "P", cost: 5, power: 6000 },
  { id: "P-112_p1", name: "Nami (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "112", type: "Character", color: "Blue", rarity: "P", cost: 5, power: 6000, imageUrl: "/api/card-image?id=P-112&variant=p1" },
  { id: "P-113", name: "Jewelry Bonney", set: "PROMOTION CARD", setCode: "P", number: "113", type: "Character", color: "Yellow", rarity: "P", cost: 4, power: 4000 },
  { id: "P-113_p1", name: "Jewelry Bonney (Alt Art)", set: "PROMOTION CARD", setCode: "P", number: "113", type: "Character", color: "Yellow", rarity: "P", cost: 4, power: 4000, imageUrl: "/api/card-image?id=P-113&variant=p1" },
  { id: "P-117", name: "Nami", set: "PROMOTION CARD", setCode: "P", number: "117", type: "Leader", color: "Blue", rarity: "P", cost: 5, power: 5000 },
];

export default P_CARDS;
