// ST13: THE THREE BROTHERS - Synced from official cardlist
// 35 entries including variants and cross-set SP/TR cards
const ST13_CARDS = [
  { id: "ST13-001", name: "Sabo", set: "THE THREE BROTHERS", setCode: "ST13", number: "001", type: "Leader", color: "Red/Yellow", rarity: "L", cost: 4, power: 5000 },
  { id: "ST13-001_p1", name: "Sabo (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "001", type: "Leader", color: "Red/Yellow", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=ST13-001&variant=p1" },
  { id: "ST13-002", name: "Portgas.D.Ace", set: "THE THREE BROTHERS", setCode: "ST13", number: "002", type: "Leader", color: "Blue/Yellow", rarity: "L", cost: 4, power: 5000 },
  { id: "ST13-002_p1", name: "Portgas.D.Ace (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "002", type: "Leader", color: "Blue/Yellow", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=ST13-002&variant=p1" },
  { id: "ST13-003", name: "Monkey.D.Luffy", set: "THE THREE BROTHERS", setCode: "ST13", number: "003", type: "Leader", color: "Black/Yellow", rarity: "L", cost: 4, power: 5000 },
  { id: "ST13-003_p1", name: "Monkey.D.Luffy (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "003", type: "Leader", color: "Black/Yellow", rarity: "L", cost: 4, power: 5000, imageUrl: "/api/card-image?id=ST13-003&variant=p1" },
  { id: "ST13-004", name: "Edward.Newgate", set: "THE THREE BROTHERS", setCode: "ST13", number: "004", type: "Character", color: "Yellow", rarity: "C", cost: 6, power: 7000 },
  { id: "ST13-004_p1", name: "Edward.Newgate (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "004", type: "Character", color: "Yellow", rarity: "C", cost: 6, power: 7000, imageUrl: "/api/card-image?id=ST13-004&variant=p1" },
  { id: "ST13-005", name: "Emporio.Ivankov", set: "THE THREE BROTHERS", setCode: "ST13", number: "005", type: "Character", color: "Yellow", rarity: "R", cost: 3, power: 4000 },
  { id: "ST13-005_p1", name: "Emporio.Ivankov (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "005", type: "Character", color: "Yellow", rarity: "R", cost: 3, power: 4000, imageUrl: "/api/card-image?id=ST13-005&variant=p1" },
  { id: "ST13-006", name: "Curly.Dadan", set: "THE THREE BROTHERS", setCode: "ST13", number: "006", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 4000 },
  { id: "ST13-006_p1", name: "Curly.Dadan (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "006", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 4000, imageUrl: "/api/card-image?id=ST13-006&variant=p1" },
  { id: "ST13-007", name: "Sabo", set: "THE THREE BROTHERS", setCode: "ST13", number: "007", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000 },
  { id: "ST13-007_p1", name: "Sabo (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "007", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000, imageUrl: "/api/card-image?id=ST13-007&variant=p1" },
  { id: "ST13-008", name: "Sabo", set: "THE THREE BROTHERS", setCode: "ST13", number: "008", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000 },
  { id: "ST13-008_p1", name: "Sabo (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "008", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000, imageUrl: "/api/card-image?id=ST13-008&variant=p1" },
  { id: "ST13-009", name: "Shanks", set: "THE THREE BROTHERS", setCode: "ST13", number: "009", type: "Character", color: "Yellow", rarity: "C", cost: 7, power: 7000 },
  { id: "ST13-009_p1", name: "Shanks (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "009", type: "Character", color: "Yellow", rarity: "C", cost: 7, power: 7000, imageUrl: "/api/card-image?id=ST13-009&variant=p1" },
  { id: "ST13-010", name: "Portgas.D.Ace", set: "THE THREE BROTHERS", setCode: "ST13", number: "010", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000 },
  { id: "ST13-010_p1", name: "Portgas.D.Ace (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "010", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000, imageUrl: "/api/card-image?id=ST13-010&variant=p1" },
  { id: "ST13-011", name: "Portgas.D.Ace", set: "THE THREE BROTHERS", setCode: "ST13", number: "011", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 7000 },
  { id: "ST13-011_p1", name: "Portgas.D.Ace (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "011", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 7000, imageUrl: "/api/card-image?id=ST13-011&variant=p1" },
  { id: "ST13-012", name: "Makino", set: "THE THREE BROTHERS", setCode: "ST13", number: "012", type: "Character", color: "Yellow", rarity: "C", cost: 1 },
  { id: "ST13-012_p1", name: "Makino (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "012", type: "Character", color: "Yellow", rarity: "C", cost: 1, imageUrl: "/api/card-image?id=ST13-012&variant=p1" },
  { id: "ST13-013", name: "Monkey.D.Garp", set: "THE THREE BROTHERS", setCode: "ST13", number: "013", type: "Character", color: "Yellow", rarity: "SR", cost: 1, power: 2000 },
  { id: "ST13-013_p1", name: "Monkey.D.Garp (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "013", type: "Character", color: "Yellow", rarity: "SR", cost: 1, power: 2000, imageUrl: "/api/card-image?id=ST13-013&variant=p1" },
  { id: "ST13-014", name: "Monkey.D.Luffy", set: "THE THREE BROTHERS", setCode: "ST13", number: "014", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000 },
  { id: "ST13-014_p1", name: "Monkey.D.Luffy (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "014", type: "Character", color: "Yellow", rarity: "C", cost: 2, power: 2000, imageUrl: "/api/card-image?id=ST13-014&variant=p1" },
  { id: "ST13-015", name: "Monkey.D.Luffy", set: "THE THREE BROTHERS", setCode: "ST13", number: "015", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000 },
  { id: "ST13-015_p1", name: "Monkey.D.Luffy (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "015", type: "Character", color: "Yellow", rarity: "SR", cost: 5, power: 6000, imageUrl: "/api/card-image?id=ST13-015&variant=p1" },
  { id: "ST13-016", name: "Yamato", set: "THE THREE BROTHERS", setCode: "ST13", number: "016", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 4000 },
  { id: "ST13-016_p1", name: "Yamato (Alt Art)", set: "THE THREE BROTHERS", setCode: "ST13", number: "016", type: "Character", color: "Yellow", rarity: "C", cost: 5, power: 4000, imageUrl: "/api/card-image?id=ST13-016&variant=p1" },
  { id: "ST13-017", name: "Flame Dragon King", set: "THE THREE BROTHERS", setCode: "ST13", number: "017", type: "Event", color: "Yellow", rarity: "C", cost: 2 },
  { id: "ST13-018", name: "Gum-Gum Jet Spear", set: "THE THREE BROTHERS", setCode: "ST13", number: "018", type: "Event", color: "Yellow", rarity: "C", cost: 1 },
  { id: "ST13-019", name: "The Three Brothers' Bond", set: "THE THREE BROTHERS", setCode: "ST13", number: "019", type: "Event", color: "Yellow", rarity: "C", cost: 1 },
];

export default ST13_CARDS;
