import { Card } from "./cards";

// Starter Decks - All English card names
export const STARTER_DECK_CARDS: Card[] = [
  // ST01 - Straw Hat Crew
  { id: "ST01-001", name: "Monkey D. Luffy", set: "Straw Hat Crew", setCode: "ST01", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 0, power: 5000 },
  { id: "ST01-002", name: "Usopp", set: "Straw Hat Crew", setCode: "ST01", number: "002", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "ST01-003", name: "Sanji", set: "Straw Hat Crew", setCode: "ST01", number: "003", type: "Character", color: "Red", rarity: "C", cost: 2, power: 4000 },
  { id: "ST01-004", name: "Jinbe", set: "Straw Hat Crew", setCode: "ST01", number: "004", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000 },
  { id: "ST01-005", name: "Tony Tony Chopper", set: "Straw Hat Crew", setCode: "ST01", number: "005", type: "Character", color: "Red", rarity: "C", cost: 1, power: 2000 },
  { id: "ST01-006", name: "Nami", set: "Straw Hat Crew", setCode: "ST01", number: "006", type: "Character", color: "Red", rarity: "C", cost: 1, power: 1000 },
  { id: "ST01-007", name: "Nico Robin", set: "Straw Hat Crew", setCode: "ST01", number: "007", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "ST01-008", name: "Nefeltari Vivi", set: "Straw Hat Crew", setCode: "ST01", number: "008", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "ST01-009", name: "Franky", set: "Straw Hat Crew", setCode: "ST01", number: "009", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000 },
  { id: "ST01-010", name: "Brook", set: "Straw Hat Crew", setCode: "ST01", number: "010", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "ST01-011", name: "Roronoa Zoro", set: "Straw Hat Crew", setCode: "ST01", number: "011", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000 },
  { id: "ST01-012", name: "Monkey D. Luffy", set: "Straw Hat Crew", setCode: "ST01", number: "012", type: "Character", color: "Red", rarity: "C", cost: 4, power: 6000 },
  { id: "ST01-013", name: "Guard Point", set: "Straw Hat Crew", setCode: "ST01", number: "013", type: "Event", color: "Red", rarity: "C", cost: 1 },
  { id: "ST01-014", name: "Diable Jambe", set: "Straw Hat Crew", setCode: "ST01", number: "014", type: "Event", color: "Red", rarity: "C", cost: 3 },
  { id: "ST01-015", name: "Gum-Gum Red Hawk", set: "Straw Hat Crew", setCode: "ST01", number: "015", type: "Event", color: "Red", rarity: "C", cost: 4 },
  { id: "ST01-016", name: "Round Table", set: "Straw Hat Crew", setCode: "ST01", number: "016", type: "Event", color: "Red", rarity: "C", cost: 2 },
  { id: "ST01-017", name: "Thousand Sunny", set: "Straw Hat Crew", setCode: "ST01", number: "017", type: "Stage", color: "Red", rarity: "C", cost: 2 },
  
  // ST02 - Worst Generation
  { id: "ST02-001", name: "Eustass Kid", set: "Worst Generation", setCode: "ST02", number: "001", type: "Leader", color: "Green", rarity: "L", cost: 0, power: 5000 },
  { id: "ST02-002", name: "Killer", set: "Worst Generation", setCode: "ST02", number: "002", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "ST02-003", name: "X Drake", set: "Worst Generation", setCode: "ST02", number: "003", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "ST02-004", name: "Basil Hawkins", set: "Worst Generation", setCode: "ST02", number: "004", type: "Character", color: "Green", rarity: "C", cost: 3, power: 3000 },
  { id: "ST02-005", name: "Jewelry Bonney", set: "Worst Generation", setCode: "ST02", number: "005", type: "Character", color: "Green", rarity: "C", cost: 2, power: 2000 },
  { id: "ST02-006", name: "Capone Bege", set: "Worst Generation", setCode: "ST02", number: "006", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000 },
  { id: "ST02-007", name: "Heat", set: "Worst Generation", setCode: "ST02", number: "007", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "ST02-008", name: "Wire", set: "Worst Generation", setCode: "ST02", number: "008", type: "Character", color: "Green", rarity: "C", cost: 2, power: 3000 },
  { id: "ST02-009", name: "Scratchmen Apoo", set: "Worst Generation", setCode: "ST02", number: "009", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "ST02-010", name: "Trafalgar Law", set: "Worst Generation", setCode: "ST02", number: "010", type: "Character", color: "Green", rarity: "C", cost: 4, power: 5000 },
  { id: "ST02-011", name: "Eustass Kid", set: "Worst Generation", setCode: "ST02", number: "011", type: "Character", color: "Green", rarity: "C", cost: 6, power: 7000 },
  { id: "ST02-012", name: "Urouge", set: "Worst Generation", setCode: "ST02", number: "012", type: "Character", color: "Green", rarity: "C", cost: 3, power: 4000 },
  { id: "ST02-013", name: "Punk Gibson", set: "Worst Generation", setCode: "ST02", number: "013", type: "Event", color: "Green", rarity: "C", cost: 2 },
  { id: "ST02-014", name: "Repel", set: "Worst Generation", setCode: "ST02", number: "014", type: "Event", color: "Green", rarity: "C", cost: 1 },
  { id: "ST02-015", name: "Straw Sword", set: "Worst Generation", setCode: "ST02", number: "015", type: "Event", color: "Green", rarity: "C", cost: 4 },
  { id: "ST02-016", name: "Spike Spire", set: "Worst Generation", setCode: "ST02", number: "016", type: "Event", color: "Green", rarity: "C", cost: 3 },
  { id: "ST02-017", name: "Kid Pirates", set: "Worst Generation", setCode: "ST02", number: "017", type: "Stage", color: "Green", rarity: "C", cost: 1 },
  
  // ST03 - The Seven Warlords of the Sea
  { id: "ST03-001", name: "Crocodile", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "001", type: "Leader", color: "Blue", rarity: "L", cost: 0, power: 5000 },
  { id: "ST03-002", name: "Gecko Moria", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "002", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 3000 },
  { id: "ST03-003", name: "Bartholomew Kuma", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "003", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000 },
  { id: "ST03-004", name: "Krieg", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "004", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000 },
  { id: "ST03-005", name: "Dracule Mihawk", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "005", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000 },
  { id: "ST03-006", name: "Buggy", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "006", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "ST03-007", name: "Perona", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "007", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 3000 },
  { id: "ST03-008", name: "Galdino", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "008", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "ST03-009", name: "Boa Hancock", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "009", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000 },
  { id: "ST03-010", name: "Edward Weevil", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "010", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000 },
  { id: "ST03-011", name: "Daz Bonez", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "011", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "ST03-012", name: "Crocodile", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "012", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000 },
  { id: "ST03-013", name: "Thrust Pad Cannon", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "013", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "ST03-014", name: "Desert Girasole", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "014", type: "Event", color: "Blue", rarity: "C", cost: 4 },
  { id: "ST03-015", name: "Love-Love Mellow", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "015", type: "Event", color: "Blue", rarity: "C", cost: 3 },
  { id: "ST03-016", name: "Coup de Vent", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "016", type: "Event", color: "Blue", rarity: "C", cost: 2 },
  { id: "ST03-017", name: "Thriller Bark", set: "The Seven Warlords of the Sea", setCode: "ST03", number: "017", type: "Stage", color: "Blue", rarity: "C", cost: 1 },
  
  // ST04 - Animal Kingdom Pirates
  { id: "ST04-001", name: "Kaido", set: "Animal Kingdom Pirates", setCode: "ST04", number: "001", type: "Leader", color: "Purple", rarity: "L", cost: 0, power: 5000 },
  { id: "ST04-002", name: "Bao Huang", set: "Animal Kingdom Pirates", setCode: "ST04", number: "002", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 1000 },
  { id: "ST04-003", name: "Hamlet", set: "Animal Kingdom Pirates", setCode: "ST04", number: "003", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "ST04-004", name: "Briscola", set: "Animal Kingdom Pirates", setCode: "ST04", number: "004", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "ST04-005", name: "Speed", set: "Animal Kingdom Pirates", setCode: "ST04", number: "005", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "ST04-006", name: "Poker", set: "Animal Kingdom Pirates", setCode: "ST04", number: "006", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "ST04-007", name: "Ulti", set: "Animal Kingdom Pirates", setCode: "ST04", number: "007", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "ST04-008", name: "Page One", set: "Animal Kingdom Pirates", setCode: "ST04", number: "008", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "ST04-009", name: "Sasaki", set: "Animal Kingdom Pirates", setCode: "ST04", number: "009", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "ST04-010", name: "Black Maria", set: "Animal Kingdom Pirates", setCode: "ST04", number: "010", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "ST04-011", name: "Who's-Who", set: "Animal Kingdom Pirates", setCode: "ST04", number: "011", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "ST04-012", name: "King", set: "Animal Kingdom Pirates", setCode: "ST04", number: "012", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 7000 },
  { id: "ST04-013", name: "Kaido", set: "Animal Kingdom Pirates", setCode: "ST04", number: "013", type: "Character", color: "Purple", rarity: "C", cost: 9, power: 10000 },
  { id: "ST04-014", name: "Blast Breath", set: "Animal Kingdom Pirates", setCode: "ST04", number: "014", type: "Event", color: "Purple", rarity: "C", cost: 2 },
  { id: "ST04-015", name: "Thunder Bagua", set: "Animal Kingdom Pirates", setCode: "ST04", number: "015", type: "Event", color: "Purple", rarity: "C", cost: 2 },
  { id: "ST04-016", name: "Sparking Queen", set: "Animal Kingdom Pirates", setCode: "ST04", number: "016", type: "Event", color: "Purple", rarity: "C", cost: 1 },
  { id: "ST04-017", name: "Onigashima", set: "Animal Kingdom Pirates", setCode: "ST04", number: "017", type: "Stage", color: "Purple", rarity: "C", cost: 1 },
  
  // ST05 - ONE PIECE FILM edition
  { id: "ST05-001", name: "Shanks", set: "ONE PIECE FILM edition", setCode: "ST05", number: "001", type: "Leader", color: "Red", rarity: "L", cost: 0, power: 5000 },
  { id: "ST05-002", name: "Coby", set: "ONE PIECE FILM edition", setCode: "ST05", number: "002", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "ST05-003", name: "Hancock", set: "ONE PIECE FILM edition", setCode: "ST05", number: "003", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000 },
  { id: "ST05-004", name: "Franky", set: "ONE PIECE FILM edition", setCode: "ST05", number: "004", type: "Character", color: "Red", rarity: "C", cost: 4, power: 5000 },
  { id: "ST05-005", name: "Jimbe", set: "ONE PIECE FILM edition", setCode: "ST05", number: "005", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "ST05-006", name: "Robin", set: "ONE PIECE FILM edition", setCode: "ST05", number: "006", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "ST05-007", name: "Chopper", set: "ONE PIECE FILM edition", setCode: "ST05", number: "007", type: "Character", color: "Red", rarity: "C", cost: 1, power: 2000 },
  { id: "ST05-008", name: "Brook", set: "ONE PIECE FILM edition", setCode: "ST05", number: "008", type: "Character", color: "Red", rarity: "C", cost: 3, power: 4000 },
  { id: "ST05-009", name: "Sanji", set: "ONE PIECE FILM edition", setCode: "ST05", number: "009", type: "Character", color: "Red", rarity: "C", cost: 2, power: 4000 },
  { id: "ST05-010", name: "Uta", set: "ONE PIECE FILM edition", setCode: "ST05", number: "010", type: "Character", color: "Red", rarity: "C", cost: 3, power: 3000 },
  { id: "ST05-011", name: "Zoro", set: "ONE PIECE FILM edition", setCode: "ST05", number: "011", type: "Character", color: "Red", rarity: "C", cost: 3, power: 5000 },
  { id: "ST05-012", name: "Luffy", set: "ONE PIECE FILM edition", setCode: "ST05", number: "012", type: "Character", color: "Red", rarity: "C", cost: 4, power: 6000 },
  { id: "ST05-013", name: "Nami", set: "ONE PIECE FILM edition", setCode: "ST05", number: "013", type: "Character", color: "Red", rarity: "C", cost: 1, power: 1000 },
  { id: "ST05-014", name: "Usopp", set: "ONE PIECE FILM edition", setCode: "ST05", number: "014", type: "Character", color: "Red", rarity: "C", cost: 2, power: 3000 },
  { id: "ST05-015", name: "Gum-Gum Red Hawk", set: "ONE PIECE FILM edition", setCode: "ST05", number: "015", type: "Event", color: "Red", rarity: "C", cost: 4 },
  { id: "ST05-016", name: "Star Gun", set: "ONE PIECE FILM edition", setCode: "ST05", number: "016", type: "Event", color: "Red", rarity: "C", cost: 1 },
  { id: "ST05-017", name: "Sky Blue", set: "ONE PIECE FILM edition", setCode: "ST05", number: "017", type: "Stage", color: "Red", rarity: "C", cost: 2 },
  
  // ST06 - Navy
  { id: "ST06-001", name: "Sakazuki", set: "Navy", setCode: "ST06", number: "001", type: "Leader", color: "Blue", rarity: "L", cost: 0, power: 5000 },
  { id: "ST06-002", name: "Hina", set: "Navy", setCode: "ST06", number: "002", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "ST06-003", name: "Smoker", set: "Navy", setCode: "ST06", number: "003", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "ST06-004", name: "Kobby", set: "Navy", setCode: "ST06", number: "004", type: "Character", color: "Blue", rarity: "C", cost: 1, power: 2000 },
  { id: "ST06-005", name: "Kuzan", set: "Navy", setCode: "ST06", number: "005", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000 },
  { id: "ST06-006", name: "Garp", set: "Navy", setCode: "ST06", number: "006", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000 },
  { id: "ST06-007", name: "Fullbody", set: "Navy", setCode: "ST06", number: "007", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 2000 },
  { id: "ST06-008", name: "Momonga", set: "Navy", setCode: "ST06", number: "008", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 4000 },
  { id: "ST06-009", name: "Borsalino", set: "Navy", setCode: "ST06", number: "009", type: "Character", color: "Blue", rarity: "C", cost: 5, power: 6000 },
  { id: "ST06-010", name: "Jango", set: "Navy", setCode: "ST06", number: "010", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "ST06-011", name: "Tashigi", set: "Navy", setCode: "ST06", number: "011", type: "Character", color: "Blue", rarity: "C", cost: 2, power: 3000 },
  { id: "ST06-012", name: "Sengoku", set: "Navy", setCode: "ST06", number: "012", type: "Character", color: "Blue", rarity: "C", cost: 4, power: 5000 },
  { id: "ST06-013", name: "Sakazuki", set: "Navy", setCode: "ST06", number: "013", type: "Character", color: "Blue", rarity: "C", cost: 7, power: 8000 },
  { id: "ST06-014", name: "Helmeppo", set: "Navy", setCode: "ST06", number: "014", type: "Character", color: "Blue", rarity: "C", cost: 3, power: 3000 },
  { id: "ST06-015", name: "Shu", set: "Navy", setCode: "ST06", number: "015", type: "Event", color: "Blue", rarity: "C", cost: 1 },
  { id: "ST06-016", name: "Meteor Volcano", set: "Navy", setCode: "ST06", number: "016", type: "Event", color: "Blue", rarity: "C", cost: 3 },
  { id: "ST06-017", name: "Navy HQ", set: "Navy", setCode: "ST06", number: "017", type: "Stage", color: "Blue", rarity: "C", cost: 1 },
  
  // ST07 - Big Mom Pirates
  { id: "ST07-001", name: "Charlotte Linlin", set: "Big Mom Pirates", setCode: "ST07", number: "001", type: "Leader", color: "Purple", rarity: "L", cost: 0, power: 5000 },
  { id: "ST07-002", name: "Charlotte Mont-d'Or", set: "Big Mom Pirates", setCode: "ST07", number: "002", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "ST07-003", name: "Charlotte Pudding", set: "Big Mom Pirates", setCode: "ST07", number: "003", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 1000 },
  { id: "ST07-004", name: "Charlotte Cracker", set: "Big Mom Pirates", setCode: "ST07", number: "004", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000 },
  { id: "ST07-005", name: "Charlotte Katakuri", set: "Big Mom Pirates", setCode: "ST07", number: "005", type: "Character", color: "Purple", rarity: "C", cost: 6, power: 7000 },
  { id: "ST07-006", name: "Charlotte Smoothie", set: "Big Mom Pirates", setCode: "ST07", number: "006", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000 },
  { id: "ST07-007", name: "Charlotte Daifuku", set: "Big Mom Pirates", setCode: "ST07", number: "007", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "ST07-008", name: "Charlotte Perospero", set: "Big Mom Pirates", setCode: "ST07", number: "008", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "ST07-009", name: "Charlotte Oven", set: "Big Mom Pirates", setCode: "ST07", number: "009", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000 },
  { id: "ST07-010", name: "Charlotte Brulee", set: "Big Mom Pirates", setCode: "ST07", number: "010", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 2000 },
  { id: "ST07-011", name: "Tamago", set: "Big Mom Pirates", setCode: "ST07", number: "011", type: "Character", color: "Purple", rarity: "C", cost: 4, power: 5000 },
  { id: "ST07-012", name: "Pekoms", set: "Big Mom Pirates", setCode: "ST07", number: "012", type: "Character", color: "Purple", rarity: "C", cost: 2, power: 3000 },
  { id: "ST07-013", name: "Streusen", set: "Big Mom Pirates", setCode: "ST07", number: "013", type: "Character", color: "Purple", rarity: "C", cost: 1, power: 2000 },
  { id: "ST07-014", name: "Compote", set: "Big Mom Pirates", setCode: "ST07", number: "014", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "ST07-015", name: "Charlotte Linlin", set: "Big Mom Pirates", setCode: "ST07", number: "015", type: "Character", color: "Purple", rarity: "C", cost: 10, power: 12000 },
  { id: "ST07-016", name: "Moscato", set: "Big Mom Pirates", setCode: "ST07", number: "016", type: "Character", color: "Purple", rarity: "C", cost: 3, power: 4000 },
  { id: "ST07-017", name: "Amande", set: "Big Mom Pirates", setCode: "ST07", number: "017", type: "Event", color: "Purple", rarity: "C", cost: 3 },
  { id: "ST07-018", name: "Soul Focus", set: "Big Mom Pirates", setCode: "ST07", number: "018", type: "Event", color: "Purple", rarity: "C", cost: 2 },
  { id: "ST07-019", name: "Whole Cake Castle", set: "Big Mom Pirates", setCode: "ST07", number: "019", type: "Stage", color: "Purple", rarity: "C", cost: 2 },
];

